bme280.c
OVERSAMPLING_SETTINGS
FILTER_STANDBY_SETTINGS
static int8_t put_device_to_sleep(const struct bme280_dev *dev)
This internal API puts the device to sleep mode.
dev : Structure instance of bme280_dev. Result of API execution status. zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_CTRL_HUM_ADDR, bme280_get_regs, BME280_OK, bme280_soft_reset, parse_device_settings, reload_device_settings.
Referenced by bme280_set_sensor_mode, bme280_set_sensor_settings.
static int8_t write_power_mode(uint8_t sensor_mode, const struct bme280_dev *dev)
This internal API writes the power mode in the sensor.
write_power_mode dev : Structure instance of bme280_dev. sensor_mode : Variable which contains the power mode to be set. Result of API execution status. zero -> Success / +ve value -> Warning / -ve value -> Error sensor_mode dev
References bme280_get_regs, BME280_OK, BME280_PWR_CTRL_ADDR, BME280_SET_BITS_POS_0, bme280_set_regs.
Referenced by bme280_set_sensor_mode.
static int8_t null_ptr_check(const struct bme280_dev *dev)
This internal API is used to validate the device pointer for null conditions.
This internal API is used to validate the device structure pointer for null conditions. dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_E_NULL_PTR, BME280_OK, bme280_dev::delay_ms, NULL, bme280_dev::read, bme280_dev::write.
Referenced by bme280_get_regs, bme280_get_sensor_data, bme280_get_sensor_mode, bme280_get_sensor_settings, bme280_init, bme280_set_regs, bme280_set_sensor_mode, bme280_set_sensor_settings, bme280_soft_reset.
static void interleave_reg_addr(const uint8_t *reg_addr, uint8_t *temp_buff, const uint8_t *reg_data, uint8_t len)
This internal API interleaves the register address between the register data buffer for burst write operation.
reg_addr : Contains the register address array. temp_buff : Contains the temporary buffer to store the register data and register address. reg_data : Contains the register data to be written in the temporary buffer. len : No of bytes of data to be written for burst write.
Referenced by bme280_set_regs.
static int8_t get_calib_data(struct bme280_dev *dev)
This internal API reads the calibration data from the sensor, parse it and store in the device structure.
dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References bme280_get_regs, BME280_HUMIDITY_CALIB_DATA_ADDR, BME280_HUMIDITY_CALIB_DATA_LEN, BME280_OK, BME280_TEMP_PRESS_CALIB_DATA_ADDR, BME280_TEMP_PRESS_CALIB_DATA_LEN, parse_humidity_calib_data, parse_temp_press_calib_data.
Referenced by bme280_init.
static void parse_temp_press_calib_data(const uint8_t *reg_data, struct bme280_dev *dev)
This internal API is used to parse the temperature and pressure calibration data and store it in the device structure.
This internal API is used to parse the temperature and pressure calibration data and store it in device structure. dev : Structure instance of bme280_dev to store the calib data. reg_data : Contains the calibration data to be parsed.
References BME280_CONCAT_BYTES, bme280_dev::calib_data, bme280_calib_data::dig_H1, bme280_calib_data::dig_P1, bme280_calib_data::dig_P2, bme280_calib_data::dig_P3, bme280_calib_data::dig_P4, bme280_calib_data::dig_P5, bme280_calib_data::dig_P6, bme280_calib_data::dig_P7, bme280_calib_data::dig_P8, bme280_calib_data::dig_P9, bme280_calib_data::dig_T1, bme280_calib_data::dig_T2, bme280_calib_data::dig_T3.
Referenced by get_calib_data.
static void parse_humidity_calib_data(const uint8_t *reg_data, struct bme280_dev *dev)
This internal API is used to parse the humidity calibration data and store it in device structure.
dev : Structure instance of bme280_dev to store the calib data. reg_data : Contains calibration data to be parsed.
References BME280_CONCAT_BYTES, bme280_dev::calib_data, bme280_calib_data::dig_H2, bme280_calib_data::dig_H3, bme280_calib_data::dig_H4, bme280_calib_data::dig_H5, bme280_calib_data::dig_H6.
Referenced by get_calib_data.
static int32_t compensate_temperature(const struct bme280_uncomp_data *uncomp_data, struct bme280_calib_data *calib_data)
This internal API is used to compensate the raw temperature data and return the compensated temperature data in integer data type.
uncomp_data : Contains the uncompensated temperature data. calib_data : Pointer to calibration data structure. Compensated temperature data. Compensated temperature data in integer.
References bme280_calib_data::dig_T1, bme280_calib_data::dig_T2, bme280_calib_data::dig_T3, bme280_calib_data::t_fine, bme280_uncomp_data::temperature.
Referenced by bme280_compensate_data.
static uint32_t compensate_pressure(const struct bme280_uncomp_data *uncomp_data, const struct bme280_calib_data *calib_data)
This internal API is used to compensate the raw pressure data and return the compensated pressure data in integer data type.
uncomp_data : Contains the uncompensated pressure data. calib_data : Pointer to the calibration data structure. Compensated pressure data. Compensated pressure data in integer.
References bme280_calib_data::dig_P1, bme280_calib_data::dig_P2, bme280_calib_data::dig_P3, bme280_calib_data::dig_P4, bme280_calib_data::dig_P5, bme280_calib_data::dig_P6, bme280_calib_data::dig_P7, bme280_calib_data::dig_P8, bme280_calib_data::dig_P9, bme280_uncomp_data::pressure, bme280_calib_data::t_fine.
Referenced by bme280_compensate_data.
static uint32_t compensate_humidity(const struct bme280_uncomp_data *uncomp_data, const struct bme280_calib_data *calib_data)
This internal API is used to compensate the raw humidity data and return the compensated humidity data in integer data type.
uncomp_data : Contains the uncompensated humidity data. calib_data : Pointer to the calibration data structure. Compensated humidity data. Compensated humidity data in integer.
References bme280_calib_data::dig_H1, bme280_calib_data::dig_H2, bme280_calib_data::dig_H3, bme280_calib_data::dig_H4, bme280_calib_data::dig_H5, bme280_calib_data::dig_H6, bme280_uncomp_data::humidity, bme280_calib_data::t_fine.
Referenced by bme280_compensate_data.
static uint8_t are_settings_changed(uint8_t sub_settings, uint8_t desired_settings)
This internal API is used to identify the settings which the user wants to modify in the sensor.
sub_settings : Contains the settings subset to identify particular group of settings which the user is interested to change. desired_settings : Contains the user specified settings. Indicates whether user is interested to modify the settings which are related to sub_settings. True -> User wants to modify this group of settings False -> User does not want to modify this group of settings
References FALSE, TRUE.
Referenced by bme280_set_sensor_settings.
static int8_t set_osr_humidity_settings(const struct bme280_settings *settings, const struct bme280_dev *dev)
This API sets the humidity oversampling settings of the sensor.
dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_CTRL_HUM_ADDR, BME280_CTRL_HUM_MSK, BME280_CTRL_MEAS_ADDR, bme280_get_regs, BME280_OK, bme280_set_regs, bme280_settings::osr_h.
Referenced by set_osr_settings.
static int8_t set_osr_settings(uint8_t desired_settings, const struct bme280_settings *settings, const struct bme280_dev *dev)
This internal API sets the oversampling settings for pressure, temperature and humidity in the sensor.
desired_settings : Variable used to select the settings which are to be set. dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_OSR_HUM_SEL, BME280_OSR_PRESS_SEL, BME280_OSR_TEMP_SEL, BME280_W_INVALID_OSR_MACRO, set_osr_humidity_settings, set_osr_press_temp_settings.
Referenced by bme280_set_sensor_settings, reload_device_settings.
static int8_t set_osr_press_temp_settings(uint8_t desired_settings, const struct bme280_settings *settings, const struct bme280_dev *dev)
This API sets the pressure and/or temperature oversampling settings in the sensor according to the settings selected by the user.
dev : Structure instance of bme280_dev. desired_settings variable to select the pressure and/or temperature oversampling settings. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_CTRL_MEAS_ADDR, bme280_get_regs, BME280_OK, BME280_OSR_PRESS_SEL, BME280_OSR_TEMP_SEL, bme280_set_regs, fill_osr_press_settings, fill_osr_temp_settings.
Referenced by set_osr_settings.
static void fill_osr_press_settings(uint8_t *reg_data, const struct bme280_settings *settings)
This internal API fills the pressure oversampling settings provided by the user in the data buffer so as to write in the sensor.
dev : Structure instance of bme280_dev. reg_data : Variable which is filled according to the pressure oversampling data provided by the user.
References BME280_SET_BITS, bme280_settings::osr_p.
Referenced by set_osr_press_temp_settings.
static void fill_osr_temp_settings(uint8_t *reg_data, const struct bme280_settings *settings)
This internal API fills the temperature oversampling settings provided by the user in the data buffer so as to write in the sensor.
dev : Structure instance of bme280_dev. reg_data : Variable which is filled according to the temperature oversampling data provided by the user.
References BME280_SET_BITS, bme280_settings::osr_t.
Referenced by set_osr_press_temp_settings.
static int8_t set_filter_standby_settings(uint8_t desired_settings, const struct bme280_settings *settings, const struct bme280_dev *dev)
This internal API sets the filter and/or standby duration settings in the sensor according to the settings selected by the user.
dev : Structure instance of bme280_dev. desired_settings : variable to select the filter and/or standby duration settings. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_CONFIG_ADDR, BME280_FILTER_SEL, bme280_get_regs, BME280_OK, bme280_set_regs, BME280_STANDBY_SEL, fill_filter_settings, fill_standby_settings.
Referenced by bme280_set_sensor_settings, reload_device_settings.
static void fill_filter_settings(uint8_t *reg_data, const struct bme280_settings *settings)
This internal API fills the filter settings provided by the user in the data buffer so as to write in the sensor.
dev : Structure instance of bme280_dev. reg_data : Variable which is filled according to the filter settings data provided by the user.
References BME280_SET_BITS, bme280_settings::filter.
Referenced by set_filter_standby_settings.
static void fill_standby_settings(uint8_t *reg_data, const struct bme280_settings *settings)
This internal API fills the standby duration settings provided by the user in the data buffer so as to write in the sensor.
dev : Structure instance of bme280_dev. reg_data : Variable which is filled according to the standby settings data provided by the user.
References BME280_SET_BITS, bme280_settings::standby_time.
Referenced by set_filter_standby_settings.
static void parse_device_settings(const uint8_t *reg_data, struct bme280_settings *settings)
This internal API parse the oversampling(pressure, temperature and humidity), filter and standby duration settings and store in the device structure.
dev : Structure instance of bme280_dev. reg_data : Register data to be parsed.
References BME280_GET_BITS, BME280_GET_BITS_POS_0, bme280_settings::filter, bme280_settings::osr_h, bme280_settings::osr_p, bme280_settings::osr_t, bme280_settings::standby_time.
Referenced by bme280_get_sensor_settings, put_device_to_sleep.
static int8_t reload_device_settings(const struct bme280_settings *settings, const struct bme280_dev *dev)
This internal API reloads the already existing device settings in the sensor after soft reset.
dev : Structure instance of bme280_dev. settings : Pointer variable which contains the settings to be set in the sensor. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_ALL_SETTINGS_SEL, BME280_OK, set_filter_standby_settings, set_osr_settings.
Referenced by put_device_to_sleep.