TeosIce
TeosIce::TeosIce()
class constructor : base class constructor
References TeosBase::badBaseAlloc, TeosBase::statusOk.
TeosIce::~TeosIce()
descendant class destructor
double TeosIce::gsw_adiabatic_lapse_rate_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
Referenced by gsw_frazil_ratios_adiabatic, gsw_frazil_ratios_adiabatic_poly.
double TeosIce::gsw_alpha_wrt_t_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
double TeosIce::gsw_chem_potential_water_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
double TeosIce::gsw_cp_ice(double t, double p)
References TeosBase::gsw_gibbs_ice, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc.
Referenced by gsw_frazil_properties, gsw_frazil_ratios_adiabatic, gsw_frazil_ratios_adiabatic_poly, gsw_pot_enthalpy_ice_freezing_first_derivatives, gsw_pt_from_pot_enthalpy_ice.
double TeosIce::gsw_ct_freezing_exact(double sa, double p, double saturation_fraction)
References TeosBase::gsw_ct_from_t, gsw_t_freezing_exact.
void TeosIce::gsw_ct_freezing_first_derivatives(double sa, double p, double saturation_fraction, double *ctfreezing_sa, double *ctfreezing_p)
References TeosBase::gsw_ct_first_derivatives_wrt_t_exact, TeosBase::gsw_t_freezing, gsw_t_freezing_first_derivatives, NULL.
Referenced by gsw_frazil_properties, gsw_frazil_properties_potential, gsw_frazil_ratios_adiabatic, gsw_ice_fraction_to_freeze_seawater, gsw_pressure_freezing_ct, gsw_sa_freezing_from_ct, gsw_seaice_fraction_to_freeze_seawater.
void TeosIce::gsw_ct_freezing_first_derivatives_poly(double sa, double p, double saturation_fraction, double *ctfreezing_sa, double *ctfreezing_p)
References GSW_FREEZING_POLY_COEFFICIENTS::a, GSW_FREEZING_POLY_COEFFICIENTS::b, GSW_FREEZING_POLY_COEFFICIENTS::c1, GSW_FREEZING_POLY_COEFFICIENTS::c10, GSW_FREEZING_POLY_COEFFICIENTS::c11, GSW_FREEZING_POLY_COEFFICIENTS::c12, GSW_FREEZING_POLY_COEFFICIENTS::c13, GSW_FREEZING_POLY_COEFFICIENTS::c14, GSW_FREEZING_POLY_COEFFICIENTS::c15, GSW_FREEZING_POLY_COEFFICIENTS::c16, GSW_FREEZING_POLY_COEFFICIENTS::c17, GSW_FREEZING_POLY_COEFFICIENTS::c18, GSW_FREEZING_POLY_COEFFICIENTS::c19, GSW_FREEZING_POLY_COEFFICIENTS::c2, GSW_FREEZING_POLY_COEFFICIENTS::c20, GSW_FREEZING_POLY_COEFFICIENTS::c21, GSW_FREEZING_POLY_COEFFICIENTS::c22, GSW_FREEZING_POLY_COEFFICIENTS::c3, GSW_FREEZING_POLY_COEFFICIENTS::c4, GSW_FREEZING_POLY_COEFFICIENTS::c5, GSW_FREEZING_POLY_COEFFICIENTS::c6, GSW_FREEZING_POLY_COEFFICIENTS::c7, GSW_FREEZING_POLY_COEFFICIENTS::c8, GSW_FREEZING_POLY_COEFFICIENTS::c9, TeosBase::gfpc, GSW_TEOS10_CONSTANTS::gsw_sso, TeosBase::gtc, NULL.
Referenced by gsw_frazil_properties_potential_poly, gsw_frazil_ratios_adiabatic_poly, gsw_sa_freezing_from_ct_poly.
double TeosIce::gsw_ct_freezing_poly(double sa, double p, double saturation_fraction=0.0)
References GSW_FREEZING_POLY_COEFFICIENTS::a, GSW_FREEZING_POLY_COEFFICIENTS::b, GSW_FREEZING_POLY_COEFFICIENTS::c0, GSW_FREEZING_POLY_COEFFICIENTS::c1, GSW_FREEZING_POLY_COEFFICIENTS::c10, GSW_FREEZING_POLY_COEFFICIENTS::c11, GSW_FREEZING_POLY_COEFFICIENTS::c12, GSW_FREEZING_POLY_COEFFICIENTS::c13, GSW_FREEZING_POLY_COEFFICIENTS::c14, GSW_FREEZING_POLY_COEFFICIENTS::c15, GSW_FREEZING_POLY_COEFFICIENTS::c16, GSW_FREEZING_POLY_COEFFICIENTS::c17, GSW_FREEZING_POLY_COEFFICIENTS::c18, GSW_FREEZING_POLY_COEFFICIENTS::c19, GSW_FREEZING_POLY_COEFFICIENTS::c2, GSW_FREEZING_POLY_COEFFICIENTS::c20, GSW_FREEZING_POLY_COEFFICIENTS::c21, GSW_FREEZING_POLY_COEFFICIENTS::c22, GSW_FREEZING_POLY_COEFFICIENTS::c3, GSW_FREEZING_POLY_COEFFICIENTS::c4, GSW_FREEZING_POLY_COEFFICIENTS::c5, GSW_FREEZING_POLY_COEFFICIENTS::c6, GSW_FREEZING_POLY_COEFFICIENTS::c7, GSW_FREEZING_POLY_COEFFICIENTS::c8, GSW_FREEZING_POLY_COEFFICIENTS::c9, TeosBase::gfpc, GSW_TEOS10_CONSTANTS::gsw_sso, TeosBase::gtc.
Referenced by gsw_ct_from_rho, gsw_frazil_properties_potential_poly, gsw_frazil_ratios_adiabatic_poly, gsw_melting_ice_equilibrium_sa_ct_ratio_poly, gsw_melting_ice_sa_ct_ratio_poly, gsw_melting_seaice_equilibrium_sa_ct_ratio_poly, gsw_melting_seaice_sa_ct_ratio_poly, gsw_sa_freezing_from_ct_poly, gsw_t_freezing_poly, gsw_t_freezing_poly.
void TeosIce::gsw_ct_from_rho(double rho, double sa, double p, double *ct, double *ct_multiple)
References cppGSW_INVALID_VALUE, gsw_ct_freezing_poly, TeosBase::gsw_ct_maxdensity, TeosBase::gsw_rho, TeosBase::gsw_rho_alpha_beta, TeosBase::gsw_specvol, NULL.
double TeosIce::gsw_deltasa_from_sp(double sp, double p, double lon, double lat)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, TeosBase::gsw_sa_from_sp, TeosBase::gsw_sr_from_sp.
double TeosIce::gsw_enthalpy_diff(double sa, double ct, double p_shallow, double p_deep)
References GSW_TEOS10_CONSTANTS::db2pa, TeosBase::gsvco, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, GSW_SPECVOL_COEFFICIENTS::h001, GSW_SPECVOL_COEFFICIENTS::h002, GSW_SPECVOL_COEFFICIENTS::h003, GSW_SPECVOL_COEFFICIENTS::h004, GSW_SPECVOL_COEFFICIENTS::h005, GSW_SPECVOL_COEFFICIENTS::h006, GSW_SPECVOL_COEFFICIENTS::h007, GSW_SPECVOL_COEFFICIENTS::h011, GSW_SPECVOL_COEFFICIENTS::h012, GSW_SPECVOL_COEFFICIENTS::h013, GSW_SPECVOL_COEFFICIENTS::h014, GSW_SPECVOL_COEFFICIENTS::h015, GSW_SPECVOL_COEFFICIENTS::h021, GSW_SPECVOL_COEFFICIENTS::h022, GSW_SPECVOL_COEFFICIENTS::h023, GSW_SPECVOL_COEFFICIENTS::h024, GSW_SPECVOL_COEFFICIENTS::h031, GSW_SPECVOL_COEFFICIENTS::h032, GSW_SPECVOL_COEFFICIENTS::h033, GSW_SPECVOL_COEFFICIENTS::h041, GSW_SPECVOL_COEFFICIENTS::h042, GSW_SPECVOL_COEFFICIENTS::h043, GSW_SPECVOL_COEFFICIENTS::h051, GSW_SPECVOL_COEFFICIENTS::h052, GSW_SPECVOL_COEFFICIENTS::h061, GSW_SPECVOL_COEFFICIENTS::h101, GSW_SPECVOL_COEFFICIENTS::h102, GSW_SPECVOL_COEFFICIENTS::h103, GSW_SPECVOL_COEFFICIENTS::h104, GSW_SPECVOL_COEFFICIENTS::h105, GSW_SPECVOL_COEFFICIENTS::h111, GSW_SPECVOL_COEFFICIENTS::h112, GSW_SPECVOL_COEFFICIENTS::h113, GSW_SPECVOL_COEFFICIENTS::h114, GSW_SPECVOL_COEFFICIENTS::h121, GSW_SPECVOL_COEFFICIENTS::h122, GSW_SPECVOL_COEFFICIENTS::h123, GSW_SPECVOL_COEFFICIENTS::h131, GSW_SPECVOL_COEFFICIENTS::h132, GSW_SPECVOL_COEFFICIENTS::h133, GSW_SPECVOL_COEFFICIENTS::h141, GSW_SPECVOL_COEFFICIENTS::h142, GSW_SPECVOL_COEFFICIENTS::h151, GSW_SPECVOL_COEFFICIENTS::h201, GSW_SPECVOL_COEFFICIENTS::h202, GSW_SPECVOL_COEFFICIENTS::h203, GSW_SPECVOL_COEFFICIENTS::h204, GSW_SPECVOL_COEFFICIENTS::h211, GSW_SPECVOL_COEFFICIENTS::h212, GSW_SPECVOL_COEFFICIENTS::h213, GSW_SPECVOL_COEFFICIENTS::h221, GSW_SPECVOL_COEFFICIENTS::h222, GSW_SPECVOL_COEFFICIENTS::h223, GSW_SPECVOL_COEFFICIENTS::h231, GSW_SPECVOL_COEFFICIENTS::h232, GSW_SPECVOL_COEFFICIENTS::h241, GSW_SPECVOL_COEFFICIENTS::h301, GSW_SPECVOL_COEFFICIENTS::h302, GSW_SPECVOL_COEFFICIENTS::h303, GSW_SPECVOL_COEFFICIENTS::h311, GSW_SPECVOL_COEFFICIENTS::h312, GSW_SPECVOL_COEFFICIENTS::h313, GSW_SPECVOL_COEFFICIENTS::h321, GSW_SPECVOL_COEFFICIENTS::h322, GSW_SPECVOL_COEFFICIENTS::h331, GSW_SPECVOL_COEFFICIENTS::h401, GSW_SPECVOL_COEFFICIENTS::h402, GSW_SPECVOL_COEFFICIENTS::h403, GSW_SPECVOL_COEFFICIENTS::h411, GSW_SPECVOL_COEFFICIENTS::h412, GSW_SPECVOL_COEFFICIENTS::h421, GSW_SPECVOL_COEFFICIENTS::h501, GSW_SPECVOL_COEFFICIENTS::h502, GSW_SPECVOL_COEFFICIENTS::h511, GSW_SPECVOL_COEFFICIENTS::h601, GSW_TEOS10_CONSTANTS::offset.
Referenced by gsw_geo_strf_dyn_height_pc.
double TeosIce::gsw_enthalpy_ice(double t, double p)
References GSW_TEOS10_CONSTANTS::db2pa, GSW_GIBBS_ICE_COEFFICIENTS::g00, GSW_GIBBS_ICE_COEFFICIENTS::g01, GSW_GIBBS_ICE_COEFFICIENTS::g02, GSW_GIBBS_ICE_COEFFICIENTS::g03, GSW_GIBBS_ICE_COEFFICIENTS::g04, TeosBase::gic, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc, TeosBase::r1, TeosBase::r20, TeosBase::r21, TeosBase::r22, GSW_GIBBS_ICE_COEFFICIENTS::rec_pt, GSW_GIBBS_ICE_COEFFICIENTS::rec_tt, TeosBase::t1, TeosBase::t2, GSW_GIBBS_ICE_COEFFICIENTS::tt.
Referenced by gsw_frazil_properties, gsw_frazil_ratios_adiabatic, gsw_frazil_ratios_adiabatic_poly, gsw_ice_fraction_to_freeze_seawater, gsw_latentheat_melting, gsw_melting_ice_equilibrium_sa_ct_ratio, gsw_melting_ice_equilibrium_sa_ct_ratio_poly, gsw_melting_ice_into_seawater, gsw_melting_ice_sa_ct_ratio, gsw_melting_ice_sa_ct_ratio_poly, gsw_melting_seaice_equilibrium_sa_ct_ratio, gsw_melting_seaice_equilibrium_sa_ct_ratio_poly, gsw_melting_seaice_into_seawater, gsw_melting_seaice_sa_ct_ratio, gsw_melting_seaice_sa_ct_ratio_poly, gsw_seaice_fraction_to_freeze_seawater.
double TeosIce::gsw_entropy_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
Referenced by gsw_t_freezing_first_derivatives.
void TeosIce::gsw_frazil_properties(double sa_bulk, double h_bulk, double p, double *sa_final, double *ct_final, double *w_ih_final)
References cppGSW_INVALID_VALUE, gsw_cp_ice, TeosBase::gsw_ct_freezing, gsw_ct_freezing_first_derivatives, TeosBase::gsw_ct_from_enthalpy_exact, TeosBase::gsw_enthalpy_ct_exact, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_min_d, TeosBase::gsw_t_freezing, gsw_t_freezing_first_derivatives, NULL.
Referenced by gsw_melting_ice_into_seawater.
void TeosIce::gsw_frazil_properties_potential(double sa_bulk, double h_pot_bulk, double p, double *sa_final, double *ct_final, double *w_ih_final)
References cppGSW_INVALID_VALUE, GSW_TEOS10_CONSTANTS::gsw_cp0, TeosBase::gsw_ct_freezing, gsw_ct_freezing_first_derivatives, gsw_pot_enthalpy_ice_freezing, gsw_pot_enthalpy_ice_freezing_first_derivatives, TeosBase::gtc, NULL.
void TeosIce::gsw_frazil_properties_potential_poly(double sa_bulk, double h_pot_bulk, double p, double *sa_final, double *ct_final, double *w_ih_final)
References cppGSW_INVALID_VALUE, GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_ct_freezing_first_derivatives_poly, gsw_ct_freezing_poly, TeosBase::gsw_pot_enthalpy_ice_freezing_first_derivatives_poly, TeosBase::gsw_pot_enthalpy_ice_freezing_poly, TeosBase::gtc, NULL.
void TeosIce::gsw_frazil_ratios_adiabatic(double sa, double p, double w_ih, double *dsa_dct_frazil, double *dsa_dp_frazil, double *dct_dp_frazil)
References gsw_adiabatic_lapse_rate_ice, gsw_cp_ice, TeosBase::gsw_ct_freezing, gsw_ct_freezing_first_derivatives, TeosBase::gsw_enthalpy_ct_exact, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_t_freezing, gsw_t_freezing_first_derivatives.
void TeosIce::gsw_frazil_ratios_adiabatic_poly(double sa, double p, double w_ih, double *dsa_dct_frazil, double *dsa_dp_frazil, double *dct_dp_frazil)
References gsw_adiabatic_lapse_rate_ice, gsw_cp_ice, gsw_ct_freezing_first_derivatives_poly, gsw_ct_freezing_poly, TeosBase::gsw_enthalpy, TeosBase::gsw_enthalpy_first_derivatives, gsw_enthalpy_ice, gsw_t_freezing_first_derivatives_poly, gsw_t_freezing_poly.
double * TeosIce::gsw_geo_strf_dyn_height_pc(double *sa, double *ct, double *delta_p, int n_levels, double *geo_strf_dyn_height_pc, double *p_mid)
References gsw_enthalpy_diff, TeosBase::gsw_enthalpy_sso_0, NULL.
double TeosIce::gsw_gibbs_ice_part_t(double t, double p)
References GSW_TEOS10_CONSTANTS::db2pa, TeosBase::gic, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc, TeosBase::r1, TeosBase::r20, TeosBase::r21, TeosBase::r22, GSW_GIBBS_ICE_COEFFICIENTS::rec_pt, GSW_GIBBS_ICE_COEFFICIENTS::rec_tt, TeosBase::t1, TeosBase::t2.
Referenced by gsw_pt0_from_t_ice, gsw_pt_from_t_ice.
double TeosIce::gsw_gibbs_ice_pt0(double pt0)
References TeosBase::gic, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc, TeosBase::r1, TeosBase::r20, GSW_GIBBS_ICE_COEFFICIENTS::rec_tt, TeosBase::t1, TeosBase::t2.
Referenced by gsw_pt0_from_t_ice.
double TeosIce::gsw_gibbs_ice_pt0_pt0(double pt0)
References TeosBase::gic, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc, TeosBase::r1, TeosBase::r20, GSW_GIBBS_ICE_COEFFICIENTS::rec_tt, TeosBase::t1, TeosBase::t2.
Referenced by gsw_pt0_from_t_ice.
double TeosIce::gsw_helmholtz_energy_ice(double t, double p)
References GSW_TEOS10_CONSTANTS::db2pa, TeosBase::gsw_gibbs_ice, GSW_TEOS10_CONSTANTS::gsw_p0, TeosBase::gtc.
void TeosIce::gsw_ice_fraction_to_freeze_seawater(double sa, double ct, double p, double t_ih, double *sa_freeze, double *ct_freeze, double *w_ih)
References cppGSW_INVALID_VALUE, TeosBase::gsw_ct_freezing, gsw_ct_freezing_first_derivatives, TeosBase::gsw_enthalpy_ct_exact, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_t_freezing, NULL.
double TeosIce::gsw_internal_energy_ice(double t, double p)
References GSW_TEOS10_CONSTANTS::db2pa, TeosBase::gsw_gibbs_ice, GSW_TEOS10_CONSTANTS::gsw_p0, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc.
void TeosIce::gsw_ipv_vs_fnsquared_ratio(double *sa, double *ct, double *p, double p_ref, int nz, double *ipv_vs_fnsquared_ratio, double *p_mid)
References cppGSW_INVALID_VALUE, TeosBase::gsw_alpha, TeosBase::gsw_beta, p_ref.
double TeosIce::gsw_kappa_const_t_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
double TeosIce::gsw_kappa_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
double TeosIce::gsw_latentheat_melting(double sa, double p)
References TeosBase::gsw_chem_potential_water_t_exact, gsw_enthalpy_ice, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gsw_t_deriv_chem_potential_water_t_exact, TeosBase::gsw_t_freezing, TeosBase::gtc.
double TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio(double sa, double p)
References TeosBase::gsw_ct_freezing, TeosBase::gsw_enthalpy_ct_exact, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_t_freezing.
double TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio_poly(double sa, double p)
References gsw_ct_freezing_poly, TeosBase::gsw_enthalpy, TeosBase::gsw_enthalpy_first_derivatives, gsw_enthalpy_ice, gsw_t_freezing_poly.
void TeosIce::gsw_melting_ice_into_seawater(double sa, double ct, double p, double w_ih, double t_ih, double *sa_final, double *ct_final, double *w_ih_final)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, TeosBase::gsw_ct_freezing, TeosBase::gsw_enthalpy_ct_exact, gsw_enthalpy_ice, gsw_frazil_properties, TeosBase::gsw_t_freezing.
double TeosIce::gsw_melting_ice_sa_ct_ratio(double sa, double ct, double p, double t_ih)
References cppGSW_INVALID_VALUE, TeosBase::gsw_ct_freezing, TeosBase::gsw_enthalpy_ct_exact, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_t_freezing.
double TeosIce::gsw_melting_ice_sa_ct_ratio_poly(double sa, double ct, double p, double t_ih)
References cppGSW_INVALID_VALUE, gsw_ct_freezing_poly, TeosBase::gsw_enthalpy, TeosBase::gsw_enthalpy_first_derivatives, gsw_enthalpy_ice, gsw_t_freezing_poly.
double TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio(double sa, double p)
References TeosBase::gsw_ct_freezing, TeosBase::gsw_enthalpy_ct_exact, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_t_freezing.
double TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio_poly(double sa, double p)
References gsw_ct_freezing_poly, TeosBase::gsw_enthalpy, TeosBase::gsw_enthalpy_first_derivatives, gsw_enthalpy_ice, gsw_t_freezing_poly.
void TeosIce::gsw_melting_seaice_into_seawater(double sa, double ct, double p, double w_seaice, double sa_seaice, double t_seaice, double *sa_final, double *ct_final)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, TeosBase::gsw_ct_freezing, TeosBase::gsw_ct_from_enthalpy_exact, TeosBase::gsw_enthalpy_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_enthalpy_t_exact, gsw_sa_freezing_from_t, TeosBase::gsw_t_freezing.
double TeosIce::gsw_melting_seaice_sa_ct_ratio(double sa, double ct, double p, double sa_seaice, double t_seaice)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, TeosBase::gsw_ct_freezing, TeosBase::gsw_enthalpy_ct_exact, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_enthalpy_t_exact, gsw_sa_freezing_from_t, TeosBase::gsw_t_freezing.
double TeosIce::gsw_melting_seaice_sa_ct_ratio_poly(double sa, double ct, double p, double sa_seaice, double t_seaice)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, gsw_ct_freezing_poly, TeosBase::gsw_ct_from_t, TeosBase::gsw_enthalpy, TeosBase::gsw_enthalpy_first_derivatives, gsw_enthalpy_ice, gsw_sa_freezing_from_t_poly, gsw_t_freezing_poly.
void TeosIce::gsw_nsquared(double *sa, double *ct, double *p, double *lat, int nz, double *n2, double *p_mid)
References GSW_TEOS10_CONSTANTS::db2pa, TeosBase::gsw_alpha, TeosBase::gsw_beta, TeosBase::gsw_grav, TeosBase::gsw_rho, TeosBase::gtc.
double TeosIce::gsw_pot_enthalpy_ice_freezing(double sa, double p)
References TeosBase::gsw_pot_enthalpy_from_pt_ice, gsw_pt0_from_t_ice, TeosBase::gsw_t_freezing.
Referenced by gsw_frazil_properties_potential.
void TeosIce::gsw_pot_enthalpy_ice_freezing_first_derivatives(double sa, double p, double *pot_enthalpy_ice_freezing_sa, double *pot_enthalpy_ice_freezing_p)
References gsw_cp_ice, TeosBase::gsw_gibbs_ice, gsw_pt0_from_t_ice, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gsw_t_freezing, gsw_t_freezing_first_derivatives, TeosBase::gtc, NULL.
Referenced by gsw_frazil_properties_potential.
double TeosIce::gsw_pot_enthalpy_from_pt_ice_poly(double pt0_ice)
References gsw_pt_from_pot_enthalpy_ice_poly, gsw_pt_from_pot_enthalpy_ice_poly_dh.
double TeosIce::gsw_pot_enthalpy_from_specvol_ice(double specvol_ice, double p)
References TeosBase::gsw_pot_enthalpy_from_pt_ice, gsw_pt0_from_t_ice, gsw_t_from_rho_ice.
double TeosIce::gsw_pressure_coefficient_ice(double t, double p)
double TeosIce::gsw_pressure_freezing_ct(double sa, double ct, double saturation_fraction)
References cppGSW_INVALID_VALUE, TeosBase::gsw_ct_freezing, gsw_ct_freezing_first_derivatives, gsw_sa_p_inrange, TeosBase::gtc, NULL, GSW_TEOS10_CONSTANTS::rec_pa2db.
double TeosIce::gsw_pt_from_pot_enthalpy_ice(double pot_enthalpy_ice)
References gsw_cp_ice, TeosBase::gsw_max_d, TeosBase::gsw_pot_enthalpy_from_pt_ice, gsw_pt0_cold_ice_poly, gsw_pt_from_pot_enthalpy_ice_poly, gsw_pt_from_pot_enthalpy_ice_poly_dh.
Referenced by gsw_specvol_from_pot_enthalpy_ice.
double TeosIce::gsw_pt_from_pot_enthalpy_ice_poly(double pot_enthalpy_ice)
Referenced by gsw_pot_enthalpy_from_pt_ice_poly, gsw_pt_from_pot_enthalpy_ice.
double TeosIce::gsw_pt_from_pot_enthalpy_ice_poly_dh(double pot_enthalpy_ice)
Referenced by gsw_pot_enthalpy_from_pt_ice_poly, gsw_pt_from_pot_enthalpy_ice.
double TeosIce::gsw_pt_from_t_ice(double t, double p, double p_ref)
References TeosBase::gsw_gibbs_ice, gsw_gibbs_ice_part_t, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc, p_ref.
Referenced by gsw_t_from_pt0_ice.
double TeosIce::gsw_pt0_cold_ice_poly(double pot_enthalpy_ice)
References GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc.
Referenced by gsw_pt_from_pot_enthalpy_ice.
double TeosIce::gsw_rho_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
double TeosIce::gsw_sa_freezing_estimate(double p, double saturation_fraction, double *ct, double *t)
References TeosBase::gsw_ct_from_t, TeosBase::gsw_max_d, GSW_TEOS10_CONSTANTS::gsw_sso, TeosBase::gtc, NULL.
Referenced by gsw_sa_freezing_from_ct, gsw_sa_freezing_from_ct_poly, gsw_sa_freezing_from_t, gsw_sa_freezing_from_t_poly.
double TeosIce::gsw_sa_freezing_from_ct(double ct, double p, double saturation_fraction)
References cppGSW_INVALID_VALUE, TeosBase::gsw_ct_freezing, gsw_ct_freezing_first_derivatives, TeosBase::gsw_max_d, gsw_sa_freezing_estimate, gsw_sa_p_inrange, NULL.
double TeosIce::gsw_sa_freezing_from_ct_poly(double ct, double p, double saturation_fraction)
References cppGSW_INVALID_VALUE, gsw_ct_freezing_first_derivatives_poly, gsw_ct_freezing_poly, TeosBase::gsw_max_d, gsw_sa_freezing_estimate, gsw_sa_p_inrange, NULL.
double TeosIce::gsw_sa_freezing_from_t(double t, double p, double saturation_fraction)
References cppGSW_INVALID_VALUE, TeosBase::gsw_max_d, gsw_sa_freezing_estimate, gsw_sa_p_inrange, TeosBase::gsw_t_freezing, gsw_t_freezing_first_derivatives, NULL.
Referenced by gsw_melting_seaice_into_seawater, gsw_melting_seaice_sa_ct_ratio, gsw_seaice_fraction_to_freeze_seawater.
double TeosIce::gsw_sa_freezing_from_t_poly(double t, double p, double saturation_fraction)
References cppGSW_INVALID_VALUE, TeosBase::gsw_max_d, gsw_sa_freezing_estimate, gsw_sa_p_inrange, gsw_t_freezing_first_derivatives_poly, gsw_t_freezing_poly, NULL.
Referenced by gsw_melting_seaice_sa_ct_ratio_poly.
int TeosIce::gsw_sa_p_inrange(double sa, double p)
Referenced by gsw_pressure_freezing_ct, gsw_sa_freezing_from_ct, gsw_sa_freezing_from_ct_poly, gsw_sa_freezing_from_t, gsw_sa_freezing_from_t_poly.
void TeosIce::gsw_seaice_fraction_to_freeze_seawater(double sa, double ct, double p, double sa_seaice, double t_seaice, double *sa_freeze, double *ct_freeze, double *w_seaice)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, TeosBase::gsw_ct_freezing, gsw_ct_freezing_first_derivatives, TeosBase::gsw_enthalpy_ct_exact, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_ice, TeosBase::gsw_enthalpy_t_exact, gsw_sa_freezing_from_t, TeosBase::gsw_t_freezing, NULL.
double TeosIce::gsw_specvol_from_pot_enthalpy_ice(double pot_enthalpy_ice, double p)
References gsw_pt_from_pot_enthalpy_ice, gsw_specvol_ice, gsw_t_from_pt0_ice.
double TeosIce::gsw_specvol_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
Referenced by gsw_specvol_from_pot_enthalpy_ice, gsw_t_freezing_first_derivatives, gsw_t_from_rho_ice.
double TeosIce::gsw_sound_speed_ice(double t, double p)
References TeosBase::gsw_gibbs_ice.
double TeosIce::gsw_pt0_from_t_ice(double t, double p)
References gsw_gibbs_ice_part_t, gsw_gibbs_ice_pt0, gsw_gibbs_ice_pt0_pt0, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc.
Referenced by gsw_pot_enthalpy_from_specvol_ice, gsw_pot_enthalpy_ice_freezing, gsw_pot_enthalpy_ice_freezing_first_derivatives.
double TeosIce::gsw_t_freezing_exact(double sa, double p, double saturation_fraction)
References TeosBase::gsw_chem_potential_water_t_exact, TeosBase::gsw_gibbs_ice, GSW_TEOS10_CONSTANTS::gsw_sso, TeosBase::gsw_t_deriv_chem_potential_water_t_exact, gsw_t_freezing_poly, TeosBase::gtc.
Referenced by gsw_ct_freezing_exact.
void TeosIce::gsw_t_freezing_first_derivatives(double sa, double p, double saturation_fraction, double *tfreezing_sa, double *tfreezing_p)
References TeosBase::gsw_dilution_coefficient_t_exact, gsw_entropy_ice, TeosBase::gsw_gibbs, gsw_specvol_ice, TeosBase::gsw_specvol_t_exact, GSW_TEOS10_CONSTANTS::gsw_sso, TeosBase::gsw_t_deriv_chem_potential_water_t_exact, TeosBase::gsw_t_freezing, TeosBase::gtc, NULL.
Referenced by gsw_ct_freezing_first_derivatives, gsw_frazil_properties, gsw_frazil_ratios_adiabatic, gsw_pot_enthalpy_ice_freezing_first_derivatives, gsw_sa_freezing_from_t.
void TeosIce::gsw_t_freezing_first_derivatives_poly(double sa, double p, double saturation_fraction, double *tfreezing_sa, double *tfreezing_p)
References TeosBase::gfpc, GSW_TEOS10_CONSTANTS::gsw_sso, TeosBase::gtc, NULL, GSW_FREEZING_POLY_COEFFICIENTS::t1, GSW_FREEZING_POLY_COEFFICIENTS::t10, GSW_FREEZING_POLY_COEFFICIENTS::t11, GSW_FREEZING_POLY_COEFFICIENTS::t12, GSW_FREEZING_POLY_COEFFICIENTS::t13, GSW_FREEZING_POLY_COEFFICIENTS::t14, GSW_FREEZING_POLY_COEFFICIENTS::t15, GSW_FREEZING_POLY_COEFFICIENTS::t16, GSW_FREEZING_POLY_COEFFICIENTS::t17, GSW_FREEZING_POLY_COEFFICIENTS::t18, GSW_FREEZING_POLY_COEFFICIENTS::t19, GSW_FREEZING_POLY_COEFFICIENTS::t2, GSW_FREEZING_POLY_COEFFICIENTS::t20, GSW_FREEZING_POLY_COEFFICIENTS::t21, GSW_FREEZING_POLY_COEFFICIENTS::t22, GSW_FREEZING_POLY_COEFFICIENTS::t3, GSW_FREEZING_POLY_COEFFICIENTS::t4, GSW_FREEZING_POLY_COEFFICIENTS::t5, GSW_FREEZING_POLY_COEFFICIENTS::t6, GSW_FREEZING_POLY_COEFFICIENTS::t7, GSW_FREEZING_POLY_COEFFICIENTS::t8, GSW_FREEZING_POLY_COEFFICIENTS::t9.
Referenced by gsw_frazil_ratios_adiabatic_poly, gsw_sa_freezing_from_t_poly.
double TeosIce::gsw_t_freezing_poly(double sa, double p, double saturation_fraction=0.0)
References gsw_ct_freezing_poly, TeosBase::gsw_t_from_ct.
Referenced by gsw_frazil_ratios_adiabatic_poly, gsw_melting_ice_equilibrium_sa_ct_ratio_poly, gsw_melting_ice_sa_ct_ratio_poly, gsw_melting_seaice_equilibrium_sa_ct_ratio_poly, gsw_melting_seaice_sa_ct_ratio_poly, gsw_sa_freezing_from_t_poly, gsw_t_freezing_exact.
double TeosIce::gsw_t_freezing_poly(double sa, double p, double saturation_fraction, int polynomial)
References TeosBase::gfpc, gsw_ct_freezing_poly, GSW_TEOS10_CONSTANTS::gsw_sso, TeosBase::gsw_t_from_ct, TeosBase::gtc, GSW_FREEZING_POLY_COEFFICIENTS::t0, GSW_FREEZING_POLY_COEFFICIENTS::t1, GSW_FREEZING_POLY_COEFFICIENTS::t10, GSW_FREEZING_POLY_COEFFICIENTS::t11, GSW_FREEZING_POLY_COEFFICIENTS::t12, GSW_FREEZING_POLY_COEFFICIENTS::t13, GSW_FREEZING_POLY_COEFFICIENTS::t14, GSW_FREEZING_POLY_COEFFICIENTS::t15, GSW_FREEZING_POLY_COEFFICIENTS::t16, GSW_FREEZING_POLY_COEFFICIENTS::t17, GSW_FREEZING_POLY_COEFFICIENTS::t18, GSW_FREEZING_POLY_COEFFICIENTS::t19, GSW_FREEZING_POLY_COEFFICIENTS::t2, GSW_FREEZING_POLY_COEFFICIENTS::t20, GSW_FREEZING_POLY_COEFFICIENTS::t21, GSW_FREEZING_POLY_COEFFICIENTS::t22, GSW_FREEZING_POLY_COEFFICIENTS::t3, GSW_FREEZING_POLY_COEFFICIENTS::t4, GSW_FREEZING_POLY_COEFFICIENTS::t5, GSW_FREEZING_POLY_COEFFICIENTS::t6, GSW_FREEZING_POLY_COEFFICIENTS::t7, GSW_FREEZING_POLY_COEFFICIENTS::t8, GSW_FREEZING_POLY_COEFFICIENTS::t9.
double TeosIce::gsw_t_from_pt0_ice(double pt0_ice, double p)
References gsw_pt_from_t_ice.
Referenced by gsw_specvol_from_pot_enthalpy_ice.
double TeosIce::gsw_t_from_rho_ice(double rho_ice, double p)
References TeosBase::gsw_gibbs_ice, gsw_specvol_ice, TeosBase::gsw_t_freezing.
Referenced by gsw_pot_enthalpy_from_specvol_ice.