Piston
state_piston
rclcpp::Node* Piston::n_
Referenced by get_all_data, i2c_open, Piston, set_piston_exit, set_piston_regulation, set_piston_reset, set_position, set_regulation_dead_zone, set_regulation_proportional.
int Piston::file_
Pointer to rclcpp Node.
Referenced by get_all_data, get_version, i2c_open, set_piston_exit, set_piston_regulation, set_piston_reset, set_position, set_regulation_dead_zone, set_regulation_proportional, ~Piston.
std::string Piston::i2c_periph_
File to the i2c port.
Referenced by getI2CPeriph, i2c_open, setI2CPeriph.
int Piston::i2c_addr_
Referenced by getI2CAddr, i2c_open, setI2CAddr.
const int Piston::code_version_
Referenced by i2c_open.
uint8_t Piston::pic_code_version_
Code version of the expected hardware.
Referenced by get_version.
double Piston::R1_
Code version read from the hardware.
Bridge
Referenced by get_all_data, PistonNode::init_parameters.
double Piston::R2_
Referenced by get_all_data, PistonNode::init_parameters.
int Piston::position_
Referenced by get_all_data, PistonNode::timer_callback.
int Piston::position_last_
Referenced by get_all_data.
bool Piston::switch_top_
Referenced by get_all_data, PistonNode::timer_callback.
bool Piston::switch_bottom_
Referenced by get_all_data, PistonNode::timer_callback.
int Piston::state_
Referenced by get_all_data, PistonNode::timer_callback, PistonNode::topic_position_set_point_callback.
bool Piston::enable_
Referenced by get_all_data, PistonNode::timer_callback.
int Piston::position_set_point_
Referenced by get_all_data, PistonNode::timer_callback, PistonNode::topic_position_set_point_callback.
float Piston::battery_voltage_
Referenced by get_all_data, PistonNode::timer_callback.
float Piston::motor_current_
Referenced by get_all_data, PistonNode::timer_callback.
int Piston::motor_set_point_
Referenced by get_all_data, PistonNode::timer_callback.
int Piston::motor_cmd_
Referenced by get_all_data, PistonNode::timer_callback.
bool Piston::motor_sens_
Referenced by get_all_data, PistonNode::timer_callback.
Piston::Piston(rclcpp::Node *n)
Piston.
References n_.
Piston::~Piston()
References file_.
int Piston::i2c_open()
Open the I2C device.
References code_version_, file_, get_version, i2c_addr_, i2c_periph_, n_.
Referenced by PistonNode::PistonNode.
uint8_t & Piston::get_version()
get the version of the pic software version
References file_, pic_code_version_.
Referenced by i2c_open.
int Piston::getI2CAddr() const
References i2c_addr_.
Referenced by PistonNode::init_parameters.
void Piston::setI2CAddr(int i2CAddr)
References i2c_addr_.
Referenced by PistonNode::init_parameters.
const std::string & Piston::getI2CPeriph() const
References i2c_periph_.
Referenced by PistonNode::init_parameters.
void Piston::setI2CPeriph(const std::string &i2CPeriph)
References i2c_periph_.
Referenced by PistonNode::init_parameters.
int Piston::set_piston_reset() const
Reset the piston to position 0
References file_, n_, PISTON_SEARCH_SWITCH_BOTTOM, REGISTER_STATE.
Referenced by PistonNode::PistonNode, PistonNode::topic_position_set_point_callback.
int Piston::set_piston_exit() const
Set piston exit mode
References file_, n_, PISTON_EXIT, REGISTER_STATE, set_position.
Referenced by PistonNode::timer_callback, PistonNode::topic_position_set_point_callback.
int Piston::set_piston_regulation() const
References file_, n_, PISTON_REGULATION, REGISTER_STATE.
Referenced by PistonNode::topic_position_set_point_callback.
void Piston::set_regulation_dead_zone(const __u16 &val) const
Set the regulation dead zone val interval of ticks
References file_, n_, REGISTER_REGULATION_DEAD_ZONE.
void Piston::set_regulation_proportional(const __u16 &val) const
Set the coefficient Kp of the regulator val
References file_, n_, REGISTER_REGULATION_PROPORTIONAL.
int Piston::set_position(const int32_t &val) const
Set the position of the piston val
References file_, n_, REGISTER_SET_POINT.
Referenced by set_piston_exit, PistonNode::topic_position_set_point_callback.
int Piston::get_all_data()
Get data from dspic
References battery_voltage_, CONVERSION_BRIDGE, CONVERSION_CURRENT, enable_, file_, motor_cmd_, motor_current_, motor_sens_, motor_set_point_, n_, position_, position_last_, position_set_point_, R1_, R2_, REGISTER_DATA_READ, REGISTER_DATA_SIZE, state_, switch_bottom_, switch_top_.
Referenced by PistonNode::timer_callback.