TLV320ADC
AdcGain
rclcpp::Node* TLV320ADC::n_
Referenced by i2c_open, set_adc_gain, set_channel_enable, set_channel_parameters, set_channel_slot, set_i2s_32bit, set_page, set_power_up, set_reset, set_wake_up, TLV320ADC.
int TLV320ADC::file_
Pointer to rclcpp Node.
Referenced by i2c_open, set_adc_gain, set_channel_enable, set_channel_parameters, set_channel_slot, set_i2s_32bit, set_page, set_power_up, set_reset, set_wake_up, ~TLV320ADC.
std::string TLV320ADC::i2c_periph_
File to the i2c port.
Referenced by getI2CPeriph, i2c_open, setI2CPeriph.
int TLV320ADC::i2c_addr_
Referenced by getI2CAddr, i2c_open, setI2CAddr.
TLV320ADC::TLV320ADC(rclcpp::Node *n)
TLV320ADC.
References n_.
TLV320ADC::~TLV320ADC()
References file_.
int TLV320ADC::i2c_open()
Open the I2C device.
References file_, i2c_addr_, i2c_periph_, n_.
int TLV320ADC::configure(uint8_t gain) const
References set_adc_gain, set_channel_enable, set_channel_parameters, set_channel_slot, set_i2s_32bit, set_page, set_power_up, set_reset, set_wake_up.
int TLV320ADC::set_channel_parameters() const
References file_, n_.
Referenced by configure.
int TLV320ADC::set_power_up() const
References file_, n_.
Referenced by configure.
int TLV320ADC::getI2CAddr() const
References i2c_addr_.
void TLV320ADC::setI2CAddr(int i2CAddr)
References i2c_addr_.
const std::string & TLV320ADC::getI2CPeriph() const
References i2c_periph_.
void TLV320ADC::setI2CPeriph(const std::string &i2CPeriph)
References i2c_periph_.
int TLV320ADC::set_adc_gain(uint8_t gain_ch1, uint8_t gain_ch2) const
References file_, n_.
Referenced by configure.
int TLV320ADC::set_wake_up() const
References file_, n_.
Referenced by configure.
int TLV320ADC::set_reset() const
References file_, n_.
Referenced by configure.
int TLV320ADC::set_page(uint8_t page) const
References file_, n_.
Referenced by configure.
int TLV320ADC::set_i2s_32bit() const
References file_, n_.
Referenced by configure.
int TLV320ADC::set_channel_slot() const
References file_, n_.
Referenced by configure.
int TLV320ADC::set_channel_enable() const
References file_, n_.
Referenced by configure.
int TLV320ADC::set_enable_channel() const
int TLV320ADC::set_enable_input_ch1(uint8_t ch1, uint8_t ch2) const
int TLV320ADC::set_enable_input(uint8_t ch1, uint8_t ch2) const