GpsdNode
gpsmm* GpsdNode::gps_
Variables.
Referenced by GpsdNode, timer_callback, ~GpsdNode.
string GpsdNode::frame_id_
Referenced by init_parameters, process_data.
bool GpsdNode::last_msg_no_fix_
Referenced by process_data.
bool GpsdNode::publish_when_no_fix_
Referenced by init_parameters, process_data.
rclcpp::TimerBase::SharedPtr GpsdNode::timer_
Rclcpp.
Referenced by GpsdNode.
std::chrono::milliseconds GpsdNode::loop_dt_
Referenced by GpsdNode, init_parameters.
rclcpp::Publisher<seabot2_msgs::msg::GpsFix>::SharedPtr GpsdNode::publisher_fix_
Topics / Services.
Referenced by init_interfaces, process_data.
rclcpp::Publisher<seabot2_msgs::msg::GpsPps>::SharedPtr GpsdNode::publisher_pps_
Referenced by init_interfaces, process_data.
GpsdNode::GpsdNode()
References gps_, init_interfaces, init_parameters, loop_dt_, timer_, timer_callback.
GpsdNode::~GpsdNode()
References gps_.
void GpsdNode::init_parameters()
Init and get parameters of the Node
References frame_id_, loop_dt_, publish_when_no_fix_.
Referenced by GpsdNode.
void GpsdNode::init_interfaces()
Init topics to this node (publishers & subscribers)
References publisher_fix_, publisher_pps_.
Referenced by GpsdNode.
void GpsdNode::process_data(const struct gps_data_t *p)
Process the data recevied from gpsd to send a ros message p
References frame_id_, last_msg_no_fix_, publish_when_no_fix_, publisher_fix_, publisher_pps_.
Referenced by timer_callback.
void GpsdNode::timer_callback()
Callback of the timer
References gps_, process_data.
Referenced by GpsdNode.