HeadingControlNode
rclcpp::TimerBase::SharedPtr HeadingControlNode::timer_
Referenced by HeadingControlNode.
std::chrono::milliseconds HeadingControlNode::loop_dt_
Referenced by HeadingControlNode, init_parameters.
double HeadingControlNode::angular_velocity_max_
loop dt
Referenced by cmd_vel_heading_callback, init_parameters.
std::chrono::milliseconds HeadingControlNode::delay_stop_
Referenced by HeadingControlNode, init_parameters, timer_callback.
double HeadingControlNode::heading_
Referenced by cmd_vel_heading_callback, imu_callback.
double HeadingControlNode::angular_cmd_
Referenced by cmd_vel_heading_callback, timer_callback.
double HeadingControlNode::linear_cmd_
Referenced by cmd_vel_heading_callback, timer_callback.
rclcpp::Time HeadingControlNode::velocity_heading_time_last_
Referenced by cmd_vel_heading_callback, HeadingControlNode, timer_callback.
rclcpp::Subscription<seabot2_msgs::msg::RPY>::SharedPtr HeadingControlNode::imu_sub_
Referenced by init_interfaces.
rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr HeadingControlNode::cmd_vel_heading_sub_
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::Velocity>::SharedPtr HeadingControlNode::control_pub_
Referenced by init_interfaces, timer_callback.
HeadingControlNode::HeadingControlNode()
References delay_stop_, init_interfaces, init_parameters, loop_dt_, timer_, timer_callback, velocity_heading_time_last_.
void HeadingControlNode::init_parameters()
Init and get parameters of the Node
References angular_velocity_max_, delay_stop_, loop_dt_.
Referenced by HeadingControlNode.
void HeadingControlNode::init_interfaces()
Init interfaces of this node
References cmd_vel_heading_callback, cmd_vel_heading_sub_, control_pub_, imu_callback, imu_sub_.
Referenced by HeadingControlNode.
void HeadingControlNode::timer_callback()
Timer callback
References angular_cmd_, control_pub_, delay_stop_, linear_cmd_, velocity_heading_time_last_.
Referenced by HeadingControlNode.
void HeadingControlNode::imu_callback(const seabot2_msgs::msg::RPY &msg)
References heading_, M_PI.
Referenced by init_interfaces.
void HeadingControlNode::cmd_vel_heading_callback(const geometry_msgs::msg::Twist &msg)
References angular_cmd_, angular_velocity_max_, heading_, linear_cmd_, M_PI, sawtooth, velocity_heading_time_last_.
Referenced by init_interfaces.