DspicAcoustic
rclcpp::Node* DspicAcoustic::n_
Referenced by DspicAcoustic, enable_chirp, get_posix_time, i2c_open, recompute_chirp, set_duration_between_shoot, set_robot_code, set_robot_data, set_shoot_offset_from_posix_zero, sync_pps.
int DspicAcoustic::file_
Pointer to rclcpp Node.
Referenced by enable_chirp, get_frequency_middle, get_frequency_range, get_posix_time, get_robot_code, get_signal_function, get_signal_number, i2c_open, recompute_chirp, set_duration_between_shoot, set_robot_code, set_robot_data, set_shoot_offset_from_posix_zero, sync_pps, wait_recompute_signal, ~DspicAcoustic.
std::string DspicAcoustic::i2c_periph_
File to the i2c port.
Referenced by getI2CPeriph, i2c_open, setI2CPeriph.
int DspicAcoustic::i2c_addr_
Referenced by getI2CAddr, i2c_open, setI2CAddr.
int DspicAcoustic::code_version
DspicAcoustic::DspicAcoustic(rclcpp::Node *n)
DspicAcoustic.
References n_.
DspicAcoustic::~DspicAcoustic()
References file_.
int DspicAcoustic::i2c_open()
Open the I2C device.
References file_, i2c_addr_, i2c_periph_, n_.
Referenced by AudioRecorderNode::AudioRecorderNode.
void DspicAcoustic::wait_recompute_signal() const
References file_.
Referenced by AudioRecorderNode::AudioRecorderNode.
int DspicAcoustic::getI2CAddr() const
References i2c_addr_.
void DspicAcoustic::setI2CAddr(int i2CAddr)
References i2c_addr_.
const std::string & DspicAcoustic::getI2CPeriph() const
References i2c_periph_.
void DspicAcoustic::setI2CPeriph(const std::string &i2CPeriph)
References i2c_periph_.
void DspicAcoustic::sync_pps() const
References file_, n_.
Referenced by AudioRecorderNode::AudioRecorderNode, AudioRecorderNode::timer_callback.
int DspicAcoustic::enable_chirp(bool enable=true) const
References file_, n_.
Referenced by AudioRecorderNode::AudioRecorderNode, AudioRecorderNode::chirp_callback, AudioRecorderNode::~AudioRecorderNode.
int DspicAcoustic::set_duration_between_shoot(uint16_t duration_seconds) const
References file_, n_.
Referenced by AudioRecorderNode::AudioRecorderNode.
int DspicAcoustic::set_shoot_offset_from_posix_zero(uint16_t offset_seconds) const
References file_, n_.
Referenced by AudioRecorderNode::AudioRecorderNode.
int DspicAcoustic::set_robot_data(const int &data_size, const uint64_t &data) const
References file_, n_.
int DspicAcoustic::recompute_chirp(const uint16_t &frequency_middle, const uint16_t &frequency_range, const uint8_t &signal_function) const
References file_, n_.
Referenced by AudioRecorderNode::AudioRecorderNode.
int DspicAcoustic::get_frequency_middle() const
References file_.
Referenced by AudioRecorderNode::AudioRecorderNode.
int DspicAcoustic::get_frequency_range() const
References file_.
Referenced by AudioRecorderNode::AudioRecorderNode.
int DspicAcoustic::get_signal_function() const
References file_.
Referenced by AudioRecorderNode::AudioRecorderNode.
int DspicAcoustic::set_robot_code(const uint8_t &robot_code) const
References file_, n_.
Referenced by AudioRecorderNode::AudioRecorderNode.
int DspicAcoustic::get_robot_code() const
References file_.
uint32_t DspicAcoustic::get_posix_time() const
References file_, n_.
Referenced by AudioRecorderNode::timer_callback.
uint16_t DspicAcoustic::get_signal_number() const
References file_.
Referenced by AudioRecorderNode::timer_callback.