AudioRecorderNode
int AudioRecorderNode::audio_frequency_
Referenced by get_arecord_command, init_parameters.
int AudioRecorderNode::audio_max_file_time_
Referenced by get_arecord_command, init_parameters.
int AudioRecorderNode::audio_nb_channels_
Referenced by get_arecord_command, init_parameters.
int AudioRecorderNode::audio_nb_bits_
Referenced by get_arecord_command, init_parameters.
std::string AudioRecorderNode::audio_device_
Referenced by get_arecord_command, init_parameters.
std::string AudioRecorderNode::audio_command_last_
Referenced by manage_subprocess, wait_kill.
int AudioRecorderNode::audio_hdd_space_limit_stop_
Referenced by init_parameters, timer_callback.
std::string AudioRecorderNode::audio_save_directory_
Referenced by AudioRecorderNode, init_parameters.
rclcpp::TimerBase::SharedPtr AudioRecorderNode::timer_
Rclcpp.
Referenced by AudioRecorderNode.
std::chrono::milliseconds AudioRecorderNode::loop_safety_dt_
Referenced by AudioRecorderNode, init_parameters.
rclcpp::CallbackGroup::SharedPtr AudioRecorderNode::callback_group_
Referenced by AudioRecorderNode.
std::string AudioRecorderNode::workingDirectory_
Referenced by AudioRecorderNode, timer_callback.
bool AudioRecorderNode::thread_currently_running_
Referenced by manage_subprocess, timer_callback, wait_kill.
std::future< int > AudioRecorderNode::subprocessFuture_
Referenced by manage_subprocess, timer_callback, wait_kill.
TLV320ADC AudioRecorderNode::tlv_
DspicAcoustic AudioRecorderNode::dspic_
Referenced by AudioRecorderNode, chirp_callback, timer_callback, ~AudioRecorderNode.
uint8_t AudioRecorderNode::gain_ch1_
Referenced by init_parameters.
uint8_t AudioRecorderNode::gain_ch2_
Referenced by init_parameters.
uint16_t AudioRecorderNode::robot_code_
Referenced by AudioRecorderNode, init_parameters.
uint16_t AudioRecorderNode::duration_between_shoot_
Referenced by AudioRecorderNode, init_parameters.
uint16_t AudioRecorderNode::time_slot_duration_
Referenced by AudioRecorderNode, init_parameters.
bool AudioRecorderNode::enable_sound_tx_
Referenced by chirp_callback, init_parameters.
bool AudioRecorderNode::enable_chirp_
Referenced by AudioRecorderNode, chirp_callback, init_parameters.
uint16_t AudioRecorderNode::frequency_middle_
Referenced by AudioRecorderNode, init_parameters.
uint16_t AudioRecorderNode::frequency_range_
Referenced by AudioRecorderNode, init_parameters.
uint8_t AudioRecorderNode::signal_function_
Referenced by AudioRecorderNode, init_parameters.
bool AudioRecorderNode::gnss_fix_once_
Referenced by gpsd_callback, timer_callback.
bool AudioRecorderNode::dspic_posix_fix_
Referenced by timer_callback.
rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr AudioRecorderNode::service_rosbag_
Interfaces.
Referenced by init_interfaces.
rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr AudioRecorderNode::service_chirp_
Referenced by init_interfaces.
rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr AudioRecorderNode::publisher_record_
Referenced by init_interfaces, manage_subprocess.
rclcpp::Publisher<seabot2_msgs::msg::SyncDspic>::SharedPtr AudioRecorderNode::publisher_dspic_debug_
Referenced by init_interfaces, timer_callback.
rclcpp::Subscription<seabot2_msgs::msg::GpsFix>::SharedPtr AudioRecorderNode::subscriber_gnss_data_
Referenced by init_interfaces.
AudioRecorderNode::AudioRecorderNode()
References audio_save_directory_, callback_group_, dspic_, duration_between_shoot_, DspicAcoustic::enable_chirp, enable_chirp_, frequency_middle_, frequency_range_, DspicAcoustic::get_frequency_middle, DspicAcoustic::get_frequency_range, DspicAcoustic::get_signal_function, DspicAcoustic::i2c_open, init_interfaces, init_parameters, loop_safety_dt_, manage_subprocess, DspicAcoustic::recompute_chirp, robot_code_, DspicAcoustic::set_duration_between_shoot, DspicAcoustic::set_robot_code, DspicAcoustic::set_shoot_offset_from_posix_zero, signal_function_, DspicAcoustic::sync_pps, time_slot_duration_, timer_, timer_callback, DspicAcoustic::wait_recompute_signal, workingDirectory_.
AudioRecorderNode::~AudioRecorderNode() override
References dspic_, DspicAcoustic::enable_chirp, wait_kill.
std::string AudioRecorderNode::get_arecord_command() const
References audio_device_, audio_frequency_, audio_max_file_time_, audio_nb_bits_, audio_nb_channels_.
Referenced by manage_subprocess.
void AudioRecorderNode::manage_subprocess(bool start_new_audio)
Parameters.
Functions
References audio_command_last_, get_arecord_command, publisher_record_, subprocessFuture_, thread_currently_running_, wait_kill.
Referenced by AudioRecorderNode, callback_trigger, timer_callback.
void AudioRecorderNode::wait_kill()
References audio_command_last_, subprocessFuture_, thread_currently_running_.
Referenced by manage_subprocess, ~AudioRecorderNode.
void AudioRecorderNode::init_parameters()
Init and get parameters of the Node
References audio_device_, audio_frequency_, audio_hdd_space_limit_stop_, audio_max_file_time_, audio_nb_bits_, audio_nb_channels_, audio_save_directory_, duration_between_shoot_, enable_chirp_, enable_sound_tx_, frequency_middle_, frequency_range_, gain_ch1_, gain_ch2_, loop_safety_dt_, robot_code_, signal_function_, time_slot_duration_.
Referenced by AudioRecorderNode.
void AudioRecorderNode::init_interfaces()
Init interfaces to this node (publishers & subscribers)
References callback_trigger, chirp_callback, gpsd_callback, publisher_dspic_debug_, publisher_record_, service_chirp_, service_rosbag_, subscriber_gnss_data_.
Referenced by AudioRecorderNode.
void AudioRecorderNode::callback_trigger(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< std_srvs::srv::SetBool::Request > request, std::shared_ptr< std_srvs::srv::SetBool::Response > response)
Callback for the service trigger request_header request response
References manage_subprocess.
Referenced by init_interfaces.
void AudioRecorderNode::gpsd_callback(const seabot2_msgs::msg::GpsFix &msg)
msg
References gnss_fix_once_.
Referenced by init_interfaces.
void AudioRecorderNode::timer_callback()
References audio_hdd_space_limit_stop_, dspic_, dspic_posix_fix_, DspicAcoustic::get_posix_time, DspicAcoustic::get_signal_number, gnss_fix_once_, manage_subprocess, publisher_dspic_debug_, subprocessFuture_, DspicAcoustic::sync_pps, thread_currently_running_, workingDirectory_.
Referenced by AudioRecorderNode.
void AudioRecorderNode::chirp_callback(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< std_srvs::srv::SetBool::Request > request, std::shared_ptr< std_srvs::srv::SetBool::Response > response)
Callback for the service chirp request_header request response
References dspic_, DspicAcoustic::enable_chirp, enable_chirp_, enable_sound_tx_.
Referenced by init_interfaces.