LambertNode
PJ_CONTEXT* LambertNode::C_
Variable.
Referenced by LambertNode.
PJ* LambertNode::P_
Referenced by gnss_callback, LambertNode.
PJ* LambertNode::P_for_GIS_
Referenced by LambertNode.
string LambertNode::epsg_source_
Referenced by init_parameters, LambertNode.
string LambertNode::epsg_target_
Referenced by init_parameters, LambertNode.
deque<double> LambertNode::east_memory_
Referenced by compute_mean, gnss_callback.
deque<double> LambertNode::north_memory_
Referenced by compute_mean, gnss_callback.
deque<rclcpp::Time> LambertNode::time_memory_
Referenced by compute_mean, gnss_callback.
std::chrono::seconds LambertNode::filter_position_mean_
Referenced by compute_mean, init_parameters.
std::chrono::seconds LambertNode::filter_dt_heading_computation_
Referenced by gnss_callback, init_parameters.
rclcpp::Subscription<seabot2_msgs::msg::GpsFix>::SharedPtr LambertNode::subscriber_gnss_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::GnssPose>::SharedPtr LambertNode::publisher_lambert_data_
Referenced by gnss_callback, init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::GnssPose>::SharedPtr LambertNode::publisher_lambert_mean_data_
Referenced by compute_mean, init_interfaces.
LambertNode::LambertNode()
References C_, epsg_source_, epsg_target_, init_interfaces, init_parameters, P_, P_for_GIS_.
void LambertNode::init_parameters()
Functions.
Init and get parameters of the Node
References epsg_source_, epsg_target_, filter_dt_heading_computation_, filter_position_mean_.
Referenced by LambertNode.
void LambertNode::init_interfaces()
Init interfaces of this node
References gnss_callback, publisher_lambert_data_, publisher_lambert_mean_data_, subscriber_gnss_data_.
Referenced by LambertNode.
void LambertNode::gnss_callback(const seabot2_msgs::msg::GpsFix &msg)
Callback of the external pressure msg
References compute_mean, east_memory_, filter_dt_heading_computation_, north_memory_, P_, publisher_lambert_data_, time_memory_.
Referenced by init_interfaces.
void LambertNode::compute_mean()
Compute mean position and heading
References east_memory_, filter_position_mean_, M_PI, north_memory_, publisher_lambert_mean_data_, time_memory_.
Referenced by gnss_callback.