LogData
MSG_TYPE
double LogData::time_now_
double LogData::gnss_speed_
Referenced by IridiumNode::gnss_pose_callback, serialize_log_state.
double LogData::gnss_heading_
Referenced by IridiumNode::gnss_pose_callback.
double LogData::battery_
Referenced by IridiumNode::power_callback, serialize_log_state.
double LogData::gnss_lat_
Referenced by serialize_log_state.
double LogData::gnss_long_
Referenced by serialize_log_state.
double LogData::gnss_mean_east_
Referenced by deserialize_log_CMD_waypoint, IridiumNode::gnss_pose_callback.
double LogData::gnss_mean_north_
Referenced by deserialize_log_CMD_waypoint, IridiumNode::gnss_pose_callback.
double LogData::gnss_mean_heading_
Referenced by serialize_log_state.
double LogData::internal_pressure_
Referenced by IridiumNode::internal_sensor_callback, serialize_log_state.
double LogData::internal_temperature_
Referenced by IridiumNode::internal_sensor_callback, serialize_log_state.
double LogData::internal_humidity_
Referenced by IridiumNode::internal_sensor_callback, serialize_log_state.
unsigned int LogData::current_waypoint_
Referenced by IridiumNode::mission_callback, serialize_log_state.
unsigned int LogData::sleep_time_
Referenced by IridiumNode::call_decode, deserialize_log_CMD_sleep.
std::vector< Waypoint > LogData::waypoint_list_
Referenced by deserialize_log_CMD_mission, deserialize_log_CMD_waypoint, MissionXML::write.
double LogData::offset_east_
double LogData::offset_north_
bool LogData::enable_mission_
Referenced by deserialize_log_CMD_parameters.
bool LogData::enable_flash_
Referenced by deserialize_log_CMD_parameters.
bool LogData::enable_depth_
Referenced by deserialize_log_CMD_parameters.
bool LogData::enable_engine_
Referenced by deserialize_log_CMD_parameters.
unsigned int LogData::last_cmd_received_
Referenced by IridiumNode::call_decode, IridiumNode::process, serialize_log_state.
unsigned int LogData::period_message_
Referenced by deserialize_log_CMD_parameters.
bool LogData::safety_global_safety_valid_
Referenced by IridiumNode::safety_callback, serialize_log_state.
bool LogData::safety_published_frequency_
Referenced by IridiumNode::safety_callback, serialize_log_state.
bool LogData::safety_depth_limit_
Referenced by IridiumNode::safety_callback, serialize_log_state.
bool LogData::safety_batteries_limit_
Referenced by IridiumNode::safety_callback, serialize_log_state.
bool LogData::safety_depressurization_
Referenced by IridiumNode::safety_callback, serialize_log_state.
bool LogData::safety_seafloor_
Referenced by IridiumNode::safety_callback, serialize_log_state.
bool LogData::safety_piston_
Referenced by IridiumNode::safety_callback, serialize_log_state.
bool LogData::safety_zero_depth_
Referenced by IridiumNode::safety_callback, serialize_log_state.
MSG_TYPE LogData::msg_type_
Referenced by IridiumNode::call_decode, deserialize_log_CMD, MissionXML::write.
LogData::LogData()=default
LogData.
bool LogData::deserialize_log_CMD(const std::string &raw_data)
deserialize_log_CMD
file_name type
References CMD_MISSION_KEEP, CMD_MISSION_NEW, CMD_PARAMETERS, CMD_SLEEP, deserialize_log_CMD_mission, deserialize_log_CMD_parameters, deserialize_log_CMD_sleep, msg_type_.
Referenced by IridiumNode::call_decode.
std::string LogData::serialize_log_state(const long long &time)
serialize_log_state
file_name
References BATT_MAX, BATT_MIN, battery_, current_waypoint_, gnss_lat_, gnss_long_, gnss_mean_heading_, gnss_speed_, internal_humidity_, internal_pressure_, internal_temperature_, last_cmd_received_, LOG_STATE, NB_BITS_LOG1, safety_batteries_limit_, safety_depressurization_, safety_depth_limit_, safety_global_safety_valid_, safety_piston_, safety_published_frequency_, safety_seafloor_, safety_zero_depth_, WGS84_LAT_MAX, WGS84_LAT_MIN, WGS84_LON_MAX, WGS84_LON_MIN.
Referenced by IridiumNode::process, xbee_driver.xbee.XbeeNode.timer_callback.
bool LogData::deserialize_log_CMD_sleep(const std::string &data)
deserialize_log_CMD_sleep
file_name
References NB_BITS_CMD_SLEEP, sleep_time_.
Referenced by deserialize_log_CMD.
bool LogData::deserialize_log_CMD_mission(const std::string &data)
deserialize_log_CMD_mission
file_name
References waypoint_list_.
Referenced by deserialize_log_CMD.
bool LogData::deserialize_log_CMD_parameters(const std::string &message)
deserialize_log_CMD_parameters
file_name
References enable_depth_, enable_engine_, enable_flash_, enable_mission_, period_message_.
Referenced by deserialize_log_CMD.
unsigned int LogData::serialize_data(T &bits, const unsigned int &nb_bit, const unsigned int &start_bit, const double &value, const double &value_min, const double &value_max)
serialize_data
bits nb_bit start_bit value min max
unsigned int LogData::deserialize_data(T &bits, const unsigned int &nb_bit, const unsigned int &start_bit, double &value, const double &value_min, const double &value_max)
deserialize_data
bits nb_bit start_bit value value_min value_max
unsigned int LogData::serialize_data(T &bits, const unsigned int &nb_bit, const unsigned int &start_bit, const unsigned int &value)
serialize_data
bits nb_bit start_bit value
unsigned int LogData::deserialize_data(const T &bits, const unsigned int &nb_bit, const unsigned int &start_bit, unsigned int &value)
deserialize_data
bits nb_bit start_bit value
unsigned int LogData::deserialize_data(const T &bits, const unsigned int &nb_bit, const unsigned int &start_bit, int &value)
deserialize_data
bits nb_bit start_bit value
unsigned int LogData::deserialize_data(const T &bits, const unsigned int &nb_bit, const unsigned int &start_bit, bool &value)
deserialize_data
bits nb_bit start_bit value
unsigned int LogData::deserialize_log_CMD_waypoint(const std::string &message, const unsigned int &bit_position)
LogData::deserialize_log_CMD_waypoint.
save_file
References gnss_mean_east_, gnss_mean_north_, NB_BITS_CMD_WAYPOINT_DEPTH, NB_BITS_CMD_WAYPOINT_TRAJ, NB_BITS_CMD_WAYPOINT_TYPE, waypoint_list_.
bool LogData::write_file(const std::string &file_name, const std::string &data, const unsigned int nb_bits=NB_BITS_LOG1)
write_file
file_name data
std::string LogData::read_file(const std::string &file_name)
read_file
file_name