DepthControl
STATE_MACHINE
const int DepthControl::PISTON_STATE_OK
Referenced by state_machine_step.
bool DepthControl::debug_
Referenced by DepthControlNode::init_parameters, state_machine_step.
AlphaSolver DepthControl::alpha_solver_
Variable.
Referenced by DepthControlNode::generate_velocity_pairs, DepthControlNode::init_parameters, DepthControlNode::timer_callback, update_waypoint.
bool DepthControl::emergency_
Referenced by state_machine_step, update_safety.
float DepthControl::limit_depth_
Referenced by update_safety, update_waypoint.
double DepthControl::physics_rho_
Physical characteristics.
Referenced by DepthControlNode::init_parameters, update_AB, update_density.
double DepthControl::physics_g_
Referenced by DepthControlNode::init_parameters, update_AB.
double DepthControl::robot_mass_
Referenced by DepthControlNode::init_parameters, update_AB.
double DepthControl::robot_added_mass_
Referenced by update_AB.
double DepthControl::robot_diameter_
Referenced by DepthControlNode::init_parameters.
double DepthControl::screw_thread_
Referenced by DepthControlNode::init_parameters, update_coeff.
double DepthControl::tick_per_turn_
Referenced by DepthControlNode::init_parameters.
double DepthControl::piston_diameter_
Referenced by DepthControlNode::init_parameters, update_coeff.
double DepthControl::piston_max_tick_value_
Referenced by DepthControlNode::init_parameters, state_machine_step.
const double DepthControl::degree_to_kelvin_
Referenced by update_temperature.
double DepthControl::tick_to_volume_
Referenced by state_machine_step, update_piston.
double DepthControl::coeff_A_
Referenced by compute_u, update_AB.
double DepthControl::coeff_B_
Referenced by compute_u, update_AB.
const double DepthControl::fz_model_boundary_velocity_positive_
Referenced by fz_computation, fz_derivative_computation.
const double DepthControl::fz_model_boundary_velocity_negative_
Referenced by fz_computation, fz_derivative_computation.
const double DepthControl::fz_derivative_at_model_boundary_positive_
Referenced by fz_computation.
const double DepthControl::fz_offset_at_model_boundary_positive_
Referenced by fz_computation.
const double DepthControl::fz_derivative_at_model_boundary_negative_
Referenced by fz_computation.
const double DepthControl::fz_offset_at_model_boundary_negative_
Referenced by fz_computation.
double DepthControl::root_regulation_
Compute regulation constant.
Referenced by compute_u, DepthControlNode::init_parameters.
double DepthControl::limit_depth_control_
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::flow_piston_sink_
m
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::piston_reach_position_dead_zone_
m3/s
Referenced by state_machine_step.
double DepthControl::piston_hysteresis_
Referenced by DepthControlNode::init_parameters.
double DepthControl::motor_max_rpm_
Referenced by DepthControlNode::init_parameters, update_coeff.
double DepthControl::flow_max_
Referenced by DepthControlNode::init_parameters, state_machine_step, update_coeff.
double DepthControl::piston_flow_security_percentage_
in m3/sec
Referenced by DepthControlNode::init_parameters.
bool DepthControl::hold_depth_enable_
Hold depth parameters.
Referenced by DepthControlNode::init_parameters, state_machine_step.
rclcpp::Duration DepthControl::hold_depth_validation_duration_
Referenced by DepthControlNode::init_parameters, state_machine_step.
rclcpp::Time DepthControl::hold_depth_validation_time_
Referenced by state_machine_step.
bool DepthControl::hold_depth_validation_
Referenced by state_machine_step.
double DepthControl::hold_depth_value_enter_
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::hold_depth_value_exit_
m
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::hold_velocity_enter_
m
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::hold_velocity_exit_
m/s
Referenced by DepthControlNode::init_parameters.
bool DepthControl::control_filter_
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::delta_velocity_lb_
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::delta_velocity_ub_
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::delta_position_lb_
Referenced by DepthControlNode::init_parameters, state_machine_step.
double DepthControl::delta_position_ub_
Referenced by DepthControlNode::init_parameters, state_machine_step.
rclcpp::Duration DepthControl::safety_time_no_data_
Referenced by state_machine_step.
int64_t DepthControl::piston_position_
Referenced by state_machine_step, update_piston.
bool DepthControl::piston_switch_top_
Referenced by state_machine_step, update_piston.
bool DepthControl::piston_switch_bottom_
Referenced by state_machine_step, update_piston.
int32_t DepthControl::piston_state_
Referenced by state_machine_step, update_piston.
double DepthControl::piston_set_point_
Referenced by DepthControlNode::publish_message, state_machine_step.
bool DepthControl::is_exit_
Referenced by DepthControlNode::publish_message, state_machine_step.
rclcpp::Time DepthControl::time_last_kalman_callback_
Callback data.
Referenced by set_start_time, state_machine_step, update_state.
rclcpp::Time DepthControl::time_last_piston_callback_
Referenced by set_start_time, state_machine_step, update_piston.
double DepthControl::kalman_velocity_
Referenced by compute_u, state_machine_step, update_state.
double DepthControl::kalman_depth_
Referenced by compute_u, state_machine_step, update_state.
double DepthControl::kalman_total_offset_
Referenced by compute_u, state_machine_step, update_state.
double DepthControl::kalman_chi_
Referenced by compute_u, update_state.
double DepthControl::kalman_chi2_
Referenced by compute_u, update_state.
double DepthControl::kalman_cz_
Referenced by compute_u, update_state.
double DepthControl::piston_volume_
Referenced by compute_u, update_piston.
double DepthControl::depth_fusion_
Referenced by state_machine_step, update_depth.
double DepthControl::depth_set_point_
Referenced by state_machine_step, update_waypoint.
double DepthControl::limit_velocity_
Referenced by state_machine_step, update_waypoint.
double DepthControl::limit_velocity_last_
Referenced by update_waypoint.
double DepthControl::approach_velocity_
Referenced by compute_u, DepthControlNode::depth_set_point_callback, update_waypoint.
double DepthControl::temperature_
Referenced by update_temperature.
double DepthControl::pressure_
Referenced by update_depth.
std::chrono::milliseconds DepthControl::last_waypoint_max_delay_
Referenced by state_machine_step.
rclcpp::Time DepthControl::last_waypoint_time_
Referenced by set_start_time, state_machine_step, update_waypoint.
STATE_MACHINE DepthControl::regulation_state_
Referenced by DepthControlNode::publish_message, state_machine_step, DepthControlNode::timer_callback.
double DepthControl::y_debug_
Debug.
Referenced by compute_u, DepthControlNode::publish_message.
double DepthControl::dy_debug_
Referenced by compute_u, DepthControlNode::publish_message.
double DepthControl::u_debug_
Referenced by DepthControlNode::publish_message, state_machine_step.
DepthControl::DepthControl(const rclcpp::Time &start_time)
References set_start_time, update_coeff.
void DepthControl::update_state(const double &velocity, const double &depth, const double &chi, const double &chi2, const double &cz, const double &offset_total, const rclcpp::Time &time_update)
Update the state of the depth control.
velocity depth offset chi chi2 cz volume_air offset_total time_update
References kalman_chi2_, kalman_chi_, kalman_cz_, kalman_depth_, kalman_total_offset_, kalman_velocity_, time_last_kalman_callback_.
Referenced by DepthControlNode::kalman_callback.
void DepthControl::update_piston(const int &position, const bool &switch_top, const bool &switch_bottom, const int &state, const rclcpp::Time &time_update)
Update the data from the piston.
position switch_top switch_bottom state time_update
References piston_position_, piston_state_, piston_switch_bottom_, piston_switch_top_, piston_volume_, tick_to_volume_, time_last_piston_callback_.
Referenced by DepthControlNode::piston_callback.
void DepthControl::update_depth(const double &depth, const double &pressure)
Update the data from depth.
depth [in m] pressure [in bar]
References depth_fusion_, pressure_.
Referenced by DepthControlNode::depth_callback.
void DepthControl::update_safety(const bool &emergency, const float &limit_depth)
Update the data from safety.
emergency limit_depth
References emergency_, limit_depth_.
Referenced by DepthControlNode::safety_callback.
void DepthControl::update_waypoint(const float &depth, const double &limit_velocity, const rclcpp::Time &time_update, const bool &enable_control)
Update the data from the mission.
depth limit_velocity time_update enable_control
References alpha_solver_, approach_velocity_, AlphaSolver::compute_alpha, depth_set_point_, last_waypoint_time_, limit_depth_, limit_velocity_, limit_velocity_last_.
Referenced by DepthControlNode::depth_set_point_callback.
void DepthControl::update_density(const float &density)
Update the data from density.
density
References physics_rho_, update_AB.
Referenced by DepthControlNode::density_callback.
void DepthControl::update_temperature(const float &temperature)
Update the data from temperature.
temperature [in degree celsius]
References degree_to_kelvin_, temperature_.
Referenced by DepthControlNode::temperature_callback.
double DepthControl::compute_u(double set_point, double limit_velocity)
Compute the command associated to the depth control.
set_point limit_velocity
References A, approach_velocity_, B, coeff_A_, coeff_B_, dy_debug_, fz_computation, fz_derivative_computation, kalman_chi2_, kalman_chi_, kalman_cz_, kalman_depth_, kalman_total_offset_, kalman_velocity_, piston_volume_, root_regulation_, y_debug_.
Referenced by state_machine_step.
void DepthControl::update_coeff()
Update coefficients computed from parameters.
References flow_max_, M_PI, motor_max_rpm_, piston_diameter_, screw_thread_, update_AB.
Referenced by DepthControl, DepthControlNode::init_parameters.
void DepthControl::state_machine_step(const rclcpp::Duration &dt, const rclcpp::Time &current_time)
Update the state machine.
dt current_time the command to send to the piston
References compute_u, control_filter_, debug_, delta_position_lb_, delta_position_ub_, delta_velocity_lb_, delta_velocity_ub_, depth_fusion_, depth_set_point_, emergency_, flow_max_, flow_piston_sink_, hold_depth_enable_, hold_depth_validation_, hold_depth_validation_duration_, hold_depth_validation_time_, hold_depth_value_enter_, hold_depth_value_exit_, hold_velocity_enter_, is_exit_, kalman_depth_, kalman_total_offset_, kalman_velocity_, last_waypoint_max_delay_, last_waypoint_time_, limit_depth_control_, limit_velocity_, optimize_u, piston_max_tick_value_, piston_position_, piston_reach_position_dead_zone_, piston_set_point_, piston_state_, PISTON_STATE_OK, piston_switch_bottom_, piston_switch_top_, regulation_state_, safety_time_no_data_, STATE_COMPUTE_ALPHA, STATE_CONTROL, STATE_HOLD_DEPTH, STATE_PISTON_ISSUE, STATE_SINK, STATE_SURFACE, tick_to_volume_, time_last_kalman_callback_, time_last_piston_callback_, u_debug_.
Referenced by DepthControlNode::timer_callback.
void DepthControl::set_start_time(const rclcpp::Time &start_time)
Set the start time of the depth control.
start_time
References last_waypoint_time_, time_last_kalman_callback_, time_last_piston_callback_.
Referenced by DepthControl.
void DepthControl::update_AB()
Update coefficients A and B
References coeff_A_, coeff_B_, physics_g_, physics_rho_, robot_added_mass_, robot_mass_.
Referenced by update_coeff, update_density.
double DepthControl::fz_computation(double velocity) const
References fz_derivative_at_model_boundary_negative_, fz_derivative_at_model_boundary_positive_, fz_model_boundary_velocity_negative_, fz_model_boundary_velocity_positive_, fz_offset_at_model_boundary_negative_, fz_offset_at_model_boundary_positive_.
Referenced by compute_u.
double DepthControl::fz_derivative_computation(double velocity) const
References fz_model_boundary_velocity_negative_, fz_model_boundary_velocity_positive_.
Referenced by compute_u.
double DepthControl::optimize_u(std::array< double, 4 > &u_tab)
Optimize the command to reduce power consumptionr.
u_tab
Referenced by state_machine_step.