IridiumNode
rclcpp::TimerBase::SharedPtr IridiumNode::timer_read_
Rclcpp.
Referenced by IridiumNode, timer_read_callback.
rclcpp::TimerBase::SharedPtr IridiumNode::timer_write_
Referenced by IridiumNode, timer_write_callback.
std::chrono::milliseconds IridiumNode::loop_serial_read_
Referenced by IridiumNode.
std::chrono::milliseconds IridiumNode::loop_serial_write_
loop dt
Referenced by IridiumNode.
rclcpp::CallbackGroup::SharedPtr IridiumNode::callback_group_
loop dt
Referenced by IridiumNode.
SBD IridiumNode::sbd_
Referenced by IridiumNode, process, timer_read_callback.
LogData IridiumNode::log_state_
Referenced by call_decode, gnss_pose_callback, internal_sensor_callback, mission_callback, power_callback, process, safety_callback.
bool IridiumNode::enable_iridium_sending_
Referenced by init_parameters, process.
bool IridiumNode::valid_fix_
Referenced by gpsd_callback, process.
bool IridiumNode::is_surface_
Referenced by depth_callback, process.
std::string IridiumNode::mission_path_
Referenced by call_decode, init_parameters.
std::string IridiumNode::mission_file_name_
Referenced by call_decode, init_parameters.
rclcpp::Time IridiumNode::last_time_communication_
Referenced by process.
std::chrono::seconds IridiumNode::time_between_communication_
Referenced by init_parameters, process.
std::chrono::milliseconds IridiumNode::surface_wait_time_
Referenced by depth_callback, init_parameters.
double IridiumNode::surface_depth_limit_
Referenced by depth_callback, init_parameters.
bool IridiumNode::surface_is_valid_
Referenced by depth_callback.
rclcpp::Time IridiumNode::surface_time_detected_
Referenced by depth_callback.
rclcpp::Time IridiumNode::time_last_log_version_
Referenced by process.
std::chrono::seconds IridiumNode::delay_last_log_version_
Referenced by init_parameters, process.
double IridiumNode::fix_latitude_
Referenced by gpsd_callback, process.
double IridiumNode::fix_longitude_
Referenced by gpsd_callback, process.
rclcpp::Time IridiumNode::time_last_gnss_
Referenced by gpsd_callback, process.
std::chrono::seconds IridiumNode::delay_last_gnss_
Referenced by init_parameters, process.
bool IridiumNode::enable_iridium_gnss_
Referenced by init_parameters, process.
std::string IridiumNode::serial_port_name_
Referenced by IridiumNode.
unsigned int IridiumNode::serial_baud_rate_
Referenced by IridiumNode.
bool IridiumNode::sbd_debug_
Referenced by init_parameters, IridiumNode.
rclcpp::Subscription<seabot2_msgs::msg::Bme280Data>::SharedPtr IridiumNode::subscriber_internal_sensor_filter_
Topics.
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::PowerState>::SharedPtr IridiumNode::subscriber_power_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::SafetyStatus2>::SharedPtr IridiumNode::subscriber_safety_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::GpsFix>::SharedPtr IridiumNode::subscriber_gnss_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::GnssPose>::SharedPtr IridiumNode::subscriber_gnss_pose_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::DepthPose>::SharedPtr IridiumNode::subscriber_depth_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::MissionState>::SharedPtr IridiumNode::subscriber_mission
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::IridiumSession>::SharedPtr IridiumNode::publisher_iridium_session_
Referenced by init_interfaces, process.
rclcpp::Publisher<seabot2_msgs::msg::IridiumStatus>::SharedPtr IridiumNode::publisher_iridium_status_
Referenced by init_interfaces, process.
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr IridiumNode::publisher_iridium_log_
Referenced by init_interfaces, process.
IridiumNode::IridiumNode()
References callback_group_, SBD::cmd_enable_alert, SBD::cmd_enable_indicator_reporting, SBD::cmd_get_imei, SBD::init, init_interfaces, init_parameters, loop_serial_read_, loop_serial_write_, sbd_, sbd_debug_, serial_baud_rate_, serial_port_name_, SBD::set_debug, timer_read_, timer_read_callback, timer_write_, timer_write_callback.
void IridiumNode::timer_read_callback()
Functions.
Callback for timer read
References SBD::read, sbd_, timer_read_.
Referenced by IridiumNode.
void IridiumNode::timer_write_callback()
Callback for timer write
References process, timer_write_.
Referenced by IridiumNode.
void IridiumNode::init_parameters()
Init and get parameters of the Node
References delay_last_gnss_, delay_last_log_version_, enable_iridium_gnss_, enable_iridium_sending_, mission_file_name_, mission_path_, sbd_debug_, surface_depth_limit_, surface_wait_time_, time_between_communication_.
Referenced by IridiumNode.
void IridiumNode::init_interfaces()
Init interfaces to this node (publishers & subscribers)
References depth_callback, gnss_pose_callback, gpsd_callback, internal_sensor_callback, mission_callback, power_callback, publisher_iridium_log_, publisher_iridium_session_, publisher_iridium_status_, safety_callback, subscriber_depth_, subscriber_gnss_data_, subscriber_gnss_pose_, subscriber_internal_sensor_filter_, subscriber_mission, subscriber_power_data_, subscriber_safety_data_.
Referenced by IridiumNode.
void IridiumNode::internal_sensor_callback(const seabot2_msgs::msg::Bme280Data &msg)
Internal sensor callback msg
References LogData::internal_humidity_, LogData::internal_pressure_, LogData::internal_temperature_, log_state_.
Referenced by init_interfaces.
void IridiumNode::power_callback(const seabot2_msgs::msg::PowerState &msg)
Power callback msg
References LogData::battery_, log_state_.
Referenced by init_interfaces.
void IridiumNode::safety_callback(const seabot2_msgs::msg::SafetyStatus2 &msg)
Safety callback msg
References log_state_, LogData::safety_batteries_limit_, LogData::safety_depressurization_, LogData::safety_depth_limit_, LogData::safety_global_safety_valid_, LogData::safety_piston_, LogData::safety_published_frequency_, LogData::safety_seafloor_, LogData::safety_zero_depth_.
Referenced by init_interfaces.
void IridiumNode::mission_callback(const seabot2_msgs::msg::MissionState &msg)
Mission callback msg
References LogData::current_waypoint_, log_state_.
Referenced by init_interfaces.
void IridiumNode::depth_callback(const seabot2_msgs::msg::DepthPose &msg)
Depth callback msg
References is_surface_, surface_depth_limit_, surface_is_valid_, surface_time_detected_, surface_wait_time_.
Referenced by init_interfaces.
void IridiumNode::gpsd_callback(const seabot2_msgs::msg::GpsFix &msg)
Gnss callback msg
References fix_latitude_, fix_longitude_, time_last_gnss_, valid_fix_.
Referenced by init_interfaces.
void IridiumNode::gnss_pose_callback(const seabot2_msgs::msg::GnssPose &msg)
Gnss pose callback msg
References LogData::gnss_heading_, LogData::gnss_mean_east_, LogData::gnss_mean_north_, LogData::gnss_speed_, log_state_.
Referenced by init_interfaces.
void IridiumNode::call_decode(const string &data_raw)
Decode data from iridium data_raw
References LogData::CMD_MISSION_KEEP, LogData::CMD_MISSION_NEW, LogData::CMD_PARAMETERS, LogData::CMD_SLEEP, LogData::deserialize_log_CMD, LogData::last_cmd_received_, log_state_, mission_file_name_, mission_path_, LogData::msg_type_, LogData::sleep_time_, MissionXML::write.
Referenced by process.
void IridiumNode::process()
Process data to iridium
References call_decode, SBD::cmd_flush_message, SBD::cmd_read_message, SBD::cmd_session, SBD::cmd_write_message, delay_last_gnss_, delay_last_log_version_, enable_iridium_gnss_, enable_iridium_sending_, fix_latitude_, fix_longitude_, SBD::get_indicator_antenna, SBD::get_indicator_service, SBD::get_indicator_signal, SBD::get_ring_alert, SBD::get_session_mo, SBD::get_session_momsn, SBD::get_session_mt, SBD::get_session_mtmsn, SBD::get_waiting, is_surface_, LogData::last_cmd_received_, last_time_communication_, LogData::LOG_STATE, log_state_, publisher_iridium_log_, publisher_iridium_session_, publisher_iridium_status_, sbd_, LogData::serialize_log_state, SBD::set_gnss, time_between_communication_, time_last_gnss_, time_last_log_version_, valid_fix_.
Referenced by timer_write_callback.