PowerNode
rclcpp::TimerBase::SharedPtr PowerNode::timer_
Rclcpp.
Referenced by PowerNode.
std::chrono::milliseconds PowerNode::loop_dt_
Referenced by init_parameters, PowerNode.
Power PowerNode::power_
loop dt
I2C configuration
Referenced by init_parameters, PowerNode, timer_callback.
rclcpp::Publisher<seabot2_msgs::msg::PowerState>::SharedPtr PowerNode::publisher_power_state_
Topics / Services.
Referenced by init_interfaces, timer_callback.
rclcpp::Time PowerNode::time_turn_off_light_
Variables.
bool PowerNode::light_is_on_
PowerNode::PowerNode()
References Power::i2c_open, init_interfaces, init_parameters, loop_dt_, power_, timer_, timer_callback.
void PowerNode::timer_callback()
Functions.
References Power::battery_volt_, Power::cell_volt_, Power::esc_current_, Power::get_all_data, Power::motor_current_, power_, Power::power_state_, publisher_power_state_.
Referenced by PowerNode.
void PowerNode::init_parameters()
Init and get parameters of the Node
References Power::getI2CAddr, Power::getI2CPeriph, loop_dt_, power_, Power::setI2CAddr, Power::setI2CPeriph.
Referenced by PowerNode.
void PowerNode::init_interfaces()
Init interface to this node
References publisher_power_state_.
Referenced by PowerNode.