LatLonControl
double LatLonControl::lat_set_point_
Referenced by compute_control_commands, LatLonControlNode::init_parameters.
double LatLonControl::lon_set_point_
Referenced by compute_control_commands, LatLonControlNode::init_parameters.
double LatLonControl::lat_
Referenced by compute_control_commands, update_lat_lon.
double LatLonControl::lon_
Referenced by compute_control_commands, update_lat_lon.
float LatLonControl::heading_
Referenced by compute_control_commands, update_heading.
float LatLonControl::linear_velocity_
Referenced by compute_control_commands, get_linear_velocity.
float LatLonControl::angular_velocity_
Referenced by compute_control_commands, get_angular_velocity.
float LatLonControl::linear_velocity_max_
Referenced by compute_control_commands, LatLonControlNode::init_parameters.
float LatLonControl::angular_velocity_max_
Referenced by compute_control_commands, LatLonControlNode::init_parameters.
float LatLonControl::distance_threshold_slowing_down_
Referenced by compute_control_commands, LatLonControlNode::init_parameters.
bool LatLonControl::global_safety_valid_
Referenced by compute_control_commands, update_safety.
LatLonControl::LatLonControl()
LatLonControl::~LatLonControl()
void LatLonControl::update_lat_lon(const double &lat, const double &lon)
References lat_, lon_.
Referenced by LatLonControlNode::gps_fix_callback.
void LatLonControl::update_heading(const double &heading)
References heading_.
Referenced by LatLonControlNode::imu_data_callback.
void LatLonControl::update_safety(const bool &global_safety_valid)
References global_safety_valid_.
Referenced by LatLonControlNode::safety_callback.
void LatLonControl::compute_control_commands()
References angular_velocity_, angular_velocity_max_, distance_threshold_slowing_down_, global_safety_valid_, heading_, inverse_geodesic, lat_, lat_set_point_, linear_velocity_, linear_velocity_max_, lon_, lon_set_point_, M_PI, sawtooth.
Referenced by LatLonControlNode::timer_callback.
float LatLonControl::get_linear_velocity() const
References linear_velocity_.
Referenced by LatLonControlNode::timer_callback.
float LatLonControl::get_angular_velocity() const
References angular_velocity_.
Referenced by LatLonControlNode::timer_callback.
void LatLonControl::inverse_geodesic(const double &lat1, const double &lon1, const double &lat2, const double &lon2, double &distance, double &heading)
Referenced by compute_control_commands.