TeosSea
TeosSea::TeosSea()
descendant class constructor : base class constructor
References TeosBase::badBaseAlloc, TeosBase::statusOk.
TeosSea::~TeosSea()
descendant class destructor
double TeosSea::gsw_adiabatic_lapse_rate_from_ct(double sa, double ct, double p)
'A'
References TeosBase::gsw_gibbs, TeosBase::gsw_pt_from_ct, TeosBase::gsw_pt_from_t.
double TeosSea::gsw_alpha_on_beta(double sa, double ct, double p)
References TeosBase::gsw_gsvco_a, TeosBase::gsw_gsvco_b, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, GSW_TEOS10_CONSTANTS::offset.
Referenced by gsw_cabbeling.
double TeosSea::gsw_alpha_wrt_t_exact(double sa, double t, double p)
References TeosBase::gsw_gibbs.
double TeosSea::gsw_beta_const_t_exact(double sa, double t, double p)
'B'
References TeosBase::gsw_gibbs.
double TeosSea::gsw_cabbeling(double sa, double ct, double p)
'C'
References gsw_alpha_on_beta, TeosBase::gsw_rho, gsw_specvol_first_derivatives, gsw_specvol_second_derivatives, NULL.
double TeosSea::gsw_cabbeling_ct_exact(double SA, double CT, double p)
References TeosBase::gsw_alpha_on_beta_CT_exact, gsw_rho_ct_exact, TeosBase::gsw_specvol_first_derivatives_CT_exact, TeosBase::gsw_specvol_second_derivatives_CT_exact.
double TeosSea::gsw_c_from_sp(double sp, double t, double p)
References GSW_SP_COEFFICIENTS::a0, GSW_SP_COEFFICIENTS::a1, GSW_SP_COEFFICIENTS::a2, GSW_SP_COEFFICIENTS::a3, GSW_SP_COEFFICIENTS::a4, GSW_SP_COEFFICIENTS::a5, GSW_SP_COEFFICIENTS::b0, GSW_SP_COEFFICIENTS::b1, GSW_SP_COEFFICIENTS::b2, GSW_SP_COEFFICIENTS::b3, GSW_SP_COEFFICIENTS::b4, GSW_SP_COEFFICIENTS::b5, GSW_SP_COEFFICIENTS::c0, GSW_SP_COEFFICIENTS::c1, GSW_SP_COEFFICIENTS::c2, GSW_SP_COEFFICIENTS::c3, GSW_SP_COEFFICIENTS::c4, GSW_SP_COEFFICIENTS::d1, GSW_SP_COEFFICIENTS::d2, GSW_SP_COEFFICIENTS::d3, GSW_SP_COEFFICIENTS::d4, GSW_SP_COEFFICIENTS::e1, GSW_SP_COEFFICIENTS::e2, GSW_SP_COEFFICIENTS::e3, TeosBase::gspc, GSW_TEOS10_CONSTANTS::gsw_c3515, TeosBase::gsw_hill_ratio_at_sp2, TeosBase::gtc, GSW_SP_COEFFICIENTS::k.
double TeosSea::gsw_cp_t_exact(double sa, double t, double p)
References TeosBase::gsw_gibbs.
Referenced by gsw_enthalpy_first_derivatives_wrt_t_exact.
double TeosSea::gsw_ct_from_entropy(double sa, double entropy)
References TeosBase::gsw_ct_from_pt, gsw_pt_from_entropy.
void TeosSea::gsw_ct_from_rho_exact(double rho, double SA, double p, double &CT, double &CT_multiple)
References TeosBase::gsw_ct_from_t, gsw_t_from_rho_exact.
void TeosSea::gsw_ct_first_derivatives(double sa, double pt, double *ct_sa, double *ct_pt)
References GSW_TEOS10_CONSTANTS::gsw_cp0, TeosBase::gsw_gibbs_pt0_pt0, GSW_TEOS10_CONSTANTS::gsw_sfac, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc, NULL.
Referenced by gsw_ct_second_derivatives.
void TeosSea::gsw_ct_second_derivatives(double sa, double pt, double *ct_sa_sa, double *ct_sa_pt, double *ct_pt_pt)
References gsw_ct_first_derivatives, NULL.
void TeosSea::gsw_enthalpy_first_derivatives_wrt_t_exact(double SA, double t, double p, double &h_SA_wrt_t, double &h_T_wrt_t, double &h_P_wrt_t)
'E'
References gsw_cp_t_exact, TeosBase::gsw_gibbs, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gsw_specvol_t_exact, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc, GSW_TEOS10_CONSTANTS::rec_db2pa.
void TeosSea::gsw_enthalpy_second_derivatives(double sa, double ct, double p, double *h_sa_sa, double *h_sa_ct, double *h_ct_ct)
References TeosBase::gsvco, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, GSW_SPECVOL_COEFFICIENTS::h021, GSW_SPECVOL_COEFFICIENTS::h022, GSW_SPECVOL_COEFFICIENTS::h023, GSW_SPECVOL_COEFFICIENTS::h024, GSW_SPECVOL_COEFFICIENTS::h031, GSW_SPECVOL_COEFFICIENTS::h032, GSW_SPECVOL_COEFFICIENTS::h033, GSW_SPECVOL_COEFFICIENTS::h041, GSW_SPECVOL_COEFFICIENTS::h042, GSW_SPECVOL_COEFFICIENTS::h043, GSW_SPECVOL_COEFFICIENTS::h051, GSW_SPECVOL_COEFFICIENTS::h052, GSW_SPECVOL_COEFFICIENTS::h061, GSW_SPECVOL_COEFFICIENTS::h101, GSW_SPECVOL_COEFFICIENTS::h102, GSW_SPECVOL_COEFFICIENTS::h103, GSW_SPECVOL_COEFFICIENTS::h104, GSW_SPECVOL_COEFFICIENTS::h105, GSW_SPECVOL_COEFFICIENTS::h111, GSW_SPECVOL_COEFFICIENTS::h112, GSW_SPECVOL_COEFFICIENTS::h113, GSW_SPECVOL_COEFFICIENTS::h114, GSW_SPECVOL_COEFFICIENTS::h121, GSW_SPECVOL_COEFFICIENTS::h122, GSW_SPECVOL_COEFFICIENTS::h123, GSW_SPECVOL_COEFFICIENTS::h131, GSW_SPECVOL_COEFFICIENTS::h132, GSW_SPECVOL_COEFFICIENTS::h133, GSW_SPECVOL_COEFFICIENTS::h141, GSW_SPECVOL_COEFFICIENTS::h142, GSW_SPECVOL_COEFFICIENTS::h151, GSW_SPECVOL_COEFFICIENTS::h211, GSW_SPECVOL_COEFFICIENTS::h212, GSW_SPECVOL_COEFFICIENTS::h213, GSW_SPECVOL_COEFFICIENTS::h221, GSW_SPECVOL_COEFFICIENTS::h222, GSW_SPECVOL_COEFFICIENTS::h223, GSW_SPECVOL_COEFFICIENTS::h231, GSW_SPECVOL_COEFFICIENTS::h232, GSW_SPECVOL_COEFFICIENTS::h241, GSW_SPECVOL_COEFFICIENTS::h301, GSW_SPECVOL_COEFFICIENTS::h302, GSW_SPECVOL_COEFFICIENTS::h303, GSW_SPECVOL_COEFFICIENTS::h311, GSW_SPECVOL_COEFFICIENTS::h312, GSW_SPECVOL_COEFFICIENTS::h313, GSW_SPECVOL_COEFFICIENTS::h321, GSW_SPECVOL_COEFFICIENTS::h322, GSW_SPECVOL_COEFFICIENTS::h331, GSW_SPECVOL_COEFFICIENTS::h401, GSW_SPECVOL_COEFFICIENTS::h402, GSW_SPECVOL_COEFFICIENTS::h403, GSW_SPECVOL_COEFFICIENTS::h411, GSW_SPECVOL_COEFFICIENTS::h412, GSW_SPECVOL_COEFFICIENTS::h421, GSW_SPECVOL_COEFFICIENTS::h501, GSW_SPECVOL_COEFFICIENTS::h502, GSW_SPECVOL_COEFFICIENTS::h511, GSW_SPECVOL_COEFFICIENTS::h601, NULL, GSW_TEOS10_CONSTANTS::offset.
Referenced by gsw_internal_energy_second_derivatives, gsw_specvol_second_derivatives_wrt_enthalpy.
double TeosSea::gsw_entropy_from_pt(double sa, double pt)
References TeosBase::gsw_gibbs.
Referenced by gsw_pt_from_entropy.
double TeosSea::gsw_entropy_from_t(double sa, double t, double p)
References TeosBase::gsw_gibbs.
double * TeosSea::gsw_geo_strf_dyn_height(double *sa, double *ct, double *p, double p_ref, int n_levels, double *dyn_height)
'G'
References GSW_TEOS10_CONSTANTS::db2pa, TeosBase::gsw_linear_interp_sa_ct, gsw_p_sequence, gsw_rr68_interp_sa_ct, gsw_specvol_anom_standard, TeosBase::gtc, NULL, p_ref.
int TeosSea::gsw_geo_strf_dyn_height_1(double *sa, double *ct, double *p, double p_ref, int n_levels, double *dyn_height, double max_dp_i, int interp_method)
void TeosSea::gsw_internal_energy_first_derivatives(double SA, double CT, double p, double &u_SA, double &u_CT, double &u_P)
I
References GSW_TEOS10_CONSTANTS::db2pa, TeosBase::gsw_enthalpy_first_derivatives, GSW_TEOS10_CONSTANTS::gsw_p0, TeosBase::gsw_specvol, gsw_specvol_first_derivatives, TeosBase::gtc.
void TeosSea::gsw_internal_energy_first_derivatives_ct_exact(double SA, double CT, double p, double &u_SA, double &u_CT, double &u_P)
References GSW_TEOS10_CONSTANTS::db2pa, TeosBase::gsw_enthalpy_first_derivatives_ct_exact, GSW_TEOS10_CONSTANTS::gsw_p0, TeosBase::gsw_specvol_CT_exact, TeosBase::gsw_specvol_first_derivatives_CT_exact, TeosBase::gtc.
void TeosSea::gsw_internal_energy_second_derivatives(double SA, double CT, double p, double &u_SA_SA, double &u_SA_CT, double &u_CT_CT, double &u_SA_P, double &u_CT_P)
References GSW_TEOS10_CONSTANTS::db2pa, gsw_enthalpy_second_derivatives, GSW_TEOS10_CONSTANTS::gsw_p0, gsw_specvol_second_derivatives, TeosBase::gtc.
double TeosSea::gsw_isopycnal_slope_ratio(double SA, double CT, double p, double p_ref=0.0)
References gsw_specvol_alpha_beta, p_ref.
double TeosSea::gsw_latentheat_evap_ct(double sa, double ct)
'L'
References GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc.
Referenced by gsw_latentheat_evap_t.
double TeosSea::gsw_latentheat_evap_t(double sa, double t)
References TeosBase::gsw_ct_from_pt, gsw_latentheat_evap_ct.
int TeosSea::gsw_linear_interp_SA_CT_for_dh(double *sa, double *ct, double *p, int nz, double *p_i, int n_i, double *sa_i, double *ct_i)
double TeosSea::gsw_ntp_pt_vs_CT_ratio(double SA, double CT, double p)
'N'
References gsw_pt_first_derivatives, gsw_specvol_alpha_beta.
void TeosSea::gsw_p_sequence(double p1, double p2, double max_dp_i, double *pseq, int *nps)
'P'
References NULL.
Referenced by gsw_geo_strf_dyn_height.
double TeosSea::gsw_pot_rho_t_exact(double sa, double t, double p, double p_ref)
References TeosBase::gsw_pt_from_t, gsw_rho_t_exact, p_ref.
void TeosSea::gsw_pt_first_derivatives(double sa, double ct, double *pt_sa, double *pt_ct)
References GSW_TEOS10_CONSTANTS::gsw_cp0, TeosBase::gsw_gibbs, TeosBase::gsw_pt_from_ct, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc, NULL.
Referenced by gsw_ntp_pt_vs_CT_ratio, gsw_pt_second_derivatives.
double TeosSea::gsw_pt_from_entropy(double sa, double entropy)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_entropy_from_pt, TeosBase::gsw_gibbs_pt0_pt0, GSW_TEOS10_CONSTANTS::gsw_sso, GSW_TEOS10_CONSTANTS::gsw_t0, TeosBase::gtc.
Referenced by gsw_ct_from_entropy, gsw_t_from_entropy.
void TeosSea::gsw_pt_second_derivatives(double sa, double ct, double *pt_sa_sa, double *pt_sa_ct, double *pt_ct_ct)
References gsw_pt_first_derivatives, NULL.
int TeosSea::gsw_refine_grid_for_dh(double *p, double p_ref, int nz, double dp, double *p_i, int ni_max, int *p_indices, int *p_ref_ind_ptr)
'R'
References p_ref.
void TeosSea::gsw_rho_alpha_beta_ct_exact(double SA, double CT, double p, double &rho_CT_exact, double &alpha_CT_exact, double &beta_CT_exact)
References TeosBase::gsw_alpha_wrt_CT_t_exact, TeosBase::gsw_beta_const_ct_t_exact, gsw_rho_t_exact, TeosBase::gsw_t_from_ct.
double TeosSea::gsw_rho_ct_exact(double SA, double CT, double p)
References gsw_rho_t_exact, TeosBase::gsw_t_from_ct.
Referenced by gsw_cabbeling_ct_exact, gsw_thermobaric_ct_exact.
void TeosSea::gsw_rho_second_derivatives(double sa, double ct, double p, double *rho_sa_sa, double *rho_sa_ct, double *rho_ct_ct, double *rho_sa_p, double *rho_ct_p)
References TeosBase::gsw_specvol, gsw_specvol_first_derivatives, gsw_specvol_second_derivatives.
void TeosSea::gsw_rho_first_derivatives(double sa, double ct, double p, double *drho_dsa, double *drho_dct, double *drho_dp)
References TeosBase::gsw_gsvco_a, TeosBase::gsw_gsvco_b, TeosBase::gsw_gsvco_c, TeosBase::gsw_gsvco_v, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, NULL, GSW_TEOS10_CONSTANTS::offset, GSW_TEOS10_CONSTANTS::pa2db.
void TeosSea::gsw_rho_first_derivatives_wrt_enthalpy(double sa, double ct, double p, double *rho_sa, double *rho_h)
References TeosBase::gsw_specvol, gsw_specvol_first_derivatives_wrt_enthalpy, NULL.
void TeosSea::gsw_rho_second_derivatives_wrt_enthalpy(double sa, double ct, double p, double *rho_sa_sa, double *rho_sa_h, double *rho_h_h)
References TeosBase::gsw_specvol, gsw_specvol_first_derivatives_wrt_enthalpy, gsw_specvol_second_derivatives_wrt_enthalpy, NULL.
double TeosSea::gsw_rho_t_exact(double sa, double t, double p)
References TeosBase::gsw_gibbs.
Referenced by gsw_pot_rho_t_exact, gsw_rho_alpha_beta_ct_exact, gsw_rho_ct_exact, gsw_sigma0_pt0_exact, gsw_sigma1_ct_exact, gsw_sigma2_ct_exact, gsw_sigma3_ct_exact, gsw_sigma4_ct_exact, gsw_t_from_rho_exact, DensityNode::timer_callback.
void TeosSea::gsw_rr68_interp_sa_ct(double *sa, double *ct, double *p, int mp, double *p_i, int mp_i, double *sa_i, double *ct_i)
References cppGSW_INVALID_VALUE, TeosBase::gsw_rr68_interp_section, gsw_util_interp1q_int, NULL.
Referenced by gsw_geo_strf_dyn_height.
double TeosSea::gsw_sa_from_rho(double rho, double ct, double p)
'S'
References cppGSW_INVALID_VALUE, TeosBase::gsw_specvol, gsw_specvol_first_derivatives, NULL.
double TeosSea::gsw_sigma0(double sa, double ct)
References TeosBase::gsvco, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, GSW_TEOS10_CONSTANTS::offset, GSW_SPECVOL_COEFFICIENTS::v000, GSW_SPECVOL_COEFFICIENTS::v010, GSW_SPECVOL_COEFFICIENTS::v020, GSW_SPECVOL_COEFFICIENTS::v030, GSW_SPECVOL_COEFFICIENTS::v040, GSW_SPECVOL_COEFFICIENTS::v050, GSW_SPECVOL_COEFFICIENTS::v060, GSW_SPECVOL_COEFFICIENTS::v100, GSW_SPECVOL_COEFFICIENTS::v110, GSW_SPECVOL_COEFFICIENTS::v120, GSW_SPECVOL_COEFFICIENTS::v130, GSW_SPECVOL_COEFFICIENTS::v140, GSW_SPECVOL_COEFFICIENTS::v150, GSW_SPECVOL_COEFFICIENTS::v200, GSW_SPECVOL_COEFFICIENTS::v210, GSW_SPECVOL_COEFFICIENTS::v220, GSW_SPECVOL_COEFFICIENTS::v230, GSW_SPECVOL_COEFFICIENTS::v240, GSW_SPECVOL_COEFFICIENTS::v300, GSW_SPECVOL_COEFFICIENTS::v310, GSW_SPECVOL_COEFFICIENTS::v320, GSW_SPECVOL_COEFFICIENTS::v330, GSW_SPECVOL_COEFFICIENTS::v400, GSW_SPECVOL_COEFFICIENTS::v410, GSW_SPECVOL_COEFFICIENTS::v420, GSW_SPECVOL_COEFFICIENTS::v500, GSW_SPECVOL_COEFFICIENTS::v510, GSW_SPECVOL_COEFFICIENTS::v600.
double TeosSea::gsw_sigma0_ct_exact(double SA, double CT)
References TeosBase::gsw_pt_from_ct, gsw_sigma0_pt0_exact.
double TeosSea::gsw_sigma0_pt0_exact(double SA, double pt0)
References gsw_rho_t_exact.
Referenced by gsw_sigma0_ct_exact.
double TeosSea::gsw_sigma1(double sa, double ct)
References TeosBase::gsw_rho.
double TeosSea::gsw_sigma1_ct_exact(double SA, double CT)
References gsw_rho_t_exact, TeosBase::gsw_t_from_ct.
double TeosSea::gsw_sigma2(double sa, double ct)
References TeosBase::gsw_rho.
double TeosSea::gsw_sigma2_ct_exact(double SA, double CT)
References gsw_rho_t_exact, TeosBase::gsw_t_from_ct.
double TeosSea::gsw_sigma3(double sa, double ct)
References TeosBase::gsw_rho.
double TeosSea::gsw_sigma3_ct_exact(double SA, double CT)
References gsw_rho_t_exact, TeosBase::gsw_t_from_ct.
double TeosSea::gsw_sigma4(double sa, double ct)
References TeosBase::gsw_rho.
double TeosSea::gsw_sigma4_ct_exact(double SA, double CT)
References gsw_rho_t_exact, TeosBase::gsw_t_from_ct.
double TeosSea::gsw_sound_speed(double sa, double ct, double p)
References TeosBase::gsw_gsvco_c, TeosBase::gsw_gsvco_v, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, GSW_TEOS10_CONSTANTS::offset.
double TeosSea::gsw_sound_speed_ct_exact(double SA, double CT, double p)
References gsw_sound_speed_t_exact, TeosBase::gsw_t_from_ct.
double TeosSea::gsw_sound_speed_t_exact(double sa, double t, double p)
References TeosBase::gsw_gibbs.
Referenced by gsw_sound_speed_ct_exact, DensityNode::timer_callback.
double TeosSea::gsw_sp_from_sk(double sk)
References cppGSW_INVALID_VALUE, GSW_TEOS10_CONSTANTS::gsw_soncl, TeosBase::gtc.
double TeosSea::gsw_sp_from_sr(double sr)
References GSW_TEOS10_CONSTANTS::gsw_ups, TeosBase::gtc.
double TeosSea::gsw_sp_from_sstar(double sstar, double p, double lon, double lat)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, TeosBase::gsw_saar, TeosBase::gsw_sp_from_sa_baltic, GSW_TEOS10_CONSTANTS::gsw_ups, TeosBase::gtc, saar.
double TeosSea::gsw_sp_salinometer(double rt, double t)
References GSW_SP_COEFFICIENTS::a0, GSW_SP_COEFFICIENTS::a1, GSW_SP_COEFFICIENTS::a2, GSW_SP_COEFFICIENTS::a3, GSW_SP_COEFFICIENTS::a4, GSW_SP_COEFFICIENTS::a5, GSW_SP_COEFFICIENTS::b0, GSW_SP_COEFFICIENTS::b1, GSW_SP_COEFFICIENTS::b2, GSW_SP_COEFFICIENTS::b3, GSW_SP_COEFFICIENTS::b4, GSW_SP_COEFFICIENTS::b5, TeosBase::gspc, TeosBase::gsw_hill_ratio_at_sp2, GSW_SP_COEFFICIENTS::k.
void TeosSea::gsw_specvol_alpha_beta(double sa, double ct, double p, double *specvol, double *alpha, double *beta)
References TeosBase::gsw_gsvco_a, TeosBase::gsw_gsvco_b, TeosBase::gsw_gsvco_v, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, NULL, GSW_TEOS10_CONSTANTS::offset, GSW_TEOS10_CONSTANTS::rec_db2pa.
Referenced by gsw_isopycnal_slope_ratio, gsw_ntp_pt_vs_CT_ratio, gsw_turner_rsubrho.
double TeosSea::gsw_specvol_anom_standard(double sa, double ct, double p)
References TeosBase::gsw_specvol, TeosBase::gsw_specvol_sso_0.
Referenced by gsw_geo_strf_dyn_height.
void TeosSea::gsw_specvol_first_derivatives(double sa, double ct, double p, double *v_sa, double *v_ct, double *v_p)
References TeosBase::gsw_gsvco_a, TeosBase::gsw_gsvco_b, TeosBase::gsw_gsvco_c, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, NULL, GSW_TEOS10_CONSTANTS::offset.
Referenced by gsw_cabbeling, gsw_internal_energy_first_derivatives, gsw_rho_second_derivatives, gsw_sa_from_rho, gsw_specvol_first_derivatives_wrt_enthalpy, gsw_specvol_second_derivatives_wrt_enthalpy, gsw_thermobaric.
void TeosSea::gsw_specvol_first_derivatives_wrt_enthalpy(double sa, double ct, double p, double *v_sa, double *v_h)
References TeosBase::gsw_enthalpy_first_derivatives, gsw_specvol_first_derivatives, NULL.
Referenced by gsw_rho_first_derivatives_wrt_enthalpy, gsw_rho_second_derivatives_wrt_enthalpy.
void TeosSea::gsw_specvol_second_derivatives(double sa, double ct, double p, double *v_sa_sa, double *v_sa_ct, double *v_ct_ct, double *v_sa_p, double *v_ct_p)
References GSW_SPECVOL_COEFFICIENTS::a001, GSW_SPECVOL_COEFFICIENTS::a002, GSW_SPECVOL_COEFFICIENTS::a003, GSW_SPECVOL_COEFFICIENTS::a004, GSW_SPECVOL_COEFFICIENTS::a010, GSW_SPECVOL_COEFFICIENTS::a011, GSW_SPECVOL_COEFFICIENTS::a012, GSW_SPECVOL_COEFFICIENTS::a013, GSW_SPECVOL_COEFFICIENTS::a020, GSW_SPECVOL_COEFFICIENTS::a021, GSW_SPECVOL_COEFFICIENTS::a022, GSW_SPECVOL_COEFFICIENTS::a030, GSW_SPECVOL_COEFFICIENTS::a031, GSW_SPECVOL_COEFFICIENTS::a032, GSW_SPECVOL_COEFFICIENTS::a040, GSW_SPECVOL_COEFFICIENTS::a041, GSW_SPECVOL_COEFFICIENTS::a050, GSW_SPECVOL_COEFFICIENTS::a101, GSW_SPECVOL_COEFFICIENTS::a102, GSW_SPECVOL_COEFFICIENTS::a103, GSW_SPECVOL_COEFFICIENTS::a110, GSW_SPECVOL_COEFFICIENTS::a111, GSW_SPECVOL_COEFFICIENTS::a112, GSW_SPECVOL_COEFFICIENTS::a120, GSW_SPECVOL_COEFFICIENTS::a121, GSW_SPECVOL_COEFFICIENTS::a122, GSW_SPECVOL_COEFFICIENTS::a130, GSW_SPECVOL_COEFFICIENTS::a131, GSW_SPECVOL_COEFFICIENTS::a140, GSW_SPECVOL_COEFFICIENTS::a201, GSW_SPECVOL_COEFFICIENTS::a202, GSW_SPECVOL_COEFFICIENTS::a210, GSW_SPECVOL_COEFFICIENTS::a211, GSW_SPECVOL_COEFFICIENTS::a212, GSW_SPECVOL_COEFFICIENTS::a220, GSW_SPECVOL_COEFFICIENTS::a221, GSW_SPECVOL_COEFFICIENTS::a230, GSW_SPECVOL_COEFFICIENTS::a301, GSW_SPECVOL_COEFFICIENTS::a302, GSW_SPECVOL_COEFFICIENTS::a310, GSW_SPECVOL_COEFFICIENTS::a311, GSW_SPECVOL_COEFFICIENTS::a320, GSW_SPECVOL_COEFFICIENTS::a401, GSW_SPECVOL_COEFFICIENTS::a410, GSW_SPECVOL_COEFFICIENTS::b000, GSW_SPECVOL_COEFFICIENTS::b001, GSW_SPECVOL_COEFFICIENTS::b002, GSW_SPECVOL_COEFFICIENTS::b003, GSW_SPECVOL_COEFFICIENTS::b004, GSW_SPECVOL_COEFFICIENTS::b010, GSW_SPECVOL_COEFFICIENTS::b011, GSW_SPECVOL_COEFFICIENTS::b012, GSW_SPECVOL_COEFFICIENTS::b013, GSW_SPECVOL_COEFFICIENTS::b020, GSW_SPECVOL_COEFFICIENTS::b021, GSW_SPECVOL_COEFFICIENTS::b022, GSW_SPECVOL_COEFFICIENTS::b030, GSW_SPECVOL_COEFFICIENTS::b031, GSW_SPECVOL_COEFFICIENTS::b032, GSW_SPECVOL_COEFFICIENTS::b040, GSW_SPECVOL_COEFFICIENTS::b041, GSW_SPECVOL_COEFFICIENTS::b050, GSW_SPECVOL_COEFFICIENTS::b101, GSW_SPECVOL_COEFFICIENTS::b102, GSW_SPECVOL_COEFFICIENTS::b103, GSW_SPECVOL_COEFFICIENTS::b110, GSW_SPECVOL_COEFFICIENTS::b111, GSW_SPECVOL_COEFFICIENTS::b112, GSW_SPECVOL_COEFFICIENTS::b120, GSW_SPECVOL_COEFFICIENTS::b121, GSW_SPECVOL_COEFFICIENTS::b122, GSW_SPECVOL_COEFFICIENTS::b130, GSW_SPECVOL_COEFFICIENTS::b131, GSW_SPECVOL_COEFFICIENTS::b140, GSW_SPECVOL_COEFFICIENTS::b200, GSW_SPECVOL_COEFFICIENTS::b201, GSW_SPECVOL_COEFFICIENTS::b202, GSW_SPECVOL_COEFFICIENTS::b210, GSW_SPECVOL_COEFFICIENTS::b211, GSW_SPECVOL_COEFFICIENTS::b212, GSW_SPECVOL_COEFFICIENTS::b220, GSW_SPECVOL_COEFFICIENTS::b221, GSW_SPECVOL_COEFFICIENTS::b230, GSW_SPECVOL_COEFFICIENTS::b300, GSW_SPECVOL_COEFFICIENTS::b301, GSW_SPECVOL_COEFFICIENTS::b302, GSW_SPECVOL_COEFFICIENTS::b310, GSW_SPECVOL_COEFFICIENTS::b311, GSW_SPECVOL_COEFFICIENTS::b320, GSW_SPECVOL_COEFFICIENTS::b400, GSW_SPECVOL_COEFFICIENTS::b401, GSW_SPECVOL_COEFFICIENTS::b410, GSW_SPECVOL_COEFFICIENTS::b500, TeosBase::gsvco, GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, NULL, GSW_TEOS10_CONSTANTS::offset.
Referenced by gsw_cabbeling, gsw_internal_energy_second_derivatives, gsw_rho_second_derivatives, gsw_specvol_second_derivatives_wrt_enthalpy, gsw_thermobaric.
void TeosSea::gsw_specvol_second_derivatives_wrt_enthalpy(double sa, double ct, double p, double *v_sa_sa, double *v_sa_h, double *v_h_h)
References TeosBase::gsw_enthalpy_first_derivatives, gsw_enthalpy_second_derivatives, gsw_specvol_first_derivatives, gsw_specvol_second_derivatives, NULL.
Referenced by gsw_rho_second_derivatives_wrt_enthalpy.
double TeosSea::gsw_spiciness0(double sa, double ct)
References GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, GSW_TEOS10_CONSTANTS::offset.
double TeosSea::gsw_spiciness1(double sa, double ct)
References GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, GSW_TEOS10_CONSTANTS::offset.
double TeosSea::gsw_spiciness2(double sa, double ct)
References GSW_TEOS10_CONSTANTS::gsw_sfac, TeosBase::gtc, GSW_TEOS10_CONSTANTS::offset.
double TeosSea::gsw_t_from_entropy(double SA, double entropy, double p)
'T'
References gsw_pt_from_entropy, TeosBase::gsw_pt_from_t.
void TeosSea::gsw_t_from_rho_exact(double rho, double SA, double p, double &t, double &t_multiple)
References TeosBase::gsw_gibbs, gsw_rho_t_exact, TeosBase::gsw_t_freezing, TeosBase::gsw_t_maxdensity_exact.
Referenced by gsw_ct_from_rho_exact.
double TeosSea::gsw_thermobaric(double sa, double ct, double p)
References TeosBase::gsw_rho, gsw_specvol_first_derivatives, gsw_specvol_second_derivatives, NULL.
double TeosSea::gsw_thermobaric_ct_exact(double SA, double CT, double p)
References gsw_rho_ct_exact, TeosBase::gsw_specvol_first_derivatives_CT_exact, TeosBase::gsw_specvol_second_derivatives_CT_exact.
void TeosSea::gsw_turner_rsubrho(double *sa, double *ct, double *p, int nz, double *tu, double *rsubrho, double *p_mid)
References cppGSW_INVALID_VALUE, gsw_specvol_alpha_beta, TeosBase::gtc, NULL, GSW_TEOS10_CONSTANTS::rad2deg.
double * TeosSea::gsw_util_interp1q_int(int nx, double *x, int *iy, int nxi, double *x_i, double *y_i)
'U'
References TeosBase::gsw_util_sort_dbl, NULL.
Referenced by gsw_rr68_interp_sa_ct.
double * TeosSea::gsw_util_linear_interp(int nx, double *x, int ny, double *y, int nxi, double *x_i, double *y_i)
References TeosBase::gsw_util_sort_dbl, NULL.
int TeosSea::gsw_util_pchip_interp(double *x, double *y, int n, double *xi, double *yi, int ni)
References TeosBase::gsw_pchip_derivs, NULL.