Mission
WAYPOINT_TYPE
MISSION_STATE
double Mission::temperature_keeping_k_
Temperature keeping gain K, used in WaypointTemperatureKeeping::process.
Referenced by MissionNode::init_parameters, WaypointTemperatureKeeping::process.
std::string Mission::file_name_
Mission file name.
Referenced by load_mission.
std::filesystem::file_time_type Mission::file_time_
Last modification time of the mission file.
Referenced by is_new_mission_file.
const std::string Mission::XML_DEPTH
Referenced by decode_paths.
const std::string Mission::XML_DEPTH_LEGACY
Referenced by decode_paths.
const std::string Mission::XML_SEAFLOOR_LANDING
Referenced by decode_paths.
const std::string Mission::XML_TEMPERATURE_KEEPING
Referenced by decode_paths.
const std::string Mission::XML_TEMPERATURE_PROFILE
Referenced by decode_paths.
const std::string Mission::XML_GNSS_PROFILE
Referenced by decode_paths.
const std::vector<std::string> Mission::XML_TYPE
XML waypoint types.
Referenced by decode_paths.
std::vector<std::pair<std::shared_ptr<Waypoint>, WAYPOINT_TYPE> > Mission::waypoints_
Vector of loaded waypoints and their types.
Referenced by decode_paths, decode_waypoint_depth, decode_waypoint_gnss_profile, decode_waypoint_temperature_keeping, decode_waypoint_temperature_profile, get_current_waypoint_temperature_keeping, get_number_waypoints, idle_state_configuration, is_current_waypoint_of_type, load_mission, update_state.
size_t Mission::current_waypoint_id_
Current waypoint index.
Referenced by get_current_waypoint_id, get_current_waypoint_temperature_keeping, is_current_waypoint_of_type, load_mission, update_state.
bool Mission::is_first_waypoint_
Flag indicating if the targeted waypoint is the first one of the mission.
Referenced by load_mission, update_state.
rclcpp::Duration Mission::duration_next_waypoint_
Remaining Duration to the next waypoint.
Referenced by get_time_to_next_waypoint, update_state.
rclcpp::Time Mission::time_start_
Mission start time.
Referenced by decode_waypoint, get_start_time, load_mission, update_state.
rclcpp::Time Mission::time_end_
Mission end time.
Referenced by get_end_time, load_mission.
double Mission::offset_north_
Offset north in meter.
Referenced by load_mission.
double Mission::offset_east_
Offset east in meter.
Referenced by load_mission.
double Mission::limit_velocity_default_
Default limit velocity in m/s.
Referenced by decode_waypoint, set_limit_velocity_default.
double Mission::default_time_to_start_
Default delay in seconds to start after the mission file has been loaded if no start time was given in the mission file
Referenced by load_mission.
unsigned int Mission::mission_mode_
Current mission mode (targeted waypoint type)
Referenced by get_mission_mode, update_state.
MISSION_STATE Mission::mission_state_
Current mission state.
Referenced by get_mission_state, update_state.
seabot2_msgs::msg::DepthControlSetPoint Mission::dc_msg_
Depth Control SetPoint message containing the current set point.
Referenced by depth_control_set_point, get_depth_control_set_point, idle_state_configuration.
double Mission::depth_
Current depth in meter.
Referenced by get_depth, update_depth.
double Mission::temperature_
Current temperature in degree Celsius.
Referenced by get_temperature, update_temperature.
Mission::Mission()=default
Construct a new Mission object.
bool Mission::is_current_waypoint_of_type(const WAYPOINT_TYPE &type) const
Check if the current waypoint is of the given type.
type true if the current waypoint is of the given type, false otherwise
References current_waypoint_id_, waypoints_.
Referenced by MissionNode::timer_callback.
bool Mission::update_state(const rclcpp::Time &t_now)
Executes a step of the mission management process.
t_now true if the targeted waypoint has changed since previous step, false otherwise
References current_waypoint_id_, duration_next_waypoint_, ENDING, idle_state_configuration, is_first_waypoint_, mission_mode_, mission_state_, NO_WP, NOT_STARTED, RUNNING, time_start_, waypoints_, WP_DEPTH, WP_GNSS_PROFILE, WP_IDLE, WP_SEAFLOOR_LANDING, WP_TEMPERATURE_KEEPING, WP_TEMPERATURE_PROFILE.
Referenced by MissionNode::timer_callback.
bool Mission::is_new_mission_file(const std::string &file_xml, const std::string &folder_path)
file_xml mission file name folder_path parent folder path true if the mission file has changed, false otherwise
References file_time_.
Referenced by MissionNode::MissionNode, MissionNode::timer_callback.
int Mission::load_mission(const std::string &file_xml, const std::string &folder_path="", const rclcpp::Time &start_time_if_not_given=rclcpp::Time(0., RCL_STEADY_TIME))
Load mission parameters from mission file.
file_xml mission file name folder_path mission file parent folder path, defaults to "" start_time_if_not_given start time to use if not given in the mission file, defaults to 0 unix epoch time EXIT_SUCCESS if mission has been loaded correctly, EXIT_FAILURE otherwise
References current_waypoint_id_, decode_paths, default_time_to_start_, file_name_, is_first_waypoint_, offset_east_, offset_north_, time_end_, time_start_, waypoints_.
Referenced by MissionNode::load_mission.
seabot2_msgs::msg::DepthControlSetPoint & Mission::depth_control_set_point()
Access by reference the Mission obect's depth control set point message.
seabot2_msgs::msg::DepthControlSetPoint&
References dc_msg_.
Referenced by WaypointDepth::process, WaypointSeafloorLanding::process, WaypointTemperatureKeeping::process, WaypointTemperatureProfile::process, WaypointGNSSProfile::process.
const seabot2_msgs::msg::DepthControlSetPoint & Mission::get_depth_control_set_point() const
Get const reference to the missions's current depth control set point message.
const seabot2_msgs::msg::DepthControlSetPoint&
References dc_msg_.
Referenced by MissionNode::timer_callback.
rclcpp::Time Mission::get_start_time() const
Get the mission start time.
rclcpp::Time
References time_start_.
rclcpp::Time Mission::get_end_time() const
Get the mission end time.
rclcpp::Time
References time_end_.
size_t Mission::get_number_waypoints() const
Get the number of waypoints in the mission.
size_t
References waypoints_.
Referenced by MissionNode::timer_callback.
size_t Mission::get_current_waypoint_id() const
Get the currently targeted waypoint id.
size_t waypoint id
References current_waypoint_id_.
Referenced by MissionNode::timer_callback.
double Mission::get_time_to_next_waypoint() const
Get the time to next waypoint.
time to next waypoint in seconds
References duration_next_waypoint_.
Referenced by MissionNode::timer_callback.
unsigned int Mission::get_mission_mode() const
Get the mission mode.
unsigned int WAYPOINT_TYPE of the currently targeted waypoint
References mission_mode_.
Referenced by MissionNode::timer_callback.
unsigned int Mission::get_mission_state() const
Get the mission state.
unsigned int MISSION_STATE
References mission_state_.
Referenced by MissionNode::timer_callback.
double Mission::get_temperature() const
Get current temperature.
double
References temperature_.
Referenced by WaypointTemperatureKeeping::process, WaypointTemperatureProfile::process.
double Mission::get_depth() const
Get current depth.
double
References depth_.
Referenced by WaypointTemperatureProfile::process.
const std::shared_ptr< WaypointTemperatureKeeping > Mission::get_current_waypoint_temperature_keeping() const
Get the current waypoint temperature keeping object.
std::shared_ptr<WaypointTemperatureKeeping>
References current_waypoint_id_, waypoints_, WP_TEMPERATURE_KEEPING.
Referenced by MissionNode::timer_callback.
void Mission::set_limit_velocity_default(const double &vel)
References limit_velocity_default_.
void Mission::update_depth(const double &depth)
Update current depth from observations.
depth Observer's depth in meter
References depth_.
Referenced by MissionNode::depth_callback.
void Mission::update_temperature(const double &temperature)
Update current temperature from observations.
temperature Observer's temperature in degree Celsius
References temperature_.
Referenced by MissionNode::temperature_callback.
void Mission::idle_state_configuration(const rclcpp::Time &t_now)
Set depth control set point to surface when mission is not running.
t_now current time
References dc_msg_, waypoints_.
Referenced by update_state.
void Mission::decode_waypoint(const std::shared_ptr< Waypoint > &w, const boost::property_tree::ptree::value_type &v, rclcpp::Time &last_time) const
Decode unspecific waypoint parameters.
Updates w waypoint pointer v property tree containing the waypoint parameters last_time Time variable to update with the waypoint end time
References limit_velocity_default_, time_start_.
Referenced by decode_paths.
void Mission::decode_waypoint_depth(const std::shared_ptr< WaypointDepth > &w, const boost::property_tree::ptree::value_type &v, const double &depth_offset) const
Decode depth waypoint parameters.
w waypoint pointer v property tree containing the waypoint parameters depth_offset
References waypoints_.
Referenced by decode_paths.
void Mission::decode_waypoint_temperature_keeping(const std::shared_ptr< WaypointTemperatureKeeping > &w, const boost::property_tree::ptree::value_type &v) const
Decode Temperature keeping waypoint parameters.
w waypoint pointer v property tree containing the waypoint parameters
References waypoints_.
Referenced by decode_paths.
void Mission::decode_waypoint_temperature_profile(const std::shared_ptr< WaypointTemperatureProfile > &w, const boost::property_tree::ptree::value_type &v) const
Decode Temperature profile waypoint parameters.
w waypoint pointer v property tree containing the waypoint parameters
References waypoints_.
Referenced by decode_paths.
void Mission::decode_waypoint_gnss_profile(const std::shared_ptr< WaypointGNSSProfile > &w, const boost::property_tree::ptree::value_type &v) const
Decode GNSS profile waypoint parameters.
w waypoint pointer v property tree containing the waypoint parameters
References waypoints_.
Referenced by decode_paths.
int Mission::decode_paths(boost::property_tree::ptree::value_type &v, rclcpp::Time &last_time, const double &depth_offset)
Decode waypoints under the paths property tree.
v paths property tree last_time time variable to update with the last waypoint end time depth_offset depth offset to apply to depth waypoints EXIT_FAILURE if an error occurred while decoding paths, EXIT_SUCCESS otherwise
References decode_paths, decode_waypoint, decode_waypoint_depth, decode_waypoint_gnss_profile, decode_waypoint_temperature_keeping, decode_waypoint_temperature_profile, waypoints_, WP_DEPTH, WP_GNSS_PROFILE, WP_TEMPERATURE_KEEPING, WP_TEMPERATURE_PROFILE, XML_DEPTH, XML_DEPTH_LEGACY, XML_GNSS_PROFILE, XML_SEAFLOOR_LANDING, XML_TEMPERATURE_KEEPING, XML_TEMPERATURE_PROFILE, XML_TYPE.
Referenced by decode_paths, load_mission.