FilterPowerNode
size_t FilterPowerNode::filter_window_size_
Rclcpp.
Referenced by init_parameters, power_callback.
size_t FilterPowerNode::filter_median_remove_side_samples_
Referenced by compute_filter, init_parameters.
deque<double> FilterPowerNode::battery_volt_memory_
Variable.
Referenced by power_callback.
deque<double> FilterPowerNode::motor_current_memory_
Referenced by power_callback.
array<deque<double>, 2> FilterPowerNode::esc_current_memory_
Referenced by power_callback.
array<deque<double>, 4> FilterPowerNode::cell_volt_memory_
Referenced by power_callback.
rclcpp::Subscription<seabot2_msgs::msg::PowerState>::SharedPtr FilterPowerNode::subscriber_power_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::PowerState>::SharedPtr FilterPowerNode::publisher_power_data_
Referenced by init_interfaces, power_callback.
FilterPowerNode::FilterPowerNode()
References init_interfaces, init_parameters.
void FilterPowerNode::init_parameters()
Functions.
Init and get parameters of the Node
References filter_median_remove_side_samples_, filter_window_size_.
Referenced by FilterPowerNode.
void FilterPowerNode::init_interfaces()
Init interfaces of this node
References power_callback, publisher_power_data_, subscriber_power_data_.
Referenced by FilterPowerNode.
void FilterPowerNode::power_callback(const seabot2_msgs::msg::PowerState &msg)
Callback of the power data msg
References battery_volt_memory_, cell_volt_memory_, compute_filter, esc_current_memory_, filter_window_size_, motor_current_memory_, publisher_power_data_.
Referenced by init_interfaces.
double FilterPowerNode::compute_filter(deque< double > queue) const
Compute the median and mean filter queue
References filter_median_remove_side_samples_.
Referenced by power_callback.