PistonNode
rclcpp::TimerBase::SharedPtr PistonNode::timer_
Rclcpp.
Referenced by PistonNode.
std::chrono::milliseconds PistonNode::loop_dt_
Referenced by init_parameters, PistonNode.
bool PistonNode::is_detected_issue_reset_
loop dt
rclcpp::Time PistonNode::time_detected_issue_reset_
std::chrono::milliseconds PistonNode::delay_detected_issue_reset_
Piston PistonNode::piston_
I2C configuration.
Referenced by init_parameters, PistonNode, timer_callback, topic_position_set_point_callback.
std::chrono::seconds PistonNode::delay_no_data_
Piston.
Referenced by init_parameters, timer_callback.
rclcpp::Time PistonNode::time_last_cmd_received_
Referenced by timer_callback, topic_position_set_point_callback.
int PistonNode::last_cmd_
Referenced by topic_position_set_point_callback.
int PistonNode::cpt_piston_error_
Referenced by topic_position_set_point_callback.
const int PistonNode::cpt_piston_error_max_reset_
Referenced by topic_position_set_point_callback.
std::chrono::seconds PistonNode::delay_reset_piston_
rclcpp::Publisher<seabot2_msgs::msg::PistonState>::SharedPtr PistonNode::publisher_piston_state_
Topics.
Referenced by init_interfaces, timer_callback.
rclcpp::Subscription<seabot2_msgs::msg::PistonSetPoint>::SharedPtr PistonNode::subscription_position_set_point_
Referenced by init_interfaces.
PistonNode::PistonNode()
References Piston::i2c_open, init_interfaces, init_parameters, loop_dt_, piston_, Piston::set_piston_reset, timer_, timer_callback.
void PistonNode::timer_callback()
Functions.
References Piston::battery_voltage_, delay_no_data_, Piston::enable_, Piston::get_all_data, Piston::motor_cmd_, Piston::motor_current_, Piston::motor_sens_, Piston::motor_set_point_, piston_, Piston::PISTON_EXIT, Piston::position_, Piston::position_set_point_, publisher_piston_state_, Piston::set_piston_exit, Piston::state_, Piston::switch_bottom_, Piston::switch_top_, time_last_cmd_received_.
Referenced by PistonNode.
void PistonNode::init_parameters()
Init and get parameters of the Node
References delay_no_data_, Piston::getI2CAddr, Piston::getI2CPeriph, loop_dt_, piston_, Piston::R1_, Piston::R2_, Piston::setI2CAddr, Piston::setI2CPeriph.
Referenced by PistonNode.
void PistonNode::init_interfaces()
Init interfaces to this node (publishers & subscribers)
References publisher_piston_state_, subscription_position_set_point_, topic_position_set_point_callback.
Referenced by PistonNode.
void PistonNode::topic_position_set_point_callback(const seabot2_msgs::msg::PistonSetPoint &msg)
Callback for set point position msg
References cpt_piston_error_, cpt_piston_error_max_reset_, last_cmd_, piston_, Piston::PISTON_EXIT, Piston::position_set_point_, Piston::set_piston_exit, Piston::set_piston_regulation, Piston::set_piston_reset, Piston::set_position, Piston::state_, time_last_cmd_received_.
Referenced by init_interfaces.