SafetyNode
POWER_STATE_STATUS
ZERO_DEPTH_STATUS
rclcpp::TimerBase::SharedPtr SafetyNode::timer_
Rclcpp.
Referenced by SafetyNode.
std::chrono::milliseconds SafetyNode::loop_dt_
Referenced by init_parameters, SafetyNode.
std::chrono::seconds SafetyNode::delay_between_warning_msg_
loop dt
Referenced by test_internal_data.
bool SafetyNode::global_safety_ok_
Variable.
Referenced by timer_callback.
bool SafetyNode::safety_published_frequency_
Referenced by test_battery, test_depth, test_internal_data, test_piston, timer_callback.
bool SafetyNode::safety_depth_limit_
Referenced by test_depth, timer_callback.
bool SafetyNode::safety_batteries_limit_
Referenced by test_battery, timer_callback.
bool SafetyNode::safety_depressurization_
Referenced by test_internal_data, timer_callback.
bool SafetyNode::safety_seafloor_
Referenced by test_seabed_reached, timer_callback.
bool SafetyNode::safety_piston_
Referenced by test_piston, timer_callback.
bool SafetyNode::safety_zero_depth_
Referenced by test_zero_pressure, timer_callback.
double SafetyNode::cpu_
Referenced by get_ram_cpu, timer_callback.
double SafetyNode::ram_
Referenced by get_ram_cpu, timer_callback.
double SafetyNode::hdd_empty_space_
Referenced by get_hard_drive_empty_space, test_hdd_available_space, timer_callback.
double SafetyNode::hdd_empty_space_limit_
Referenced by init_parameters, test_hdd_available_space.
double SafetyNode::internal_humidity_
Referenced by internal_sensor_callback, test_internal_data.
double SafetyNode::internal_pressure_
Referenced by internal_sensor_callback, test_internal_data.
double SafetyNode::internal_temperature_
Referenced by internal_sensor_callback.
rclcpp::Time SafetyNode::internal_last_received_
Referenced by internal_sensor_callback, test_internal_data.
std::chrono::milliseconds SafetyNode::internal_no_data_warning_
Referenced by init_parameters, test_internal_data.
double SafetyNode::internal_humidity_limit_
Referenced by init_parameters, test_internal_data.
double SafetyNode::internal_pressure_limit_
Referenced by init_parameters, test_internal_data.
rclcpp::Time SafetyNode::internal_last_rclcpp_warning_
Referenced by test_internal_data.
double SafetyNode::depth_
Referenced by depth_callback, enable_chirp, flash_surface, test_depth, test_depth_max, test_zero_pressure.
double SafetyNode::velocity_
Referenced by depth_callback, test_seabed_reached, test_zero_pressure.
rclcpp::Time SafetyNode::depth_last_received_
Referenced by depth_callback, test_depth, test_depth_max.
std::chrono::milliseconds SafetyNode::depth_no_data_warning_
Referenced by init_parameters, test_depth, test_depth_max.
rclcpp::Time SafetyNode::depth_limit_live_last_update_
Referenced by test_depth_max.
std::chrono::milliseconds SafetyNode::depth_limit_live_last_update_warning_
Referenced by test_depth_max.
double SafetyNode::depth_limit_max_
Referenced by init_parameters, test_depth.
double SafetyNode::battery_volt_
Referenced by power_callback, test_battery.
rclcpp::Time SafetyNode::battery_last_received_
Referenced by power_callback, test_battery.
std::chrono::milliseconds SafetyNode::battery_no_data_warning_
Referenced by init_parameters, test_battery.
double SafetyNode::battery_volt_limit_
Referenced by init_parameters, test_battery.
int SafetyNode::power_state_
Referenced by power_callback, test_battery.
double SafetyNode::depth_flash_surface_
Referenced by enable_chirp, flash_surface, init_parameters.
bool SafetyNode::flash_surface_enable_
Referenced by flash_surface, timer_callback.
double SafetyNode::depth_chrip_enable_
Referenced by enable_chirp.
bool SafetyNode::chirp_is_enable_
Referenced by enable_chirp, timer_callback.
double SafetyNode::piston_position_
Referenced by piston_callback, test_piston.
double SafetyNode::piston_set_point_
Referenced by piston_callback, test_piston.
bool SafetyNode::piston_switch_top_
Referenced by piston_callback, test_seabed_reached.
int SafetyNode::piston_state_
Referenced by piston_callback, test_zero_pressure.
rclcpp::Time SafetyNode::piston_last_received_
Referenced by piston_callback, test_piston.
std::chrono::milliseconds SafetyNode::piston_no_data_warning_
Referenced by init_parameters, test_piston.
double SafetyNode::limit_piston_position_reset_depth_
uint16_t SafetyNode::piston_motor_speed_
Referenced by piston_callback, test_piston.
uint16_t SafetyNode::piston_motor_speed_stop_
Referenced by test_piston.
rclcpp::Time SafetyNode::piston_error_velocity_time_
Referenced by test_piston.
bool SafetyNode::piston_error_velocity_detected_
Referenced by test_piston.
std::chrono::milliseconds SafetyNode::piston_error_velocity_delay_
Referenced by init_parameters, test_piston.
double SafetyNode::piston_error_threshold_set_point_
Referenced by init_parameters, test_piston.
double SafetyNode::piston_error_threshold_position_
Referenced by init_parameters, test_piston.
double SafetyNode::piston_last_position_
Referenced by test_piston.
double SafetyNode::max_depth_reset_zero_
Referenced by init_parameters, test_zero_pressure.
double SafetyNode::max_velocity_reset_zero_
Referenced by init_parameters, test_seabed_reached, test_zero_pressure.
ZERO_DEPTH_STATUS SafetyNode::reset_depth_status_
Referenced by test_zero_pressure.
rclcpp::Time SafetyNode::depth_reset_time_wait_
Referenced by test_zero_pressure.
std::chrono::milliseconds SafetyNode::depth_reset_delay_wait_
Referenced by test_zero_pressure.
bool SafetyNode::is_zero_depth_once_
Referenced by test_zero_pressure.
double SafetyNode::ping_altitude_
Referenced by profile_callback, test_depth_max.
int SafetyNode::ping_confidence_
Referenced by profile_callback, test_depth_max.
int SafetyNode::ping_confidence_threshold_
Referenced by init_parameters, test_depth_max.
rclcpp::Time SafetyNode::ping_last_time_received_
Referenced by profile_callback, test_depth_max.
double SafetyNode::robot_height_ping_
Referenced by init_parameters, test_depth_max.
double SafetyNode::safety_distance_from_seabed_
Referenced by init_parameters, test_depth_max.
double SafetyNode::bathy_
Referenced by test_depth_max, timer_callback.
double SafetyNode::depth_allowed_max_
Referenced by init_parameters, test_depth_max.
double SafetyNode::depth_allowed_min_
Referenced by init_parameters, test_depth_max.
double SafetyNode::depth_limit_live_
Referenced by test_depth_max, timer_callback.
double SafetyNode::limit_depth_filter_coeff_
Referenced by test_depth_max.
std::chrono::milliseconds SafetyNode::ping_no_data_warning_
Referenced by init_parameters, test_depth_max.
bool SafetyNode::seabed_test_detected_
Referenced by test_seabed_reached.
rclcpp::Time SafetyNode::seabed_test_first_detected_
Referenced by test_seabed_reached.
std::chrono::milliseconds SafetyNode::seabed_delay_detection_
Referenced by init_parameters, test_seabed_reached.
bool SafetyNode::gnss_fix_once_
Referenced by test_gnss_fix, timer_callback.
int SafetyNode::gnss_mode_
Referenced by gpsd_callback, test_gnss_fix.
bool SafetyNode::gnss_fix_once_enable_
Referenced by init_parameters, test_gnss_fix.
bool SafetyNode::enable_limit_depth_
Referenced by init_parameters, test_depth_max.
bool SafetyNode::enable_flash_underwater_
Referenced by flash_surface, init_parameters.
rclcpp::Publisher<seabot2_msgs::msg::SafetyStatus2>::SharedPtr SafetyNode::publisher_safety_
Interfaces.
Referenced by init_interfaces, timer_callback.
rclcpp::Subscription<seabot2_msgs::msg::DepthPose>::SharedPtr SafetyNode::subscriber_depth_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::Bme280Data>::SharedPtr SafetyNode::subscriber_internal_sensor_filter_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::PowerState>::SharedPtr SafetyNode::subscriber_power_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::PistonState>::SharedPtr SafetyNode::subscriber_piston_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::Profile>::SharedPtr SafetyNode::subscriber_profile_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::GpsFix>::SharedPtr SafetyNode::subscriber_gnss_data_
Referenced by init_interfaces.
rclcpp::Client<std_srvs::srv::Trigger>::SharedPtr SafetyNode::client_zero_pressure_
Referenced by call_service_zero_depth, init_interfaces.
rclcpp::Client<std_srvs::srv::SetBool>::SharedPtr SafetyNode::client_flash_surface_
Referenced by call_service_flash_surface, init_interfaces.
rclcpp::Client<std_srvs::srv::SetBool>::SharedPtr SafetyNode::client_chirp_enable_
Referenced by call_service_chirp_enable, init_interfaces.
SafetyNode::SafetyNode()
References init_interfaces, init_parameters, loop_dt_, timer_, timer_callback.
void SafetyNode::init_parameters()
Init and get parameters of the Node
References battery_no_data_warning_, battery_volt_limit_, depth_allowed_max_, depth_allowed_min_, depth_flash_surface_, depth_limit_max_, depth_no_data_warning_, enable_flash_underwater_, enable_limit_depth_, gnss_fix_once_enable_, hdd_empty_space_limit_, internal_humidity_limit_, internal_no_data_warning_, internal_pressure_limit_, loop_dt_, max_depth_reset_zero_, max_velocity_reset_zero_, ping_confidence_threshold_, ping_no_data_warning_, piston_error_threshold_position_, piston_error_threshold_set_point_, piston_error_velocity_delay_, piston_no_data_warning_, robot_height_ping_, safety_distance_from_seabed_, seabed_delay_detection_.
Referenced by SafetyNode.
void SafetyNode::init_interfaces()
Init interfaces of this node
References client_chirp_enable_, client_flash_surface_, client_zero_pressure_, depth_callback, gpsd_callback, internal_sensor_callback, piston_callback, power_callback, profile_callback, publisher_safety_, subscriber_depth_data_, subscriber_gnss_data_, subscriber_internal_sensor_filter_, subscriber_piston_data_, subscriber_power_data_, subscriber_profile_data_.
Referenced by SafetyNode.
void SafetyNode::timer_callback()
Timer callback
References bathy_, chirp_is_enable_, cpu_, depth_limit_live_, enable_chirp, flash_surface, flash_surface_enable_, get_ram_cpu, global_safety_ok_, gnss_fix_once_, hdd_empty_space_, publisher_safety_, ram_, safety_batteries_limit_, safety_depressurization_, safety_depth_limit_, safety_piston_, safety_published_frequency_, safety_seafloor_, safety_zero_depth_, test_battery, test_depth, test_depth_max, test_gnss_fix, test_hdd_available_space, test_internal_data, test_piston, test_seabed_reached, test_zero_pressure.
Referenced by SafetyNode.
void SafetyNode::depth_callback(const seabot2_msgs::msg::DepthPose &msg)
Depth Callback msg
References depth_, depth_last_received_, velocity_.
Referenced by init_interfaces.
void SafetyNode::internal_sensor_callback(const seabot2_msgs::msg::Bme280Data &msg)
Internal sensor callback msg
References internal_humidity_, internal_last_received_, internal_pressure_, internal_temperature_.
Referenced by init_interfaces.
void SafetyNode::power_callback(const seabot2_msgs::msg::PowerState &msg)
Power callback msg
References battery_last_received_, battery_volt_, power_state_.
Referenced by init_interfaces.
void SafetyNode::piston_callback(const seabot2_msgs::msg::PistonState &msg)
msg
References piston_last_received_, piston_motor_speed_, piston_position_, piston_set_point_, piston_state_, piston_switch_top_.
Referenced by init_interfaces.
void SafetyNode::profile_callback(const seabot2_msgs::msg::Profile &msg)
Profile callback msg
References ping_altitude_, ping_confidence_, ping_last_time_received_.
Referenced by init_interfaces.
void SafetyNode::gpsd_callback(const seabot2_msgs::msg::GpsFix &msg)
Gnss callback msg
References gnss_mode_.
Referenced by init_interfaces.
bool SafetyNode::test_depth()
References depth_, depth_last_received_, depth_limit_max_, depth_no_data_warning_, safety_depth_limit_, safety_published_frequency_.
Referenced by timer_callback.
bool SafetyNode::test_zero_pressure()
References call_service_zero_depth, depth_, depth_reset_delay_wait_, depth_reset_time_wait_, IDLE, is_zero_depth_once_, max_depth_reset_zero_, max_velocity_reset_zero_, piston_state_, reset_depth_status_, safety_zero_depth_, velocity_, WAIT_RESET.
Referenced by timer_callback.
bool SafetyNode::test_battery()
References battery_last_received_, battery_no_data_warning_, battery_volt_, battery_volt_limit_, POWER_ON, power_state_, safety_batteries_limit_, safety_published_frequency_.
Referenced by timer_callback.
bool SafetyNode::test_piston()
References piston_error_threshold_position_, piston_error_threshold_set_point_, piston_error_velocity_delay_, piston_error_velocity_detected_, piston_error_velocity_time_, piston_last_position_, piston_last_received_, piston_motor_speed_, piston_motor_speed_stop_, piston_no_data_warning_, piston_position_, piston_set_point_, safety_piston_, safety_published_frequency_.
Referenced by timer_callback.
bool SafetyNode::test_internal_data()
References delay_between_warning_msg_, internal_humidity_, internal_humidity_limit_, internal_last_rclcpp_warning_, internal_last_received_, internal_no_data_warning_, internal_pressure_, internal_pressure_limit_, safety_depressurization_, safety_published_frequency_.
Referenced by timer_callback.
void SafetyNode::test_depth_max()
Test max depth
References bathy_, depth_, depth_allowed_max_, depth_allowed_min_, depth_last_received_, depth_limit_live_, depth_limit_live_last_update_, depth_limit_live_last_update_warning_, depth_no_data_warning_, enable_limit_depth_, limit_depth_filter_coeff_, ping_altitude_, ping_confidence_, ping_confidence_threshold_, ping_last_time_received_, ping_no_data_warning_, robot_height_ping_, safety_distance_from_seabed_.
Referenced by timer_callback.
bool SafetyNode::test_seabed_reached()
Test if seabed is reached
References max_velocity_reset_zero_, piston_switch_top_, safety_seafloor_, seabed_delay_detection_, seabed_test_detected_, seabed_test_first_detected_, velocity_.
Referenced by timer_callback.
bool SafetyNode::test_gnss_fix()
Test if gnss fix is ok
References gnss_fix_once_, gnss_fix_once_enable_, gnss_mode_.
Referenced by timer_callback.
bool SafetyNode::test_hdd_available_space()
References get_hard_drive_empty_space, hdd_empty_space_, hdd_empty_space_limit_.
Referenced by timer_callback.
void SafetyNode::flash_surface()
Detect if surface is reached
References call_service_flash_surface, depth_, depth_flash_surface_, enable_flash_underwater_, flash_surface_enable_.
Referenced by timer_callback.
void SafetyNode::enable_chirp()
Enable chirp
References call_service_chirp_enable, chirp_is_enable_, depth_, depth_chrip_enable_, depth_flash_surface_.
Referenced by timer_callback.
int SafetyNode::call_service_flash_surface(const bool &is_surface) const
is_surface
References client_flash_surface_.
Referenced by flash_surface.
int SafetyNode::call_service_chirp_enable(const bool &enable) const
call_service_chirp_enable enable
References client_chirp_enable_.
Referenced by enable_chirp.
int SafetyNode::call_service_zero_depth() const
References client_zero_pressure_.
Referenced by test_zero_pressure.
void SafetyNode::get_ram_cpu()
References cpu_, file, ram_.
Referenced by timer_callback.
void SafetyNode::get_hard_drive_empty_space()
Get the hard drive empty space
References hdd_empty_space_.
Referenced by test_hdd_available_space.