AlphaSolver
double AlphaSolver::alpha_search_max_
Referenced by compute_alpha.
vector< array < double, 2 > > AlphaSolver::computed_memory_
Referenced by add_to_memory, exist_in_memory, get_computed_memory.
bool AlphaSolver::enable_test_in_memory_
Referenced by exist_in_memory, set_test_in_memory.
AlphaSolver::AlphaSolver()=default
double AlphaSolver::compute_alpha(const double beta)
References alpha_search_max_, exist_in_memory.
Referenced by DepthControlNode::generate_velocity_pairs, DepthControlNode::timer_callback, DepthControl::update_waypoint.
pair< bool, double > AlphaSolver::exist_in_memory(const double beta)
Update the coefficients Cz A B dVp_max Check if the value is already computed
References computed_memory_, enable_test_in_memory_.
Referenced by compute_alpha.
void AlphaSolver::add_to_memory(const double beta, const double alpha)
Add the value to the memory beta alpha
References computed_memory_.
Referenced by DepthControlNode::init_parameters.
vector< array< double, 2 > > & AlphaSolver::get_computed_memory()
get_computed_memory
References computed_memory_.
Referenced by DepthControlNode::generate_velocity_pairs.
void AlphaSolver::set_test_in_memory(bool enable)
set_test_in_memory enable
References enable_test_in_memory_.
Referenced by DepthControlNode::generate_velocity_pairs.