Kalman
const int Kalman::NB_MESURES
const int Kalman::NB_STATES
const int Kalman::NB_COMMAND
double Kalman::physics_rho_
Physical characteristics.
Referenced by KalmanNode::init_parameters, update_coeffAB, update_density.
double Kalman::physics_g_
Referenced by KalmanNode::init_parameters, update_coeffAB.
double Kalman::robot_mass_
Referenced by KalmanNode::init_parameters, update_coeffAB.
double Kalman::robot_added_mass_
Referenced by update_coeffAB.
double Kalman::robot_diameter_
Referenced by KalmanNode::init_parameters.
double Kalman::screw_thread_
Referenced by KalmanNode::init_parameters, init_parameters.
double Kalman::tick_per_turn_
Referenced by KalmanNode::init_parameters, init_parameters.
double Kalman::piston_diameter_
Referenced by KalmanNode::init_parameters, init_parameters.
double Kalman::piston_max_tick_
Referenced by KalmanNode::init_parameters, init_parameters.
const double Kalman::degree_to_kelvin_
Referenced by update_temperature.
double Kalman::tick_to_volume_
Referenced by compute_kalman, init_parameters.
double Kalman::coeff_A_
Referenced by f_dyn, kalman_predict, update_coeffAB.
double Kalman::coeff_B_
Referenced by f_dyn, kalman_predict, update_coeffAB.
const double Kalman::fz_model_boundary_velocity_positive_
Referenced by fz_computation, fz_derivative_computation.
const double Kalman::fz_model_boundary_velocity_negative_
Referenced by fz_computation, fz_derivative_computation.
const double Kalman::fz_derivative_at_model_boundary_positive_
Referenced by fz_computation.
const double Kalman::fz_offset_at_model_boundary_positive_
Referenced by fz_computation.
const double Kalman::fz_derivative_at_model_boundary_negative_
Referenced by fz_computation.
const double Kalman::fz_offset_at_model_boundary_negative_
Referenced by fz_computation.
double Kalman::piston_max_volume_
Referenced by init_parameters, is_out_of_range.
double Kalman::enable_kalman_depth_
Initialization variables.
Referenced by compute_kalman, KalmanNode::init_parameters.
double Kalman::piston_volume_eq_init_
m
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::init_chi_
m3
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::init_chi2_
m3/m
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::init_cz_
m3/m2
Referenced by KalmanNode::init_parameters.
double Kalman::init_volume_air_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_alpha_velocity_
(V*P/T)
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_alpha_depth_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_alpha_offset_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_alpha_chi_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_alpha_chi2_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_alpha_cz_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_alpha_volume_air_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_init_velocity_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_init_depth_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_init_offset_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_init_chi_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_init_chi2_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_init_cz_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_init_volume_air_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::gamma_beta_depth_
Referenced by init_kalman, KalmanNode::init_parameters.
double Kalman::fusion_depth_
Callback data.
Referenced by compute_kalman, init_kalman, set_new_depth_data.
double Kalman::fusion_velocity_
Referenced by compute_kalman, init_kalman, set_new_depth_data.
rclcpp::Time Kalman::fusion_stamp_
Referenced by compute_kalman, set_new_depth_data.
double Kalman::piston_position_
Referenced by compute_kalman, set_new_piston_data.
rclcpp::Time Kalman::piston_stamp_
Referenced by compute_kalman, set_new_piston_data.
double Kalman::temperature_
Referenced by compute_kalman, f_dyn, KalmanNode::init_parameters, kalman_predict, update_temperature.
double Kalman::pressure_
in K (15C)
Referenced by compute_kalman, f_dyn, KalmanNode::init_parameters, kalman_predict, update_pressure.
Matrix< double, NB_STATES, 1 > Kalman::xhat_
in Pa (1013.23 hPa)
Kalman variables
Referenced by compute_kalman, init_kalman.
Matrix< double, NB_STATES, 1 > Kalman::x_forcast_
Referenced by compute_kalman, init_kalman, KalmanNode::publish_data.
Matrix< double, NB_STATES, NB_STATES > Kalman::gamma_
Referenced by compute_kalman, init_kalman.
Matrix< double, NB_STATES, NB_STATES > Kalman::gamma_forcast_
Referenced by compute_kalman, KalmanNode::publish_data.
double Kalman::offset_total_
Referenced by compute_kalman, KalmanNode::publish_data.
Matrix< double, NB_STATES, NB_STATES > Kalman::gamma_alpha_
Referenced by compute_kalman, init_kalman.
Matrix< double, NB_MESURES, NB_MESURES > Kalman::gamma_beta_
Referenced by compute_kalman, init_kalman.
Matrix< double, NB_MESURES, NB_STATES > Kalman::Ck_
Referenced by compute_kalman, init_kalman.
bool Kalman::enable_kalman_
Referenced by compute_kalman.
bool Kalman::is_valid_
Referenced by compute_kalman, KalmanNode::publish_data.
rclcpp::Time Kalman::time_last_predict_
Referenced by compute_kalman, init_parameters, kalman_predict, KalmanNode::publish_data.
std::chrono::milliseconds Kalman::forecast_dt_
Referenced by compute_kalman.
Kalman::Kalman()
References init_kalman.
void Kalman::init_parameters(const rclcpp::Time &init_time)
References init_kalman, M_PI, piston_diameter_, piston_max_tick_, piston_max_volume_, screw_thread_, tick_per_turn_, tick_to_volume_, time_last_predict_, update_coeffAB.
Referenced by KalmanNode::init_parameters.
void Kalman::update_density(double physics_rho)
physics_rho
References physics_rho_, update_coeffAB.
Referenced by KalmanNode::density_callback.
double Kalman::fz_computation(double velocity) const
References fz_derivative_at_model_boundary_negative_, fz_derivative_at_model_boundary_positive_, fz_model_boundary_velocity_negative_, fz_model_boundary_velocity_positive_, fz_offset_at_model_boundary_negative_, fz_offset_at_model_boundary_positive_.
Referenced by f_dyn.
double Kalman::fz_derivative_computation(double velocity) const
References fz_model_boundary_velocity_negative_, fz_model_boundary_velocity_positive_.
Referenced by kalman_predict.
void Kalman::compute_kalman(bool new_depth_data=false, bool new_piston_data=false)
new_depth_data new_piston_data
References Ck_, enable_kalman_, enable_kalman_depth_, forecast_dt_, fusion_depth_, fusion_stamp_, fusion_velocity_, gamma_, gamma_alpha_, gamma_beta_, gamma_forcast_, init_kalman, is_out_of_range, is_valid_, kalman_correc, kalman_predict, offset_total_, piston_position_, piston_stamp_, pressure_, temperature_, tick_to_volume_, time_last_predict_, x_forcast_, xhat_.
Referenced by set_new_depth_data, set_new_piston_data.
void Kalman::set_new_piston_data(double position, double set_point, const rclcpp::Time &stamp)
position set_point stamp
References compute_kalman, piston_position_, piston_stamp_.
Referenced by KalmanNode::state_callback.
void Kalman::set_new_depth_data(double depth, double velocity, const rclcpp::Time &stamp)
depth velocity stamp
References compute_kalman, fusion_depth_, fusion_stamp_, fusion_velocity_.
Referenced by KalmanNode::depth_callback.
void Kalman::update_temperature(double temperature)
temperature
References degree_to_kelvin_, temperature_.
Referenced by KalmanNode::temperature_callback.
void Kalman::update_pressure(double pressure)
pressure [absolute, in bar]
References pressure_.
Referenced by KalmanNode::depth_callback.
void Kalman::update_coeffAB()
Update the coefficients of the equation of state
References coeff_A_, coeff_B_, physics_g_, physics_rho_, robot_added_mass_, robot_mass_.
Referenced by init_parameters, update_density.
Matrix< double, Kalman::NB_STATES, 1 > Kalman::f_dyn(const Matrix< double, NB_STATES, 1 > &x, const Matrix< double, NB_COMMAND, 1 > &u) const
x u
References coeff_A_, coeff_B_, fz_computation, pressure_, temperature_.
Referenced by kalman_predict.
void Kalman::kalman_predict(Matrix< double, NB_STATES, 1 > &x, Matrix< double, NB_STATES, NB_STATES > &gamma, const Matrix< double, NB_COMMAND, 1 > &u, const Matrix< double, NB_STATES, NB_STATES > &gamma_alpha, const double &dt) const
x gamma u gamma_alpha dt
References coeff_A_, coeff_B_, f_dyn, fz_derivative_computation, pressure_, temperature_, time_last_predict_.
Referenced by compute_kalman.
void Kalman::init_kalman()
References Ck_, fusion_depth_, fusion_velocity_, gamma_, gamma_alpha_, gamma_alpha_chi2_, gamma_alpha_chi_, gamma_alpha_cz_, gamma_alpha_depth_, gamma_alpha_offset_, gamma_alpha_velocity_, gamma_alpha_volume_air_, gamma_beta_, gamma_beta_depth_, gamma_init_chi2_, gamma_init_chi_, gamma_init_cz_, gamma_init_depth_, gamma_init_offset_, gamma_init_velocity_, gamma_init_volume_air_, init_chi2_, init_chi_, init_volume_air_, piston_volume_eq_init_, x_forcast_, xhat_.
Referenced by compute_kalman, init_parameters, Kalman.
bool Kalman::is_out_of_range(const Matrix< double, NB_STATES, 1 > &xhat) const
Test if state of Kalman filter is out of range of admissible values xhat
References piston_max_volume_.
Referenced by compute_kalman.
void Kalman::kalman_correc(Matrix< double, NB_STATES, 1 > &x, Matrix< double, NB_STATES, NB_STATES > &gamma, const Matrix< double, NB_MESURES, 1 > &y, const Matrix< double, NB_MESURES, NB_MESURES > &gamma_beta, const Matrix< double, NB_MESURES, NB_STATES > &Ck)
x gamma y gamma_beta Ck
Referenced by compute_kalman.