TemperatureTSYS01Node
rclcpp::TimerBase::SharedPtr TemperatureTSYS01Node::timer_
Variables.
Referenced by TemperatureTSYS01Node.
rclcpp::Publisher<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr TemperatureTSYS01Node::publisher_sensor_
Referenced by init_interfaces, timer_callback.
Temperature_TSYS01 TemperatureTSYS01Node::temperature_sensor_
Referenced by init_parameters, TemperatureTSYS01Node, timer_callback.
std::chrono::milliseconds TemperatureTSYS01Node::loop_dt_
Referenced by init_parameters, TemperatureTSYS01Node.
TemperatureTSYS01Node::TemperatureTSYS01Node()
References init_interfaces, init_parameters, Temperature_TSYS01::init_sensor, loop_dt_, temperature_sensor_, timer_, timer_callback.
void TemperatureTSYS01Node::timer_callback()
Functions.
References Temperature_TSYS01::get_temperature, Temperature_TSYS01::measure, publisher_sensor_, temperature_sensor_.
Referenced by TemperatureTSYS01Node.
void TemperatureTSYS01Node::init_parameters()
References Temperature_TSYS01::getI2CAddr, Temperature_TSYS01::getI2CPeriph, loop_dt_, Temperature_TSYS01::setI2CAddr, Temperature_TSYS01::setI2CPeriph, temperature_sensor_.
Referenced by TemperatureTSYS01Node.
void TemperatureTSYS01Node::init_interfaces()
References publisher_sensor_.
Referenced by TemperatureTSYS01Node.