Temperature_TSYS01
rclcpp::Node* Temperature_TSYS01::n_
Referenced by i2c_open, init_sensor, measure, reset, Temperature_TSYS01.
int Temperature_TSYS01::file_
Pointer to rclcpp Node.
Referenced by i2c_open, init_sensor, measure, reset, ~Temperature_TSYS01.
int Temperature_TSYS01::i2c_addr_
Referenced by getI2CAddr, i2c_open, measure, setI2CAddr.
std::string Temperature_TSYS01::i2c_periph_
Referenced by getI2CPeriph, i2c_open, setI2CPeriph.
u_int16_t Temperature_TSYS01::k_[5][5]
Referenced by init_sensor, measure.
bool Temperature_TSYS01::valid_data_
Referenced by measure.
double Temperature_TSYS01::temperature_
Referenced by get_temperature, measure.
Temperature_TSYS01::Temperature_TSYS01(rclcpp::Node *n)
Constructor of the object n
References n_.
Temperature_TSYS01::~Temperature_TSYS01()
References file_.
int Temperature_TSYS01::i2c_open()
References file_, i2c_addr_, i2c_periph_, n_.
Referenced by init_sensor.
int Temperature_TSYS01::init_sensor()
References CMD_PROM, file_, i2c_open, k_, n_, reset.
Referenced by TemperatureTSYS01Node::TemperatureTSYS01Node.
int Temperature_TSYS01::reset() const
References CMD_RESET, file_, n_.
Referenced by init_sensor.
bool Temperature_TSYS01::measure()
References CMD_ADC_CONV, CMD_ADC_READ, file_, i2c_addr_, k_, n_, temperature_, valid_data_.
Referenced by TemperatureTSYS01Node::timer_callback.
double Temperature_TSYS01::get_temperature() const
References temperature_.
Referenced by TemperatureTSYS01Node::timer_callback.
int Temperature_TSYS01::getI2CAddr() const
References i2c_addr_.
Referenced by TemperatureTSYS01Node::init_parameters.
void Temperature_TSYS01::setI2CAddr(int i2CAddr)
i2CAddr
References i2c_addr_.
Referenced by TemperatureTSYS01Node::init_parameters.
const string & Temperature_TSYS01::getI2CPeriph() const
References i2c_periph_.
Referenced by TemperatureTSYS01Node::init_parameters.
void Temperature_TSYS01::setI2CPeriph(const std::string &i2CPeriph)
i2CPeriph
References i2c_periph_.
Referenced by TemperatureTSYS01Node::init_parameters.