LatLonControlNode
rclcpp::TimerBase::SharedPtr LatLonControlNode::timer_
Rclcpp.
Referenced by LatLonControlNode.
std::chrono::milliseconds LatLonControlNode::loop_dt_
Referenced by init_parameters, LatLonControlNode.
LatLonControl LatLonControlNode::llc_
loop dt
Referenced by gps_fix_callback, imu_data_callback, init_parameters, safety_callback, timer_callback.
rclcpp::Subscription<seabot2_msgs::msg::GpsFix>::SharedPtr LatLonControlNode::subscriber_gps_fix_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::RawData>::SharedPtr LatLonControlNode::subscriber_imu_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::SafetyStatus2>::SharedPtr LatLonControlNode::subscriber_safety_data_
Referenced by init_interfaces.
rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr LatLonControlNode::publisher_thrusters_cmd_
Referenced by init_interfaces, timer_callback.
LatLonControlNode::LatLonControlNode()
References init_interfaces, init_parameters, loop_dt_, timer_, timer_callback.
LatLonControlNode::~LatLonControlNode()
void LatLonControlNode::init_parameters()
Init and get parameters of the Node
References LatLonControl::angular_velocity_max_, LatLonControl::distance_threshold_slowing_down_, LatLonControl::lat_set_point_, LatLonControl::linear_velocity_max_, llc_, LatLonControl::lon_set_point_, loop_dt_.
Referenced by LatLonControlNode.
void LatLonControlNode::init_interfaces()
Init interfaces of this node
References gps_fix_callback, imu_data_callback, publisher_thrusters_cmd_, safety_callback, subscriber_gps_fix_data_, subscriber_imu_data_, subscriber_safety_data_.
Referenced by LatLonControlNode.
void LatLonControlNode::timer_callback()
Timer callback
References LatLonControl::compute_control_commands, LatLonControl::get_angular_velocity, LatLonControl::get_linear_velocity, llc_, publisher_thrusters_cmd_.
Referenced by LatLonControlNode.
void LatLonControlNode::imu_data_callback(const seabot2_msgs::msg::RawData &msg)
msg
References llc_, LatLonControl::update_heading.
Referenced by init_interfaces.
void LatLonControlNode::gps_fix_callback(const seabot2_msgs::msg::GpsFix &msg)
msg
References llc_, LatLonControl::update_lat_lon.
Referenced by init_interfaces.
void LatLonControlNode::safety_callback(const seabot2_msgs::msg::SafetyStatus2 &msg)
msg
References llc_, LatLonControl::update_safety.
Referenced by init_interfaces.