ICM20948
double ICM20948::acc_x_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::acc_y_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::acc_z_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::gyro_x_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::gyro_y_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::gyro_z_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::mag_x_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::mag_y_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::mag_z_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
float ICM20948::temp_
Referenced by ICM20948Node::compute_ahrs, get_measure, ICM20948Node::timer_callback.
double ICM20948::accel_x_bias_
Referenced by init.
double ICM20948::accel_y_bias_
Referenced by init.
double ICM20948::accel_z_bias_
Referenced by init.
double ICM20948::mag_x_old_
double ICM20948::mag_y_old_
double ICM20948::mag_z_old_
int ICM20948::nb_not_update
bool ICM20948::mag_data_has_been_skipped_
Referenced by ICM20948Node::compute_ahrs, get_measure.
bool ICM20948::mag_data_is_ready_
Referenced by ICM20948Node::compute_ahrs, get_measure.
bool ICM20948::mag_sensor_magnetic_overflow_
Referenced by ICM20948Node::compute_ahrs, get_measure.
uint8_t ICM20948::spi_bus_
Referenced by init.
uint8_t ICM20948::spi_device_
Referenced by init.
uint8_t ICM20948::gyro_dlpfcfg_
Referenced by init.
uint8_t ICM20948::gyro_fs_sel_
Referenced by get_measure, init, ICM20948Node::init_parameters.
uint8_t ICM20948::gyro_fchoice_
Referenced by init.
uint8_t ICM20948::gyro_avgcfg_
Referenced by init.
uint8_t ICM20948::gyro_smplrt_div_
Referenced by init.
uint8_t ICM20948::accel_smplrt_div_
Referenced by init.
uint8_t ICM20948::accel_dlpfcfg_
Referenced by init.
uint8_t ICM20948::accel_fs_sel_
Referenced by get_measure, init, ICM20948Node::init_parameters.
uint8_t ICM20948::accel_fchoice_
Referenced by init.
uint8_t ICM20948::acc_dec3Cfg_
Referenced by init.
uint8_t ICM20948::accel_intel_en_
Referenced by init.
uint8_t ICM20948::accel_intel_mode_int_
Referenced by init.
uint8_t ICM20948::accel_intel_thr_
Referenced by init.
const std::array< double, 4 > ICM20948::accel_sensitivity_
Referenced by get_measure.
const std::array< double, 4 > ICM20948::gyro_sensitivity_
Referenced by get_measure.
const std::array< double, 4 > ICM20948::gyro_full_scale_
Referenced by ICM20948Node::init_parameters.
const std::array< double, 4 > ICM20948::accel_full_scale_
const double ICM20948::mag_sensitivity_
Referenced by get_measure.
const double ICM20948::mag_normalization_
Referenced by get_measure.
AK09916_mode_e ICM20948::mag_mode_
Referenced by init_magnetometer.
uint8_t ICM20948::i2c_smplrt_div_
uint8_t ICM20948::slv4_dly_
Referenced by init, read_i2c_AK09916_byte, write_i2c_AK09916_byte.
uint8_t ICM20948::i2c_slv0_delay_en_
Referenced by init.
uint8_t ICM20948::i2c_frequency_clk_
Referenced by init_magnetometer.
uint8_t ICM20948::i2c_lp_mode_
uint8_t ICM20948::i2c_if_dis_
Referenced by init_magnetometer, reset_i2c.
int ICM20948::spi_fd_
Referenced by init, open_spi, readRegister, writeRegister, ~ICM20948.
uint32_t ICM20948::speed_
Referenced by open_spi, readRegister, writeRegister.
int ICM20948::current_bank_
Referenced by select_bank.
uint8_t ICM20948::cs_change_
uint16_t ICM20948::delay_usecs_
Referenced by readRegister, writeRegister.
ICM20948::ICM20948()=default
Constructor
ICM20948::~ICM20948()
Destructor
References spi_fd_.
int ICM20948::init()
Init IMU
References acc_dec3Cfg_, accel_dlpfcfg_, accel_fchoice_, accel_fs_sel_, accel_intel_en_, accel_intel_mode_int_, accel_intel_thr_, accel_smplrt_div_, accel_x_bias_, accel_y_bias_, accel_z_bias_, AK09916_ADDRESS, AK09916_ST1, gyro_avgcfg_, gyro_dlpfcfg_, gyro_fchoice_, gyro_fs_sel_, gyro_smplrt_div_, i2c_slv0_delay_en_, ICM20948_BK0_PWR_MGMT_1, ICM20948_BK0_WHO_AM_I, ICM20948_BK1_XA_OFFS_H, ICM20948_BK2_ACCEL_CONFIG, ICM20948_BK2_ACCEL_CONFIG_2, ICM20948_BK2_ACCEL_INTEL_CTRL, ICM20948_BK2_ACCEL_SMPLRT_DIV_1, ICM20948_BK2_ACCEL_SMPLRT_DIV_2, ICM20948_BK2_ACCEL_WOM_THR, ICM20948_BK2_GYRO_CONFIG_1, ICM20948_BK2_GYRO_CONFIG_2, ICM20948_BK2_GYRO_SMPLRT_DIV, ICM20948_BK3_I2C_MST_DELAY_CTRL, ICM20948_BK3_I2C_SLV0_ADDR, ICM20948_BK3_I2C_SLV0_CTRL, ICM20948_BK3_I2C_SLV0_REG, ICM20948_BK3_I2C_SLV4_CTRL, ICM20948_WHO_AM_I, imuJoinAccelConfig, imuJoinAccelConfig2, imuJoinAccelIntelCtrl, imuJoinAccelSmplrtDiv1, imuJoinAccelSmplrtDiv2, imuJoinGyroConfig1, imuJoinGyroConfig2, imuJoinI2cMstDelayCtrl, imuJoinI2cSlv4Ctrl, imuJoinPwrMgmt1, init_magnetometer, open_spi, readRegister, select_bank, slv4_dly_, spi_bus_, spi_device_, spi_fd_, writeRegister.
Referenced by ICM20948Node::ICM20948Node.
int ICM20948::get_measure()
Get measure
References acc_x_, acc_y_, acc_z_, accel_fs_sel_, accel_sensitivity_, gyro_fs_sel_, gyro_sensitivity_, gyro_x_, gyro_y_, gyro_z_, ICM20948_BK0_ACCEL_XOUT_H, mag_data_has_been_skipped_, mag_data_is_ready_, mag_normalization_, mag_sensitivity_, mag_sensor_magnetic_overflow_, mag_x_, mag_y_, mag_z_, readRegister, select_bank, temp_.
Referenced by ICM20948Node::timer_callback.
int ICM20948::open_spi(const unsigned int &spi_bus, const unsigned int &spi_device)
Open SPI
References speed_, spi_fd_.
Referenced by init.
std::vector< uint8_t > ICM20948::readRegister(const uint8_t &reg, const uint32_t &len=1) const
Read register reg len
References delay_usecs_, speed_, spi_fd_.
Referenced by dump_bank, get_measure, i2c_master_reset, init, read_i2c_AK09916_byte, write_i2c_AK09916_byte, writeRegister.
int ICM20948::writeRegister(const uint8_t &reg, const std::vector< uint8_t > &data) const
Write register reg data
References delay_usecs_, speed_, spi_fd_.
Referenced by dump_bank, i2c_master_reset, init, init_magnetometer, read_i2c_AK09916_byte, reset_i2c, reset_i2c_slv4, select_bank, write_i2c_AK09916_byte, writeRegister.
int ICM20948::writeRegister(const uint8_t &reg, const uint8_t &data, bool check_write=true)
Write register reg data
References readRegister, writeRegister.
void ICM20948::dump_bank(const int &bank_id)
Dump bank bank_id
References ICM20948_BK0_REG_BANK_SEL, imuJoinBankId, readRegister, writeRegister.
Referenced by dump_icm20948.
void ICM20948::dump_ak09916()
dump ak09916
References read_i2c_AK09916_byte.
void ICM20948::dump_icm20948()
dump ICMS20948
References dump_bank.
int ICM20948::reset_i2c_slv4()
reset i2c slv4
References ICM20948_BK0_REG_BANK_SEL, ICM20948_BK3_I2C_SLV4_ADDR, ICM20948_BK3_I2C_SLV4_DO, ICM20948_BK3_I2C_SLV4_REG, imuJoinBankId, writeRegister.
int ICM20948::reset_i2c()
reset i2c
References i2c_if_dis_, ICM20948_BK0_USER_CTRL, imuJoinUserCtrl, writeRegister.
int ICM20948::select_bank(const uint8_t &bank_id)
select bank
References current_bank_, ICM20948_BK0_REG_BANK_SEL, imuJoinBankId, writeRegister.
Referenced by get_measure, i2c_master_reset, init, init_magnetometer, read_i2c_AK09916_byte, write_i2c_AK09916_byte.
int ICM20948::i2c_master_reset()
i2c master reset
References ICM20948_BK0_USER_CTRL, readRegister, select_bank, writeRegister.
Referenced by init_magnetometer.
bool ICM20948::test_who_i_am_mag()
test who I am magnetometer
References AK09916_WHO_AM_I, AK09916_WHO_AM_I_REG, read_i2c_AK09916_byte.
Referenced by init_magnetometer.
int ICM20948::set_mag_mode(const AK09916_mode_e &mode)
Set magnetometer mode mode
References AK09916_CNTL2, AK09916_mode_power_down, read_i2c_AK09916_byte, write_i2c_AK09916_byte.
Referenced by init_magnetometer.
int ICM20948::init_magnetometer()
Init magnetometer
References i2c_frequency_clk_, i2c_if_dis_, i2c_master_reset, ICM20948_BK0_INT_ENABLE, ICM20948_BK0_INT_PIN_CFG, ICM20948_BK0_USER_CTRL, ICM20948_BK3_I2C_MST_CTRL, imuJoinIntEnable, imuJoinIntPinCfg, imuJoinMstCtrl, imuJoinUserCtrl, mag_mode_, select_bank, set_mag_mode, test_who_i_am_mag, writeRegister.
Referenced by init.
int ICM20948::write_i2c_AK09916_byte(const uint8_t &reg, const uint8_t &data)
References AK09916_ADDRESS, ICM20948_BK0_I2C_MST_STATUS, ICM20948_BK3_I2C_SLV4_ADDR, ICM20948_BK3_I2C_SLV4_CTRL, ICM20948_BK3_I2C_SLV4_DO, ICM20948_BK3_I2C_SLV4_REG, imuJoinI2cSlv4Ctrl, readRegister, select_bank, slv4_dly_, writeRegister.
Referenced by set_mag_mode.
int ICM20948::read_i2c_AK09916_byte(const uint8_t &reg, uint8_t &data)
References AK09916_ADDRESS, ICM20948_BK0_I2C_MST_STATUS, ICM20948_BK3_I2C_SLV4_ADDR, ICM20948_BK3_I2C_SLV4_CTRL, ICM20948_BK3_I2C_SLV4_DI, ICM20948_BK3_I2C_SLV4_REG, imuJoinI2cSlv4Ctrl, readRegister, select_bank, slv4_dly_, writeRegister.
Referenced by dump_ak09916, set_mag_mode, test_who_i_am_mag.
uint8_t ICM20948::imuJoinUserCtrl(const uint8_t dmpEn, const uint8_t fifoEn, const uint8_t i2cMstEn, const uint8_t i2cIfDis, const uint8_t dmpRst, const uint8_t sramRst, const uint8_t i2cMstRst)
imuJoinUserCtrl dmpEn 1: Enables DMP (Digital Motion Processor) features 0: disables fifoEn 1: Enable FIFO operation mode 0: Disable FIFO access from serial interface i2cMstEn 1: Enable i2c master 0: disable i2c master i2cIfDis 1: Reset I2C Slave module and put the serial interface in SPI mode on dmpRst 1: reset DMP module (autoclear bit) sramRst 1: reset SRAM module (autoclear bit) i2cMstRst 1: reset i2c Master (autoclear bit)
Referenced by init_magnetometer, reset_i2c.
uint8_t ICM20948::imuJoinLpConfig(const uint8_t i2cMstCycle, const uint8_t accelCycle, const uint8_t gyroCycle)
imuJoinLpConfig i2cMstCycle 1: i2c master will operate in duty cycle mode (ODR -> I2C_MST_ODR_CONFIG) 0: disable i2c master duty cycle accelCycle 1: operate accel in duty cycle mode (ODR -> ACCEL_SMPRT_DIV) 0: disable gyroCycle 1: operate gyro in duty cycle mode (ODR -> ACCEL_SMPRT_DIV) 0: disable
uint8_t ICM20948::imuJoinPwrMgmt1(const uint8_t deviceRst, const uint8_t sleep, const uint8_t lpEn, const uint8_t tempDis, const uint8_t clkSel)
imuJoinPwrMgmt1 deviceRst 1: Reset internal registers - the bit will auto clear sleep 1: chip enters sleep mode, 0: awake chip lpEn 1: turn on low power feature, 0 turn off tempDis 1: disable temperature sensor clkSel 0: internal 20MHz oscillator, 1-5: auto selects best available clk source, 6: internal 20 MHz oscillator, 7: Stops the clock and keeps timing generator in reset
Referenced by init.
uint8_t ICM20948::imuJoinPwrMgmt2(const uint8_t disableAccel, const uint8_t disableGyro)
imuJoinPwrMgmt2 disableAccel 1: all accel disable 0: all accel enable disableGyro 1: all gyro disable 0: all gyro enable
uint8_t ICM20948::joinGyroSmplrtDiv(const uint8_t gyroSmplrtDiv)
imuJoinGyroSmplrtDiv
uint8_t ICM20948::imuJoinGyroConfig1(const uint8_t gyroDlpfCfg, const uint8_t gyroFsSel, const uint8_t gyroFchoice)
imuJoinGyroConfig1 gyroDlpfcfg GYRO_DLPFCFG_BW196HZ = 0 (3dB BW: 196.6 Hz NBW: 229.8) GYRO_DLPFCFG_BW151HZ = 1 (3dB BW: 151.8 Hz NBW: 187.6) GYRO_DLPFCFG_BW119HZ = 2 (3dB BW: 119.5 Hz NBW: 154.3) GYRO_DLPFCFG_BW51HZ = 3 (3dB BW: 51.2 Hz NBW: 73.3) GYRO_DLPFCFG_BW23HZ = 4 (3dB BW: 23.9 Hz NBW: 35.9) GYRO_DLPFCFG_BW11HZ = 5 (3dB BW: 11.6 Hz NBW: 17.8) GYRO_DLPFCFG_BW5HZ = 6 (3dB BW: 5.7 Hz NBW: 8.9) GYRO_DLPFCFG_BW361HZ = 7 (3dB BW: 361.4 Hz NBW: 375.6) gyroFsSel GYRO_FS_SEL_250DPS = 0 (+/- 250 /s full scale) GYRO_FS_SEL_500DPS = 1 GYRO_FS_SEL_1000DPS = 2 GYRO_FS_SEL_2000DPS = 3 gyroFchoice 0: Bypass gyro Digital Low Pass Filter 3dB bandwith is 12106 Hz ant Output Data Rate (ODR) is 9000Hz 1: Enable gyro DLPF 3db bandwith is given by gyroDlpfcfg (self.GYRO_DLPFCFG_BWXXX values)
Referenced by init.
uint8_t ICM20948::imuJoinGyroConfig2(const uint8_t xGyroCten, const uint8_t yGyroCten, const uint8_t zGyroCten, const uint8_t gyroAvgcfg)
imuJoinGyroConfig2 xGyroCten X Gyro self-test enable yGyroCten zGyroCten gyroAvgcfg Averaging filter configuration settings for low power mode GYRO_AVGCFG_1X = 0 GYRO_AVGCFG_2X = 1 GYRO_AVGCFG_4X = 2 GYRO_AVGCFG_8X = 3 GYRO_AVGCFG_16X = 4 GYRO_AVGCFG_32X = 5 GYRO_AVGCFG_64X = 6 GYRO_AVGCFG_128X = 7
Referenced by init.
uint8_t ICM20948::imuJoinAccelSmplrtDiv1(const uint16_t accelSmplrtDiv)
imuJoinAccelSmplrtDiv1 accelSmplrtDiv
Referenced by init.
uint8_t ICM20948::imuJoinAccelSmplrtDiv2(const uint16_t accelSmplrtDiv)
imuJoinAccelSmplrtDiv2 accelSmplrtDiv
Referenced by init.
uint8_t ICM20948::imuJoinAccelIntelCtrl(const uint8_t accelIntelEn, const uint8_t accelIntelModeInt)
imuJoinAccelIntelCtrl accelIntEn Enable the Wake On Motion logic accelIntelModeInt selects WOM algorithm 1: compare the current sample with the previous sample 0: initial sample is stored, all future samples are compared to the initial sample
Referenced by init.
uint8_t ICM20948::imuJoinAccelConfig(const uint8_t accelDlpfcfg, const uint8_t accelFsSel, const uint8_t accelFchoice)
imuJoinAccelConfig accelDlpfcfg Accelerometer low pas filter configuration accelFsSel Accelerometer full scale select (self.ACCEL_FS_SEL_xG) accelFchoice 0: bypass accel Digital Low Pass Filter 1: Enable accel Digital Low Pass Filter
Referenced by init.
uint8_t ICM20948::imuJoinAccelConfig2(const uint8_t axStEnReg, const uint8_t ayStEnReg, const uint8_t azStEnReg, const uint8_t dec3Cfg)
imuJoinAccelConfig2 axStEnReg X accel self test enable ayStEnReg Y accel self test enable azStEnReg Z accel self test enable dec3Cfg Controls the number of samples averaged in the accelerometer decimator 0: Average 1 or 4 samples depending on ACCEL_FCHOICE (see Table 19) 1: Average 8 samples 2: Average 16 samples 3: Average 32 samples
Referenced by init.
uint8_t ICM20948::imuJoinBankId(const uint8_t bank_id)
imuJoinBankId bank_id
Referenced by dump_bank, reset_i2c_slv4, select_bank.
uint8_t ICM20948::imuJoinMstCtrl(const uint8_t multMstEn, const uint8_t i2cMstPNsr, const uint8_t i2cMstClk)
multMstEn Enables multi-master capability. When disabled, clocking to the I2C_MST_IF can be disabled when not in use and the logic to detect lost arbitration is disabled i2cMstPNsr This bit controls the I2C Masters transition from one slave read to the next slave read. \ 0 - There is a restart between reads. 1 - There is a stop between reads. i2cMstClk Sets I2C master clock frequency (it is recommended to set I2C_MST_CLK = 7)
Referenced by init_magnetometer.
uint8_t ICM20948::imuJoinIntEnable(const uint8_t regWofEn, const uint8_t womIntEn, const uint8_t pllRdyEn, const uint8_t dmpInt1En, const uint8_t i2cMstIntEn)
imuJoinIntEnable regWofEn 1 Enable wake on FSYNC interrupt womIntEn 1 Enable interrupt for wake on motion to propagate to interrupt pin 1. 0 Function is disabled. pllRdyEn 1 Enable PLL RDY interrupt (PLL RDY means PLL is running and in use as the clock source for the system) to propagate to interrupt pin 1. 0 Function is disabled. dmpInt1En 1 Enable DMP interrupt to propagate to interrupt pin 1. 0 Function is disabled. i2cMstIntEn 1 Enable I2C master interrupt to propagate to interrupt pin 1. 0 Function is disabled.
Referenced by init_magnetometer.
uint8_t ICM20948::imuJoinI2cMstDelayCtrl(const uint8_t delayEsShadow, const uint8_t i2cSlv4DelayEn, const uint8_t i2cSlv3DelayEn, const uint8_t i2cSlv2DelayEn, const uint8_t i2cSlv1DelayEn, const uint8_t i2cSlv0DelayEn)
imuJoinI2cMstDelayCtrl delayEsShadow Delays shadowing of external sensor data until all data is received. i2cSlv4DelayEn When enabled, slave 4 will only be accessed 1/(1+I2C_SLC4_DLY) samples as determined by I2C_MST_ODR_CONFIG. i2cSlv3DelayEn When enabled, slave 3 will only be accessed 1/(1+I2C_SLC4_DLY) samples as determined by I2C_MST_ODR_CONFIG. i2cSlv2DelayEn When enabled, slave 2 will only be accessed 1/(1+I2C_SLC4_DLY) samples as determined by I2C_MST_ODR_CONFIG. i2cSlv1DelayEn When enabled, slave 1 will only be accessed 1/(1+I2C_SLC4_DLY) samples as determined by I2C_MST_ODR_CONFIG. i2cSlv0DelayEn When enabled, slave 0 will only be accessed 1/(1+I2C_SLC4_DLY) samples as determined by I2C_MST_ODR_CONFIG
Referenced by init.
uint8_t ICM20948::imuJoinI2cSlv4Ctrl(const uint8_t i2cSlv4En, const uint8_t i2cSlv4IntEn, const uint8_t i2cSlv4RegDis, const uint8_t i2cSlv4Dly)
imuJoinI2cSlv4Ctrl i2cSlv4En 1 Enable data transfer with this slave at the sample rate. If read command, store data in I2C_SLV4_DI register, if write command, write data stored in I2C_SLV4_DO register. Bit is cleared when a single transfer is complete. Be sure to write I2C_SLV4_DO first. 0 Function is disabled for this slave. i2cSlv4IntEn 1 Enables the completion of the I2C slave 4 data transfer to cause an interrupt. 0 Completion of the I2C slave 4 data transfer will not cause an interrupt. i2cSlv4RegDis When set, the transaction does not write a register value, it will only read data, or write data. i2cSlv4Dly When enabled via the I2C_MST_DELAY_CTRL, those slaves will only be enabled every 1/(1+I2C_SLV4_DLY) samples as determined by I2C_MST_ODR_CONFIG
Referenced by init, read_i2c_AK09916_byte, write_i2c_AK09916_byte.
uint8_t ICM20948::imuJoinIntPinCfg(const uint8_t int1Actl, const uint8_t int1Open, const uint8_t int1LatchEn, const uint8_t int1Anyrd2Clear, const uint8_t int1FsyncLvl, const uint8_t int1FsyncEn, const uint8_t int1BypassEn)
imuJoinIntPinCfg int1Actl 1 - The logic level for INT1 pin is active low. 0 - The logic level for INT1 pin is active high. int1Open 1 - INT1 pin is configured as open drain. 0 - INT1 pin is configured as push-pull. int1LatchEn 1 - INT1 pin level held until interrupt status is cleared. 0 - INT1 pin indicates interrupt pulse is width 50 s. int1Anyrd2Clear 1 - Interrupt status in INT_STATUS is cleared (set to 0) if any read operation is performed. 0 - Interrupt status in INT_STATUS is cleared (set to 0) only by reading INT_STATUS register. This bit only affects the interrupt status bits that are contained in the register INT_STATUS, and the corresponding hardware interrupt. This bit does not affect the interrupt status bits that are contained in registers INT_STATUS_1, INT_STATUS_2, INT_STATUS_3, and the corresponding hardware interrupt. int1FsyncLvl 1 - The logic level for the FSYNC pin as an interrupt to the ICM-20948 is active low. 0 - The logic level for the FSYNC pin as an interrupt to the ICM-20948 is active high. int1FsyncEn 1 - This enables the FSYNC pin to be used as an interrupt. A transition to the active level described by the ACTL_FSYNC bit will cause an interrupt. The status of the interrupt is read in the I2C Master Status register PASS_THROUGH bit. 0 - This disables the FSYNC pin from causing an interrupt. int1BypassEn When asserted, the I2C_MASTER interface pins (ES_CL and ES_DA) will go into bypass mode when the I2C master interface is disabled
Referenced by init_magnetometer.