InternalSensorFilterNode
size_t InternalSensorFilterNode::filter_window_size_
Referenced by init_parameters, pressure_callback.
size_t InternalSensorFilterNode::filter_median_remove_side_samples_
Referenced by compute_filter, init_parameters.
deque<double> InternalSensorFilterNode::pressure_memory_
Variable.
Referenced by pressure_callback.
deque<double> InternalSensorFilterNode::temperature_memory_
Referenced by pressure_callback.
deque<double> InternalSensorFilterNode::humidity_memory_
Referenced by pressure_callback.
rclcpp::Subscription<seabot2_msgs::msg::Bme280Data>::SharedPtr InternalSensorFilterNode::subscriber_pressure_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::Bme280Data>::SharedPtr InternalSensorFilterNode::publisher_pressure_data_
Referenced by init_interfaces, pressure_callback.
InternalSensorFilterNode::InternalSensorFilterNode()
References init_interfaces, init_parameters.
void InternalSensorFilterNode::init_parameters()
Functions.
Init and get parameters of the Node
References filter_median_remove_side_samples_, filter_window_size_.
Referenced by InternalSensorFilterNode.
void InternalSensorFilterNode::init_interfaces()
Init interfaces of this node
References pressure_callback, publisher_pressure_data_, subscriber_pressure_data_.
Referenced by InternalSensorFilterNode.
void InternalSensorFilterNode::pressure_callback(const seabot2_msgs::msg::Bme280Data &msg)
Callback of the external pressure msg
References compute_filter, filter_window_size_, humidity_memory_, pressure_memory_, publisher_pressure_data_, temperature_memory_.
Referenced by init_interfaces.
double InternalSensorFilterNode::compute_filter(deque< double > queue) const
Compute the median and mean filter queue
References filter_median_remove_side_samples_.
Referenced by pressure_callback.