Screen
Robot_Status
rclcpp::Node* Screen::n_
Referenced by i2c_open, Screen, write_current_waypoint, write_hygro, write_ip, write_mission_name, write_number_waypoints, write_pressure, write_remaining_time, write_robot_name, write_robot_status, write_screen, write_temperature, write_time, write_voltage.
int Screen::file_
Pointer to rclcpp Node.
Referenced by i2c_open, write_current_waypoint, write_hygro, write_ip, write_mission_name, write_number_waypoints, write_pressure, write_remaining_time, write_robot_name, write_robot_status, write_screen, write_temperature, write_time, write_voltage, ~Screen.
int Screen::i2c_addr_
File to the i2c port.
Referenced by getI2CAddr, i2c_open, setI2CAddr.
std::string Screen::i2c_periph_
Referenced by getI2CPeriph, i2c_open, setI2CPeriph.
Screen::Screen(rclcpp::Node *n)
Screen.
References n_.
Screen::~Screen()
References file_.
int Screen::i2c_open()
Open the I2C device.
References DELAY_SLEEP_US, file_, i2c_addr_, i2c_periph_, n_.
Referenced by ScreenNode::ScreenNode.
void Screen::write_ip(const std::array< unsigned char, 4 > &data)
Write the IP to the screen data the four value of the IP
References DELAY_SLEEP_US, file_, n_, REGISTER_IP.
Referenced by ScreenNode::timer_callback.
void Screen::write_pressure(const short &pressure)
Write the pression pressure in mbar [xxxx] mbar
References DELAY_SLEEP_US, file_, n_, REGISTER_PRESSURE.
Referenced by ScreenNode::timer_callback.
void Screen::write_temperature(const short &temperature)
Write the temperature temperature in tenth of degree (205 for 20.5 deg) [xx.x] deg
References DELAY_SLEEP_US, file_, n_, REGISTER_TEMPERATURE.
Referenced by ScreenNode::timer_callback.
void Screen::write_hygro(const short &hygro)
Write the hygrometer hygro in percentage [xx]%
References DELAY_SLEEP_US, file_, n_, REGISTER_HYGRO.
Referenced by ScreenNode::timer_callback.
void Screen::write_voltage(const char &volt)
Write the voltage of the battery volt in tenth of volt (125 for 12.5V) [xx.x] V
References DELAY_SLEEP_US, file_, n_, REGISTER_VOLTAGE.
Referenced by ScreenNode::timer_callback.
void Screen::write_robot_name(const std::string &name)
Write the name of the robot name (max of 16 characters)
References DELAY_SLEEP_US, file_, n_, REGISTER_ROBOT_NAME, SCREEN_ROBOT_NAME_SIZE.
Referenced by ScreenNode::timer_callback.
void Screen::write_mission_name(const std::string &mission_name)
Write the name of the mission mission_name (max of 16 characters)
References DELAY_SLEEP_US, file_, n_, REGISTER_MISSION_NAME, SCREEN_MISSION_NAME_SIZE.
Referenced by ScreenNode::timer_callback.
void Screen::write_current_waypoint(const unsigned char &wp_id)
Write the id of the current waypoint wp_id [0, 255]
References DELAY_SLEEP_US, file_, n_, REGISTER_WAYPOINT_ID.
Referenced by ScreenNode::timer_callback.
void Screen::write_number_waypoints(const unsigned char &id_max)
Write the number of waypoint in the mission id_max [0, 255]
References DELAY_SLEEP_US, file_, n_, REGISTER_NB_WAYPOINT.
Referenced by ScreenNode::timer_callback.
void Screen::write_time(const char &hour, const char &minute)
Write the Time hour minute
References DELAY_SLEEP_US, file_, n_, REGISTER_TIME.
Referenced by ScreenNode::timer_callback.
void Screen::write_remaining_time(const char &minute, const char &second)
Write the remaining time before next waypoint minute second
References DELAY_SLEEP_US, file_, n_, REGISTER_TIME_REMAINING.
Referenced by ScreenNode::timer_callback.
void Screen::write_robot_status(const Robot_Status &status)
Write the robot status status
References DELAY_SLEEP_US, file_, n_, REGISTER_STATUS.
Referenced by ScreenNode::timer_callback, ScreenNode::~ScreenNode.
void Screen::write_screen()
Write the screen with data sent
References DELAY_SLEEP_US, file_, n_, REGISTER_WRITE_SCREEN.
Referenced by ScreenNode::timer_callback, ScreenNode::~ScreenNode.
int Screen::getI2CAddr() const
References i2c_addr_.
Referenced by ScreenNode::init_parameters.
void Screen::setI2CAddr(int i2CAddr)
References i2c_addr_.
Referenced by ScreenNode::init_parameters.
const std::string & Screen::getI2CPeriph() const
References i2c_periph_.
Referenced by ScreenNode::init_parameters.
void Screen::setI2CPeriph(const std::string &i2CPeriph)
References i2c_periph_.
Referenced by ScreenNode::init_parameters.