DepthControlNode
WAYPOINT_TYPE
rclcpp::TimerBase::SharedPtr DepthControlNode::timer_
Rclcpp.
Referenced by DepthControlNode, timer_callback.
std::chrono::milliseconds DepthControlNode::loop_dt_
Referenced by DepthControlNode, init_parameters, timer_callback.
rclcpp::CallbackGroup::SharedPtr DepthControlNode::callback_group_
loop dt
Referenced by DepthControlNode.
DepthControl DepthControlNode::dc_
Referenced by density_callback, depth_callback, depth_set_point_callback, generate_velocity_pairs, init_parameters, kalman_callback, piston_callback, publish_message, safety_callback, temperature_callback, timer_callback.
std::vector<float> DepthControlNode::velocity_limits_requests_
Referenced by alpha_mission_pre_computation, timer_callback.
bool DepthControlNode::velocity_limits_computations_
Referenced by alpha_mission_pre_computation, timer_callback.
bool DepthControlNode::enable_control_
Referenced by depth_set_point_callback, publish_message.
WAYPOINT_TYPE DepthControlNode::wp_type_
std::vector<double> DepthControlNode::solver_velocity_
Referenced by init_parameters.
std::vector<double> DepthControlNode::solver_alpha_
Referenced by init_parameters.
rclcpp::Subscription<seabot2_msgs::msg::KalmanState>::SharedPtr DepthControlNode::subscriber_kalman_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::PistonState>::SharedPtr DepthControlNode::subscriber_state_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::DepthPose>::SharedPtr DepthControlNode::subscriber_depth_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::DepthControlSetPoint>::SharedPtr DepthControlNode::subscriber_mission_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::SafetyStatus2>::SharedPtr DepthControlNode::subscriber_safety_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::Density>::SharedPtr DepthControlNode::subscriber_density_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr DepthControlNode::subscriber_temperature_data_
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::PistonSetPoint>::SharedPtr DepthControlNode::publisher_piston_
Referenced by init_interfaces, publish_message.
rclcpp::Publisher<seabot2_msgs::msg::DepthControlDebug>::SharedPtr DepthControlNode::publisher_debug_
Referenced by init_interfaces, publish_message.
rclcpp::Publisher<seabot2_msgs::msg::AlphaDebug>::SharedPtr DepthControlNode::publisher_alpha_debug_
Referenced by depth_set_point_callback, init_interfaces.
rclcpp::Service<seabot2_srvs::srv::AlphaMission>::SharedPtr DepthControlNode::service_alpha_computation_
Referenced by init_interfaces.
rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr DepthControlNode::service_alpha_generation_
Referenced by init_interfaces.
DepthControlNode::DepthControlNode()
References callback_group_, init_interfaces, init_parameters, loop_dt_, timer_, timer_callback.
void DepthControlNode::init_parameters()
Init and get parameters of the Node
References AlphaSolver::add_to_memory, DepthControl::alpha_solver_, DepthControl::control_filter_, dc_, DepthControl::debug_, DepthControl::delta_position_lb_, DepthControl::delta_position_ub_, DepthControl::delta_velocity_lb_, DepthControl::delta_velocity_ub_, DepthControl::flow_max_, DepthControl::flow_piston_sink_, DepthControl::hold_depth_enable_, DepthControl::hold_depth_validation_duration_, DepthControl::hold_depth_value_enter_, DepthControl::hold_depth_value_exit_, DepthControl::hold_velocity_enter_, DepthControl::hold_velocity_exit_, DepthControl::limit_depth_control_, loop_dt_, DepthControl::motor_max_rpm_, DepthControl::physics_g_, DepthControl::physics_rho_, DepthControl::piston_diameter_, DepthControl::piston_flow_security_percentage_, DepthControl::piston_hysteresis_, DepthControl::piston_max_tick_value_, DepthControl::robot_diameter_, DepthControl::robot_mass_, DepthControl::root_regulation_, DepthControl::screw_thread_, solver_alpha_, solver_velocity_, DepthControl::tick_per_turn_, DepthControl::update_coeff.
Referenced by DepthControlNode.
void DepthControlNode::init_interfaces()
Init interfaces of this node
References alpha_generation, alpha_mission_pre_computation, density_callback, depth_callback, depth_set_point_callback, kalman_callback, piston_callback, publisher_alpha_debug_, publisher_debug_, publisher_piston_, safety_callback, service_alpha_computation_, service_alpha_generation_, subscriber_density_, subscriber_depth_data_, subscriber_kalman_data_, subscriber_mission_data_, subscriber_safety_data_, subscriber_state_data_, subscriber_temperature_data_, temperature_callback.
Referenced by DepthControlNode.
void DepthControlNode::timer_callback()
Timer callback
References DepthControl::alpha_solver_, AlphaSolver::compute_alpha, dc_, loop_dt_, publish_message, DepthControl::regulation_state_, DepthControl::STATE_COMPUTE_ALPHA, DepthControl::state_machine_step, DepthControl::STATE_SURFACE, timer_, velocity_limits_computations_, velocity_limits_requests_.
Referenced by DepthControlNode.
void DepthControlNode::kalman_callback(const seabot2_msgs::msg::KalmanState &msg)
msg
References dc_, DepthControl::update_state.
Referenced by init_interfaces.
void DepthControlNode::density_callback(const seabot2_msgs::msg::Density &msg)
msg
References dc_, DepthControl::update_density.
Referenced by init_interfaces.
void DepthControlNode::piston_callback(const seabot2_msgs::msg::PistonState &msg)
msg
References dc_, DepthControl::update_piston.
Referenced by init_interfaces.
void DepthControlNode::depth_callback(const seabot2_msgs::msg::DepthPose &msg)
msg
References dc_, DepthControl::update_depth.
Referenced by init_interfaces.
void DepthControlNode::safety_callback(const seabot2_msgs::msg::SafetyStatus2 &msg)
msg
References dc_, DepthControl::update_safety.
Referenced by init_interfaces.
void DepthControlNode::depth_set_point_callback(const seabot2_msgs::msg::DepthControlSetPoint &msg)
msg
References DepthControl::approach_velocity_, dc_, enable_control_, publisher_alpha_debug_, DepthControl::update_waypoint.
Referenced by init_interfaces.
void DepthControlNode::temperature_callback(const seabot2_msgs::msg::TemperatureSensorData &msg)
msg
References dc_, DepthControl::update_temperature.
Referenced by init_interfaces.
void DepthControlNode::alpha_mission_pre_computation(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< seabot2_srvs::srv::AlphaMission::Request > request, std::shared_ptr< seabot2_srvs::srv::AlphaMission::Response > response)
Compute the alpha values request_header request response
References velocity_limits_computations_, velocity_limits_requests_.
Referenced by init_interfaces.
void DepthControlNode::alpha_generation(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< std_srvs::srv::Trigger::Request > request, std::shared_ptr< std_srvs::srv::Trigger::Response > response)
request_header request response
References generate_velocity_pairs.
Referenced by init_interfaces.
void DepthControlNode::publish_message()
Publish messages
References dc_, DepthControl::dy_debug_, enable_control_, DepthControl::is_exit_, DepthControl::piston_set_point_, publisher_debug_, publisher_piston_, DepthControl::regulation_state_, DepthControl::u_debug_, DepthControl::y_debug_.
Referenced by timer_callback.
void DepthControlNode::generate_velocity_pairs()
Generate velocities
References DepthControl::alpha_solver_, AlphaSolver::compute_alpha, dc_, file, AlphaSolver::get_computed_memory, AlphaSolver::set_test_in_memory.
Referenced by alpha_generation.