Thruster
const uint8_t Thruster::MOTOR_PWM_STOP
Referenced by ThrusterNode::convert_to_pwm, ThrusterNode::invert_cmd, ~Thruster.
const uint8_t Thruster::MAX_PWM
Referenced by ThrusterNode::convert_to_pwm.
const uint8_t Thruster::MIN_PWM
Referenced by ThrusterNode::convert_to_pwm.
const uint8_t Thruster::ENABLE_MOTOR
Referenced by write_enable_motors.
rclcpp::Node* Thruster::n_
Referenced by i2c_open, Thruster, write_cmd, write_enable_motors.
int Thruster::file_
Pointer to rclcpp Node.
Referenced by get_version, i2c_open, write_cmd, write_enable_motors, ~Thruster.
int Thruster::i2c_addr_
File to the i2c port.
Referenced by getI2CAddr, i2c_open, setI2CAddr.
const int Thruster::code_version_
Referenced by i2c_open.
uint8_t Thruster::pic_code_version_
Code version of the expected hardware.
Referenced by get_version.
std::string Thruster::i2c_periph_
Code version read from the hardware.
Referenced by getI2CPeriph, i2c_open, setI2CPeriph.
bool Thruster::reverse_thruster_order_
Thruster::Thruster(rclcpp::Node *n)
Thruster.
References i2c_open, n_.
Thruster::~Thruster()
References file_, MOTOR_PWM_STOP, write_cmd.
int Thruster::i2c_open()
Open the I2C device.
References code_version_, file_, get_version, i2c_addr_, i2c_periph_, n_.
Referenced by Thruster, ThrusterNode::ThrusterNode.
int Thruster::write_cmd(const uint8_t &left, const uint8_t &right) const
Send the pwm value to the thrusters Max values .
Stopped 151 Max forward 191 Max reverse 111 left right 0 if success
References file_, n_.
Referenced by ThrusterNode::timer_callback, ~Thruster.
void Thruster::write_enable_motors(bool enable)
Enable/Disable the left & right motor enable
References ENABLE_MOTOR, file_, n_.
uint8_t & Thruster::get_version()
get the version of the pic software version
References file_, pic_code_version_.
Referenced by i2c_open.
int Thruster::getI2CAddr() const
References i2c_addr_.
Referenced by ThrusterNode::init_parameters.
void Thruster::setI2CAddr(int i2CAddr)
References i2c_addr_.
Referenced by ThrusterNode::init_parameters.
const std::string & Thruster::getI2CPeriph() const
References i2c_periph_.
Referenced by ThrusterNode::init_parameters.
void Thruster::setI2CPeriph(const std::string &i2CPeriph)
References i2c_periph_.
Referenced by ThrusterNode::init_parameters.