ScreenNode
Screen ScreenNode::screen_
I2C configuration.
Referenced by init_parameters, ScreenNode, timer_callback, ~ScreenNode.
rclcpp::TimerBase::SharedPtr ScreenNode::timer_
Rclcpp.
Referenced by ScreenNode.
std::chrono::milliseconds ScreenNode::loop_dt_
Referenced by init_parameters, ScreenNode.
std::array< unsigned char, 4 > ScreenNode::ip_
Variable.
Referenced by get_ip, timer_callback.
double ScreenNode::pressure_
Referenced by timer_callback, topic_internal_pressure_callback.
double ScreenNode::temperature_
Referenced by timer_callback, topic_internal_pressure_callback.
double ScreenNode::hygro_
Referenced by timer_callback, topic_internal_pressure_callback.
double ScreenNode::voltage_
Referenced by power_callback, timer_callback.
string ScreenNode::robot_name_
Referenced by get_hostname, timer_callback.
string ScreenNode::mission_name_
Referenced by timer_callback.
unsigned int ScreenNode::wp_id_
Referenced by timer_callback, waypoint_callback.
unsigned int ScreenNode::wp_max_
Referenced by timer_callback, waypoint_callback.
rclcpp::Time ScreenNode::time_next_wp_
Referenced by timer_callback, waypoint_callback.
Screen::Robot_Status ScreenNode::status_
Referenced by safety_callback, timer_callback.
double ScreenNode::depth_
Referenced by timer_callback.
double ScreenNode::depth_no_update_
Referenced by init_parameters, timer_callback.
rclcpp::Subscription<seabot2_msgs::msg::Bme280Data>::SharedPtr ScreenNode::subscriber_sensor_internal_
Topics.
Referenced by init_topics.
rclcpp::Subscription<seabot2_msgs::msg::MissionState>::SharedPtr ScreenNode::subscriber_mission_
Referenced by init_topics.
rclcpp::Subscription<seabot2_msgs::msg::PowerState>::SharedPtr ScreenNode::subscriber_power_
Referenced by init_topics.
rclcpp::Subscription<seabot2_msgs::msg::SafetyStatus2>::SharedPtr ScreenNode::subscriber_safety_
Referenced by init_topics.
ScreenNode::ScreenNode()
References get_hostname, get_ip, Screen::i2c_open, init_parameters, init_topics, loop_dt_, screen_, timer_, timer_callback.
ScreenNode::~ScreenNode() override
References Screen::ERROR, screen_, Screen::write_robot_status, Screen::write_screen.
void ScreenNode::timer_callback()
Functions.
References depth_, depth_no_update_, get_ip, hygro_, ip_, mission_name_, pressure_, robot_name_, screen_, status_, temperature_, time_next_wp_, voltage_, wp_id_, wp_max_, Screen::write_current_waypoint, Screen::write_hygro, Screen::write_ip, Screen::write_mission_name, Screen::write_number_waypoints, Screen::write_pressure, Screen::write_remaining_time, Screen::write_robot_name, Screen::write_robot_status, Screen::write_screen, Screen::write_temperature, Screen::write_time, Screen::write_voltage.
Referenced by ScreenNode.
void ScreenNode::init_parameters()
Init and get parameters of the Node
References depth_no_update_, Screen::getI2CAddr, Screen::getI2CPeriph, loop_dt_, screen_, Screen::setI2CAddr, Screen::setI2CPeriph.
Referenced by ScreenNode.
void ScreenNode::init_topics()
Init topics to this node (publishers & subscribers)
References power_callback, safety_callback, subscriber_mission_, subscriber_power_, subscriber_safety_, subscriber_sensor_internal_, topic_internal_pressure_callback, waypoint_callback.
Referenced by ScreenNode.
void ScreenNode::get_hostname()
Get the hostname of the robot
References robot_name_.
Referenced by ScreenNode.
void ScreenNode::get_ip()
Get the ip of the robot
References ip_.
Referenced by ScreenNode, timer_callback.
void ScreenNode::topic_internal_pressure_callback(const seabot2_msgs::msg::Bme280Data &msg)
Callback for internal pressure messages msg
References hygro_, pressure_, temperature_.
Referenced by init_topics.
void ScreenNode::waypoint_callback(const seabot2_msgs::msg::MissionState &msg)
Callback for waypoints msg
References time_next_wp_, wp_id_, wp_max_.
Referenced by init_topics.
void ScreenNode::power_callback(const seabot2_msgs::msg::PowerState &msg)
Callback for voltage msg
References voltage_.
Referenced by init_topics.
void ScreenNode::safety_callback(const seabot2_msgs::msg::SafetyStatus2 &msg)
msg
References Screen::ERROR, Screen::OK, status_.
Referenced by init_topics.