PressureMS5837Node
rclcpp::TimerBase::SharedPtr PressureMS5837Node::timer_
Variables.
Referenced by PressureMS5837Node.
rclcpp::Publisher<seabot2_msgs::msg::PressureSensorData>::SharedPtr PressureMS5837Node::publisher_sensor_
Referenced by init_interfaces, timer_callback.
Pressure_ms5837 PressureMS5837Node::pressure_sensor_
Referenced by init_parameters, PressureMS5837Node, timer_callback.
std::chrono::milliseconds PressureMS5837Node::loop_dt_
Referenced by init_parameters, PressureMS5837Node.
PressureMS5837Node::PressureMS5837Node()
References init_interfaces, init_parameters, Pressure_ms5837::init_sensor, loop_dt_, pressure_sensor_, timer_, timer_callback.
void PressureMS5837Node::timer_callback()
Functions.
References Pressure_ms5837::get_pression, Pressure_ms5837::get_temperature, Pressure_ms5837::measure, pressure_sensor_, publisher_sensor_.
Referenced by PressureMS5837Node.
void PressureMS5837Node::init_parameters()
References Pressure_ms5837::getI2CAddr, Pressure_ms5837::getI2CPeriph, loop_dt_, pressure_sensor_, Pressure_ms5837::setI2CAddr, Pressure_ms5837::setI2CPeriph.
Referenced by PressureMS5837Node.
void PressureMS5837Node::init_interfaces()
References publisher_sensor_.
Referenced by PressureMS5837Node.