TemperatureProfileNode
rclcpp::TimerBase::SharedPtr TemperatureProfileNode::timer_
Variable Rclcpp
std::chrono::milliseconds TemperatureProfileNode::loop_dt_
Referenced by init_parameters.
TemperatureProfile TemperatureProfileNode::t_
loop dt
Referenced by temperature_callback.
double TemperatureProfileNode::depth_
Referenced by depth_callback, temperature_callback.
rclcpp::Subscription<seabot2_msgs::msg::DepthPose>::SharedPtr TemperatureProfileNode::subscriber_depth_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr TemperatureProfileNode::subscriber_temperature_
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::TemperatureProfile>::SharedPtr TemperatureProfileNode::publisher_temperature_profile_
Referenced by init_interfaces, temperature_callback.
TemperatureProfileNode::TemperatureProfileNode()
References init_interfaces, init_parameters.
void TemperatureProfileNode::init_parameters()
Functions.
Init and get parameters of the Node
References loop_dt_.
Referenced by TemperatureProfileNode.
void TemperatureProfileNode::init_interfaces()
Init interfaces of this node
References depth_callback, publisher_temperature_profile_, subscriber_depth_data_, subscriber_temperature_, temperature_callback.
Referenced by TemperatureProfileNode.
void TemperatureProfileNode::depth_callback(const seabot2_msgs::msg::DepthPose &msg)
msg
References depth_.
Referenced by init_interfaces.
void TemperatureProfileNode::temperature_callback(const seabot2_msgs::msg::TemperatureSensorData &msg)
msg
References TemperatureProfile::compute_profile, depth_, TemperatureProfile::profile_intercept_, TemperatureProfile::profile_slope_, publisher_temperature_profile_, t_, TemperatureProfile::update_temperature.
Referenced by init_interfaces.