LightNode
rclcpp::TimerBase::SharedPtr LightNode::timer_
Rclcpp.
Referenced by LightNode.
std::chrono::milliseconds LightNode::loop_dt_
Referenced by init_parameters, LightNode.
Light LightNode::light_
loop dt
I2C configuration
Referenced by init_parameters, LightNode, service_light_callback, timer_callback, ~LightNode.
rclcpp::Service<seabot2_srvs::srv::Light>::SharedPtr LightNode::service_light_
Topics / Services.
Referenced by init_interfaces.
rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr LightNode::service_flash_surface_
Referenced by init_interfaces.
rclcpp::Time LightNode::time_turn_off_light_
Variables.
Referenced by service_light_callback, timer_callback.
bool LightNode::special_flash_
Referenced by service_light_callback, timer_callback.
bool LightNode::light_is_on_
Referenced by LightNode, service_light_callback, timer_callback.
bool LightNode::is_surface_
Referenced by service_flash_surface_callback, timer_callback.
const int LightNode::nb_surface_flash_
Referenced by timer_callback.
LightNode::LightNode()
References Light::get_light_enable, Light::i2c_open, init_interfaces, init_parameters, light_, light_is_on_, loop_dt_, timer_, timer_callback.
LightNode::~LightNode() override
References light_, Light::set_light_enable.
void LightNode::timer_callback()
Functions.
References is_surface_, light_, light_is_on_, nb_surface_flash_, Light::set_flash_number, Light::set_light_enable, special_flash_, time_turn_off_light_.
Referenced by LightNode.
void LightNode::init_parameters()
Init and get parameters of the Node
References Light::flash_duration_, Light::flash_pause_between_flash_, Light::flash_pause_end_, Light::getI2CAddr, Light::getI2CPeriph, light_, loop_dt_, Light::setI2CAddr, Light::setI2CPeriph.
Referenced by LightNode.
void LightNode::init_interfaces()
Init interfaces of this node
References service_flash_surface_, service_flash_surface_callback, service_light_, service_light_callback.
Referenced by LightNode.
void LightNode::service_flash_surface_callback(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< std_srvs::srv::SetBool::Request > request, std::shared_ptr< std_srvs::srv::SetBool::Response > response)
Callback service flash surface request_header request response
References is_surface_.
Referenced by init_interfaces.
void LightNode::service_light_callback(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< seabot2_srvs::srv::Light::Request > request, std::shared_ptr< seabot2_srvs::srv::Light::Response > response)
request response
References light_, light_is_on_, Light::set_flash_number, Light::set_light_enable, special_flash_, time_turn_off_light_.
Referenced by init_interfaces.