SaarDataHandler
SaarDataHandler::SaarDataHandler()
constructor
SaarDataHandler::~SaarDataHandler()
destructor
const double SaarDataHandler::get_p_ref(unsigned pos)
References p_ref, SAAR_ERROR_LIMIT, sdata_lat_max.
Referenced by TeosBase::gsw_deltasa_atlas, TeosBase::gsw_saar, TeosBase::gsw_util_indxPref.
const double SaarDataHandler::get_lats_ref(unsigned pos)
References SAAR_ERROR_LIMIT, sdata_lat_max.
Referenced by TeosBase::gsw_deltasa_atlas, TeosBase::gsw_saar.
const double SaarDataHandler::get_longs_ref(unsigned pos)
References SAAR_ERROR_LIMIT, sdata_long_max.
Referenced by TeosBase::gsw_deltasa_atlas, TeosBase::gsw_saar.
const double SaarDataHandler::get_saar_ref(unsigned pos)
References getSaarValue, SAAR_ERROR_LIMIT, saar_max.
Referenced by TeosBase::gsw_saar.
const double SaarDataHandler::get_ndepth_ref(unsigned pos)
References ndepth_ref, ndepth_ref_max, SAAR_ERROR_LIMIT.
Referenced by TeosBase::gsw_deltasa_atlas, TeosBase::gsw_saar.
const double SaarDataHandler::get_delta_sa_ref(unsigned pos)
References delta_sa_max, getDeltaSaValue, SAAR_ERROR_LIMIT.
Referenced by TeosBase::gsw_deltasa_atlas.
double SaarDataHandler::getSaarValue(unsigned tpos)
mapping access functionality ('tpos' is the original VLA position)
References ARRAYINFO::begins, getOffset, getSaarArrayPos, repeatSectionValue, saar, saarArrayInfo, ARRAYINFO::wasRepeatValue.
Referenced by get_saar_ref.
double SaarDataHandler::getDeltaSaValue(unsigned tpos)
References ARRAYINFO::begins, deltasa, deltaSaArrayInfo, getDeltaSaArrayPos, getOffset, repeatSectionValue, ARRAYINFO::wasRepeatValue.
Referenced by get_delta_sa_ref.
unsigned SaarDataHandler::getSaarArrayPos(unsigned valPos)
References ARRAYINFO::ends, maxSAARCOUNT, saarArrayInfo.
Referenced by getSaarValue.
unsigned SaarDataHandler::getDeltaSaArrayPos(unsigned valPos)
References deltaSaArrayInfo, ARRAYINFO::ends, maxDELTASACOUNT.
Referenced by getDeltaSaValue.
unsigned SaarDataHandler::getOffset(unsigned arrayNumber, bool isSaar)
References deltaSaArrayInfo, ARRAYINFO::elements, saarArrayInfo.
Referenced by getDeltaSaValue, getSaarValue.