WtfNode
rclcpp::TimerBase::SharedPtr WtfNode::timer_
Rclcpp.
Referenced by WtfNode.
std::chrono::milliseconds WtfNode::loop_dt_
Referenced by init_parameters, WtfNode.
string WtfNode::hostname_
loop dt
Referenced by update_robot, WtfNode.
const array<std::string, 4> WtfNode::gpsd_mode_string_
Referenced by update_gnss.
const array<std::string, 6> WtfNode::piston_state_string_
Referenced by update_piston.
const array<std::string, 6> WtfNode::power_state_string_
Referenced by update_power.
const array<std::string, 8> WtfNode::depth_control_string_
Referenced by update_depth_control.
const array<std::string, 8> WtfNode::mission_mode_string_
Referenced by update_mission_windows.
const array<std::string, 8> WtfNode::mission_state_string_
Referenced by update_mission_windows.
WINDOW* WtfNode::windows_robot_
Variable.
Referenced by create_windows, update_robot.
WINDOW* WtfNode::windows_safety_
Referenced by create_windows, update_safety_windows.
WINDOW* WtfNode::windows_internal_pressure_
Referenced by create_windows, update_internal_pressure_windows.
WINDOW* WtfNode::windows_depth_
Referenced by create_windows, update_depth.
WINDOW* WtfNode::windows_power_
Referenced by create_windows, update_power.
WINDOW* WtfNode::windows_depth_control_
Referenced by create_windows, update_depth_control.
WINDOW* WtfNode::windows_piston_
Referenced by create_windows, update_piston.
WINDOW* WtfNode::windows_mission_
Referenced by create_windows, update_mission_windows.
WINDOW* WtfNode::windows_gnss_
Referenced by create_windows, update_gnss, update_sensors.
WINDOW* WtfNode::windows_sensors_
Referenced by create_windows, update_sensors.
WINDOW* WtfNode::windows_log_
Referenced by create_windows, update_log.
WINDOW* WtfNode::windows_audio_
Referenced by create_windows, update_audio.
WINDOW* WtfNode::windows_com_
int WtfNode::windows_max_y_
Referenced by create_new_sub_window, create_windows.
int WtfNode::windows_max_x_
Referenced by create_windows, update_log.
int WtfNode::windows_default_y_
Referenced by create_new_sub_window, create_windows.
int WtfNode::windows_current_y_
Referenced by create_new_sub_window, create_windows.
int WtfNode::windows_current_x_
Referenced by create_new_sub_window.
int WtfNode::windows_width_max_
Referenced by create_new_sub_window.
seabot2_msgs::msg::SafetyStatus2 WtfNode::msg_safety_
Variable.
Referenced by safety_callback, update_safety_windows.
seabot2_msgs::msg::DepthPose WtfNode::msg_depth_data_
Referenced by depth_callback, update_depth.
seabot2_msgs::msg::Bme280Data WtfNode::msg_internal_sensor_filter_
Referenced by internal_sensor_callback, update_internal_pressure_windows.
seabot2_msgs::msg::PowerState WtfNode::msg_power_data_
Referenced by power_callback, update_power.
seabot2_msgs::msg::PistonState WtfNode::msg_piston_data_
Referenced by piston_callback, update_depth_control, update_piston.
seabot2_msgs::msg::DepthControlSetPoint WtfNode::msg_depth_control_set_point_
Referenced by depth_control_set_point_callback, update_mission_windows.
seabot2_msgs::msg::MissionState WtfNode::msg_mission_state_
Referenced by mission_state_callback, update_mission_windows.
seabot2_msgs::msg::DepthControlDebug WtfNode::msg_depth_control_
Referenced by depth_control_callback, update_depth_control.
seabot2_msgs::msg::GpsFix WtfNode::msg_gnss_
Referenced by gnss_callback, update_gnss, update_safety_windows.
seabot2_msgs::msg::Profile WtfNode::msg_profile_
Referenced by profile_callback, update_sensors.
seabot2_msgs::msg::Density WtfNode::msg_density_
Referenced by density_callback, update_sensors.
seabot2_msgs::msg::TemperatureSensorData WtfNode::msg_temperature_sensor_data_
Referenced by temperature_sensor_data_callback, update_sensors.
seabot2_msgs::msg::SyncDspic WtfNode::msg_audio_dspic_
Referenced by audio_dspic_callback, update_audio.
deque<rcl_interfaces::msg::Log> WtfNode::msg_queue_log_
Referenced by log_callback, update_log.
rclcpp::Time WtfNode::time_last_safety_
Referenced by safety_callback, update_safety_windows.
rclcpp::Time WtfNode::time_last_depth_data_
Referenced by depth_callback, update_depth.
rclcpp::Time WtfNode::time_last_internal_sensor_filter_
Referenced by internal_sensor_callback, update_internal_pressure_windows.
rclcpp::Time WtfNode::time_last_power_data_
Referenced by power_callback, update_power.
rclcpp::Time WtfNode::time_last_piston_data_
Referenced by piston_callback, update_piston.
rclcpp::Time WtfNode::time_last_mission_state_
Referenced by mission_state_callback, update_mission_windows.
rclcpp::Time WtfNode::time_last_depth_control_set_point_
Referenced by depth_control_set_point_callback, update_mission_windows.
rclcpp::Time WtfNode::time_last_depth_control_
Referenced by depth_control_callback, update_depth_control.
rclcpp::Time WtfNode::time_last_gnss_
Referenced by gnss_callback, update_gnss.
rclcpp::Time WtfNode::time_last_profile_
Referenced by profile_callback, update_sensors.
rclcpp::Time WtfNode::time_last_density_
Referenced by density_callback.
rclcpp::Time WtfNode::time_last_temperature_sensor_data_
Referenced by temperature_sensor_data_callback.
rclcpp::Time WtfNode::time_last_audio_dspic_
Referenced by audio_dspic_callback, update_audio.
bool WtfNode::msg_first_received_safety_
Referenced by safety_callback, update_safety_windows.
bool WtfNode::msg_first_received_depth_data_
Referenced by depth_callback, update_depth.
bool WtfNode::msg_first_received_internal_sensor_filter_
Referenced by internal_sensor_callback, update_internal_pressure_windows.
bool WtfNode::msg_first_received_power_data_
Referenced by power_callback, update_power.
bool WtfNode::msg_first_received_piston_data_
Referenced by piston_callback, update_piston.
bool WtfNode::msg_first_received_mission_state_
Referenced by mission_state_callback, update_mission_windows.
bool WtfNode::msg_first_received_depth_control_set_point
Referenced by depth_control_set_point_callback, update_mission_windows.
bool WtfNode::msg_first_received_depth_control_
Referenced by depth_control_callback, update_depth_control.
bool WtfNode::msg_first_received_gnss_
Referenced by gnss_callback, update_gnss.
bool WtfNode::msg_first_received_profile_
Referenced by profile_callback, update_sensors.
bool WtfNode::msg_first_received_density_
Referenced by density_callback, update_sensors.
bool WtfNode::msg_first_received_temperature_sensor_data_
Referenced by temperature_sensor_data_callback, update_sensors.
bool WtfNode::msg_first_received_audio_dspic_
Referenced by audio_dspic_callback, update_audio.
size_t WtfNode::msg_queue_log_size_
Referenced by log_callback.
rclcpp::Subscription<seabot2_msgs::msg::SafetyStatus2>::SharedPtr WtfNode::subscriber_safety_
Interfaces.
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::DepthPose>::SharedPtr WtfNode::subscriber_depth_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::Bme280Data>::SharedPtr WtfNode::subscriber_internal_sensor_filter_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::PowerState>::SharedPtr WtfNode::subscriber_power_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::PistonState>::SharedPtr WtfNode::subscriber_piston_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::MissionState>::SharedPtr WtfNode::subscriber_mission_state_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::DepthControlSetPoint>::SharedPtr WtfNode::subscriber_depth_control_set_point_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::DepthControlDebug>::SharedPtr WtfNode::subscriber_control_debug_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::GpsFix>::SharedPtr WtfNode::subscriber_gnss_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::Profile>::SharedPtr WtfNode::subscriber_profile_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::Density>::SharedPtr WtfNode::subscriber_density_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr WtfNode::subscriber_temperature_sensor_data_
Referenced by init_interfaces.
rclcpp::Subscription<rcl_interfaces::msg::Log>::SharedPtr WtfNode::subscriber_log_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::SyncDspic>::SharedPtr WtfNode::subscriber_audio_dspic_
Referenced by init_interfaces.
WtfNode::WtfNode()
References COLOR_DEFAULT, COLOR_NOT_VALID, COLOR_VALID, create_windows, hostname_, init_interfaces, init_parameters, loop_dt_, timer_, timer_callback.
WtfNode::~WtfNode() override
void WtfNode::init_parameters()
Init and get parameters of the Node
References loop_dt_.
Referenced by WtfNode.
void WtfNode::init_interfaces()
Init interfaces of this node
References audio_dspic_callback, density_callback, depth_callback, depth_control_callback, depth_control_set_point_callback, gnss_callback, internal_sensor_callback, log_callback, mission_state_callback, piston_callback, power_callback, profile_callback, safety_callback, subscriber_audio_dspic_, subscriber_control_debug_, subscriber_density_, subscriber_depth_control_set_point_, subscriber_depth_data_, subscriber_gnss_, subscriber_internal_sensor_filter_, subscriber_log_, subscriber_mission_state_, subscriber_piston_data_, subscriber_power_data_, subscriber_profile_, subscriber_safety_, subscriber_temperature_sensor_data_, temperature_sensor_data_callback.
Referenced by WtfNode.
void WtfNode::timer_callback()
Timer callback
References update_audio, update_depth, update_depth_control, update_gnss, update_internal_pressure_windows, update_log, update_mission_windows, update_piston, update_power, update_robot, update_safety_windows, update_sensors.
Referenced by WtfNode.
void WtfNode::depth_callback(const seabot2_msgs::msg::DepthPose &msg)
Depth Callback msg
References msg_depth_data_, msg_first_received_depth_data_, time_last_depth_data_.
Referenced by init_interfaces.
void WtfNode::internal_sensor_callback(const seabot2_msgs::msg::Bme280Data &msg)
Internal sensor callback msg
References msg_first_received_internal_sensor_filter_, msg_internal_sensor_filter_, time_last_internal_sensor_filter_.
Referenced by init_interfaces.
void WtfNode::power_callback(const seabot2_msgs::msg::PowerState &msg)
Power callback msg
References msg_first_received_power_data_, msg_power_data_, time_last_power_data_.
Referenced by init_interfaces.
void WtfNode::piston_callback(const seabot2_msgs::msg::PistonState &msg)
Piston callback msg
References msg_first_received_piston_data_, msg_piston_data_, time_last_piston_data_.
Referenced by init_interfaces.
void WtfNode::safety_callback(const seabot2_msgs::msg::SafetyStatus2 &msg)
Safety callback msg
References msg_first_received_safety_, msg_safety_, time_last_safety_.
Referenced by init_interfaces.
void WtfNode::mission_state_callback(const seabot2_msgs::msg::MissionState &msg)
Mission state callback msg
References msg_first_received_mission_state_, msg_mission_state_, time_last_mission_state_.
Referenced by init_interfaces.
void WtfNode::depth_control_set_point_callback(const seabot2_msgs::msg::DepthControlSetPoint &msg)
Depth control set point callback msg
References msg_depth_control_set_point_, msg_first_received_depth_control_set_point, time_last_depth_control_set_point_.
Referenced by init_interfaces.
void WtfNode::depth_control_callback(const seabot2_msgs::msg::DepthControlDebug &msg)
Control debug callback msg
References msg_depth_control_, msg_first_received_depth_control_, time_last_depth_control_.
Referenced by init_interfaces.
void WtfNode::gnss_callback(const seabot2_msgs::msg::GpsFix &msg)
Gps callback msg
References msg_first_received_gnss_, msg_gnss_, time_last_gnss_.
Referenced by init_interfaces.
void WtfNode::profile_callback(const seabot2_msgs::msg::Profile &msg)
Profile callback msg
References msg_first_received_profile_, msg_profile_, time_last_profile_.
Referenced by init_interfaces.
void WtfNode::density_callback(const seabot2_msgs::msg::Density &msg)
Density callback msg
References msg_density_, msg_first_received_density_, time_last_density_.
Referenced by init_interfaces.
void WtfNode::temperature_sensor_data_callback(const seabot2_msgs::msg::TemperatureSensorData &msg)
Temperature sensor data callback msg
References msg_first_received_temperature_sensor_data_, msg_temperature_sensor_data_, time_last_temperature_sensor_data_.
Referenced by init_interfaces.
void WtfNode::log_callback(const rcl_interfaces::msg::Log &msg)
Log callback msg
References msg_queue_log_, msg_queue_log_size_.
Referenced by init_interfaces.
void WtfNode::audio_dspic_callback(const seabot2_msgs::msg::SyncDspic &msg)
Audio dspic callback msg
References msg_audio_dspic_, msg_first_received_audio_dspic_, time_last_audio_dspic_.
Referenced by init_interfaces.
void WtfNode::update_safety_windows()
Update safety windows
References COLOR_DEFAULT, msg_first_received_safety_, msg_gnss_, msg_safety_, set_color_valid, time_last_safety_, windows_safety_.
Referenced by timer_callback.
void WtfNode::update_mission_windows()
Update mission windows
References mission_mode_string_, mission_state_string_, msg_depth_control_set_point_, msg_first_received_depth_control_set_point, msg_first_received_mission_state_, msg_mission_state_, time_last_depth_control_set_point_, time_last_mission_state_, windows_mission_.
Referenced by timer_callback.
void WtfNode::update_internal_pressure_windows()
Update internal pressure windows
References msg_first_received_internal_sensor_filter_, msg_internal_sensor_filter_, time_last_internal_sensor_filter_, windows_internal_pressure_.
Referenced by timer_callback.
void WtfNode::update_power()
Update power windows
References msg_first_received_power_data_, msg_power_data_, power_state_string_, time_last_power_data_, windows_power_.
Referenced by timer_callback.
void WtfNode::update_depth()
Update depth windows
References msg_depth_data_, msg_first_received_depth_data_, time_last_depth_data_, windows_depth_.
Referenced by timer_callback.
void WtfNode::update_piston()
Update piston windows
References get_bool_text, msg_first_received_piston_data_, msg_piston_data_, piston_state_string_, time_last_piston_data_, windows_piston_.
Referenced by timer_callback.
void WtfNode::update_robot()
Update robot info windows
References hostname_, windows_robot_.
Referenced by timer_callback.
void WtfNode::update_depth_control()
Update depth windows
References depth_control_string_, msg_depth_control_, msg_first_received_depth_control_, msg_piston_data_, time_last_depth_control_, windows_depth_control_.
Referenced by timer_callback.
void WtfNode::update_gnss()
Update gnss windows
References COLOR_DEFAULT, gpsd_mode_string_, msg_first_received_gnss_, msg_gnss_, time_last_gnss_, windows_gnss_.
Referenced by timer_callback.
void WtfNode::update_sensors()
Update sensor windows
References msg_density_, msg_first_received_density_, msg_first_received_profile_, msg_first_received_temperature_sensor_data_, msg_profile_, msg_temperature_sensor_data_, time_last_profile_, windows_gnss_, windows_sensors_.
Referenced by timer_callback.
void WtfNode::update_audio() const
Update audio windows
References msg_audio_dspic_, msg_first_received_audio_dspic_, time_last_audio_dspic_, windows_audio_.
Referenced by timer_callback.
void WtfNode::update_log() const
Update log windows
References msg_queue_log_, windows_log_, windows_max_x_.
Referenced by timer_callback.
WINDOW * WtfNode::create_new_sub_window(int height, int width, const string &name)
Create new sub window
References windows_current_x_, windows_current_y_, windows_default_y_, windows_max_y_, windows_width_max_.
Referenced by create_windows.
void WtfNode::create_windows()
Create windows
References create_new_sub_window, windows_audio_, windows_current_y_, windows_default_y_, windows_depth_, windows_depth_control_, windows_gnss_, windows_internal_pressure_, windows_log_, windows_max_x_, windows_max_y_, windows_mission_, windows_piston_, windows_power_, windows_robot_, windows_safety_, windows_sensors_.
Referenced by WtfNode.
std::string WtfNode::set_color_valid(WINDOW *w, bool valid, const std::string &text="")
Update all windows
References COLOR_NOT_VALID, COLOR_VALID.
Referenced by update_safety_windows.
std::string WtfNode::get_bool_text(bool valid)
valid
Referenced by update_piston.