DepthPoseNode
double DepthPoseNode::rho_
Variable.
Referenced by init_parameters, pressure_callback.
double DepthPoseNode::g_
Referenced by init_parameters, pressure_callback.
double DepthPoseNode::velocity_limit_
Referenced by init_parameters, pressure_callback.
double DepthPoseNode::zero_depth_
Referenced by pressure_callback, service_zero_pressure_callback.
deque<double> DepthPoseNode::pressure_deque_
Pressure to Depth.
Referenced by pressure_callback.
size_t DepthPoseNode::filter_window_size_
Referenced by init_parameters, pressure_callback.
int DepthPoseNode::filter_median_remove_side_samples_
Referenced by init_parameters, pressure_callback.
double DepthPoseNode::threshold_wrong_depth_measure_
Referenced by init_parameters, pressure_callback.
deque<pair<double, rclcpp::Time> > DepthPoseNode::depth_memory_
Velocity.
Referenced by pressure_callback.
size_t DepthPoseNode::filter_velocity_window_size_
Referenced by init_parameters, pressure_callback.
size_t DepthPoseNode::velocity_dt_gap_sample_
Referenced by init_parameters, pressure_callback.
size_t DepthPoseNode::filter_velocity_median_remove_side_samples_
Referenced by init_parameters, pressure_callback.
deque<double> DepthPoseNode::pressure_zero_depth_deque_
Referenced by pressure_callback, service_zero_pressure_callback.
size_t DepthPoseNode::zero_depth_window_size_
Referenced by init_parameters, pressure_callback.
bool DepthPoseNode::new_data_
rclcpp::Subscription<seabot2_msgs::msg::PressureSensorData>::SharedPtr DepthPoseNode::subscriber_pressure_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::DepthPose>::SharedPtr DepthPoseNode::publisher_depth_data_
Referenced by init_interfaces, pressure_callback.
rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr DepthPoseNode::service_zero_depth_
Referenced by init_interfaces.
DepthPoseNode::DepthPoseNode()
References init_interfaces, init_parameters.
void DepthPoseNode::init_parameters()
Functions.
Init and get parameters of the Node
References filter_median_remove_side_samples_, filter_velocity_median_remove_side_samples_, filter_velocity_window_size_, filter_window_size_, g_, rho_, threshold_wrong_depth_measure_, velocity_dt_gap_sample_, velocity_limit_, zero_depth_window_size_.
Referenced by DepthPoseNode.
void DepthPoseNode::init_interfaces()
Init interfaces of this node
References pressure_callback, publisher_depth_data_, service_zero_depth_, service_zero_pressure_callback, subscriber_pressure_data_.
Referenced by DepthPoseNode.
void DepthPoseNode::pressure_callback(const seabot2_msgs::msg::PressureSensorData &msg)
Callback of the external pressure msg
References depth_memory_, filter_median_remove_side_samples_, filter_velocity_median_remove_side_samples_, filter_velocity_window_size_, filter_window_size_, g_, pressure_deque_, pressure_zero_depth_deque_, publisher_depth_data_, rho_, threshold_wrong_depth_measure_, velocity_dt_gap_sample_, velocity_limit_, zero_depth_, zero_depth_window_size_.
Referenced by init_interfaces.
void DepthPoseNode::service_zero_pressure_callback(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< std_srvs::srv::Trigger::Request > request, std::shared_ptr< std_srvs::srv::Trigger::Response > response)
Service callback request_header request response
References pressure_zero_depth_deque_, zero_depth_.
Referenced by init_interfaces.