AsyncSerial
const int AsyncSerial::readBufferSize
Read buffer maximum size
Referenced by doRead.
std::shared_ptr< AsyncSerialImpl > AsyncSerial::pimpl
Referenced by clearReadCallback, close, doClose, doRead, doWrite, errorStatus, isOpen, open, readEnd, setErrorStatus, setReadCallback, write, write, writeEnd, writeString.
AsyncSerial::AsyncSerial()
AsyncSerial::AsyncSerial(const std::string &devname, unsigned int baud_rate, boost::asio::serial_port_base::parity opt_parity=boost::asio::serial_port_base::parity(boost::asio::serial_port_base::parity::none), boost::asio::serial_port_base::character_size opt_csize=boost::asio::serial_port_base::character_size(8), boost::asio::serial_port_base::flow_control opt_flow=boost::asio::serial_port_base::flow_control(boost::asio::serial_port_base::flow_control::none), boost::asio::serial_port_base::stop_bits opt_stop=boost::asio::serial_port_base::stop_bits(boost::asio::serial_port_base::stop_bits::one))
Constructor. Creates and opens a serial device. devname serial device name, example "/dev/ttyS0" or "COM1" baud_rate serial baud rate opt_parity serial parity, default none opt_csize serial character size, default 8bit opt_flow serial flow control, default none opt_stop serial stop bits, default 1 boost::system::system_error if cannot open the serial device
void AsyncSerial::open(const std::string &devname, unsigned int baud_rate, boost::asio::serial_port_base::parity opt_parity=boost::asio::serial_port_base::parity(boost::asio::serial_port_base::parity::none), boost::asio::serial_port_base::character_size opt_csize=boost::asio::serial_port_base::character_size(8), boost::asio::serial_port_base::flow_control opt_flow=boost::asio::serial_port_base::flow_control(boost::asio::serial_port_base::flow_control::none), boost::asio::serial_port_base::stop_bits opt_stop=boost::asio::serial_port_base::stop_bits(boost::asio::serial_port_base::stop_bits::one))
Opens a serial device. devname serial device name, example "/dev/ttyS0" or "COM1" baud_rate serial baud rate opt_parity serial parity, default none opt_csize serial character size, default 8bit opt_flow serial flow control, default none opt_stop serial stop bits, default 1 boost::system::system_error if cannot open the serial device
References close, doRead, isOpen, pimpl, setErrorStatus.
Referenced by SBD::init.
bool AsyncSerial::isOpen() const
true if serial device is open
References pimpl.
Referenced by close, open, readEnd, ~AsyncSerial.
bool AsyncSerial::errorStatus() const
true if error were found
References pimpl.
Referenced by close.
void AsyncSerial::close()
Close the serial device boost::system::system_error if any error
References doClose, errorStatus, isOpen, pimpl.
Referenced by open, ~AsyncSerial, SBD::~SBD.
void AsyncSerial::write(const char *data, size_t size)
Write data asynchronously. Returns immediately. data array of char to be sent through the serial device size array size
References doWrite, pimpl.
void AsyncSerial::write(const std::vector< char > &data)
Write data asynchronously. Returns immediately. data to be sent through the serial device
References doWrite, pimpl.
void AsyncSerial::writeString(const std::string &s)
Write a string asynchronously. Returns immediately. Can be used to send ASCII data to the serial device. To send binary data, use write() s string to send
References doWrite, pimpl.
Referenced by SBD::write.
AsyncSerial::~AsyncSerial()=0
References close, isOpen.
void AsyncSerial::doRead()
Callback called to start an asynchronous read operation. This callback is called by the io_service in the spawned thread.
References pimpl, readBufferSize, readEnd.
Referenced by open, readEnd.
void AsyncSerial::readEnd(const boost::system::error_code &error, size_t bytes_transferred)
Callback called at the end of the asynchronous operation. This callback is called by the io_service in the spawned thread.
References doClose, doRead, isOpen, pimpl, setErrorStatus.
Referenced by doRead.
void AsyncSerial::doWrite()
Callback called to start an asynchronous write operation. If it is already in progress, does nothing. This callback is called by the io_service in the spawned thread.
References pimpl, writeEnd.
Referenced by write, write, writeString.
void AsyncSerial::writeEnd(const boost::system::error_code &error)
Callback called at the end of an asynchronuous write operation, if there is more data to write, restarts a new write operation. This callback is called by the io_service in the spawned thread.
References doClose, pimpl, setErrorStatus, writeEnd.
Referenced by doWrite, writeEnd.
void AsyncSerial::doClose()
Callback to close serial port
References pimpl, setErrorStatus.
Referenced by close, readEnd, writeEnd.
void AsyncSerial::setErrorStatus(bool e)
To allow derived classes to report errors e error status
References pimpl.
Referenced by doClose, open, readEnd, writeEnd.
void AsyncSerial::setReadCallback(const std::function< void(const char *, size_t) > &callback)
To allow derived classes to set a read callback
References pimpl.
Referenced by BufferedAsyncSerial::BufferedAsyncSerial, CallbackAsyncSerial::setCallback.
void AsyncSerial::clearReadCallback()
To unregister the read callback in the derived class destructor so it does not get called after the derived class destructor but before the base class destructor
References pimpl.
Referenced by CallbackAsyncSerial::clearCallback, BufferedAsyncSerial::~BufferedAsyncSerial, CallbackAsyncSerial::~CallbackAsyncSerial.