DensityNode
rclcpp::TimerBase::SharedPtr DensityNode::timer_
Rclcpp.
Referenced by DensityNode.
std::chrono::milliseconds DensityNode::loop_dt_
Referenced by DensityNode, init_parameters.
double DensityNode::sea_pressure_
loop dt
Variable
Referenced by pressure_callback, timer_callback.
double DensityNode::temperature_
Referenced by temperature_callback, timer_callback.
double DensityNode::salinity_
Referenced by init_parameters, timer_callback.
double DensityNode::water_density_
Referenced by timer_callback.
double DensityNode::water_sound_speed_
Referenced by timer_callback.
TeosSea DensityNode::ts
Referenced by timer_callback.
rclcpp::Subscription<seabot2_msgs::msg::DepthPose>::SharedPtr DensityNode::subscriber_depth_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr DensityNode::subscriber_temperature_data_
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::Density>::SharedPtr DensityNode::publisher_density_
Referenced by init_interfaces, timer_callback.
DensityNode::DensityNode()
References init_interfaces, init_parameters, loop_dt_, timer_, timer_callback.
void DensityNode::timer_callback()
Functions.
Callback
References TeosSea::gsw_rho_t_exact, TeosSea::gsw_sound_speed_t_exact, publisher_density_, salinity_, sea_pressure_, temperature_, ts, water_density_, water_sound_speed_.
Referenced by DensityNode.
void DensityNode::init_parameters()
Init and get parameters of the Node
References loop_dt_, salinity_.
Referenced by DensityNode.
void DensityNode::init_interfaces()
Init interfaces of this node
References pressure_callback, publisher_density_, subscriber_depth_data_, subscriber_temperature_data_, temperature_callback.
Referenced by DensityNode.
void DensityNode::temperature_callback(const seabot2_msgs::msg::TemperatureSensorData &msg)
Callback of the external pressure msg
References temperature_.
Referenced by init_interfaces.
void DensityNode::pressure_callback(const seabot2_msgs::msg::DepthPose &msg)
Callback of depth msg
References sea_pressure_.
Referenced by init_interfaces.