PingNode
rclcpp::Publisher<seabot2_msgs::msg::Profile>::SharedPtr PingNode::publisher_profile_
Topics / Services.
Referenced by init_interfaces, wait_message.
rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr PingNode::service_ping_enable_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::Density>::SharedPtr PingNode::subscriber_density_
Referenced by init_interfaces.
std::string PingNode::uart_port_
Variables.
Referenced by init_driver, init_parameters.
unsigned int PingNode::uart_baudrate_
Referenced by init_driver, init_parameters.
std::unique_ptr< Ping1d > PingNode::device_
Referenced by init_driver, ping_enable_callback, sound_speed_callback, wait_message, ~PingNode.
std::shared_ptr< AbstractLink > PingNode::port_
Referenced by init_driver.
bool PingNode::enable_ping_
Referenced by init_driver, init_parameters, ping_enable_callback, wait_message, ~PingNode.
bool PingNode::mode_auto_
Referenced by init_driver, init_parameters.
double PingNode::speed_of_sound_
mode
Referenced by init_driver, init_parameters, sound_speed_callback.
int PingNode::ping_interval_
speed of sound [m/s]
Referenced by init_driver, init_parameters.
int PingNode::gain_setting_
interval [ms]
Referenced by init_driver, init_parameters.
PingNode::PingNode()
References init_driver, init_interfaces, init_parameters.
PingNode::~PingNode()
References device_, enable_ping_.
void PingNode::wait_message() const
Functions.
References device_, enable_ping_, publisher_profile_.
void PingNode::init_parameters()
gain [1, 2, 3, 4, 5, 6]
Init and get parameters of the Node
References enable_ping_, gain_setting_, mode_auto_, ping_interval_, speed_of_sound_, uart_baudrate_, uart_port_.
Referenced by PingNode.
void PingNode::init_interfaces()
Init interfaces of the node
References ping_enable_callback, publisher_profile_, service_ping_enable_, sound_speed_callback, subscriber_density_.
Referenced by PingNode.
void PingNode::init_driver()
Init the ping1D driver
References device_, enable_ping_, gain_setting_, mode_auto_, ping_interval_, port_, speed_of_sound_, uart_baudrate_, uart_port_.
Referenced by PingNode.
void PingNode::ping_enable_callback(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< std_srvs::srv::SetBool::Request > request, std::shared_ptr< std_srvs::srv::SetBool::Response > response)
request_header request response
References device_, enable_ping_.
Referenced by init_interfaces.
void PingNode::sound_speed_callback(const seabot2_msgs::msg::Density &msg)
Callback of the sound speed msg
References device_, speed_of_sound_.
Referenced by init_interfaces.