ICM20948Node
rclcpp::TimerBase::SharedPtr ICM20948Node::timer_
Rclcpp.
Referenced by ICM20948Node.
std::chrono::milliseconds ICM20948Node::loop_dt_
Referenced by ICM20948Node, init_parameters.
ICM20948 ICM20948Node::icm20948_
loop dt
Referenced by compute_ahrs, ICM20948Node, init_parameters, timer_callback.
rclcpp::Publisher<seabot2_msgs::msg::RawData>::SharedPtr ICM20948Node::publisher_raw_data_
Topics.
Referenced by init_interfaces, timer_callback.
rclcpp::Publisher<seabot2_msgs::msg::RawData>::SharedPtr ICM20948Node::publisher_calibrated_data_
Referenced by compute_ahrs, init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::RPY>::SharedPtr ICM20948Node::publisher_rpy_
Referenced by compute_ahrs, init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::DebugFusion>::SharedPtr ICM20948Node::publisher_debug_fusion_
Referenced by compute_ahrs, init_interfaces.
bool ICM20948Node::publish_raw_data_
Referenced by init_parameters, timer_callback.
bool ICM20948Node::publish_calibrated_data_
Referenced by compute_ahrs, init_parameters.
bool ICM20948Node::publish_rpy_
Referenced by compute_ahrs, init_parameters.
bool ICM20948Node::publish_debug_fusion_
Referenced by compute_ahrs, init_parameters.
FusionMatrix ICM20948Node::gyroscopeMisalignment_
Parameters.
Referenced by compute_ahrs, init_parameters.
FusionVector ICM20948Node::gyroscopeSensitivity_
Referenced by compute_ahrs, init_parameters.
FusionVector ICM20948Node::gyroscopeOffset_
Referenced by compute_ahrs, init_parameters.
FusionMatrix ICM20948Node::accelerometerMisalignment_
Referenced by compute_ahrs, init_parameters.
FusionVector ICM20948Node::accelerometerSensitivity_
Referenced by compute_ahrs, init_parameters.
FusionVector ICM20948Node::accelerometerOffset_
Referenced by compute_ahrs, init_parameters.
FusionMatrix ICM20948Node::magnetometerMisalignment_
Referenced by compute_ahrs, init_parameters.
FusionVector ICM20948Node::magnetometerSensitivity_
Referenced by compute_ahrs, init_parameters.
FusionVector ICM20948Node::magnetometerOffset_
Referenced by compute_ahrs, init_parameters.
FusionMatrix ICM20948Node::softIronMatrix_
Referenced by compute_ahrs, init_parameters.
FusionVector ICM20948Node::hardIronOffset_
Referenced by compute_ahrs, init_parameters.
FusionOffset ICM20948Node::offset_
Referenced by compute_ahrs, init_parameters.
FusionAhrs ICM20948Node::ahrs_
Referenced by compute_ahrs, init_parameters.
FusionConvention ICM20948Node::convention_
Referenced by init_parameters.
float ICM20948Node::fusion_gain_
Referenced by init_parameters.
unsigned int ICM20948Node::sample_rate_
Referenced by init_parameters.
rclcpp::Time ICM20948Node::last_time_fusion_
Referenced by compute_ahrs, init_parameters.
rclcpp::Clock ICM20948Node::steady_clock_
Referenced by compute_ahrs, init_parameters.
float ICM20948Node::acceleration_rejection_
Referenced by init_parameters.
float ICM20948Node::magnetic_rejection_
Referenced by init_parameters.
unsigned int ICM20948Node::recovery_trigger_period_
Referenced by init_parameters.
ICM20948Node::ICM20948Node()
References icm20948_, ICM20948::init, init_interfaces, init_parameters, loop_dt_, timer_, timer_callback.
void ICM20948Node::compute_ahrs()
References ICM20948::acc_x_, ICM20948::acc_y_, ICM20948::acc_z_, FusionAhrsInternalStates::accelerationError, FusionAhrsFlags::accelerationRecovery, FusionAhrsInternalStates::accelerationRecoveryTrigger, FusionAhrsInternalStates::accelerometerIgnored, accelerometerMisalignment_, accelerometerOffset_, accelerometerSensitivity_, ahrs_, FusionEuler::angle, FusionAhrsFlags::angularRateRecovery, FusionVector::axis, FusionAhrsGetFlags, FusionAhrsGetInternalStates, FusionAhrsGetLinearAcceleration, FusionAhrsGetQuaternion, FusionAhrsUpdate, FusionCalibrationInertial, FusionCalibrationMagnetic, FusionOffsetUpdate, FusionQuaternionToEuler, ICM20948::gyro_x_, ICM20948::gyro_y_, ICM20948::gyro_z_, gyroscopeMisalignment_, gyroscopeOffset_, gyroscopeSensitivity_, hardIronOffset_, icm20948_, FusionAhrsFlags::initialising, last_time_fusion_, ICM20948::mag_data_has_been_skipped_, ICM20948::mag_data_is_ready_, ICM20948::mag_sensor_magnetic_overflow_, ICM20948::mag_x_, ICM20948::mag_y_, ICM20948::mag_z_, FusionAhrsInternalStates::magneticError, FusionAhrsFlags::magneticRecovery, FusionAhrsInternalStates::magneticRecoveryTrigger, FusionAhrsInternalStates::magnetometerIgnored, magnetometerMisalignment_, magnetometerOffset_, magnetometerSensitivity_, offset_, FusionEuler::pitch, publish_calibrated_data_, publish_debug_fusion_, publish_rpy_, publisher_calibrated_data_, publisher_debug_fusion_, publisher_rpy_, FusionEuler::roll, softIronMatrix_, steady_clock_, ICM20948::temp_, FusionVector::x, FusionVector::y, FusionEuler::yaw, FusionVector::z.
Referenced by timer_callback.
void ICM20948Node::init_parameters()
Functions.
Init and get parameters of the Node
References ICM20948::accel_fs_sel_, acceleration_rejection_, FusionAhrsSettings::accelerationRejection, accelerometerMisalignment_, accelerometerOffset_, accelerometerSensitivity_, ahrs_, FusionVector::axis, FusionAhrsSettings::convention, convention_, FusionMatrix::element, fusion_gain_, FusionAhrsInitialise, FusionAhrsSetSettings, FusionMatrixFromStdVector, FusionMatrixToStdVector, FusionOffsetInitialise, FusionVectorFromStdVector, FusionVectorToStdVector, FusionAhrsSettings::gain, ICM20948::gyro_fs_sel_, ICM20948::gyro_full_scale_, gyroscopeMisalignment_, gyroscopeOffset_, FusionAhrsSettings::gyroscopeRange, gyroscopeSensitivity_, hardIronOffset_, icm20948_, last_time_fusion_, loop_dt_, magnetic_rejection_, FusionAhrsSettings::magneticRejection, magnetometerMisalignment_, magnetometerOffset_, magnetometerSensitivity_, offset_, publish_calibrated_data_, publish_debug_fusion_, publish_raw_data_, publish_rpy_, recovery_trigger_period_, FusionAhrsSettings::recoveryTriggerPeriod, sample_rate_, softIronMatrix_, steady_clock_, FusionVector::x, FusionMatrix::xx, FusionMatrix::xy, FusionMatrix::xz, FusionVector::y, FusionMatrix::yx, FusionMatrix::yy, FusionMatrix::yz, FusionVector::z, FusionMatrix::zx, FusionMatrix::zy, FusionMatrix::zz.
Referenced by ICM20948Node.
void ICM20948Node::init_interfaces()
Init interfaces to this node (publishers & subscribers)
References publisher_calibrated_data_, publisher_debug_fusion_, publisher_raw_data_, publisher_rpy_.
Referenced by ICM20948Node.
void ICM20948Node::timer_callback()
Timer callback
References ICM20948::acc_x_, ICM20948::acc_y_, ICM20948::acc_z_, compute_ahrs, ICM20948::get_measure, ICM20948::gyro_x_, ICM20948::gyro_y_, ICM20948::gyro_z_, icm20948_, ICM20948::mag_x_, ICM20948::mag_y_, ICM20948::mag_z_, publish_raw_data_, publisher_raw_data_, ICM20948::temp_.
Referenced by ICM20948Node.