PressureMS5803Node
rclcpp::TimerBase::SharedPtr PressureMS5803Node::timer_
Variables.
Referenced by PressureMS5803Node.
rclcpp::Publisher<seabot2_msgs::msg::PressureSensorData>::SharedPtr PressureMS5803Node::publisher_sensor_
Referenced by init_interfaces, timer_callback.
Pressure_ms5803 PressureMS5803Node::pressure_sensor_
Referenced by init_parameters, PressureMS5803Node, timer_callback.
std::chrono::milliseconds PressureMS5803Node::loop_dt_
Referenced by init_parameters, PressureMS5803Node.
PressureMS5803Node::PressureMS5803Node()
References init_interfaces, init_parameters, Pressure_ms5803::init_sensor, loop_dt_, pressure_sensor_, timer_, timer_callback.
void PressureMS5803Node::timer_callback()
Functions.
References Pressure_ms5803::get_pression, Pressure_ms5803::get_temperature, Pressure_ms5803::measure, pressure_sensor_, publisher_sensor_.
Referenced by PressureMS5803Node.
void PressureMS5803Node::init_parameters()
References Pressure_ms5803::getI2CAddr, Pressure_ms5803::getI2CPeriph, loop_dt_, pressure_sensor_, Pressure_ms5803::setI2CAddr, Pressure_ms5803::setI2CPeriph.
Referenced by PressureMS5803Node.
void PressureMS5803Node::init_interfaces()
References publisher_sensor_.
Referenced by PressureMS5803Node.