Power
rclcpp::Node* Power::n_
Referenced by get_all_data, i2c_open, Power, set_sleep.
int Power::file_
Pointer to rclcpp Node.
Referenced by get_all_data, get_version, i2c_open, set_sleep, ~Power.
std::string Power::i2c_periph_
File to the i2c port.
Referenced by getI2CPeriph, i2c_open, setI2CPeriph.
int Power::i2c_addr_
Referenced by getI2CAddr, i2c_open, setI2CAddr.
const int Power::code_version_
Referenced by i2c_open.
uint8_t Power::pic_code_version_
Code version of the expected hardware.
Referenced by get_version.
std::array< double, 2 > Power::R1_
Code version read from the hardware.
Referenced by get_all_data.
std::array< double, 2 > Power::R2_
Referenced by get_all_data.
std::array< float, 2 > Power::cell_volt_
Variables.
Referenced by get_all_data, PowerNode::timer_callback.
double Power::battery_volt_
Referenced by get_all_data, PowerNode::timer_callback.
std::array< float, 2 > Power::esc_current_
Referenced by get_all_data, PowerNode::timer_callback.
float Power::motor_current_
Referenced by get_all_data, PowerNode::timer_callback.
int Power::power_state_
Referenced by get_all_data, PowerNode::timer_callback.
Power::Power(rclcpp::Node *n)
Power.
References n_.
Power::~Power()
References file_.
int Power::i2c_open()
Open the I2C device.
References code_version_, file_, get_version, i2c_addr_, i2c_periph_, n_.
Referenced by PowerNode::PowerNode.
uint8_t & Power::get_version()
get the version of the pic software version
References file_, pic_code_version_.
Referenced by i2c_open.
int Power::getI2CAddr() const
References i2c_addr_.
Referenced by PowerNode::init_parameters.
void Power::setI2CAddr(int i2CAddr)
References i2c_addr_.
Referenced by PowerNode::init_parameters.
const std::string & Power::getI2CPeriph() const
References i2c_periph_.
Referenced by PowerNode::init_parameters.
void Power::setI2CPeriph(const std::string &i2CPeriph)
References i2c_periph_.
Referenced by PowerNode::init_parameters.
int Power::get_all_data()
Get all the data from the pic
References battery_volt_, cell_volt_, CONVERT_BRIDGE_BATTERY, CONVERT_BRIDGE_CURRENT, CONVERT_CURRENT_V_to_A, esc_current_, file_, motor_current_, n_, power_state_, R1_, R2_, REGISTER_DATA_READ, REGISTER_DATA_SIZE.
Referenced by PowerNode::timer_callback.
int Power::set_sleep()
Set the seabot2 to sleep (default delay of 60s before going to sleep)
References file_, n_.