TeosBase
complex< double > TeosBase::t1
these complex numbers are initialized in the constructor
Referenced by gsw_deltasa_atlas, TeosIce::gsw_enthalpy_ice, gsw_gibbs_ice, TeosIce::gsw_gibbs_ice_part_t, TeosIce::gsw_gibbs_ice_pt0, TeosIce::gsw_gibbs_ice_pt0_pt0, gsw_pot_enthalpy_from_pt_ice, gsw_saar.
complex< double > TeosBase::t2
Referenced by TeosIce::gsw_enthalpy_ice, gsw_gibbs_ice, TeosIce::gsw_gibbs_ice_part_t, TeosIce::gsw_gibbs_ice_pt0, TeosIce::gsw_gibbs_ice_pt0_pt0, gsw_pot_enthalpy_from_pt_ice.
complex< double > TeosBase::r1
Referenced by gsw_deltasa_atlas, TeosIce::gsw_enthalpy_ice, gsw_gibbs_ice, TeosIce::gsw_gibbs_ice_part_t, TeosIce::gsw_gibbs_ice_pt0, TeosIce::gsw_gibbs_ice_pt0_pt0, gsw_pot_enthalpy_from_pt_ice, gsw_R_from_SP, gsw_saar.
complex< double > TeosBase::r20
Referenced by TeosIce::gsw_enthalpy_ice, gsw_gibbs_ice, TeosIce::gsw_gibbs_ice_part_t, TeosIce::gsw_gibbs_ice_pt0, TeosIce::gsw_gibbs_ice_pt0_pt0, gsw_pot_enthalpy_from_pt_ice, gsw_R_from_SP.
complex< double > TeosBase::r21
Referenced by TeosIce::gsw_enthalpy_ice, gsw_gibbs_ice, TeosIce::gsw_gibbs_ice_part_t.
complex< double > TeosBase::r22
Referenced by TeosIce::gsw_enthalpy_ice, gsw_gibbs_ice, TeosIce::gsw_gibbs_ice_part_t.
SaarDataHandler* TeosBase::pSaarData
Specialized data handler
Referenced by gsw_deltasa_atlas, gsw_saar, gsw_util_indxPref, TeosBase, ~TeosBase.
GSW_TEOS10_CONSTANTS TeosBase::gtc
Referenced by gsw_Abs_Pressure_from_p, gsw_alpha, TeosSea::gsw_alpha_on_beta, gsw_alpha_wrt_CT_t_exact, gsw_Arsol_SP_pt, gsw_beta, gsw_beta_const_ct_t_exact, gsw_beta_const_pt_t_exact, TeosSea::gsw_c_from_sp, gsw_chem_potential_water_t_exact, TeosIce::gsw_cp_ice, TeosSea::gsw_ct_first_derivatives, gsw_ct_first_derivatives_wrt_t_exact, TeosIce::gsw_ct_freezing_first_derivatives_poly, TeosIce::gsw_ct_freezing_poly, gsw_ct_from_enthalpy, gsw_ct_from_enthalpy_exact, gsw_ct_from_pt, gsw_dilution_coefficient_t_exact, gsw_dynamic_enthalpy, gsw_dynamic_enthalpy_CT_exact, gsw_dynamic_enthalpy_t_exact, gsw_enthalpy, TeosIce::gsw_enthalpy_diff, gsw_enthalpy_first_derivatives, gsw_enthalpy_first_derivatives_ct_exact, TeosSea::gsw_enthalpy_first_derivatives_wrt_t_exact, TeosIce::gsw_enthalpy_ice, TeosSea::gsw_enthalpy_second_derivatives, gsw_enthalpy_second_derivatives_ct_exact, gsw_enthalpy_sso_0, gsw_enthalpy_t_exact, gsw_entropy_first_derivatives, gsw_entropy_part, gsw_entropy_part_zerop, gsw_entropy_second_derivatives, TeosIce::gsw_frazil_properties_potential, TeosIce::gsw_frazil_properties_potential_poly, TeosSea::gsw_geo_strf_dyn_height, gsw_gibbs, gsw_gibbs_g03plusg08_f, gsw_gibbs_g08_a, gsw_gibbs_g08_b, gsw_gibbs_g08_c, gsw_gibbs_ice, TeosIce::gsw_gibbs_ice_part_t, TeosIce::gsw_gibbs_ice_pt0, TeosIce::gsw_gibbs_ice_pt0_pt0, gsw_gibbs_pt0_pt0, gsw_grav, TeosIce::gsw_helmholtz_energy_ice, gsw_Helmholtz_energy_t_exact, gsw_Hesol, gsw_Hesol_SP_pt, gsw_internal_energy, TeosSea::gsw_internal_energy_first_derivatives, TeosSea::gsw_internal_energy_first_derivatives_ct_exact, TeosIce::gsw_internal_energy_ice, TeosSea::gsw_internal_energy_second_derivatives, gsw_internal_energy_t_exact, gsw_isochoric_heat_cap_t_exact, gsw_kappa, gsw_Krsol, gsw_Krsol_SP_pt, TeosSea::gsw_latentheat_evap_ct, TeosIce::gsw_latentheat_melting, gsw_N2Osol, gsw_N2Osol_SP_pt, gsw_N2sol, gsw_N2sol_SP_pt, TeosIce::gsw_nsquared, gsw_o2sol, gsw_o2sol_sp_pt, gsw_osmotic_coefficient_t_exact, gsw_osmotic_pressure_t_exact, gsw_p_from_Abs_Pressure, gsw_p_from_z, gsw_pot_enthalpy_from_pt, gsw_pot_enthalpy_from_pt_ice, TeosIce::gsw_pot_enthalpy_ice_freezing_first_derivatives, TeosIce::gsw_pressure_freezing_ct, TeosIce::gsw_pt0_cold_ice_poly, gsw_pt0_from_t, TeosIce::gsw_pt0_from_t_ice, TeosSea::gsw_pt_first_derivatives, gsw_pt_from_ct, TeosSea::gsw_pt_from_entropy, gsw_pt_from_t, TeosIce::gsw_pt_from_t_ice, gsw_rho_alpha_beta, gsw_rho_alpha_beta_indexed, TeosSea::gsw_rho_first_derivatives, gsw_rho_first_derivatives_CT_exact, TeosIce::gsw_sa_freezing_estimate, gsw_sa_from_sp, gsw_sa_from_sp_baltic, TeosSea::gsw_sigma0, TeosSea::gsw_sound_speed, gsw_sp_from_c, gsw_sp_from_sa, gsw_sp_from_sa_baltic, TeosSea::gsw_sp_from_sk, TeosSea::gsw_sp_from_sr, TeosSea::gsw_sp_from_sstar, gsw_specvol, TeosSea::gsw_specvol_alpha_beta, gsw_specvol_anom, gsw_specvol_anom_standard_t_exact, gsw_specvol_anom_t_exact, gsw_specvol_diff, TeosSea::gsw_specvol_first_derivatives, gsw_specvol_first_derivatives_CT_exact, gsw_specvol_p_parts, TeosSea::gsw_specvol_second_derivatives, gsw_specvol_second_derivatives_CT_exact, TeosSea::gsw_spiciness0, TeosSea::gsw_spiciness1, TeosSea::gsw_spiciness2, gsw_sr_from_sp, gsw_sstar_from_sp, gsw_t_deriv_chem_potential_water_t_exact, gsw_t_freezing, TeosIce::gsw_t_freezing_exact, TeosIce::gsw_t_freezing_first_derivatives, TeosIce::gsw_t_freezing_first_derivatives_poly, TeosIce::gsw_t_freezing_poly, TeosSea::gsw_turner_rsubrho, gsw_z_from_p, TeosBase.
GSW_SPECVOL_COEFFICIENTS TeosBase::gsvco
Referenced by TeosIce::gsw_enthalpy_diff, gsw_enthalpy_first_derivatives, TeosSea::gsw_enthalpy_second_derivatives, gsw_enthalpy_sso_0, gsw_get_dyn_enth_prt, gsw_gsvco_a, gsw_gsvco_b, gsw_gsvco_c, gsw_gsvco_v, gsw_rho_alpha_beta_indexed, TeosSea::gsw_sigma0, gsw_specvol_diff, gsw_specvol_p_parts, TeosSea::gsw_specvol_second_derivatives, gsw_specvol_sso_0, TeosBase.
GSW_SP_COEFFICIENTS TeosBase::gspc
Referenced by TeosSea::gsw_c_from_sp, gsw_hill_ratio_at_sp2, gsw_R_from_SP, gsw_sp_from_c, gsw_SP_from_R, TeosSea::gsw_sp_salinometer, TeosBase.
GSW_BALTIC_DATA TeosBase::gbalt
Referenced by gsw_sa_from_sp_baltic, gsw_sp_from_sa_baltic, TeosBase.
GSW_SAAR_DATA TeosBase::gsaar
Referenced by gsw_add_barrier, gsw_deltasa_atlas, gsw_saar, TeosBase.
GSW_FREEZING_POLY_COEFFICIENTS TeosBase::gfpc
Referenced by TeosIce::gsw_ct_freezing_first_derivatives_poly, TeosIce::gsw_ct_freezing_poly, gsw_t_freezing, TeosIce::gsw_t_freezing_first_derivatives_poly, TeosIce::gsw_t_freezing_poly, TeosBase.
GSW_GIBBS_ICE_COEFFICIENTS TeosBase::gic
Referenced by TeosIce::gsw_enthalpy_ice, gsw_gibbs_ice, TeosIce::gsw_gibbs_ice_part_t, TeosIce::gsw_gibbs_ice_pt0, TeosIce::gsw_gibbs_ice_pt0_pt0, gsw_pot_enthalpy_from_pt_ice, TeosBase.
bool TeosBase::statusOk
Referenced by TeosIce::TeosIce, TeosSea::TeosSea.
const unsigned TeosBase::badBaseAlloc
Referenced by TeosBase, TeosIce::TeosIce, TeosSea::TeosSea.
TeosBase::TeosBase()
initialize the complex numbers
References badBaseAlloc, gbalt, gfpc, gic, gsaar, gspc, gsvco, gtc, GSW_BALTIC_DATA::init_GSW_BALTIC_DATA, GSW_FREEZING_POLY_COEFFICIENTS::init_GSW_FREEZING_POLY_COEFFICIENTS, GSW_GIBBS_ICE_COEFFICIENTS::init_GSW_GIBBS_ICE_COEFFICIENTS, GSW_SAAR_DATA::init_GSW_SAAR_DATA, GSW_SP_COEFFICIENTS::init_GSW_SP_COEFFICIENTS, GSW_SPECVOL_COEFFICIENTS::init_GSW_SPECVOL_COEFFICIENTS, GSW_TEOS10_CONSTANTS::init_GSW_TEOS10_CONSTANTS, pSaarData.
TeosBase::~TeosBase()
References NULL, pSaarData.
double TeosBase::gsw_Abs_Pressure_from_p(double p)
A
References GSW_TEOS10_CONSTANTS::db2pa, gtc.
void TeosBase::gsw_add_barrier(double *input_data, double lon, double lat, double long_grid, double lat_grid, double dlong_grid, double dlat_grid, double *output_data)
References gsaar, gsw_util_indx, GSW_SAAR_DATA::lats_pan, GSW_SAAR_DATA::longs_pan, GSW_SAAR_DATA::npan.
Referenced by gsw_deltasa_atlas, gsw_saar.
void TeosBase::gsw_add_mean(double *data_in, double *data_out)
Referenced by gsw_deltasa_atlas, gsw_saar.
double TeosBase::gsw_adiabatic_lapse_rate_from_t(double SA, double t, double p)
References gsw_gibbs.
Referenced by gsw_adiabatic_lapse_rate_t_exact.
double TeosBase::gsw_adiabatic_lapse_rate_t_exact(double SA, double t, double p)
References gsw_adiabatic_lapse_rate_from_t.
double TeosBase::gsw_alpha(double sa, double ct, double p)
References gsw_get_v_ct_part, GSW_TEOS10_CONSTANTS::gsw_sfac, gsw_specvol, gtc, GSW_TEOS10_CONSTANTS::offset.
Referenced by gsw_ct_maxdensity, TeosIce::gsw_ipv_vs_fnsquared_ratio, TeosIce::gsw_nsquared.
double TeosBase::gsw_alpha_CT_exact(double SA, double CT, double p)
References gsw_alpha_wrt_CT_t_exact, gsw_t_from_ct.
double TeosBase::gsw_alpha_on_beta_CT_exact(double SA, double CT, double p)
References gsw_specvol_alpha_beta_CT_exact.
Referenced by TeosSea::gsw_cabbeling_ct_exact.
double TeosBase::gsw_alpha_wrt_CT_t_exact(double SA, double t, double p)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_gibbs, gsw_pt0_from_t, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
Referenced by gsw_alpha_CT_exact, TeosSea::gsw_rho_alpha_beta_ct_exact, gsw_specvol_alpha_beta_CT_exact.
double TeosBase::gsw_alpha_wrt_pt_t_exact(double SA, double t, double p)
References gsw_gibbs, gsw_pt0_from_t.
double TeosBase::gsw_Arsol(double SA, double CT, double p, double lon, double lat)
References gsw_pt_from_ct, gsw_sp_from_sa.
double TeosBase::gsw_Arsol_SP_pt(double SP, double pt)
References GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_atomic_weight(void)
double TeosBase::gsw_beta(double sa, double ct, double p)
B
References gsw_gsvco_b, GSW_TEOS10_CONSTANTS::gsw_sfac, gsw_specvol, gtc, GSW_TEOS10_CONSTANTS::offset.
Referenced by TeosIce::gsw_ipv_vs_fnsquared_ratio, TeosIce::gsw_nsquared.
double TeosBase::gsw_beta_const_ct_t_exact(double SA, double t, double p)
References gsw_gibbs, gsw_pt0_from_t, GSW_TEOS10_CONSTANTS::gsw_sfac, GSW_TEOS10_CONSTANTS::gsw_t0, gtc, GSW_TEOS10_CONSTANTS::rec_db2pa.
Referenced by TeosSea::gsw_rho_alpha_beta_ct_exact, gsw_specvol_alpha_beta_CT_exact.
double TeosBase::gsw_beta_const_pt_t_exact(double SA, double t, double p)
References gsw_gibbs, gsw_pt0_from_t, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::rec_db2pa.
double TeosBase::gsw_chem_potential_relative_t_exact(double SA, double t, double p)
C
References gsw_gibbs.
Referenced by gsw_chem_potential_salt_t_exact.
double TeosBase::gsw_chem_potential_salt_t_exact(double SA, double t, double p)
References gsw_chem_potential_relative_t_exact, gsw_chem_potential_water_t_exact.
double TeosBase::gsw_chem_potential_water_t_exact(double sa, double t, double p)
References gsw_get_g03plusg08_h, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by gsw_chem_potential_salt_t_exact, TeosIce::gsw_latentheat_melting, gsw_osmotic_pressure_t_exact, gsw_t_freezing, TeosIce::gsw_t_freezing_exact.
void TeosBase::gsw_ct_first_derivatives_wrt_t_exact(double sa, double t, double p, double *ct_sa_wrt_t, double *ct_t_wrt_t, double *ct_p_wrt_t)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_gibbs, gsw_pt0_from_t, GSW_TEOS10_CONSTANTS::gsw_sfac, GSW_TEOS10_CONSTANTS::gsw_t0, gtc, NULL, GSW_TEOS10_CONSTANTS::rec_db2pa.
Referenced by TeosIce::gsw_ct_freezing_first_derivatives.
double TeosBase::gsw_ct_freezing(double sa, double p, double saturation_fraction=0.0)
References gsw_ct_from_t, gsw_t_freezing.
Referenced by gsw_ct_from_enthalpy, TeosIce::gsw_frazil_properties, TeosIce::gsw_frazil_properties_potential, TeosIce::gsw_frazil_ratios_adiabatic, TeosIce::gsw_ice_fraction_to_freeze_seawater, TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio, TeosIce::gsw_melting_ice_into_seawater, TeosIce::gsw_melting_ice_sa_ct_ratio, TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio, TeosIce::gsw_melting_seaice_into_seawater, TeosIce::gsw_melting_seaice_sa_ct_ratio, TeosIce::gsw_pressure_freezing_ct, TeosIce::gsw_sa_freezing_from_ct, TeosIce::gsw_seaice_fraction_to_freeze_seawater.
double TeosBase::gsw_CT_freezing(double SA, double saturation_fraction=0.0)
double TeosBase::gsw_ct_from_enthalpy(double sa, double h, double p)
References cppGSW_INVALID_VALUE, GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_ct_freezing, gsw_enthalpy, gsw_enthalpy_first_derivatives, gtc, NULL.
double TeosBase::gsw_ct_from_enthalpy_exact(double sa, double h, double p)
References cppGSW_INVALID_VALUE, GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_enthalpy_ct_exact, gsw_enthalpy_first_derivatives_ct_exact, gsw_t_freezing, gtc, NULL.
Referenced by TeosIce::gsw_frazil_properties, TeosIce::gsw_melting_seaice_into_seawater.
double TeosBase::gsw_ct_from_pt(double sa, double pt)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_get_pot_ent, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by TeosSea::gsw_ct_from_entropy, gsw_ct_from_t, TeosSea::gsw_latentheat_evap_t, gsw_pt_from_ct.
double TeosBase::gsw_ct_from_t(double sa, double t, double p)
References gsw_ct_from_pt, gsw_pt0_from_t.
Referenced by gsw_ct_freezing, TeosIce::gsw_ct_freezing_exact, TeosSea::gsw_ct_from_rho_exact, gsw_CT_maxdensity_exact, gsw_dynamic_enthalpy_t_exact, TeosIce::gsw_melting_seaice_sa_ct_ratio_poly, TeosIce::gsw_sa_freezing_estimate.
double TeosBase::gsw_ct_maxdensity(double sa, double p)
References gsw_alpha.
Referenced by TeosIce::gsw_ct_from_rho.
double TeosBase::gsw_CT_maxdensity_exact(double SA, double p)
References gsw_ct_from_t, gsw_t_maxdensity_exact.
double TeosBase::gsw_deltasa_atlas(double p, double lon, double lat)
D
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, GSW_SAAR_DATA::deli, GSW_SAAR_DATA::delj, SaarDataHandler::get_delta_sa_ref, SaarDataHandler::get_lats_ref, SaarDataHandler::get_longs_ref, SaarDataHandler::get_ndepth_ref, SaarDataHandler::get_p_ref, gsaar, gsw_add_barrier, gsw_add_mean, gsw_max_d, gsw_nx, gsw_ny, gsw_nz, gsw_sum, gsw_util_indxPref, GSW_SAAR_DATA::lats_pan, GSW_SAAR_DATA::longs_pan, GSW_SAAR_DATA::npan, pSaarData, r1, t1.
double TeosBase::gsw_depth_from_z(double z)
double TeosBase::gsw_dilution_coefficient_t_exact(double sa, double t, double p)
References gsw_g08_d, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by TeosIce::gsw_t_freezing_first_derivatives.
double TeosBase::gsw_dynamic_enthalpy(double sa, double ct, double p)
References GSW_TEOS10_CONSTANTS::db2pa, gsw_get_dyn_enth_prt, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::offset.
Referenced by gsw_enthalpy.
double TeosBase::gsw_dynamic_enthalpy_CT_exact(double SA, double CT, double p)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_enthalpy_t_exact, gsw_t_from_ct, gtc.
double TeosBase::gsw_dynamic_enthalpy_t_exact(double SA, double t, double p)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_ct_from_t, gsw_enthalpy_t_exact, gtc.
double TeosBase::gsw_enthalpy(double sa, double ct, double p)
E
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_dynamic_enthalpy, gtc.
Referenced by gsw_ct_from_enthalpy, TeosIce::gsw_frazil_ratios_adiabatic_poly, gsw_internal_energy, TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio_poly, TeosIce::gsw_melting_ice_sa_ct_ratio_poly, TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio_poly, TeosIce::gsw_melting_seaice_sa_ct_ratio_poly.
double TeosBase::gsw_enthalpy_ct_exact(double sa, double ct, double p)
References gsw_enthalpy_t_exact, gsw_t_from_ct.
Referenced by gsw_ct_from_enthalpy_exact, TeosIce::gsw_frazil_properties, TeosIce::gsw_frazil_ratios_adiabatic, TeosIce::gsw_ice_fraction_to_freeze_seawater, TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio, TeosIce::gsw_melting_ice_into_seawater, TeosIce::gsw_melting_ice_sa_ct_ratio, TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio, TeosIce::gsw_melting_seaice_into_seawater, TeosIce::gsw_melting_seaice_sa_ct_ratio, TeosIce::gsw_seaice_fraction_to_freeze_seawater.
double TeosBase::gsw_enthalpy_diff_CT_exact(double SA, double CT, double p_shallow, double p_deep)
References gsw_enthalpy_t_exact, gsw_t_from_ct.
void TeosBase::gsw_enthalpy_first_derivatives(double sa, double ct, double p, double *h_sa, double *h_ct)
References gsvco, GSW_TEOS10_CONSTANTS::gsw_cp0, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_SPECVOL_COEFFICIENTS::h011, GSW_SPECVOL_COEFFICIENTS::h012, GSW_SPECVOL_COEFFICIENTS::h013, GSW_SPECVOL_COEFFICIENTS::h014, GSW_SPECVOL_COEFFICIENTS::h015, GSW_SPECVOL_COEFFICIENTS::h021, GSW_SPECVOL_COEFFICIENTS::h022, GSW_SPECVOL_COEFFICIENTS::h023, GSW_SPECVOL_COEFFICIENTS::h024, GSW_SPECVOL_COEFFICIENTS::h031, GSW_SPECVOL_COEFFICIENTS::h032, GSW_SPECVOL_COEFFICIENTS::h033, GSW_SPECVOL_COEFFICIENTS::h041, GSW_SPECVOL_COEFFICIENTS::h042, GSW_SPECVOL_COEFFICIENTS::h043, GSW_SPECVOL_COEFFICIENTS::h051, GSW_SPECVOL_COEFFICIENTS::h052, GSW_SPECVOL_COEFFICIENTS::h061, GSW_SPECVOL_COEFFICIENTS::h101, GSW_SPECVOL_COEFFICIENTS::h102, GSW_SPECVOL_COEFFICIENTS::h103, GSW_SPECVOL_COEFFICIENTS::h104, GSW_SPECVOL_COEFFICIENTS::h105, GSW_SPECVOL_COEFFICIENTS::h111, GSW_SPECVOL_COEFFICIENTS::h112, GSW_SPECVOL_COEFFICIENTS::h113, GSW_SPECVOL_COEFFICIENTS::h114, GSW_SPECVOL_COEFFICIENTS::h121, GSW_SPECVOL_COEFFICIENTS::h122, GSW_SPECVOL_COEFFICIENTS::h123, GSW_SPECVOL_COEFFICIENTS::h131, GSW_SPECVOL_COEFFICIENTS::h132, GSW_SPECVOL_COEFFICIENTS::h133, GSW_SPECVOL_COEFFICIENTS::h141, GSW_SPECVOL_COEFFICIENTS::h142, GSW_SPECVOL_COEFFICIENTS::h151, GSW_SPECVOL_COEFFICIENTS::h201, GSW_SPECVOL_COEFFICIENTS::h202, GSW_SPECVOL_COEFFICIENTS::h203, GSW_SPECVOL_COEFFICIENTS::h204, GSW_SPECVOL_COEFFICIENTS::h211, GSW_SPECVOL_COEFFICIENTS::h212, GSW_SPECVOL_COEFFICIENTS::h213, GSW_SPECVOL_COEFFICIENTS::h221, GSW_SPECVOL_COEFFICIENTS::h222, GSW_SPECVOL_COEFFICIENTS::h223, GSW_SPECVOL_COEFFICIENTS::h231, GSW_SPECVOL_COEFFICIENTS::h232, GSW_SPECVOL_COEFFICIENTS::h241, GSW_SPECVOL_COEFFICIENTS::h301, GSW_SPECVOL_COEFFICIENTS::h302, GSW_SPECVOL_COEFFICIENTS::h303, GSW_SPECVOL_COEFFICIENTS::h311, GSW_SPECVOL_COEFFICIENTS::h312, GSW_SPECVOL_COEFFICIENTS::h313, GSW_SPECVOL_COEFFICIENTS::h321, GSW_SPECVOL_COEFFICIENTS::h322, GSW_SPECVOL_COEFFICIENTS::h331, GSW_SPECVOL_COEFFICIENTS::h401, GSW_SPECVOL_COEFFICIENTS::h402, GSW_SPECVOL_COEFFICIENTS::h403, GSW_SPECVOL_COEFFICIENTS::h411, GSW_SPECVOL_COEFFICIENTS::h412, GSW_SPECVOL_COEFFICIENTS::h421, GSW_SPECVOL_COEFFICIENTS::h501, GSW_SPECVOL_COEFFICIENTS::h502, GSW_SPECVOL_COEFFICIENTS::h511, GSW_SPECVOL_COEFFICIENTS::h601, NULL, GSW_TEOS10_CONSTANTS::offset, GSW_TEOS10_CONSTANTS::rec_db2pa.
Referenced by gsw_ct_from_enthalpy, TeosIce::gsw_frazil_ratios_adiabatic_poly, TeosSea::gsw_internal_energy_first_derivatives, TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio_poly, TeosIce::gsw_melting_ice_sa_ct_ratio_poly, TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio_poly, TeosIce::gsw_melting_seaice_sa_ct_ratio_poly, TeosSea::gsw_specvol_first_derivatives_wrt_enthalpy, TeosSea::gsw_specvol_second_derivatives_wrt_enthalpy.
void TeosBase::gsw_enthalpy_first_derivatives_ct_exact(double sa, double ct, double p, double *h_sa, double *h_ct)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_pt_from_ct, GSW_TEOS10_CONSTANTS::gsw_sfac, GSW_TEOS10_CONSTANTS::gsw_t0, gsw_t_from_ct, gtc, NULL, GSW_TEOS10_CONSTANTS::rec_db2pa.
Referenced by gsw_ct_from_enthalpy_exact, TeosIce::gsw_frazil_properties, TeosIce::gsw_frazil_ratios_adiabatic, TeosIce::gsw_ice_fraction_to_freeze_seawater, TeosSea::gsw_internal_energy_first_derivatives_ct_exact, TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio, TeosIce::gsw_melting_ice_sa_ct_ratio, TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio, TeosIce::gsw_melting_seaice_sa_ct_ratio, TeosIce::gsw_seaice_fraction_to_freeze_seawater, gsw_specvol_first_derivatives_wrt_enthalpy_CT_exact.
void TeosBase::gsw_enthalpy_second_derivatives_ct_exact(double sa, double ct, double p, double &h_sa_sa, double &h_sa_ct, double &h_ct_ct)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_gibbs, gsw_pt_from_ct, gsw_pt_from_t, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_enthalpy_sso_0(double p)
References GSW_TEOS10_CONSTANTS::db2pa, gsvco, gtc, GSW_SPECVOL_COEFFICIENTS::h006, GSW_SPECVOL_COEFFICIENTS::h007.
Referenced by TeosIce::gsw_geo_strf_dyn_height_pc, gsw_p_from_z, gsw_z_from_p.
double TeosBase::gsw_enthalpy_t_exact(double sa, double t, double p)
References gsw_gibbs, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
Referenced by gsw_dynamic_enthalpy_CT_exact, gsw_dynamic_enthalpy_t_exact, gsw_enthalpy_ct_exact, gsw_enthalpy_diff_CT_exact, TeosIce::gsw_melting_seaice_into_seawater, TeosIce::gsw_melting_seaice_sa_ct_ratio, TeosIce::gsw_seaice_fraction_to_freeze_seawater.
void TeosBase::gsw_entropy_first_derivatives(double sa, double ct, double *eta_sa, double *eta_ct)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_gibbs, gsw_pt_from_ct, GSW_TEOS10_CONSTANTS::gsw_t0, gtc, NULL.
double TeosBase::gsw_entropy_from_ct(double sa, double ct)
References gsw_gibbs, gsw_pt_from_ct.
double TeosBase::gsw_entropy_part(double sa, double t, double p)
References gsw_get_g03plusg08, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by gsw_pt0_from_t, gsw_pt_from_t.
double TeosBase::gsw_entropy_part_zerop(double sa, double pt0)
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by gsw_pt0_from_t.
void TeosBase::gsw_entropy_second_derivatives(double sa, double ct, double *eta_sa_sa, double *eta_sa_ct, double *eta_ct_ct)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_gibbs, gsw_pt_from_ct, GSW_TEOS10_CONSTANTS::gsw_t0, gtc, NULL.
double TeosBase::gsw_f(double lat)
F
double TeosBase::gsw_fdelta(double p, double lon, double lat)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, gsw_saar, saar.
double TeosBase::gsw_gibbs(int ns, int nt, int np, double sa, double t, double p)
G
References cppGSW_INVALID_VALUE, gsw_gibbs_g03plusg08_a, gsw_gibbs_g03plusg08_b, gsw_gibbs_g03plusg08_c, gsw_gibbs_g03plusg08_d, gsw_gibbs_g03plusg08_e, gsw_gibbs_g03plusg08_f, gsw_gibbs_g03plusg08_g, gsw_gibbs_g08_a, gsw_gibbs_g08_b, gsw_gibbs_g08_c, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::rec_db2pa.
Referenced by TeosSea::gsw_adiabatic_lapse_rate_from_ct, gsw_adiabatic_lapse_rate_from_t, gsw_alpha_wrt_CT_t_exact, gsw_alpha_wrt_pt_t_exact, TeosSea::gsw_alpha_wrt_t_exact, gsw_beta_const_ct_t_exact, gsw_beta_const_pt_t_exact, TeosSea::gsw_beta_const_t_exact, gsw_chem_potential_relative_t_exact, TeosSea::gsw_cp_t_exact, gsw_ct_first_derivatives_wrt_t_exact, TeosSea::gsw_enthalpy_first_derivatives_wrt_t_exact, gsw_enthalpy_second_derivatives_ct_exact, gsw_enthalpy_t_exact, gsw_entropy_first_derivatives, gsw_entropy_from_ct, TeosSea::gsw_entropy_from_pt, TeosSea::gsw_entropy_from_t, gsw_entropy_second_derivatives, gsw_Gibbs_energy_t_exact, gsw_Helmholtz_energy_t_exact, gsw_internal_energy_t_exact, gsw_isochoric_heat_cap_t_exact, gsw_kappa_const_t_exact, gsw_kappa_CT_exact, gsw_kappa_t_exact, gsw_osmotic_pressure_t_exact, TeosSea::gsw_pt_first_derivatives, gsw_pt_from_t, gsw_rho_first_derivatives_CT_exact, TeosSea::gsw_rho_t_exact, TeosSea::gsw_sound_speed_t_exact, gsw_specvol_anom_CT_exact, gsw_specvol_anom_standard_t_exact, gsw_specvol_anom_t_exact, gsw_specvol_first_derivatives_CT_exact, gsw_specvol_second_derivatives_CT_exact, gsw_specvol_t_exact, TeosIce::gsw_t_freezing_first_derivatives, TeosSea::gsw_t_from_rho_exact, gsw_t_maxdensity_exact.
double TeosBase::gsw_Gibbs_energy_t_exact(double SA, double t, double p)
References gsw_gibbs.
double TeosBase::gsw_gibbs_ice(int nt, int np, double t, double p)
References cppGSW_INVALID_VALUE, GSW_TEOS10_CONSTANTS::db2pa, GSW_GIBBS_ICE_COEFFICIENTS::g00, GSW_GIBBS_ICE_COEFFICIENTS::g01, GSW_GIBBS_ICE_COEFFICIENTS::g02, GSW_GIBBS_ICE_COEFFICIENTS::g03, GSW_GIBBS_ICE_COEFFICIENTS::g04, gic, GSW_TEOS10_CONSTANTS::gsw_t0, gtc, r1, r20, r21, r22, GSW_GIBBS_ICE_COEFFICIENTS::rec_pt, GSW_GIBBS_ICE_COEFFICIENTS::rec_tt, t1, t2, GSW_GIBBS_ICE_COEFFICIENTS::tt.
Referenced by TeosIce::gsw_adiabatic_lapse_rate_ice, TeosIce::gsw_alpha_wrt_t_ice, TeosIce::gsw_chem_potential_water_ice, TeosIce::gsw_cp_ice, TeosIce::gsw_entropy_ice, TeosIce::gsw_helmholtz_energy_ice, TeosIce::gsw_internal_energy_ice, TeosIce::gsw_kappa_const_t_ice, TeosIce::gsw_kappa_ice, TeosIce::gsw_pot_enthalpy_ice_freezing_first_derivatives, TeosIce::gsw_pt_from_t_ice, TeosIce::gsw_rho_ice, TeosIce::gsw_sound_speed_ice, TeosIce::gsw_specvol_ice, gsw_t_freezing, TeosIce::gsw_t_freezing_exact, TeosIce::gsw_t_from_rho_ice.
double TeosBase::gsw_gibbs_pt0_pt0(double sa, double pt0)
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by TeosSea::gsw_ct_first_derivatives, gsw_pt0_from_t, gsw_pt_from_ct, TeosSea::gsw_pt_from_entropy.
double TeosBase::gsw_grav(double lat, double p)
References GSW_TEOS10_CONSTANTS::deg2rad, GSW_TEOS10_CONSTANTS::gamma, gsw_z_from_p, gtc.
Referenced by TeosIce::gsw_nsquared.
double TeosBase::gsw_Helmholtz_energy_t_exact(double SA, double t, double p)
H
References GSW_TEOS10_CONSTANTS::db2pa, gsw_gibbs, GSW_TEOS10_CONSTANTS::gsw_p0, gtc.
double TeosBase::gsw_Hesol(double SA, double CT, double p, double lon, double lat)
References gsw_pt_from_ct, gsw_sp_from_sa, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_Hesol_SP_pt(double SP, double pt)
References GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_hill_ratio_at_sp2(double t)
References GSW_SP_COEFFICIENTS::a0, GSW_SP_COEFFICIENTS::a1, GSW_SP_COEFFICIENTS::a2, GSW_SP_COEFFICIENTS::a3, GSW_SP_COEFFICIENTS::a4, GSW_SP_COEFFICIENTS::a5, GSW_SP_COEFFICIENTS::b0, GSW_SP_COEFFICIENTS::b1, GSW_SP_COEFFICIENTS::b2, GSW_SP_COEFFICIENTS::b3, GSW_SP_COEFFICIENTS::b4, GSW_SP_COEFFICIENTS::b5, gspc, GSW_SP_COEFFICIENTS::k.
Referenced by TeosSea::gsw_c_from_sp, gsw_R_from_SP, gsw_sp_from_c, gsw_SP_from_R, TeosSea::gsw_sp_salinometer.
void TeosBase::gsw_Hill_ratio_at_SP2(const double t_data[], const int t_size[2], double Hill_ratio_data[], int Hill_ratio_size[2])
double TeosBase::gsw_internal_energy(double sa, double ct, double p)
I
References GSW_TEOS10_CONSTANTS::db2pa, gsw_enthalpy, GSW_TEOS10_CONSTANTS::gsw_p0, gsw_specvol, gtc.
double TeosBase::gsw_internal_energy_CT_exact(double SA, double CT, double p)
References gsw_internal_energy_t_exact, gsw_t_from_ct.
void TeosBase::gsw_internal_energy_second_derivatives(double SA, double CT, double p, double &u_SA_SA, double &u_SA_CT, double &u_CT_CT, double &u_SA_P, double &u_CT_P)
double TeosBase::gsw_internal_energy_t_exact(double SA, double t, double p)
References GSW_TEOS10_CONSTANTS::db2pa, gsw_gibbs, GSW_TEOS10_CONSTANTS::gsw_p0, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
Referenced by gsw_internal_energy_CT_exact.
double TeosBase::gsw_isochoric_heat_cap_t_exact(double SA, double t, double p)
References gsw_gibbs, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_kappa(double sa, double ct, double p)
K
References gsw_gsvco_c, gsw_gsvco_v, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::offset.
double TeosBase::gsw_kappa_const_t_exact(double SA, double t, double p)
References gsw_gibbs.
double TeosBase::gsw_kappa_CT_exact(double SA, double CT, double p)
References gsw_gibbs, gsw_t_from_ct.
double TeosBase::gsw_kappa_t_exact(double sa, double t, double p)
References gsw_gibbs.
double TeosBase::gsw_Krsol(double SA, double CT, double p, double lon, double lat)
References gsw_pt_from_ct, gsw_sp_from_sa, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_Krsol_SP_pt(double SP, double pt)
References GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
void TeosBase::gsw_linear_interp_sa_ct(double *sa, double *ct, double *p, int np, double *p_i, int npi, double *sa_i, double *ct_i)
L
References gsw_util_sort_dbl, NULL.
Referenced by TeosSea::gsw_geo_strf_dyn_height, gsw_rr68_interp_section.
int TeosBase::gsw_linear_interp_sa_ct_for_dh(double *sa, double *ct, double *p, int nz, double *p_i, int n_i, double *sa_i, double *ct_i)
double TeosBase::gsw_molality_from_SA(double SA)
M
double TeosBase::gsw_N2sol(double SA, double CT, double p, double lon, double lat)
N
References gsw_pt_from_ct, gsw_sp_from_sa, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_N2sol_SP_pt(double SP, double pt)
References GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_N2Osol(double SA, double CT, double p, double lon, double lat)
References gsw_pt_from_ct, gsw_sp_from_sa, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_N2Osol_SP_pt(double SP, double pt)
References GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_Nsquared_lowerlimit(double p, double b_long, double lat)
References rtNaN.
double TeosBase::gsw_osmotic_coefficient_t_exact(double SA, double t, double p)
O
References GSW_TEOS10_CONSTANTS::gsw_sfac, GSW_TEOS10_CONSTANTS::gsw_t0, gtc, GSW_TEOS10_CONSTANTS::rec_db2pa.
double TeosBase::gsw_osmotic_pressure_t_exact(double SA, double t, double pw)
References GSW_TEOS10_CONSTANTS::db2pa, gsw_chem_potential_water_t_exact, gsw_gibbs, gtc.
double TeosBase::gsw_o2sol(double sa, double ct, double p, double lon, double lat)
References gsw_pt_from_ct, gsw_sp_from_sa, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_o2sol_sp_pt(double sp, double pt)
References GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
double TeosBase::gsw_p_from_Abs_Pressure(double Absolute_Pressure)
P
References GSW_TEOS10_CONSTANTS::gsw_p0, gtc.
double TeosBase::gsw_p_from_z(double z, double lat, double geo_strf_dyn_height=0.0, double sea_surface_geopotential=0.0)
References cppGSW_INVALID_VALUE, GSW_TEOS10_CONSTANTS::db2pa, GSW_TEOS10_CONSTANTS::deg2rad, GSW_TEOS10_CONSTANTS::gamma, gsw_enthalpy_sso_0, gsw_specvol_sso_0, gtc.
int TeosBase::gsw_pchip_derivs(double *x, double *y, int n, double *d)
References gsw_pchip_edge_case, gsw_sgn.
Referenced by TeosSea::gsw_util_pchip_interp.
double TeosBase::gsw_pchip_edge_case(double h0, double h1, double m0, double m1)
References gsw_sgn.
Referenced by gsw_pchip_derivs.
double TeosBase::gsw_pot_enthalpy_from_pt(double SA, double pt)
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
double TeosBase::gsw_pot_enthalpy_from_pt_ice(double pt0_ice)
References GSW_GIBBS_ICE_COEFFICIENTS::g00, gic, GSW_TEOS10_CONSTANTS::gsw_t0, gtc, r1, r20, GSW_GIBBS_ICE_COEFFICIENTS::rec_tt, t1, t2, GSW_GIBBS_ICE_COEFFICIENTS::tt.
Referenced by TeosIce::gsw_pot_enthalpy_from_specvol_ice, TeosIce::gsw_pot_enthalpy_ice_freezing, TeosIce::gsw_pt_from_pot_enthalpy_ice.
double TeosBase::gsw_pot_enthalpy_from_specvol_ice_poly(double specvol_ice, double p)
References gsw_specvol_from_pot_enthalpy_ice_first_derivatives_poly, gsw_specvol_from_pot_enthalpy_ice_poly.
void TeosBase::gsw_pot_enthalpy_ice_freezing_first_derivatives_poly(double sa, double p, double *pot_enthalpy_ice_freezing_sa, double *pot_enthalpy_ice_freezing_p)
References NULL.
Referenced by TeosIce::gsw_frazil_properties_potential_poly.
double TeosBase::gsw_pot_enthalpy_ice_freezing_poly(double sa, double p)
Referenced by TeosIce::gsw_frazil_properties_potential_poly.
double TeosBase::gsw_pt_from_ct(double sa, double ct)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_ct_from_pt, gsw_gibbs_pt0_pt0, GSW_TEOS10_CONSTANTS::gsw_t0, GSW_TEOS10_CONSTANTS::gsw_ups, gtc.
Referenced by TeosSea::gsw_adiabatic_lapse_rate_from_ct, gsw_Arsol, gsw_enthalpy_first_derivatives_ct_exact, gsw_enthalpy_second_derivatives_ct_exact, gsw_entropy_first_derivatives, gsw_entropy_from_ct, gsw_entropy_second_derivatives, gsw_Hesol, gsw_Krsol, gsw_N2Osol, gsw_N2sol, gsw_o2sol, TeosSea::gsw_pt_first_derivatives, TeosSea::gsw_sigma0_ct_exact, gsw_specvol_first_derivatives_CT_exact, gsw_specvol_second_derivatives_CT_exact, gsw_t_from_ct.
double TeosBase::gsw_pt_from_t(double sa, double t, double p, double p_ref=0.0)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_entropy_part, gsw_gibbs, GSW_TEOS10_CONSTANTS::gsw_sso, GSW_TEOS10_CONSTANTS::gsw_t0, GSW_TEOS10_CONSTANTS::gsw_ups, gtc, p_ref.
Referenced by TeosSea::gsw_adiabatic_lapse_rate_from_ct, gsw_enthalpy_second_derivatives_ct_exact, TeosSea::gsw_pot_rho_t_exact, gsw_specvol_first_derivatives_CT_exact, gsw_specvol_second_derivatives_CT_exact, gsw_t_from_ct, TeosSea::gsw_t_from_entropy, gsw_t_from_pt0.
double TeosBase::gsw_pt0_from_t(double sa, double t, double p)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_entropy_part, gsw_entropy_part_zerop, gsw_gibbs_pt0_pt0, GSW_TEOS10_CONSTANTS::gsw_sso, GSW_TEOS10_CONSTANTS::gsw_t0, GSW_TEOS10_CONSTANTS::gsw_ups, gtc.
Referenced by gsw_alpha_wrt_CT_t_exact, gsw_alpha_wrt_pt_t_exact, gsw_beta_const_ct_t_exact, gsw_beta_const_pt_t_exact, gsw_ct_first_derivatives_wrt_t_exact, gsw_ct_from_t, gsw_rho_first_derivatives_CT_exact.
double TeosBase::gsw_R_from_SP(double SP, double t, double p)
R
References A, GSW_SP_COEFFICIENTS::a0, GSW_SP_COEFFICIENTS::a1, GSW_SP_COEFFICIENTS::a2, GSW_SP_COEFFICIENTS::a3, GSW_SP_COEFFICIENTS::a4, GSW_SP_COEFFICIENTS::a5, B, GSW_SP_COEFFICIENTS::b0, GSW_SP_COEFFICIENTS::b1, GSW_SP_COEFFICIENTS::b2, GSW_SP_COEFFICIENTS::b3, GSW_SP_COEFFICIENTS::b4, GSW_SP_COEFFICIENTS::b5, GSW_SP_COEFFICIENTS::c0, GSW_SP_COEFFICIENTS::c1, GSW_SP_COEFFICIENTS::c2, GSW_SP_COEFFICIENTS::c3, GSW_SP_COEFFICIENTS::c4, GSW_SP_COEFFICIENTS::d1, GSW_SP_COEFFICIENTS::d2, GSW_SP_COEFFICIENTS::d3, GSW_SP_COEFFICIENTS::d4, GSW_SP_COEFFICIENTS::e1, GSW_SP_COEFFICIENTS::e2, GSW_SP_COEFFICIENTS::e3, gspc, gsw_hill_ratio_at_sp2, GSW_SP_COEFFICIENTS::k, r1, r20.
double TeosBase::gsw_rho(double sa, double ct, double p)
References gsw_specvol.
Referenced by TeosSea::gsw_cabbeling, TeosIce::gsw_ct_from_rho, TeosIce::gsw_nsquared, TeosSea::gsw_sigma1, TeosSea::gsw_sigma2, TeosSea::gsw_sigma3, TeosSea::gsw_sigma4, TeosSea::gsw_thermobaric.
void TeosBase::gsw_rho_alpha_beta(double sa, double ct, double p, double *rho, double *alpha, double *beta)
References gsw_gsvco_a, gsw_gsvco_b, gsw_gsvco_v, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, NULL, GSW_TEOS10_CONSTANTS::offset.
Referenced by TeosIce::gsw_ct_from_rho.
void TeosBase::gsw_rho_alpha_beta_indexed(double SA, double CT, double p, double &rho, double &alpha, double &beta)
References GSW_SPECVOL_COEFFICIENTS::a000, GSW_SPECVOL_COEFFICIENTS::a001, GSW_SPECVOL_COEFFICIENTS::a002, GSW_SPECVOL_COEFFICIENTS::a003, GSW_SPECVOL_COEFFICIENTS::a004, GSW_SPECVOL_COEFFICIENTS::a010, GSW_SPECVOL_COEFFICIENTS::a011, GSW_SPECVOL_COEFFICIENTS::a012, GSW_SPECVOL_COEFFICIENTS::a013, GSW_SPECVOL_COEFFICIENTS::a020, GSW_SPECVOL_COEFFICIENTS::a021, GSW_SPECVOL_COEFFICIENTS::a022, GSW_SPECVOL_COEFFICIENTS::a030, GSW_SPECVOL_COEFFICIENTS::a031, GSW_SPECVOL_COEFFICIENTS::a032, GSW_SPECVOL_COEFFICIENTS::a040, GSW_SPECVOL_COEFFICIENTS::a041, GSW_SPECVOL_COEFFICIENTS::a050, GSW_SPECVOL_COEFFICIENTS::a100, GSW_SPECVOL_COEFFICIENTS::a101, GSW_SPECVOL_COEFFICIENTS::a102, GSW_SPECVOL_COEFFICIENTS::a103, GSW_SPECVOL_COEFFICIENTS::a110, GSW_SPECVOL_COEFFICIENTS::a111, GSW_SPECVOL_COEFFICIENTS::a112, GSW_SPECVOL_COEFFICIENTS::a120, GSW_SPECVOL_COEFFICIENTS::a121, GSW_SPECVOL_COEFFICIENTS::a122, GSW_SPECVOL_COEFFICIENTS::a130, GSW_SPECVOL_COEFFICIENTS::a131, GSW_SPECVOL_COEFFICIENTS::a140, GSW_SPECVOL_COEFFICIENTS::a200, GSW_SPECVOL_COEFFICIENTS::a201, GSW_SPECVOL_COEFFICIENTS::a202, GSW_SPECVOL_COEFFICIENTS::a210, GSW_SPECVOL_COEFFICIENTS::a211, GSW_SPECVOL_COEFFICIENTS::a212, GSW_SPECVOL_COEFFICIENTS::a220, GSW_SPECVOL_COEFFICIENTS::a221, GSW_SPECVOL_COEFFICIENTS::a230, GSW_SPECVOL_COEFFICIENTS::a300, GSW_SPECVOL_COEFFICIENTS::a301, GSW_SPECVOL_COEFFICIENTS::a302, GSW_SPECVOL_COEFFICIENTS::a310, GSW_SPECVOL_COEFFICIENTS::a311, GSW_SPECVOL_COEFFICIENTS::a320, GSW_SPECVOL_COEFFICIENTS::a400, GSW_SPECVOL_COEFFICIENTS::a401, GSW_SPECVOL_COEFFICIENTS::a410, GSW_SPECVOL_COEFFICIENTS::a500, GSW_SPECVOL_COEFFICIENTS::b000, GSW_SPECVOL_COEFFICIENTS::b001, GSW_SPECVOL_COEFFICIENTS::b002, GSW_SPECVOL_COEFFICIENTS::b003, GSW_SPECVOL_COEFFICIENTS::b004, GSW_SPECVOL_COEFFICIENTS::b010, GSW_SPECVOL_COEFFICIENTS::b011, GSW_SPECVOL_COEFFICIENTS::b012, GSW_SPECVOL_COEFFICIENTS::b013, GSW_SPECVOL_COEFFICIENTS::b020, GSW_SPECVOL_COEFFICIENTS::b021, GSW_SPECVOL_COEFFICIENTS::b022, GSW_SPECVOL_COEFFICIENTS::b030, GSW_SPECVOL_COEFFICIENTS::b031, GSW_SPECVOL_COEFFICIENTS::b032, GSW_SPECVOL_COEFFICIENTS::b040, GSW_SPECVOL_COEFFICIENTS::b041, GSW_SPECVOL_COEFFICIENTS::b050, GSW_SPECVOL_COEFFICIENTS::b100, GSW_SPECVOL_COEFFICIENTS::b101, GSW_SPECVOL_COEFFICIENTS::b102, GSW_SPECVOL_COEFFICIENTS::b103, GSW_SPECVOL_COEFFICIENTS::b110, GSW_SPECVOL_COEFFICIENTS::b111, GSW_SPECVOL_COEFFICIENTS::b112, GSW_SPECVOL_COEFFICIENTS::b120, GSW_SPECVOL_COEFFICIENTS::b121, GSW_SPECVOL_COEFFICIENTS::b122, GSW_SPECVOL_COEFFICIENTS::b130, GSW_SPECVOL_COEFFICIENTS::b131, GSW_SPECVOL_COEFFICIENTS::b140, GSW_SPECVOL_COEFFICIENTS::b200, GSW_SPECVOL_COEFFICIENTS::b201, GSW_SPECVOL_COEFFICIENTS::b202, GSW_SPECVOL_COEFFICIENTS::b210, GSW_SPECVOL_COEFFICIENTS::b211, GSW_SPECVOL_COEFFICIENTS::b212, GSW_SPECVOL_COEFFICIENTS::b220, GSW_SPECVOL_COEFFICIENTS::b221, GSW_SPECVOL_COEFFICIENTS::b230, GSW_SPECVOL_COEFFICIENTS::b300, GSW_SPECVOL_COEFFICIENTS::b301, GSW_SPECVOL_COEFFICIENTS::b302, GSW_SPECVOL_COEFFICIENTS::b310, GSW_SPECVOL_COEFFICIENTS::b311, GSW_SPECVOL_COEFFICIENTS::b320, GSW_SPECVOL_COEFFICIENTS::b400, GSW_SPECVOL_COEFFICIENTS::b401, GSW_SPECVOL_COEFFICIENTS::b410, GSW_SPECVOL_COEFFICIENTS::b500, gsvco, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::offset, GSW_TEOS10_CONSTANTS::rec_db2pa, GSW_SPECVOL_COEFFICIENTS::v000, GSW_SPECVOL_COEFFICIENTS::v001, GSW_SPECVOL_COEFFICIENTS::v002, GSW_SPECVOL_COEFFICIENTS::v003, GSW_SPECVOL_COEFFICIENTS::v004, GSW_SPECVOL_COEFFICIENTS::v005, GSW_SPECVOL_COEFFICIENTS::v006, GSW_SPECVOL_COEFFICIENTS::v010, GSW_SPECVOL_COEFFICIENTS::v011, GSW_SPECVOL_COEFFICIENTS::v012, GSW_SPECVOL_COEFFICIENTS::v013, GSW_SPECVOL_COEFFICIENTS::v014, GSW_SPECVOL_COEFFICIENTS::v020, GSW_SPECVOL_COEFFICIENTS::v021, GSW_SPECVOL_COEFFICIENTS::v022, GSW_SPECVOL_COEFFICIENTS::v023, GSW_SPECVOL_COEFFICIENTS::v030, GSW_SPECVOL_COEFFICIENTS::v031, GSW_SPECVOL_COEFFICIENTS::v032, GSW_SPECVOL_COEFFICIENTS::v040, GSW_SPECVOL_COEFFICIENTS::v041, GSW_SPECVOL_COEFFICIENTS::v042, GSW_SPECVOL_COEFFICIENTS::v050, GSW_SPECVOL_COEFFICIENTS::v051, GSW_SPECVOL_COEFFICIENTS::v060, GSW_SPECVOL_COEFFICIENTS::v100, GSW_SPECVOL_COEFFICIENTS::v101, GSW_SPECVOL_COEFFICIENTS::v102, GSW_SPECVOL_COEFFICIENTS::v103, GSW_SPECVOL_COEFFICIENTS::v104, GSW_SPECVOL_COEFFICIENTS::v110, GSW_SPECVOL_COEFFICIENTS::v111, GSW_SPECVOL_COEFFICIENTS::v112, GSW_SPECVOL_COEFFICIENTS::v113, GSW_SPECVOL_COEFFICIENTS::v120, GSW_SPECVOL_COEFFICIENTS::v121, GSW_SPECVOL_COEFFICIENTS::v122, GSW_SPECVOL_COEFFICIENTS::v130, GSW_SPECVOL_COEFFICIENTS::v131, GSW_SPECVOL_COEFFICIENTS::v132, GSW_SPECVOL_COEFFICIENTS::v140, GSW_SPECVOL_COEFFICIENTS::v141, GSW_SPECVOL_COEFFICIENTS::v150, GSW_SPECVOL_COEFFICIENTS::v200, GSW_SPECVOL_COEFFICIENTS::v201, GSW_SPECVOL_COEFFICIENTS::v202, GSW_SPECVOL_COEFFICIENTS::v203, GSW_SPECVOL_COEFFICIENTS::v210, GSW_SPECVOL_COEFFICIENTS::v211, GSW_SPECVOL_COEFFICIENTS::v212, GSW_SPECVOL_COEFFICIENTS::v220, GSW_SPECVOL_COEFFICIENTS::v221, GSW_SPECVOL_COEFFICIENTS::v222, GSW_SPECVOL_COEFFICIENTS::v230, GSW_SPECVOL_COEFFICIENTS::v231, GSW_SPECVOL_COEFFICIENTS::v240, GSW_SPECVOL_COEFFICIENTS::v300, GSW_SPECVOL_COEFFICIENTS::v301, GSW_SPECVOL_COEFFICIENTS::v302, GSW_SPECVOL_COEFFICIENTS::v310, GSW_SPECVOL_COEFFICIENTS::v311, GSW_SPECVOL_COEFFICIENTS::v312, GSW_SPECVOL_COEFFICIENTS::v320, GSW_SPECVOL_COEFFICIENTS::v321, GSW_SPECVOL_COEFFICIENTS::v330, GSW_SPECVOL_COEFFICIENTS::v400, GSW_SPECVOL_COEFFICIENTS::v401, GSW_SPECVOL_COEFFICIENTS::v402, GSW_SPECVOL_COEFFICIENTS::v410, GSW_SPECVOL_COEFFICIENTS::v411, GSW_SPECVOL_COEFFICIENTS::v420, GSW_SPECVOL_COEFFICIENTS::v500, GSW_SPECVOL_COEFFICIENTS::v501, GSW_SPECVOL_COEFFICIENTS::v510, GSW_SPECVOL_COEFFICIENTS::v600.
void TeosBase::gsw_rho_first_derivatives_CT_exact(double SA, double CT, double p, double &rho_SA, double &rho_CT, double &rho_P)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_gibbs, gsw_pt0_from_t, GSW_TEOS10_CONSTANTS::gsw_sfac, GSW_TEOS10_CONSTANTS::gsw_t0, gsw_t_from_ct, gtc, GSW_TEOS10_CONSTANTS::rec_db2pa.
void TeosBase::gsw_rho_first_derivatives_wrt_enthalpy_CT_exact(double SA, double CT, double p, double &rho_SA, double &rho_h)
References gsw_specvol_CT_exact, gsw_specvol_first_derivatives_wrt_enthalpy_CT_exact.
void TeosBase::gsw_rho_second_derivatives_CT_exact(double SA, double CT, double p, double *rho_SA_SA, double *rho_SA_CT, double *rho_CT_CT, double *rho_SA_P, double *rho_CT_P)
References gsw_specvol_CT_exact, gsw_specvol_first_derivatives_CT_exact, gsw_specvol_second_derivatives_CT_exact.
void TeosBase::gsw_rho_second_derivatives_wrt_enthalpy_CT_exact(double SA, double CT, double p, double &rho_SA_SA, double &rho_SA_h, double &rho_h_h)
void TeosBase::gsw_rr68_interp_section(int sectnum, double *sa, double *ct, double *p, int mp, int nsect, double *ip_sect, int *ip_isect, double *p_i, double *sa_i, double *ct_i)
References gsw_linear_interp_sa_ct, NULL.
Referenced by TeosSea::gsw_rr68_interp_sa_ct.
bool TeosBase::gsw_rtIsNaN(double val)
References rtNaN.
Referenced by gsw_weighted_nanmean.
bool TeosBase::gsw_rtIsNaNF(double val)
References rtNanF.
double TeosBase::gsw_saar(double p, double lon, double lat)
S
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, GSW_SAAR_DATA::deli, GSW_SAAR_DATA::delj, SaarDataHandler::get_lats_ref, SaarDataHandler::get_longs_ref, SaarDataHandler::get_ndepth_ref, SaarDataHandler::get_p_ref, SaarDataHandler::get_saar_ref, gsaar, gsw_add_barrier, gsw_add_mean, gsw_max_d, gsw_nx, gsw_ny, gsw_nz, gsw_sum, gsw_util_indxPref, GSW_SAAR_DATA::lats_pan, GSW_SAAR_DATA::longs_pan, GSW_SAAR_DATA::npan, pSaarData, r1, saar, t1.
Referenced by gsw_fdelta, gsw_sa_from_sp, gsw_sa_from_sstar, gsw_sp_from_sa, TeosSea::gsw_sp_from_sstar, gsw_sstar_from_sa, gsw_sstar_from_sp.
double TeosBase::gsw_SA_freezing_from_CT_poly(double CT, double p, double saturation_fraction=0.0)
double TeosBase::gsw_sa_from_sp(double sp, double p, double lon, double lat)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, gsw_sa_from_sp_baltic, gsw_saar, GSW_TEOS10_CONSTANTS::gsw_ups, gtc, saar.
Referenced by TeosIce::gsw_deltasa_from_sp.
double TeosBase::gsw_sa_from_sp_baltic(double sp, double lon, double lat)
References cppGSW_INVALID_VALUE, gbalt, GSW_TEOS10_CONSTANTS::gsw_sso, gsw_util_xinterp1, gtc, GSW_BALTIC_DATA::xb_left, GSW_BALTIC_DATA::xb_right, GSW_BALTIC_DATA::yb_left, GSW_BALTIC_DATA::yb_right.
Referenced by gsw_sa_from_sp, gsw_sstar_from_sp.
double TeosBase::gsw_sa_from_sstar(double sstar, double p, double lon, double lat)
References cppGSW_INVALID_VALUE, gsw_saar, saar.
int TeosBase::gsw_sgn(double x)
Referenced by gsw_pchip_derivs, gsw_pchip_edge_case.
double TeosBase::gsw_sp_from_c(double c, double t, double p)
References GSW_SP_COEFFICIENTS::a0, GSW_SP_COEFFICIENTS::a1, GSW_SP_COEFFICIENTS::a2, GSW_SP_COEFFICIENTS::a3, GSW_SP_COEFFICIENTS::a4, GSW_SP_COEFFICIENTS::a5, GSW_SP_COEFFICIENTS::b0, GSW_SP_COEFFICIENTS::b1, GSW_SP_COEFFICIENTS::b2, GSW_SP_COEFFICIENTS::b3, GSW_SP_COEFFICIENTS::b4, GSW_SP_COEFFICIENTS::b5, GSW_SP_COEFFICIENTS::c0, GSW_SP_COEFFICIENTS::c1, GSW_SP_COEFFICIENTS::c2, GSW_SP_COEFFICIENTS::c3, GSW_SP_COEFFICIENTS::c4, cppGSW_INVALID_VALUE, GSW_SP_COEFFICIENTS::d1, GSW_SP_COEFFICIENTS::d2, GSW_SP_COEFFICIENTS::d3, GSW_SP_COEFFICIENTS::d4, GSW_SP_COEFFICIENTS::e1, GSW_SP_COEFFICIENTS::e2, GSW_SP_COEFFICIENTS::e3, gspc, GSW_TEOS10_CONSTANTS::gsw_c3515, gsw_hill_ratio_at_sp2, gtc, GSW_SP_COEFFICIENTS::k.
double TeosBase::gsw_SP_from_R(double R, double t, double p)
References GSW_SP_COEFFICIENTS::a0, GSW_SP_COEFFICIENTS::a1, GSW_SP_COEFFICIENTS::a2, GSW_SP_COEFFICIENTS::a3, GSW_SP_COEFFICIENTS::a4, GSW_SP_COEFFICIENTS::a5, GSW_SP_COEFFICIENTS::b0, GSW_SP_COEFFICIENTS::b1, GSW_SP_COEFFICIENTS::b2, GSW_SP_COEFFICIENTS::b3, GSW_SP_COEFFICIENTS::b4, GSW_SP_COEFFICIENTS::b5, GSW_SP_COEFFICIENTS::c0, GSW_SP_COEFFICIENTS::c1, GSW_SP_COEFFICIENTS::c2, GSW_SP_COEFFICIENTS::c3, GSW_SP_COEFFICIENTS::c4, GSW_SP_COEFFICIENTS::d1, GSW_SP_COEFFICIENTS::d2, GSW_SP_COEFFICIENTS::d3, GSW_SP_COEFFICIENTS::d4, GSW_SP_COEFFICIENTS::e1, GSW_SP_COEFFICIENTS::e2, GSW_SP_COEFFICIENTS::e3, gspc, gsw_hill_ratio_at_sp2, GSW_SP_COEFFICIENTS::k, R.
double TeosBase::gsw_sp_from_sa(double sa, double p, double lon, double lat)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, gsw_saar, gsw_sp_from_sa_baltic, GSW_TEOS10_CONSTANTS::gsw_ups, gtc, saar.
Referenced by gsw_Arsol, gsw_Hesol, gsw_Krsol, gsw_N2Osol, gsw_N2sol, gsw_o2sol.
double TeosBase::gsw_sp_from_sa_baltic(double sa, double lon, double lat)
References cppGSW_INVALID_VALUE, gbalt, GSW_TEOS10_CONSTANTS::gsw_sso, gsw_util_xinterp1, gtc, GSW_BALTIC_DATA::xb_left, GSW_BALTIC_DATA::xb_right, GSW_BALTIC_DATA::yb_left, GSW_BALTIC_DATA::yb_right.
Referenced by gsw_sp_from_sa, TeosSea::gsw_sp_from_sstar.
double TeosBase::gsw_specvol(double sa, double ct, double p)
References gsw_gsvco_v, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::offset.
Referenced by gsw_alpha, gsw_beta, TeosIce::gsw_ct_from_rho, gsw_internal_energy, TeosSea::gsw_internal_energy_first_derivatives, gsw_rho, TeosSea::gsw_rho_first_derivatives_wrt_enthalpy, TeosSea::gsw_rho_second_derivatives, TeosSea::gsw_rho_second_derivatives_wrt_enthalpy, TeosSea::gsw_sa_from_rho, TeosSea::gsw_specvol_anom_standard.
void TeosBase::gsw_specvol_alpha_beta_CT_exact(double SA, double CT, double p, double &specvol_CT_exact, double &alpha_CT_exact, double &beta_CT_exact)
References gsw_alpha_wrt_CT_t_exact, gsw_beta_const_ct_t_exact, gsw_specvol_t_exact, gsw_t_from_ct.
Referenced by gsw_alpha_on_beta_CT_exact.
double TeosBase::gsw_specvol_anom(double SA, double CT, double p, double SA_ref, double CT_ref)
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::offset, GSW_TEOS10_CONSTANTS::rec_db2pa.
double TeosBase::gsw_specvol_anom_CT_exact(double SA, double CT, double p, double SA_ref, double CT_ref)
References gsw_gibbs, gsw_specvol_anom_standard_t_exact, gsw_t_from_ct.
double TeosBase::gsw_specvol_anom_standard_CT_exact(double SA, double CT, double p)
References gsw_specvol_anom_standard_t_exact, gsw_t_from_ct.
double TeosBase::gsw_specvol_anom_standard_t_exact(double SA, double t, double p)
References gsw_gibbs, GSW_TEOS10_CONSTANTS::gsw_sso, gsw_t_from_ct, gtc.
Referenced by gsw_specvol_anom_CT_exact, gsw_specvol_anom_standard_CT_exact.
double TeosBase::gsw_specvol_anom_t_exact(double SA, double t, double p)
References gsw_gibbs, GSW_TEOS10_CONSTANTS::gsw_sso, gsw_t_from_ct, gtc.
double TeosBase::gsw_specvol_CT_exact(double SA, double CT, double p)
References gsw_specvol_t_exact, gsw_t_from_ct.
Referenced by TeosSea::gsw_internal_energy_first_derivatives_ct_exact, gsw_rho_first_derivatives_wrt_enthalpy_CT_exact, gsw_rho_second_derivatives_CT_exact.
double TeosBase::gsw_specvol_diff(double SA, double CT, double p_shallow, double p_deep)
References gsvco, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::offset, GSW_TEOS10_CONSTANTS::rec_db2pa, GSW_SPECVOL_COEFFICIENTS::v001, GSW_SPECVOL_COEFFICIENTS::v002, GSW_SPECVOL_COEFFICIENTS::v003, GSW_SPECVOL_COEFFICIENTS::v004, GSW_SPECVOL_COEFFICIENTS::v005, GSW_SPECVOL_COEFFICIENTS::v006, GSW_SPECVOL_COEFFICIENTS::v111, GSW_SPECVOL_COEFFICIENTS::v112, GSW_SPECVOL_COEFFICIENTS::v113, GSW_SPECVOL_COEFFICIENTS::v221, GSW_SPECVOL_COEFFICIENTS::v222.
void TeosBase::gsw_specvol_first_derivatives_CT_exact(double SA, double CT, double p, double &v_SA, double &v_CT, double &v_P)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_gibbs, gsw_pt_from_ct, gsw_pt_from_t, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
Referenced by TeosSea::gsw_cabbeling_ct_exact, TeosSea::gsw_internal_energy_first_derivatives_ct_exact, gsw_rho_second_derivatives_CT_exact, gsw_specvol_first_derivatives_wrt_enthalpy_CT_exact, TeosSea::gsw_thermobaric_ct_exact.
void TeosBase::gsw_specvol_first_derivatives_wrt_enthalpy_CT_exact(double SA, double CT, double p, double &v_SA, double &v_h)
References gsw_enthalpy_first_derivatives_ct_exact, gsw_specvol_first_derivatives_CT_exact.
Referenced by gsw_rho_first_derivatives_wrt_enthalpy_CT_exact.
double TeosBase::gsw_specvol_from_pot_enthalpy_ice_first_derivatives_poly(double pot_enthalpy_ice, double p)
Referenced by gsw_pot_enthalpy_from_specvol_ice_poly.
double TeosBase::gsw_specvol_from_pot_enthalpy_ice_poly(double pot_enthalpy_ice, double p)
Referenced by gsw_pot_enthalpy_from_specvol_ice_poly.
void TeosBase::gsw_specvol_p_parts(double SA, double CT, double &vp0, double &vp1, double &vp2, double &vp3, double &vp4, double &vp5, double &vp6)
References gsvco, GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::offset, GSW_SPECVOL_COEFFICIENTS::v000, GSW_SPECVOL_COEFFICIENTS::v001, GSW_SPECVOL_COEFFICIENTS::v002, GSW_SPECVOL_COEFFICIENTS::v003, GSW_SPECVOL_COEFFICIENTS::v004, GSW_SPECVOL_COEFFICIENTS::v005, GSW_SPECVOL_COEFFICIENTS::v006, GSW_SPECVOL_COEFFICIENTS::v010, GSW_SPECVOL_COEFFICIENTS::v011, GSW_SPECVOL_COEFFICIENTS::v012, GSW_SPECVOL_COEFFICIENTS::v013, GSW_SPECVOL_COEFFICIENTS::v014, GSW_SPECVOL_COEFFICIENTS::v020, GSW_SPECVOL_COEFFICIENTS::v021, GSW_SPECVOL_COEFFICIENTS::v022, GSW_SPECVOL_COEFFICIENTS::v023, GSW_SPECVOL_COEFFICIENTS::v030, GSW_SPECVOL_COEFFICIENTS::v031, GSW_SPECVOL_COEFFICIENTS::v032, GSW_SPECVOL_COEFFICIENTS::v040, GSW_SPECVOL_COEFFICIENTS::v041, GSW_SPECVOL_COEFFICIENTS::v042, GSW_SPECVOL_COEFFICIENTS::v050, GSW_SPECVOL_COEFFICIENTS::v051, GSW_SPECVOL_COEFFICIENTS::v060, GSW_SPECVOL_COEFFICIENTS::v100, GSW_SPECVOL_COEFFICIENTS::v101, GSW_SPECVOL_COEFFICIENTS::v102, GSW_SPECVOL_COEFFICIENTS::v103, GSW_SPECVOL_COEFFICIENTS::v104, GSW_SPECVOL_COEFFICIENTS::v110, GSW_SPECVOL_COEFFICIENTS::v111, GSW_SPECVOL_COEFFICIENTS::v112, GSW_SPECVOL_COEFFICIENTS::v113, GSW_SPECVOL_COEFFICIENTS::v120, GSW_SPECVOL_COEFFICIENTS::v121, GSW_SPECVOL_COEFFICIENTS::v122, GSW_SPECVOL_COEFFICIENTS::v130, GSW_SPECVOL_COEFFICIENTS::v131, GSW_SPECVOL_COEFFICIENTS::v132, GSW_SPECVOL_COEFFICIENTS::v140, GSW_SPECVOL_COEFFICIENTS::v141, GSW_SPECVOL_COEFFICIENTS::v150, GSW_SPECVOL_COEFFICIENTS::v200, GSW_SPECVOL_COEFFICIENTS::v201, GSW_SPECVOL_COEFFICIENTS::v202, GSW_SPECVOL_COEFFICIENTS::v203, GSW_SPECVOL_COEFFICIENTS::v210, GSW_SPECVOL_COEFFICIENTS::v211, GSW_SPECVOL_COEFFICIENTS::v212, GSW_SPECVOL_COEFFICIENTS::v220, GSW_SPECVOL_COEFFICIENTS::v221, GSW_SPECVOL_COEFFICIENTS::v222, GSW_SPECVOL_COEFFICIENTS::v230, GSW_SPECVOL_COEFFICIENTS::v231, GSW_SPECVOL_COEFFICIENTS::v240, GSW_SPECVOL_COEFFICIENTS::v300, GSW_SPECVOL_COEFFICIENTS::v301, GSW_SPECVOL_COEFFICIENTS::v302, GSW_SPECVOL_COEFFICIENTS::v310, GSW_SPECVOL_COEFFICIENTS::v311, GSW_SPECVOL_COEFFICIENTS::v312, GSW_SPECVOL_COEFFICIENTS::v320, GSW_SPECVOL_COEFFICIENTS::v321, GSW_SPECVOL_COEFFICIENTS::v330, GSW_SPECVOL_COEFFICIENTS::v400, GSW_SPECVOL_COEFFICIENTS::v401, GSW_SPECVOL_COEFFICIENTS::v402, GSW_SPECVOL_COEFFICIENTS::v410, GSW_SPECVOL_COEFFICIENTS::v411, GSW_SPECVOL_COEFFICIENTS::v420, GSW_SPECVOL_COEFFICIENTS::v500, GSW_SPECVOL_COEFFICIENTS::v501, GSW_SPECVOL_COEFFICIENTS::v510, GSW_SPECVOL_COEFFICIENTS::v600.
void TeosBase::gsw_specvol_second_derivatives_CT_exact(double SA, double CT, double p, double &v_SA_SA, double &v_SA_CT, double &v_CT_CT, double &v_SA_P, double &v_CT_P)
References GSW_TEOS10_CONSTANTS::gsw_cp0, gsw_gibbs, gsw_pt_from_ct, gsw_pt_from_t, GSW_TEOS10_CONSTANTS::gsw_t0, gtc.
Referenced by TeosSea::gsw_cabbeling_ct_exact, gsw_rho_second_derivatives_CT_exact, TeosSea::gsw_thermobaric_ct_exact.
double TeosBase::gsw_specvol_t_exact(double sa, double t, double p)
References gsw_gibbs.
Referenced by TeosSea::gsw_enthalpy_first_derivatives_wrt_t_exact, gsw_specvol_alpha_beta_CT_exact, gsw_specvol_CT_exact, TeosIce::gsw_t_freezing_first_derivatives.
double TeosBase::gsw_specvol_sso_0(double p)
References gsvco, GSW_SPECVOL_COEFFICIENTS::v005, GSW_SPECVOL_COEFFICIENTS::v006.
Referenced by gsw_p_from_z, TeosSea::gsw_specvol_anom_standard.
double TeosBase::gsw_sr_from_sp(double sp)
References GSW_TEOS10_CONSTANTS::gsw_ups, gtc.
Referenced by TeosIce::gsw_deltasa_from_sp.
double TeosBase::gsw_SSO(void)
double TeosBase::gsw_sstar_from_sa(double sa, double p, double lon, double lat)
References cppGSW_INVALID_VALUE, gsw_saar, saar.
double TeosBase::gsw_sstar_from_sp(double sp, double p, double lon, double lat)
References cppGSW_ERROR_LIMIT, cppGSW_INVALID_VALUE, gsw_sa_from_sp_baltic, gsw_saar, GSW_TEOS10_CONSTANTS::gsw_ups, gtc, saar.
double TeosBase::gsw_sum(double *x, int n)
Referenced by gsw_deltasa_atlas, gsw_saar.
double TeosBase::gsw_t_deriv_chem_potential_water_t_exact(double sa, double t, double p)
T
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc, GSW_TEOS10_CONSTANTS::rec_db2pa.
Referenced by TeosIce::gsw_latentheat_melting, gsw_t_freezing, TeosIce::gsw_t_freezing_exact, TeosIce::gsw_t_freezing_first_derivatives.
double TeosBase::gsw_t_freezing(double sa, double p, double saturation_fraction=0.0)
References gfpc, gsw_chem_potential_water_t_exact, gsw_gibbs_ice, GSW_TEOS10_CONSTANTS::gsw_sso, gsw_t_deriv_chem_potential_water_t_exact, gtc, GSW_FREEZING_POLY_COEFFICIENTS::t0, GSW_FREEZING_POLY_COEFFICIENTS::t1, GSW_FREEZING_POLY_COEFFICIENTS::t10, GSW_FREEZING_POLY_COEFFICIENTS::t11, GSW_FREEZING_POLY_COEFFICIENTS::t12, GSW_FREEZING_POLY_COEFFICIENTS::t13, GSW_FREEZING_POLY_COEFFICIENTS::t14, GSW_FREEZING_POLY_COEFFICIENTS::t15, GSW_FREEZING_POLY_COEFFICIENTS::t16, GSW_FREEZING_POLY_COEFFICIENTS::t17, GSW_FREEZING_POLY_COEFFICIENTS::t18, GSW_FREEZING_POLY_COEFFICIENTS::t19, GSW_FREEZING_POLY_COEFFICIENTS::t2, GSW_FREEZING_POLY_COEFFICIENTS::t20, GSW_FREEZING_POLY_COEFFICIENTS::t21, GSW_FREEZING_POLY_COEFFICIENTS::t22, GSW_FREEZING_POLY_COEFFICIENTS::t3, GSW_FREEZING_POLY_COEFFICIENTS::t4, GSW_FREEZING_POLY_COEFFICIENTS::t5, GSW_FREEZING_POLY_COEFFICIENTS::t6, GSW_FREEZING_POLY_COEFFICIENTS::t7, GSW_FREEZING_POLY_COEFFICIENTS::t8, GSW_FREEZING_POLY_COEFFICIENTS::t9.
Referenced by gsw_ct_freezing, TeosIce::gsw_ct_freezing_first_derivatives, gsw_ct_from_enthalpy_exact, TeosIce::gsw_frazil_properties, TeosIce::gsw_frazil_ratios_adiabatic, TeosIce::gsw_ice_fraction_to_freeze_seawater, TeosIce::gsw_latentheat_melting, TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio, TeosIce::gsw_melting_ice_into_seawater, TeosIce::gsw_melting_ice_sa_ct_ratio, TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio, TeosIce::gsw_melting_seaice_into_seawater, TeosIce::gsw_melting_seaice_sa_ct_ratio, TeosIce::gsw_pot_enthalpy_ice_freezing, TeosIce::gsw_pot_enthalpy_ice_freezing_first_derivatives, TeosIce::gsw_sa_freezing_from_t, TeosIce::gsw_seaice_fraction_to_freeze_seawater, TeosIce::gsw_t_freezing_first_derivatives, TeosSea::gsw_t_from_rho_exact, TeosIce::gsw_t_from_rho_ice.
double TeosBase::gsw_t_from_ct(double sa, double ct, double p)
References gsw_pt_from_ct, gsw_pt_from_t.
Referenced by gsw_alpha_CT_exact, gsw_dynamic_enthalpy_CT_exact, gsw_enthalpy_ct_exact, gsw_enthalpy_diff_CT_exact, gsw_enthalpy_first_derivatives_ct_exact, gsw_internal_energy_CT_exact, gsw_kappa_CT_exact, TeosSea::gsw_rho_alpha_beta_ct_exact, TeosSea::gsw_rho_ct_exact, gsw_rho_first_derivatives_CT_exact, TeosSea::gsw_sigma1_ct_exact, TeosSea::gsw_sigma2_ct_exact, TeosSea::gsw_sigma3_ct_exact, TeosSea::gsw_sigma4_ct_exact, TeosSea::gsw_sound_speed_ct_exact, gsw_specvol_alpha_beta_CT_exact, gsw_specvol_anom_CT_exact, gsw_specvol_anom_standard_CT_exact, gsw_specvol_anom_standard_t_exact, gsw_specvol_anom_t_exact, gsw_specvol_CT_exact, TeosIce::gsw_t_freezing_poly, TeosIce::gsw_t_freezing_poly.
double TeosBase::gsw_t_from_pt0(double SA, double pt0, double p)
References gsw_pt_from_t.
double TeosBase::gsw_t_maxdensity_exact(double SA, double p)
References gsw_gibbs.
Referenced by gsw_CT_maxdensity_exact, TeosSea::gsw_t_from_rho_exact.
double TeosBase::gsw_t90_from_t48(double t48)
double TeosBase::gsw_t90_from_t68(double t68)
int TeosBase::gsw_util_indx(double *x, int n, double z)
U
Referenced by gsw_add_barrier, gsw_util_xinterp1.
void TeosBase::gsw_util_sort_dbl(double *dArray, int nx, int *iArray, bool ASC=false)
References DI::d, DI::i, orderByLargeToSmall, orderBySmallToLarge.
Referenced by gsw_linear_interp_sa_ct, TeosSea::gsw_util_interp1q_int, TeosSea::gsw_util_linear_interp.
double TeosBase::gsw_util_xinterp1(double *x, double *y, int n, double x0)
References gsw_util_indx.
Referenced by gsw_sa_from_sp_baltic, gsw_sp_from_sa_baltic.
void TeosBase::gsw_weighted_nanmean(double data, double weights, double &weighted_mean, double &weighted_weights)
W
References gsw_rtIsNaN, rtNaN.
double TeosBase::gsw_z_from_depth(double depth)
Z
double TeosBase::gsw_z_from_p(double p, double lat, double geo_strf_dyn_height=0.0, double sea_surface_geopotential=0.0)
References GSW_TEOS10_CONSTANTS::deg2rad, GSW_TEOS10_CONSTANTS::gamma, gsw_enthalpy_sso_0, gtc.
Referenced by gsw_grav.
double TeosBase::gsw_gsvco_a(double xs, double ys, double z)
References GSW_SPECVOL_COEFFICIENTS::a000, GSW_SPECVOL_COEFFICIENTS::a001, GSW_SPECVOL_COEFFICIENTS::a002, GSW_SPECVOL_COEFFICIENTS::a003, GSW_SPECVOL_COEFFICIENTS::a004, GSW_SPECVOL_COEFFICIENTS::a010, GSW_SPECVOL_COEFFICIENTS::a011, GSW_SPECVOL_COEFFICIENTS::a012, GSW_SPECVOL_COEFFICIENTS::a013, GSW_SPECVOL_COEFFICIENTS::a020, GSW_SPECVOL_COEFFICIENTS::a021, GSW_SPECVOL_COEFFICIENTS::a022, GSW_SPECVOL_COEFFICIENTS::a030, GSW_SPECVOL_COEFFICIENTS::a031, GSW_SPECVOL_COEFFICIENTS::a032, GSW_SPECVOL_COEFFICIENTS::a040, GSW_SPECVOL_COEFFICIENTS::a041, GSW_SPECVOL_COEFFICIENTS::a050, GSW_SPECVOL_COEFFICIENTS::a100, GSW_SPECVOL_COEFFICIENTS::a101, GSW_SPECVOL_COEFFICIENTS::a102, GSW_SPECVOL_COEFFICIENTS::a103, GSW_SPECVOL_COEFFICIENTS::a110, GSW_SPECVOL_COEFFICIENTS::a111, GSW_SPECVOL_COEFFICIENTS::a112, GSW_SPECVOL_COEFFICIENTS::a120, GSW_SPECVOL_COEFFICIENTS::a121, GSW_SPECVOL_COEFFICIENTS::a122, GSW_SPECVOL_COEFFICIENTS::a130, GSW_SPECVOL_COEFFICIENTS::a131, GSW_SPECVOL_COEFFICIENTS::a140, GSW_SPECVOL_COEFFICIENTS::a200, GSW_SPECVOL_COEFFICIENTS::a201, GSW_SPECVOL_COEFFICIENTS::a202, GSW_SPECVOL_COEFFICIENTS::a210, GSW_SPECVOL_COEFFICIENTS::a211, GSW_SPECVOL_COEFFICIENTS::a212, GSW_SPECVOL_COEFFICIENTS::a220, GSW_SPECVOL_COEFFICIENTS::a221, GSW_SPECVOL_COEFFICIENTS::a230, GSW_SPECVOL_COEFFICIENTS::a300, GSW_SPECVOL_COEFFICIENTS::a301, GSW_SPECVOL_COEFFICIENTS::a302, GSW_SPECVOL_COEFFICIENTS::a310, GSW_SPECVOL_COEFFICIENTS::a311, GSW_SPECVOL_COEFFICIENTS::a320, GSW_SPECVOL_COEFFICIENTS::a400, GSW_SPECVOL_COEFFICIENTS::a401, GSW_SPECVOL_COEFFICIENTS::a410, GSW_SPECVOL_COEFFICIENTS::a500, gsvco.
Referenced by TeosSea::gsw_alpha_on_beta, gsw_get_v_ct_part, gsw_rho_alpha_beta, TeosSea::gsw_rho_first_derivatives, TeosSea::gsw_specvol_alpha_beta, TeosSea::gsw_specvol_first_derivatives.
double TeosBase::gsw_gsvco_b(double xs, double ys, double z)
References GSW_SPECVOL_COEFFICIENTS::b000, GSW_SPECVOL_COEFFICIENTS::b001, GSW_SPECVOL_COEFFICIENTS::b002, GSW_SPECVOL_COEFFICIENTS::b003, GSW_SPECVOL_COEFFICIENTS::b004, GSW_SPECVOL_COEFFICIENTS::b010, GSW_SPECVOL_COEFFICIENTS::b011, GSW_SPECVOL_COEFFICIENTS::b012, GSW_SPECVOL_COEFFICIENTS::b013, GSW_SPECVOL_COEFFICIENTS::b020, GSW_SPECVOL_COEFFICIENTS::b021, GSW_SPECVOL_COEFFICIENTS::b022, GSW_SPECVOL_COEFFICIENTS::b030, GSW_SPECVOL_COEFFICIENTS::b031, GSW_SPECVOL_COEFFICIENTS::b032, GSW_SPECVOL_COEFFICIENTS::b040, GSW_SPECVOL_COEFFICIENTS::b041, GSW_SPECVOL_COEFFICIENTS::b050, GSW_SPECVOL_COEFFICIENTS::b100, GSW_SPECVOL_COEFFICIENTS::b101, GSW_SPECVOL_COEFFICIENTS::b102, GSW_SPECVOL_COEFFICIENTS::b103, GSW_SPECVOL_COEFFICIENTS::b110, GSW_SPECVOL_COEFFICIENTS::b111, GSW_SPECVOL_COEFFICIENTS::b112, GSW_SPECVOL_COEFFICIENTS::b120, GSW_SPECVOL_COEFFICIENTS::b121, GSW_SPECVOL_COEFFICIENTS::b122, GSW_SPECVOL_COEFFICIENTS::b130, GSW_SPECVOL_COEFFICIENTS::b131, GSW_SPECVOL_COEFFICIENTS::b140, GSW_SPECVOL_COEFFICIENTS::b200, GSW_SPECVOL_COEFFICIENTS::b201, GSW_SPECVOL_COEFFICIENTS::b202, GSW_SPECVOL_COEFFICIENTS::b210, GSW_SPECVOL_COEFFICIENTS::b211, GSW_SPECVOL_COEFFICIENTS::b212, GSW_SPECVOL_COEFFICIENTS::b220, GSW_SPECVOL_COEFFICIENTS::b221, GSW_SPECVOL_COEFFICIENTS::b230, GSW_SPECVOL_COEFFICIENTS::b300, GSW_SPECVOL_COEFFICIENTS::b301, GSW_SPECVOL_COEFFICIENTS::b302, GSW_SPECVOL_COEFFICIENTS::b310, GSW_SPECVOL_COEFFICIENTS::b311, GSW_SPECVOL_COEFFICIENTS::b320, GSW_SPECVOL_COEFFICIENTS::b400, GSW_SPECVOL_COEFFICIENTS::b401, GSW_SPECVOL_COEFFICIENTS::b410, GSW_SPECVOL_COEFFICIENTS::b500, gsvco.
Referenced by TeosSea::gsw_alpha_on_beta, gsw_beta, gsw_rho_alpha_beta, TeosSea::gsw_rho_first_derivatives, TeosSea::gsw_specvol_alpha_beta, TeosSea::gsw_specvol_first_derivatives.
double TeosBase::gsw_gsvco_c(double xs, double ys, double z)
References GSW_SPECVOL_COEFFICIENTS::c000, GSW_SPECVOL_COEFFICIENTS::c001, GSW_SPECVOL_COEFFICIENTS::c002, GSW_SPECVOL_COEFFICIENTS::c003, GSW_SPECVOL_COEFFICIENTS::c004, GSW_SPECVOL_COEFFICIENTS::c005, GSW_SPECVOL_COEFFICIENTS::c010, GSW_SPECVOL_COEFFICIENTS::c011, GSW_SPECVOL_COEFFICIENTS::c012, GSW_SPECVOL_COEFFICIENTS::c013, GSW_SPECVOL_COEFFICIENTS::c020, GSW_SPECVOL_COEFFICIENTS::c021, GSW_SPECVOL_COEFFICIENTS::c022, GSW_SPECVOL_COEFFICIENTS::c030, GSW_SPECVOL_COEFFICIENTS::c031, GSW_SPECVOL_COEFFICIENTS::c040, GSW_SPECVOL_COEFFICIENTS::c041, GSW_SPECVOL_COEFFICIENTS::c050, GSW_SPECVOL_COEFFICIENTS::c100, GSW_SPECVOL_COEFFICIENTS::c101, GSW_SPECVOL_COEFFICIENTS::c102, GSW_SPECVOL_COEFFICIENTS::c103, GSW_SPECVOL_COEFFICIENTS::c110, GSW_SPECVOL_COEFFICIENTS::c111, GSW_SPECVOL_COEFFICIENTS::c112, GSW_SPECVOL_COEFFICIENTS::c120, GSW_SPECVOL_COEFFICIENTS::c121, GSW_SPECVOL_COEFFICIENTS::c130, GSW_SPECVOL_COEFFICIENTS::c131, GSW_SPECVOL_COEFFICIENTS::c140, GSW_SPECVOL_COEFFICIENTS::c200, GSW_SPECVOL_COEFFICIENTS::c201, GSW_SPECVOL_COEFFICIENTS::c202, GSW_SPECVOL_COEFFICIENTS::c210, GSW_SPECVOL_COEFFICIENTS::c211, GSW_SPECVOL_COEFFICIENTS::c220, GSW_SPECVOL_COEFFICIENTS::c221, GSW_SPECVOL_COEFFICIENTS::c230, GSW_SPECVOL_COEFFICIENTS::c300, GSW_SPECVOL_COEFFICIENTS::c301, GSW_SPECVOL_COEFFICIENTS::c310, GSW_SPECVOL_COEFFICIENTS::c311, GSW_SPECVOL_COEFFICIENTS::c320, GSW_SPECVOL_COEFFICIENTS::c400, GSW_SPECVOL_COEFFICIENTS::c401, GSW_SPECVOL_COEFFICIENTS::c410, GSW_SPECVOL_COEFFICIENTS::c500, gsvco.
Referenced by gsw_kappa, TeosSea::gsw_rho_first_derivatives, TeosSea::gsw_sound_speed, TeosSea::gsw_specvol_first_derivatives.
double TeosBase::gsw_gsvco_v(double xs, double ys, double z)
References gsvco, GSW_SPECVOL_COEFFICIENTS::v000, GSW_SPECVOL_COEFFICIENTS::v001, GSW_SPECVOL_COEFFICIENTS::v002, GSW_SPECVOL_COEFFICIENTS::v003, GSW_SPECVOL_COEFFICIENTS::v004, GSW_SPECVOL_COEFFICIENTS::v005, GSW_SPECVOL_COEFFICIENTS::v006, GSW_SPECVOL_COEFFICIENTS::v010, GSW_SPECVOL_COEFFICIENTS::v011, GSW_SPECVOL_COEFFICIENTS::v012, GSW_SPECVOL_COEFFICIENTS::v013, GSW_SPECVOL_COEFFICIENTS::v014, GSW_SPECVOL_COEFFICIENTS::v020, GSW_SPECVOL_COEFFICIENTS::v021, GSW_SPECVOL_COEFFICIENTS::v022, GSW_SPECVOL_COEFFICIENTS::v023, GSW_SPECVOL_COEFFICIENTS::v030, GSW_SPECVOL_COEFFICIENTS::v031, GSW_SPECVOL_COEFFICIENTS::v032, GSW_SPECVOL_COEFFICIENTS::v040, GSW_SPECVOL_COEFFICIENTS::v041, GSW_SPECVOL_COEFFICIENTS::v042, GSW_SPECVOL_COEFFICIENTS::v050, GSW_SPECVOL_COEFFICIENTS::v051, GSW_SPECVOL_COEFFICIENTS::v060, GSW_SPECVOL_COEFFICIENTS::v100, GSW_SPECVOL_COEFFICIENTS::v101, GSW_SPECVOL_COEFFICIENTS::v102, GSW_SPECVOL_COEFFICIENTS::v103, GSW_SPECVOL_COEFFICIENTS::v104, GSW_SPECVOL_COEFFICIENTS::v110, GSW_SPECVOL_COEFFICIENTS::v111, GSW_SPECVOL_COEFFICIENTS::v112, GSW_SPECVOL_COEFFICIENTS::v113, GSW_SPECVOL_COEFFICIENTS::v120, GSW_SPECVOL_COEFFICIENTS::v121, GSW_SPECVOL_COEFFICIENTS::v122, GSW_SPECVOL_COEFFICIENTS::v130, GSW_SPECVOL_COEFFICIENTS::v131, GSW_SPECVOL_COEFFICIENTS::v132, GSW_SPECVOL_COEFFICIENTS::v140, GSW_SPECVOL_COEFFICIENTS::v141, GSW_SPECVOL_COEFFICIENTS::v150, GSW_SPECVOL_COEFFICIENTS::v200, GSW_SPECVOL_COEFFICIENTS::v201, GSW_SPECVOL_COEFFICIENTS::v202, GSW_SPECVOL_COEFFICIENTS::v203, GSW_SPECVOL_COEFFICIENTS::v210, GSW_SPECVOL_COEFFICIENTS::v211, GSW_SPECVOL_COEFFICIENTS::v212, GSW_SPECVOL_COEFFICIENTS::v220, GSW_SPECVOL_COEFFICIENTS::v221, GSW_SPECVOL_COEFFICIENTS::v222, GSW_SPECVOL_COEFFICIENTS::v230, GSW_SPECVOL_COEFFICIENTS::v231, GSW_SPECVOL_COEFFICIENTS::v240, GSW_SPECVOL_COEFFICIENTS::v300, GSW_SPECVOL_COEFFICIENTS::v301, GSW_SPECVOL_COEFFICIENTS::v302, GSW_SPECVOL_COEFFICIENTS::v310, GSW_SPECVOL_COEFFICIENTS::v311, GSW_SPECVOL_COEFFICIENTS::v312, GSW_SPECVOL_COEFFICIENTS::v320, GSW_SPECVOL_COEFFICIENTS::v321, GSW_SPECVOL_COEFFICIENTS::v330, GSW_SPECVOL_COEFFICIENTS::v400, GSW_SPECVOL_COEFFICIENTS::v401, GSW_SPECVOL_COEFFICIENTS::v402, GSW_SPECVOL_COEFFICIENTS::v410, GSW_SPECVOL_COEFFICIENTS::v411, GSW_SPECVOL_COEFFICIENTS::v420, GSW_SPECVOL_COEFFICIENTS::v500, GSW_SPECVOL_COEFFICIENTS::v501, GSW_SPECVOL_COEFFICIENTS::v510, GSW_SPECVOL_COEFFICIENTS::v600.
Referenced by gsw_kappa, gsw_rho_alpha_beta, TeosSea::gsw_rho_first_derivatives, TeosSea::gsw_sound_speed, gsw_specvol, TeosSea::gsw_specvol_alpha_beta.
double TeosBase::gsw_max_d(double a, double b)
Referenced by gsw_deltasa_atlas, TeosIce::gsw_pt_from_pot_enthalpy_ice, TeosIce::gsw_sa_freezing_estimate, TeosIce::gsw_sa_freezing_from_ct, TeosIce::gsw_sa_freezing_from_ct_poly, TeosIce::gsw_sa_freezing_from_t, TeosIce::gsw_sa_freezing_from_t_poly, gsw_saar.
double TeosBase::gsw_min_d(double a, double b)
Referenced by TeosIce::gsw_frazil_properties.
double TeosBase::gsw_get_pot_ent(double x2, double x, double y)
Referenced by gsw_ct_from_pt.
unsigned TeosBase::gsw_max_u(unsigned a, unsigned b)
unsigned TeosBase::gsw_min_u(unsigned a, unsigned b)
int TeosBase::gsw_max_i(int a, int b)
int TeosBase::gsw_min_i(int a, int b)
int TeosBase::gsw_util_indxPref(int n, double z)
References SaarDataHandler::get_p_ref, pSaarData.
Referenced by gsw_deltasa_atlas, gsw_saar.
double TeosBase::gsw_get_dyn_enth_prt(double xs, double ys, double z)
References gsvco, GSW_SPECVOL_COEFFICIENTS::h001, GSW_SPECVOL_COEFFICIENTS::h002, GSW_SPECVOL_COEFFICIENTS::h003, GSW_SPECVOL_COEFFICIENTS::h004, GSW_SPECVOL_COEFFICIENTS::h005, GSW_SPECVOL_COEFFICIENTS::h006, GSW_SPECVOL_COEFFICIENTS::h007, GSW_SPECVOL_COEFFICIENTS::h011, GSW_SPECVOL_COEFFICIENTS::h012, GSW_SPECVOL_COEFFICIENTS::h013, GSW_SPECVOL_COEFFICIENTS::h014, GSW_SPECVOL_COEFFICIENTS::h015, GSW_SPECVOL_COEFFICIENTS::h021, GSW_SPECVOL_COEFFICIENTS::h022, GSW_SPECVOL_COEFFICIENTS::h023, GSW_SPECVOL_COEFFICIENTS::h024, GSW_SPECVOL_COEFFICIENTS::h031, GSW_SPECVOL_COEFFICIENTS::h032, GSW_SPECVOL_COEFFICIENTS::h033, GSW_SPECVOL_COEFFICIENTS::h041, GSW_SPECVOL_COEFFICIENTS::h042, GSW_SPECVOL_COEFFICIENTS::h043, GSW_SPECVOL_COEFFICIENTS::h051, GSW_SPECVOL_COEFFICIENTS::h052, GSW_SPECVOL_COEFFICIENTS::h061, GSW_SPECVOL_COEFFICIENTS::h101, GSW_SPECVOL_COEFFICIENTS::h102, GSW_SPECVOL_COEFFICIENTS::h103, GSW_SPECVOL_COEFFICIENTS::h104, GSW_SPECVOL_COEFFICIENTS::h105, GSW_SPECVOL_COEFFICIENTS::h111, GSW_SPECVOL_COEFFICIENTS::h112, GSW_SPECVOL_COEFFICIENTS::h113, GSW_SPECVOL_COEFFICIENTS::h114, GSW_SPECVOL_COEFFICIENTS::h121, GSW_SPECVOL_COEFFICIENTS::h122, GSW_SPECVOL_COEFFICIENTS::h123, GSW_SPECVOL_COEFFICIENTS::h131, GSW_SPECVOL_COEFFICIENTS::h132, GSW_SPECVOL_COEFFICIENTS::h133, GSW_SPECVOL_COEFFICIENTS::h141, GSW_SPECVOL_COEFFICIENTS::h142, GSW_SPECVOL_COEFFICIENTS::h151, GSW_SPECVOL_COEFFICIENTS::h201, GSW_SPECVOL_COEFFICIENTS::h202, GSW_SPECVOL_COEFFICIENTS::h203, GSW_SPECVOL_COEFFICIENTS::h204, GSW_SPECVOL_COEFFICIENTS::h211, GSW_SPECVOL_COEFFICIENTS::h212, GSW_SPECVOL_COEFFICIENTS::h213, GSW_SPECVOL_COEFFICIENTS::h221, GSW_SPECVOL_COEFFICIENTS::h222, GSW_SPECVOL_COEFFICIENTS::h223, GSW_SPECVOL_COEFFICIENTS::h231, GSW_SPECVOL_COEFFICIENTS::h232, GSW_SPECVOL_COEFFICIENTS::h241, GSW_SPECVOL_COEFFICIENTS::h301, GSW_SPECVOL_COEFFICIENTS::h302, GSW_SPECVOL_COEFFICIENTS::h303, GSW_SPECVOL_COEFFICIENTS::h311, GSW_SPECVOL_COEFFICIENTS::h312, GSW_SPECVOL_COEFFICIENTS::h313, GSW_SPECVOL_COEFFICIENTS::h321, GSW_SPECVOL_COEFFICIENTS::h322, GSW_SPECVOL_COEFFICIENTS::h331, GSW_SPECVOL_COEFFICIENTS::h401, GSW_SPECVOL_COEFFICIENTS::h402, GSW_SPECVOL_COEFFICIENTS::h403, GSW_SPECVOL_COEFFICIENTS::h411, GSW_SPECVOL_COEFFICIENTS::h412, GSW_SPECVOL_COEFFICIENTS::h421, GSW_SPECVOL_COEFFICIENTS::h501, GSW_SPECVOL_COEFFICIENTS::h502, GSW_SPECVOL_COEFFICIENTS::h511, GSW_SPECVOL_COEFFICIENTS::h601.
Referenced by gsw_dynamic_enthalpy.
double TeosBase::gsw_get_g03plusg08(double z, double y, double x2, double x)
Referenced by gsw_entropy_part.
double TeosBase::gsw_get_g03plusg08_h(double z, double y, double x2, double x)
Referenced by gsw_chem_potential_water_t_exact.
double TeosBase::gsw_get_v_ct_part(double xs, double ys, double z)
References gsw_gsvco_a.
Referenced by gsw_alpha.
double TeosBase::gsw_gibbs_g03plusg08_a(double sa, double z, double y, double x2, double x)
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g03plusg08_b(double sa, double z, double y, double x2, double x)
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g03plusg08_c(double z, double y, double x2, double x)
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g03plusg08_d(double z, double y, double x2, double x)
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g03plusg08_e(double z, double y, double x2, double x)
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g03plusg08_f(double z, double y, double x2, double x)
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g03plusg08_g(double z, double y, double x2, double x)
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g08_a(double sa, double z, double y, double x)
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g08_b(double z, double y, double x)
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by gsw_gibbs.
double TeosBase::gsw_gibbs_g08_c(double sa, double z, double y, double x)
References GSW_TEOS10_CONSTANTS::gsw_sfac, gtc.
Referenced by gsw_gibbs.
double TeosBase::gsw_g08_d(double x2, double z, double y, double x)
Referenced by gsw_dilution_coefficient_t_exact.