TemperatureFilterNode
size_t TemperatureFilterNode::filter_window_size_
Referenced by init_parameters, temperature_callback.
size_t TemperatureFilterNode::filter_median_remove_side_samples_
Referenced by compute_filter, init_parameters.
deque<double> TemperatureFilterNode::temperature_memory_
Variable.
Referenced by temperature_callback.
rclcpp::Subscription<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr TemperatureFilterNode::subscriber_temperature_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr TemperatureFilterNode::publisher_temperature_data_
Referenced by init_interfaces, temperature_callback.
TemperatureFilterNode::TemperatureFilterNode()
References init_interfaces, init_parameters.
void TemperatureFilterNode::init_parameters()
Functions.
Init and get parameters of the Node
References filter_median_remove_side_samples_, filter_window_size_.
Referenced by TemperatureFilterNode.
void TemperatureFilterNode::init_interfaces()
Init interfaces of this node
References publisher_temperature_data_, subscriber_temperature_data_, temperature_callback.
Referenced by TemperatureFilterNode.
void TemperatureFilterNode::temperature_callback(const seabot2_msgs::msg::TemperatureSensorData &msg)
Callback of the external pressure msg
References compute_filter, filter_window_size_, publisher_temperature_data_, temperature_memory_.
Referenced by init_interfaces.
double TemperatureFilterNode::compute_filter(deque< double > queue) const
Compute the median and mean filter queue
References filter_median_remove_side_samples_.
Referenced by temperature_callback.