KalmanNode
rclcpp::TimerBase::SharedPtr KalmanNode::timer_
Variable Rclcpp
std::chrono::milliseconds KalmanNode::loop_dt_
Referenced by init_parameters.
Kalman KalmanNode::k_
loop dt
Referenced by density_callback, depth_callback, init_parameters, publish_data, state_callback, temperature_callback.
rclcpp::Subscription<seabot2_msgs::msg::DepthPose>::SharedPtr KalmanNode::subscriber_depth_data_
Interfaces.
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::PistonState>::SharedPtr KalmanNode::subscriber_state_data_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::Density>::SharedPtr KalmanNode::subscriber_density_
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr KalmanNode::subscriber_temperature_
Referenced by init_interfaces.
rclcpp::Publisher<seabot2_msgs::msg::KalmanState>::SharedPtr KalmanNode::publisher_kalman_
Referenced by init_interfaces, publish_data.
KalmanNode::KalmanNode()
References init_interfaces, init_parameters.
void KalmanNode::init_parameters()
Functions.
Init and get parameters of the Node
References Kalman::enable_kalman_depth_, Kalman::gamma_alpha_chi2_, Kalman::gamma_alpha_chi_, Kalman::gamma_alpha_cz_, Kalman::gamma_alpha_depth_, Kalman::gamma_alpha_offset_, Kalman::gamma_alpha_velocity_, Kalman::gamma_alpha_volume_air_, Kalman::gamma_beta_depth_, Kalman::gamma_init_chi2_, Kalman::gamma_init_chi_, Kalman::gamma_init_cz_, Kalman::gamma_init_depth_, Kalman::gamma_init_offset_, Kalman::gamma_init_velocity_, Kalman::gamma_init_volume_air_, Kalman::init_chi2_, Kalman::init_chi_, Kalman::init_cz_, Kalman::init_parameters, Kalman::init_volume_air_, k_, loop_dt_, Kalman::physics_g_, Kalman::physics_rho_, Kalman::piston_diameter_, Kalman::piston_max_tick_, Kalman::piston_volume_eq_init_, Kalman::pressure_, Kalman::robot_diameter_, Kalman::robot_mass_, Kalman::screw_thread_, Kalman::temperature_, Kalman::tick_per_turn_.
Referenced by KalmanNode.
void KalmanNode::init_interfaces()
Init interfaces of this node
References density_callback, depth_callback, publisher_kalman_, state_callback, subscriber_density_, subscriber_depth_data_, subscriber_state_data_, subscriber_temperature_, temperature_callback.
Referenced by KalmanNode.
void KalmanNode::state_callback(const seabot2_msgs::msg::PistonState &msg)
msg
References k_, Kalman::set_new_piston_data.
Referenced by init_interfaces.
void KalmanNode::depth_callback(const seabot2_msgs::msg::DepthPose &msg)
msg
References k_, publish_data, Kalman::set_new_depth_data, Kalman::update_pressure.
Referenced by init_interfaces.
void KalmanNode::density_callback(const seabot2_msgs::msg::Density &msg)
msg
References k_, Kalman::update_density.
Referenced by init_interfaces.
void KalmanNode::pressure_callback(const seabot2_msgs::msg::PressureSensorData &msg)
msg
void KalmanNode::temperature_callback(const seabot2_msgs::msg::TemperatureSensorData &msg)
msg
References k_, Kalman::update_temperature.
Referenced by init_interfaces.
void KalmanNode::publish_data()
References Kalman::gamma_forcast_, Kalman::is_valid_, k_, Kalman::offset_total_, publisher_kalman_, Kalman::time_last_predict_, Kalman::x_forcast_.
Referenced by depth_callback.