MissionNode
rclcpp::TimerBase::SharedPtr MissionNode::timer_
rclcpp timer
Referenced by MissionNode.
std::chrono::milliseconds MissionNode::loop_dt_
loop dt (ms)
Referenced by init_parameters, MissionNode.
rclcpp::CallbackGroup::SharedPtr MissionNode::callback_group_
Reentrant callback group to avoid deadlocks between synchronous service calls.
Referenced by init_interfaces, MissionNode.
Mission MissionNode::mission_
Mission manager.
Referenced by depth_callback, init_parameters, load_mission, MissionNode, temperature_callback, timer_callback.
std::string MissionNode::mission_file_name_
Referenced by init_parameters, load_mission, MissionNode, timer_callback.
std::string MissionNode::mission_path_
Referenced by init_parameters, load_mission, MissionNode, timer_callback.
double MissionNode::flash_next_waypoint_time_
Flash signal duration when a new waypoint is targeted.
Referenced by call_light, init_parameters.
int MissionNode::flash_number_
Number of flashes in the pattern when a new waypoint is targeted.
Referenced by call_light, init_parameters.
double MissionNode::limit_velocity_default_
Referenced by init_parameters.
rclcpp::Publisher<seabot2_msgs::msg::MissionState>::SharedPtr MissionNode::publisher_mission_state_
Publishes MissionState msgs on the /mission/mission_state topic.
Referenced by init_interfaces, timer_callback.
rclcpp::Publisher<seabot2_msgs::msg::DepthControlSetPoint>::SharedPtr MissionNode::publisher_depth_control_set_point_
Publishes DepthControlSetPoint msgs on the /mission/depth_control_set_point topic.
Referenced by init_interfaces, timer_callback.
rclcpp::Publisher<seabot2_msgs::msg::TemperatureKeepingDebug>::SharedPtr MissionNode::publisher_temperature_keeping_debug_
Publishes TemperatureKeepingDebug msgs on the /mission/temperature_keeping_debug topic.
Referenced by init_interfaces, timer_callback.
rclcpp::Subscription<seabot2_msgs::msg::DepthPose>::SharedPtr MissionNode::subscriber_depth_data_
Subscribes to DepthPose msgs from the /observer/depth topic.
Referenced by init_interfaces.
rclcpp::Subscription<seabot2_msgs::msg::TemperatureSensorData>::SharedPtr MissionNode::subscriber_temperature_data_
Subscribes to DepthPose msgs from the /observer/temperature topic.
Referenced by init_interfaces.
rclcpp::Client<seabot2_srvs::srv::Light>::SharedPtr MissionNode::client_light_
Client for the /driver/light service.
Referenced by call_light, init_interfaces.
rclcpp::Client<std_srvs::srv::Trigger>::SharedPtr MissionNode::client_log_parameters_
Client for the /observer/log_parameters service.
Referenced by call_log_params, init_interfaces.
rclcpp::Client<std_srvs::srv::Trigger>::SharedPtr MissionNode::client_bag_recorder_
Client for the /observer/restart_bag service.
Referenced by call_restart_bag, init_interfaces.
rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr MissionNode::service_mission_reload_
Service /mission/mission_reload.
Referenced by init_interfaces.
MissionNode::MissionNode()
Construct a new Mission Node object.
References callback_group_, init_interfaces, init_parameters, Mission::is_new_mission_file, load_mission, loop_dt_, mission_, mission_file_name_, mission_path_, timer_, timer_callback.
void MissionNode::init_parameters()
Init and get parameters of the Node.
References flash_next_waypoint_time_, flash_number_, limit_velocity_default_, loop_dt_, mission_, mission_file_name_, mission_path_, Mission::temperature_keeping_k_.
Referenced by MissionNode.
void MissionNode::init_interfaces()
Init interfaces of this node.
References callback_group_, client_bag_recorder_, client_light_, client_log_parameters_, depth_callback, publisher_depth_control_set_point_, publisher_mission_state_, publisher_temperature_keeping_debug_, service_mission_reload_, service_mission_reload_callback, subscriber_depth_data_, subscriber_temperature_data_, temperature_callback.
Referenced by MissionNode.
void MissionNode::timer_callback()
Executes a step of the mission management process and publish depth control setpoint.
References call_light, Mission::get_current_waypoint_id, Mission::get_current_waypoint_temperature_keeping, Mission::get_depth_control_set_point, Mission::get_mission_mode, Mission::get_mission_state, Mission::get_number_waypoints, Mission::get_time_to_next_waypoint, Mission::is_current_waypoint_of_type, Mission::is_new_mission_file, load_mission, mission_, mission_file_name_, mission_path_, publisher_depth_control_set_point_, publisher_mission_state_, publisher_temperature_keeping_debug_, Mission::update_state, Mission::WP_TEMPERATURE_KEEPING.
Referenced by MissionNode.
void MissionNode::depth_callback(const seabot2_msgs::msg::DepthPose::SharedPtr msg)
Updates depth.
msg
References mission_, Mission::update_depth.
Referenced by init_interfaces.
void MissionNode::temperature_callback(const seabot2_msgs::msg::TemperatureSensorData::SharedPtr msg)
Updates temperature.
msg
References mission_, Mission::update_temperature.
Referenced by init_interfaces.
void MissionNode::service_mission_reload_callback(const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< std_srvs::srv::Trigger::Request > request, std::shared_ptr< std_srvs::srv::Trigger::Response > response)
request_header request response
References load_mission.
Referenced by init_interfaces.
void MissionNode::call_light()
Calls light service.
References client_light_, flash_next_waypoint_time_, flash_number_.
Referenced by timer_callback.
void MissionNode::call_log_params() const
Calls log params service.
References client_log_parameters_.
Referenced by load_mission.
void MissionNode::call_restart_bag() const
Calls restart bag.
References client_bag_recorder_.
Referenced by load_mission.
int MissionNode::load_mission()
Restarts rosbag and loads the mission from the mission file.
Also calls for log of parameters EXIT_SUCCESS if mission has been loaded correctly, EXIT_FAILURE otherwise
References call_log_params, call_restart_bag, Mission::load_mission, mission_, mission_file_name_, mission_path_.
Referenced by MissionNode, service_mission_reload_callback, timer_callback.