FusionMath.h
FUSION_VECTOR_ZERO
Vector of zeros.
FUSION_VECTOR_ONES
Vector of ones.
FUSION_IDENTITY_QUATERNION
Identity quaternion.
FUSION_IDENTITY_MATRIX
Identity matrix.
FUSION_EULER_ZERO
Euler angles of zero.
M_PI
Pi. May not be defined in math.h.
A
B
A
B
Q
V
Q
R
Q
Q
static float FusionDegreesToRadians(const float degrees)
Include this definition or add as a preprocessor definition to use normal square root operations.
Converts degrees to radians. degrees Degrees. Radians.
References M_PI.
Referenced by FusionAhrsSetHeading, FusionAhrsSetSettings, FusionAhrsUpdate, FusionAhrsUpdateExternalHeading.
static float FusionRadiansToDegrees(const float radians)
Converts radians to degrees.
radians Radians. Degrees.
References M_PI.
Referenced by FusionAhrsGetInternalStates, FusionCompassCalculateHeading, FusionQuaternionToEuler.
static float FusionAsin(const float value)
Returns the arc sine of the value.
value Value. Arc sine of the value.
References M_PI.
Referenced by FusionAhrsGetInternalStates, FusionQuaternionToEuler.
static float FusionFastInverseSqrt(const float x)
Calculates the reciprocal of the square root. See https://pizer.wordpress.com/2008/10/12/fast-inverse-square-root/.
x Operand. Reciprocal of the square root of x.
Referenced by FusionQuaternionNormalise, FusionVectorNormalise.
static bool FusionVectorIsZero(const FusionVector vector)
Returns true if the vector is zero.
vector Vector. True if the vector is zero.
References FusionVector::axis, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by FusionAhrsUpdate.
static FusionVector FusionVectorAdd(const FusionVector vectorA, const FusionVector vectorB)
Returns the sum of two vectors.
vectorA Vector A. vectorB Vector B. Sum of two vectors.
References FusionVector::axis, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by FusionAhrsGetLinearAcceleration, FusionAhrsUpdate, FusionOffsetUpdate.
static FusionVector FusionVectorSubtract(const FusionVector vectorA, const FusionVector vectorB)
Returns vector B subtracted from vector A.
vectorA Vector A. vectorB Vector B. Vector B subtracted from vector A.
References FusionVector::axis, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by FusionAhrsGetLinearAcceleration, FusionCalibrationInertial, FusionCalibrationMagnetic, FusionOffsetUpdate.
static float FusionVectorSum(const FusionVector vector)
Returns the sum of the elements.
vector Vector. Sum of the elements.
References FusionVector::axis, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by FusionVectorDotProduct, FusionVectorMagnitudeSquared.
static FusionVector FusionVectorMultiplyScalar(const FusionVector vector, const float scalar)
Returns the multiplication of a vector by a scalar.
vector Vector. scalar Scalar. Multiplication of a vector by a scalar.
References FusionVector::axis, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by FusionAhrsUpdate, FusionCompassCalculateHeading, FusionOffsetUpdate, FusionVectorNormalise.
static FusionVector FusionVectorHadamardProduct(const FusionVector vectorA, const FusionVector vectorB)
Calculates the Hadamard product (element-wise multiplication).
vectorA Vector A. vectorB Vector B. Hadamard product.
References FusionVector::axis, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by FusionCalibrationInertial, FusionVectorDotProduct, FusionVectorMagnitudeSquared.
static FusionVector FusionVectorCrossProduct(const FusionVector vectorA, const FusionVector vectorB)
Returns the cross product.
vectorA Vector A. vectorB Vector B. Cross product.
References A, FusionVector::axis, B, FusionVector::x.
Referenced by Feedback, FusionAhrsUpdate, FusionCompassCalculateHeading.
static float FusionVectorDotProduct(const FusionVector vectorA, const FusionVector vectorB)
Returns the dot product.
vectorA Vector A. vectorB Vector B. Dot product.
References FusionVectorHadamardProduct, FusionVectorSum.
Referenced by Feedback.
static float FusionVectorMagnitudeSquared(const FusionVector vector)
Returns the vector magnitude squared.
vector Vector. Vector magnitude squared.
References FusionVectorHadamardProduct, FusionVectorSum.
Referenced by FusionAhrsUpdate, FusionVectorMagnitude, FusionVectorNormalise.
static float FusionVectorMagnitude(const FusionVector vector)
Returns the vector magnitude.
vector Vector. Vector magnitude.
References FusionVectorMagnitudeSquared.
Referenced by FusionAhrsGetInternalStates.
static FusionVector FusionVectorNormalise(const FusionVector vector)
Returns the normalised vector.
vector Vector. Normalised vector.
References FusionFastInverseSqrt, FusionVectorMagnitudeSquared, FusionVectorMultiplyScalar.
Referenced by Feedback, FusionAhrsUpdate, FusionCompassCalculateHeading.
static FusionQuaternion FusionQuaternionAdd(const FusionQuaternion quaternionA, const FusionQuaternion quaternionB)
Returns the sum of two quaternions.
quaternionA Quaternion A. quaternionB Quaternion B. Sum of two quaternions.
References FusionQuaternion::element, FusionQuaternion::w, FusionQuaternion::x, FusionQuaternion::y, FusionQuaternion::z.
Referenced by FusionAhrsUpdate.
static FusionQuaternion FusionQuaternionMultiply(const FusionQuaternion quaternionA, const FusionQuaternion quaternionB)
Returns the multiplication of two quaternions.
quaternionA Quaternion A (to be post-multiplied). quaternionB Quaternion B (to be pre-multiplied). Multiplication of two quaternions.
References A, B, FusionQuaternion::element, FusionQuaternion::w.
Referenced by FusionAhrsSetHeading.
static FusionQuaternion FusionQuaternionMultiplyVector(const FusionQuaternion quaternion, const FusionVector vector)
Returns the multiplication of a quaternion with a vector. This is a normal quaternion multiplication where the vector is treated a quaternion with a W element value of zero. The quaternion is post- multiplied by the vector.
quaternion Quaternion. vector Vector. Multiplication of a quaternion with a vector.
References FusionQuaternion::element, Q, V, FusionQuaternion::w.
Referenced by FusionAhrsUpdate.
static FusionQuaternion FusionQuaternionNormalise(const FusionQuaternion quaternion)
Returns the normalised quaternion.
quaternion Quaternion. Normalised quaternion.
References FusionQuaternion::element, FusionFastInverseSqrt, Q, FusionQuaternion::w.
Referenced by FusionAhrsUpdate.
static FusionVector FusionMatrixMultiplyVector(const FusionMatrix matrix, const FusionVector vector)
Returns the multiplication of a matrix with a vector.
matrix Matrix. vector Vector. Multiplication of a matrix with a vector.
References FusionVector::axis, R, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by FusionCalibrationInertial, FusionCalibrationMagnetic.
static FusionMatrix FusionQuaternionToMatrix(const FusionQuaternion quaternion)
Converts a quaternion to a rotation matrix.
quaternion Quaternion. Rotation matrix.
References FusionMatrix::element, Q, FusionMatrix::xx.
static FusionEuler FusionQuaternionToEuler(const FusionQuaternion quaternion)
Converts a quaternion to ZYX Euler angles in degrees.
quaternion Quaternion. Euler angles in degrees.
References FusionEuler::angle, FusionAsin, FusionRadiansToDegrees, Q, FusionEuler::roll.
Referenced by ICM20948Node::compute_ahrs.