FusionConverter.h
static FusionVector FusionVectorFromStdVector(const std::vector< double > &vector)
Converts a std::vector to a FusionVector.
vector Vector. FusionVector.
References FusionVector::axis, FusionVector::x.
Referenced by ICM20948Node::init_parameters.
static FusionMatrix FusionMatrixFromStdVector(const std::vector< double > &matrix)
Converts a std::vector to a FusionQuaternion.
matrix
References FusionMatrix::element, FusionMatrix::xx.
Referenced by ICM20948Node::init_parameters.
static FusionQuaternion FusionQuaternionFromStdVector(const std::vector< double > &quaternion)
Converts a std::vector to a FusionQuaternion.
quaternion
References FusionQuaternion::element, FusionQuaternion::w.
static FusionEuler FusionEulerFromStdVector(const std::vector< double > &euler)
Converts a std::vector to a FusionEuler.
euler
References FusionEuler::angle, FusionEuler::roll.
static std::vector< double > FusionVectorToStdVector(const FusionVector &vector)
Converts a FusionVector to a std::vector.
vector Vector. std::vector.
References FusionVector::axis, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by ICM20948Node::init_parameters.
static std::vector< double > FusionMatrixToStdVector(const FusionMatrix &matrix)
Converts a FusionMatrix to a std::vector.
matrix
References FusionMatrix::element, FusionMatrix::xx, FusionMatrix::xy, FusionMatrix::xz, FusionMatrix::yx, FusionMatrix::yy, FusionMatrix::yz, FusionMatrix::zx, FusionMatrix::zy, FusionMatrix::zz.
Referenced by ICM20948Node::init_parameters.
static std::vector< double > FusionQuaternionToStdVector(const FusionQuaternion &quaternion)
Converts a FusionQuaternion to a std::vector.
quaternion
References FusionQuaternion::element, FusionQuaternion::w, FusionQuaternion::x, FusionQuaternion::y, FusionQuaternion::z.
static std::vector< double > FusionEulerToStdVector(const FusionEuler &euler)
Converts a FusionEuler to a std::vector.
euler
References FusionEuler::angle, FusionEuler::pitch, FusionEuler::roll, FusionEuler::yaw.