FusionAhrs.h
void FusionAhrsInitialise(FusionAhrs *const ahrs)
Initialises the AHRS algorithm structure.
ahrs AHRS algorithm structure.
References FusionAhrsSettings::convention, FusionAhrsReset, FusionAhrsSetSettings, FusionConventionNwu.
Referenced by ICM20948Node::init_parameters.
void FusionAhrsReset(FusionAhrs *const ahrs)
Resets the AHRS algorithm. This is equivalent to reinitialising the algorithm while maintaining the current settings.
ahrs AHRS algorithm structure.
References FusionAhrs::accelerationRecoveryTimeout, FusionAhrs::accelerationRecoveryTrigger, FusionAhrs::accelerometer, FusionAhrs::accelerometerIgnored, FusionAhrs::angularRateRecovery, FUSION_IDENTITY_QUATERNION, FUSION_VECTOR_ZERO, FusionAhrs::halfAccelerometerFeedback, FusionAhrs::halfMagnetometerFeedback, INITIAL_GAIN, FusionAhrs::initialising, FusionAhrs::magneticRecoveryTimeout, FusionAhrs::magneticRecoveryTrigger, FusionAhrs::magnetometerIgnored, FusionAhrs::quaternion, FusionAhrs::rampedGain, FusionAhrsSettings::recoveryTriggerPeriod, FusionAhrs::settings.
Referenced by FusionAhrsInitialise, FusionAhrsUpdate.
void FusionAhrsSetSettings(FusionAhrs *const ahrs, const FusionAhrsSettings *const settings)
Sets the AHRS algorithm settings.
ahrs AHRS algorithm structure. settings Settings.
References FusionAhrs::accelerationRecoveryTimeout, FusionAhrsSettings::accelerationRejection, FusionAhrsSettings::convention, FusionDegreesToRadians, FusionAhrsSettings::gain, FusionAhrsSettings::gyroscopeRange, INITIAL_GAIN, INITIALISATION_PERIOD, FusionAhrs::initialising, FusionAhrs::magneticRecoveryTimeout, FusionAhrsSettings::magneticRejection, FusionAhrs::rampedGain, FusionAhrs::rampedGainStep, FusionAhrsSettings::recoveryTriggerPeriod, FusionAhrs::settings.
Referenced by FusionAhrsInitialise, ICM20948Node::init_parameters.
void FusionAhrsUpdate(FusionAhrs *const ahrs, const FusionVector gyroscope, const FusionVector accelerometer, const FusionVector magnetometer, const float deltaTime)
Updates the AHRS algorithm using the gyroscope, accelerometer, and magnetometer measurements.
ahrs AHRS algorithm structure. gyroscope Gyroscope measurement in degrees per second. accelerometer Accelerometer measurement in g. magnetometer Magnetometer measurement in arbitrary units. deltaTime Delta time in seconds.
References FusionAhrs::accelerationRecoveryTimeout, FusionAhrs::accelerationRecoveryTrigger, FusionAhrsSettings::accelerationRejection, FusionAhrs::accelerometer, FusionAhrs::accelerometerIgnored, FusionAhrs::angularRateRecovery, FusionVector::axis, Clamp, Feedback, FUSION_VECTOR_ZERO, FusionAhrsReset, FusionDegreesToRadians, FusionQuaternionAdd, FusionQuaternionMultiplyVector, FusionQuaternionNormalise, FusionVectorAdd, FusionVectorCrossProduct, FusionVectorIsZero, FusionVectorMagnitudeSquared, FusionVectorMultiplyScalar, FusionVectorNormalise, FusionAhrsSettings::gain, FusionAhrsSettings::gyroscopeRange, FusionAhrs::halfAccelerometerFeedback, HalfGravity, HalfMagnetic, FusionAhrs::halfMagnetometerFeedback, FusionAhrs::initialising, FusionAhrs::magneticRecoveryTimeout, FusionAhrs::magneticRecoveryTrigger, FusionAhrsSettings::magneticRejection, FusionAhrs::magnetometerIgnored, FusionAhrs::quaternion, FusionAhrs::rampedGain, FusionAhrs::rampedGainStep, FusionAhrsSettings::recoveryTriggerPeriod, FusionAhrs::settings, FusionVector::x, FusionVector::y, FusionVector::z.
Referenced by ICM20948Node::compute_ahrs, FusionAhrsUpdateExternalHeading, FusionAhrsUpdateNoMagnetometer.
void FusionAhrsUpdateNoMagnetometer(FusionAhrs *const ahrs, const FusionVector gyroscope, const FusionVector accelerometer, const float deltaTime)
Updates the AHRS algorithm using the gyroscope and accelerometer measurements only.
ahrs AHRS algorithm structure. gyroscope Gyroscope measurement in degrees per second. accelerometer Accelerometer measurement in g. deltaTime Delta time in seconds.
References FUSION_VECTOR_ZERO, FusionAhrsSetHeading, FusionAhrsUpdate, FusionAhrs::initialising.
void FusionAhrsUpdateExternalHeading(FusionAhrs *const ahrs, const FusionVector gyroscope, const FusionVector accelerometer, const float heading, const float deltaTime)
Updates the AHRS algorithm using the gyroscope, accelerometer, and heading measurements.
ahrs AHRS algorithm structure. gyroscope Gyroscope measurement in degrees per second. accelerometer Accelerometer measurement in g. heading Heading measurement in degrees. deltaTime Delta time in seconds.
References FusionVector::axis, FusionAhrsUpdate, FusionDegreesToRadians, Q, FusionVector::x.
FusionQuaternion FusionAhrsGetQuaternion(const FusionAhrs *const ahrs)
Returns the quaternion describing the sensor relative to the Earth.
ahrs AHRS algorithm structure. Quaternion describing the sensor relative to the Earth.
References FusionAhrs::quaternion.
Referenced by ICM20948Node::compute_ahrs.
void FusionAhrsSetQuaternion(FusionAhrs *const ahrs, const FusionQuaternion quaternion)
Sets the quaternion describing the sensor relative to the Earth.
ahrs AHRS algorithm structure. quaternion Quaternion describing the sensor relative to the Earth.
References FusionAhrs::quaternion.
FusionVector FusionAhrsGetLinearAcceleration(const FusionAhrs *const ahrs)
Returns the linear acceleration measurement equal to the accelerometer measurement with the 1 g of gravity removed.
ahrs AHRS algorithm structure. Linear acceleration measurement in g.
References FusionAhrs::accelerometer, FusionVector::axis, FusionAhrsSettings::convention, FUSION_VECTOR_ZERO, FusionConventionEnu, FusionConventionNed, FusionConventionNwu, FusionVectorAdd, FusionVectorSubtract, Q, FusionAhrs::settings, FusionVector::x.
Referenced by ICM20948Node::compute_ahrs.
FusionVector FusionAhrsGetEarthAcceleration(const FusionAhrs *const ahrs)
Returns the Earth acceleration measurement equal to accelerometer measurement in the Earth coordinate frame with the 1 g of gravity removed.
ahrs AHRS algorithm structure. Earth acceleration measurement in g.
References A, FusionVector::axis, FusionAhrsSettings::convention, FusionConventionEnu, FusionConventionNed, FusionConventionNwu, Q, FusionAhrs::settings, FusionVector::x, FusionVector::z.
FusionAhrsInternalStates FusionAhrsGetInternalStates(const FusionAhrs *const ahrs)
Returns the AHRS algorithm internal states.
ahrs AHRS algorithm structure. AHRS algorithm internal states.
References FusionAhrsInternalStates::accelerationError, FusionAhrs::accelerationRecoveryTrigger, FusionAhrs::accelerometerIgnored, FusionAsin, FusionRadiansToDegrees, FusionVectorMagnitude, FusionAhrs::halfAccelerometerFeedback, FusionAhrs::halfMagnetometerFeedback, FusionAhrs::magneticRecoveryTrigger, FusionAhrs::magnetometerIgnored, FusionAhrsSettings::recoveryTriggerPeriod, FusionAhrs::settings.
Referenced by ICM20948Node::compute_ahrs.
FusionAhrsFlags FusionAhrsGetFlags(const FusionAhrs *const ahrs)
Returns the AHRS algorithm flags.
ahrs AHRS algorithm structure. AHRS algorithm flags.
References FusionAhrs::accelerationRecoveryTimeout, FusionAhrs::accelerationRecoveryTrigger, FusionAhrs::angularRateRecovery, FusionAhrs::initialising, FusionAhrsFlags::initialising, FusionAhrs::magneticRecoveryTimeout, FusionAhrs::magneticRecoveryTrigger.
Referenced by ICM20948Node::compute_ahrs.
void FusionAhrsSetHeading(FusionAhrs *const ahrs, const float heading)
Sets the heading of the orientation measurement provided by the AHRS algorithm. This function can be used to reset drift in heading when the AHRS algorithm is being used without a magnetometer.
ahrs AHRS algorithm structure. heading Heading angle in degrees.
References FusionQuaternion::element, FusionDegreesToRadians, FusionQuaternionMultiply, Q, FusionAhrs::quaternion, FusionQuaternion::w.
Referenced by FusionAhrsUpdateNoMagnetometer.