BME280
bme280_intf
SPI interface
typedef int8_t(* bme280_com_fptr_t) (uint8_t dev_id, uint8_t reg_addr, uint8_t *data, uint16_t len))(uint8_t dev_id, uint8_t reg_addr, uint8_t *data, uint16_t len)
Type definitions.
typedef void(* bme280_delay_fptr_t) (uint32_t period))(uint32_t period)
BME280_FILTER_COEFF_OFF
BME280_FILTER_COEFF_2
BME280_FILTER_COEFF_4
BME280_FILTER_COEFF_8
BME280_FILTER_COEFF_16
INT8_C
UINT8_C
INT16_C
UINT16_C
INT32_C
UINT32_C
INT64_C
UINT64_C
NULL
BME280_FLOAT_ENABLE
TRUE
FALSE
BME280_I2C_ADDR_PRIM
BME280_I2C_ADDR_SEC
BME280_CHIP_ID
BME280_CHIP_ID_ADDR
BME280_RESET_ADDR
BME280_TEMP_PRESS_CALIB_DATA_ADDR
BME280_HUMIDITY_CALIB_DATA_ADDR
BME280_PWR_CTRL_ADDR
BME280_CTRL_HUM_ADDR
BME280_CTRL_MEAS_ADDR
BME280_CONFIG_ADDR
BME280_DATA_ADDR
BME280_OK
BME280_E_NULL_PTR
BME280_E_DEV_NOT_FOUND
BME280_E_INVALID_LEN
BME280_E_COMM_FAIL
BME280_E_SLEEP_MODE_FAIL
BME280_W_INVALID_OSR_MACRO
BME280_TEMP_PRESS_CALIB_DATA_LEN
BME280_HUMIDITY_CALIB_DATA_LEN
BME280_P_T_H_DATA_LEN
BME280_SLEEP_MODE
BME280_FORCED_MODE
BME280_NORMAL_MODE
BME280_CONCAT_BYTES
BME280_SET_BITS
BME280_SET_BITS_POS_0
BME280_GET_BITS
BME280_GET_BITS_POS_0
BME280_SENSOR_MODE_MSK
BME280_SENSOR_MODE_POS
BME280_CTRL_HUM_MSK
BME280_CTRL_HUM_POS
BME280_CTRL_PRESS_MSK
BME280_CTRL_PRESS_POS
BME280_CTRL_TEMP_MSK
BME280_CTRL_TEMP_POS
BME280_FILTER_MSK
BME280_FILTER_POS
BME280_STANDBY_MSK
BME280_STANDBY_POS
BME280_PRESS
BME280_TEMP
BME280_HUM
BME280_ALL
BME280_OSR_PRESS_SEL
BME280_OSR_TEMP_SEL
BME280_OSR_HUM_SEL
BME280_FILTER_SEL
BME280_STANDBY_SEL
BME280_ALL_SETTINGS_SEL
BME280_NO_OVERSAMPLING
BME280_OVERSAMPLING_1X
BME280_OVERSAMPLING_2X
BME280_OVERSAMPLING_4X
BME280_OVERSAMPLING_8X
BME280_OVERSAMPLING_16X
BME280_STANDBY_TIME_1_MS
BME280_STANDBY_TIME_62_5_MS
BME280_STANDBY_TIME_125_MS
BME280_STANDBY_TIME_250_MS
BME280_STANDBY_TIME_500_MS
BME280_STANDBY_TIME_1000_MS
BME280_STANDBY_TIME_10_MS
BME280_STANDBY_TIME_20_MS
int8_t bme280_init(struct bme280_dev *dev)
This API is the entry point. It reads the chip-id and calibration data from the sensor.
CPP guard dev : Structure instance of bme280_dev Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_CHIP_ID, BME280_CHIP_ID_ADDR, BME280_E_DEV_NOT_FOUND, bme280_get_regs, BME280_OK, bme280_soft_reset, bme280_dev::chip_id, bme280_dev::delay_ms, get_calib_data, null_ptr_check.
Referenced by Bme280Node::sensor_init.
int8_t bme280_set_regs(uint8_t *reg_addr, const uint8_t *reg_data, uint8_t len, const struct bme280_dev *dev)
This API writes the given data to the register address of the sensor.
reg_addr : Register address from where the data to be written. reg_data : Pointer to data buffer which is to be written in the sensor. len : No of bytes of data to write.. dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_E_COMM_FAIL, BME280_E_INVALID_LEN, BME280_E_NULL_PTR, BME280_I2C_INTF, BME280_OK, bme280_dev::dev_id, interleave_reg_addr, bme280_dev::intf, NULL, null_ptr_check, bme280_dev::write.
Referenced by bme280_soft_reset, set_filter_standby_settings, set_osr_humidity_settings, set_osr_press_temp_settings, write_power_mode.
int8_t bme280_get_regs(uint8_t reg_addr, uint8_t *reg_data, uint16_t len, const struct bme280_dev *dev)
This API reads the data from the given register address of the sensor.
reg_addr : Register address from where the data to be read reg_data : Pointer to data buffer to store the read data. len : No of bytes of data to be read. dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_E_COMM_FAIL, BME280_I2C_INTF, BME280_OK, bme280_dev::dev_id, bme280_dev::intf, null_ptr_check, bme280_dev::read.
Referenced by bme280_get_sensor_data, bme280_get_sensor_mode, bme280_get_sensor_settings, bme280_init, get_calib_data, put_device_to_sleep, set_filter_standby_settings, set_osr_humidity_settings, set_osr_press_temp_settings, write_power_mode.
int8_t bme280_set_sensor_settings(uint8_t desired_settings, const struct bme280_dev *dev)
This API sets the oversampling, filter and standby duration (normal mode) settings in the sensor.
dev : Structure instance of bme280_dev. desired_settings : Variable used to select the settings which are to be set in the sensor. : Below are the macros to be used by the user for selecting the desired settings. User can do OR operation of these macros for configuring multiple settings. Macros Functionality BME280_OSR_PRESS_SEL To set pressure oversampling. BME280_OSR_TEMP_SEL To set temperature oversampling. BME280_OSR_HUM_SEL To set humidity oversampling. BME280_FILTER_SEL To set filter setting. BME280_STANDBY_SEL To set standby duration setting. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error.
References are_settings_changed, bme280_get_sensor_mode, BME280_OK, BME280_SLEEP_MODE, FILTER_STANDBY_SETTINGS, null_ptr_check, OVERSAMPLING_SETTINGS, put_device_to_sleep, set_filter_standby_settings, set_osr_settings, bme280_dev::settings.
Referenced by Bme280Node::sensor_init.
int8_t bme280_get_sensor_settings(struct bme280_dev *dev)
This API gets the oversampling, filter and standby duration (normal mode) settings from the sensor.
dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error.
References BME280_CTRL_HUM_ADDR, bme280_get_regs, BME280_OK, null_ptr_check, parse_device_settings, bme280_dev::settings.
int8_t bme280_set_sensor_mode(uint8_t sensor_mode, const struct bme280_dev *dev)
This API sets the power mode of the sensor.
dev : Structure instance of bme280_dev. sensor_mode : Variable which contains the power mode to be set. sensor_mode Macros 0 BME280_SLEEP_MODE 1 BME280_FORCED_MODE 3 BME280_NORMAL_MODE Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References bme280_get_sensor_mode, BME280_OK, BME280_SLEEP_MODE, null_ptr_check, put_device_to_sleep, write_power_mode.
Referenced by Bme280Node::sensor_init.
int8_t bme280_get_sensor_mode(uint8_t *sensor_mode, const struct bme280_dev *dev)
This API gets the power mode of the sensor.
dev : Structure instance of bme280_dev. sensor_mode : Pointer variable to store the power mode. sensor_mode Macros 0 BME280_SLEEP_MODE 1 BME280_FORCED_MODE 3 BME280_NORMAL_MODE Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References BME280_GET_BITS_POS_0, bme280_get_regs, BME280_OK, BME280_PWR_CTRL_ADDR, null_ptr_check.
Referenced by bme280_set_sensor_mode, bme280_set_sensor_settings, Bme280Node::print_sensor_mode.
int8_t bme280_soft_reset(const struct bme280_dev *dev)
This API performs the soft reset of the sensor.
dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error.
References BME280_OK, BME280_RESET_ADDR, bme280_set_regs, bme280_dev::delay_ms, null_ptr_check.
Referenced by bme280_init, put_device_to_sleep.
int8_t bme280_get_sensor_data(uint8_t sensor_comp, struct bme280_data *comp_data, struct bme280_dev *dev)
This API reads the pressure, temperature and humidity data from the sensor, compensates the data and store it in the bme280_data structure instance passed by the user.
sensor_comp : Variable which selects which data to be read from the sensor. sensor_comp Macros 1 BME280_PRESS 2 BME280_TEMP 4 BME280_HUM 7 BME280_ALL comp_data : Structure instance of bme280_data. dev : Structure instance of bme280_dev. Result of API execution status zero -> Success / +ve value -> Warning / -ve value -> Error
References bme280_compensate_data, BME280_DATA_ADDR, BME280_E_NULL_PTR, bme280_get_regs, BME280_OK, BME280_P_T_H_DATA_LEN, bme280_parse_sensor_data, bme280_dev::calib_data, NULL, null_ptr_check.
Referenced by Bme280Node::timer_callback.
void bme280_parse_sensor_data(const uint8_t *reg_data, struct bme280_uncomp_data *uncomp_data)
This API is used to parse the pressure, temperature and humidity data and store it in the bme280_uncomp_data structure instance.
reg_data : Contains register data which needs to be parsed uncomp_data : Contains the uncompensated pressure, temperature and humidity data.
References bme280_uncomp_data::humidity, bme280_uncomp_data::pressure, bme280_uncomp_data::temperature.
Referenced by bme280_get_sensor_data.
int8_t bme280_compensate_data(uint8_t sensor_comp, const struct bme280_uncomp_data *uncomp_data, struct bme280_data *comp_data, struct bme280_calib_data *calib_data)
This API is used to compensate the pressure and/or temperature and/or humidity data according to the component selected by the user.
sensor_comp : Used to select pressure and/or temperature and/or humidity. uncomp_data : Contains the uncompensated pressure, temperature and humidity data. comp_data : Contains the compensated pressure and/or temperature and/or humidity data. calib_data : Pointer to the calibration data structure. Result of API execution status. zero -> Success / -ve value -> Error
References BME280_E_NULL_PTR, BME280_HUM, BME280_OK, BME280_PRESS, BME280_TEMP, compensate_humidity, compensate_pressure, compensate_temperature, bme280_data::humidity, NULL, bme280_data::pressure, bme280_data::temperature.
Referenced by bme280_get_sensor_data.