xbee_driver::xbee
xbee_driver.xbee.serialize_data(data, val, nb_bit, start_bit, value_min=None, value_max=None, flag_debug=False)
Referenced by xbee_driver.xbee.XbeeNode.manual_velocity_callback, xbee_driver.xbee.XbeeNode.serialize_log_state.
xbee_driver.xbee.deserialize_data(data, nb_bit, start_bit, value_min=None, value_max=None)
Referenced by xbee_driver.xbee.XbeeNode.data_received_callback, xbee_driver.xbee.XbeeNode.deserialize_log_state, xbee_driver.xbee.XbeeNode.deserialize_log_type.
xbee_driver.xbee.main(args=None)
References xbee_driver.xbee.main.
Referenced by xbee_driver.xbee.main.