var searchData=
[
  ['n_20r_20iterations_0',['technique, making a total of one and a half modified N-R iterations.',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosSea.cpp#autotoc_md61',1,'']]],
  ['need_20to_20be_20performed_1',['of this code does not need to be performed.',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md33',1,'']]],
  ['negative_2',['negative',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md13',1,'Setting the three outputs for data points that have func0 non-negative'],['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md23',1,'Setting the three outputs for data points that have func0 non-negative']]],
  ['newton_20raphson_20iteration_20to_20find_20rt_20at_20sp_202_3',['Begin a single modified Newton-Raphson iteration to find Rt at SP = 2.',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosBase.cpp#autotoc_md7',1,'']]],
  ['newton_20raphson_20iterative_20procedure_4',['newton raphson iterative procedure',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosBase.cpp#autotoc_md3',1,'Begin the modified Newton-Raphson iterative procedure'],['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosBase.cpp#autotoc_md1',1,'Begin the modified Newton-Raphson iterative procedure'],['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md9',1,'Begin the modified Newton-Raphson iterative procedure']]],
  ['newton_20raphson_20method_5',['Begin the modified Newton-Raphson method.',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosSea.cpp#autotoc_md57',1,'']]],
  ['newton_20raphson_20technique_6',['iteration of the modified Newton-Raphson technique.',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosSea.cpp#autotoc_md59',1,'']]],
  ['newton_20s_20method_7',['newton s method',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md29',1,'be fed into Newton s Method.'],['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md19',1,'fed into Newton s Method.'],['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md37',1,'fed into the iterative Newton s Method.']]],
  ['no_20more_20than_20max_5fdp_5fi_20the_20default_20value_20being_201_20dbar_8',['increment being no more than max_dp_i (the default value being 1 dbar).',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosSea.cpp#autotoc_md65',1,'']]],
  ['non_20negative_9',['non negative',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md23',1,'Setting the three outputs for data points that have func0 non-negative'],['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md13',1,'Setting the three outputs for data points that have func0 non-negative']]],
  ['not_20need_20to_20be_20performed_10',['of this code does not need to be performed.',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosIce.cpp#autotoc_md33',1,'']]],
  ['not_20radius_11',['Note : error in the thesis formula : diam and not radius',['../classSimulator.html#autotoc_md66',1,'']]],
  ['note_20_3a_20error_20in_20the_20thesis_20formula_20_3a_20diam_20and_20not_20radius_12',['Note : error in the thesis formula : diam and not radius',['../classSimulator.html#autotoc_md66',1,'']]],
  ['now_20go_20from_20rtx_20to_20rt_20and_20then_20to_20the_20conductivity_20ratio_20r_20at_20pressure_20p_13',['Now go from Rtx to Rt and then to the conductivity ratio R at pressure p.',['..//home/tristanlf/seabot2/seabot2-ros/src/seabot2_observer/seabot2_density/TeosCpp/src/TeosSea.cpp#autotoc_md63',1,'']]]
];
